RawSpeed: rawspeed::FujiDecompressor Class Reference
rawspeed::FujiDecompressor Class Reference final
#include "decompressors/FujiDecompressor.h"
Classes
struct fuji_compressed_block
struct fuji_compressed_params
struct FujiHeader
struct FujiStrip
struct int_pair
Public Member Functions
FujiDecompressor (const RawImage &img, ByteStream input)
void fuji_compressed_load_raw ()
void decompress () const
Public Attributes
FujiHeader header
Protected Types
enum xt_lines {
R0 = 0, R1, R2, R3,
R4, G0, G1, G2,
G3, G4, G5, G6,
G7, B0, B1, B2,
B3, B4, ltotal
}
Protected Attributes
fuji_compressed_params common_info
Private Member Functions
void decompressThread () const noexcept
void fuji_decode_strip (fuji_compressed_block *info_block, const FujiStrip &strip) const
template<typename T >
void copy_line (fuji_compressed_block *info, const FujiStrip &strip, int cur_line, T &&idx) const
void copy_line_to_xtrans (fuji_compressed_block *info, const FujiStrip &strip, int cur_line) const
void copy_line_to_bayer (fuji_compressed_block *info, const FujiStrip &strip, int cur_line) const
template<typename T1 , typename T2 >
void fuji_decode_sample (T1 &&func_0, T2 &&func_1, fuji_compressed_block *info, uint16_t *line_buf, int *pos, std::array< int_pair, 41 > *grads) const
void fuji_decode_sample_even (fuji_compressed_block *info, uint16_t *line_buf, int *pos, std::array< int_pair, 41 > *grads) const
void fuji_decode_sample_odd (fuji_compressed_block *info, uint16_t *line_buf, int *pos, std::array< int_pair, 41 > *grads) const
void xtrans_decode_block (fuji_compressed_block *info, int cur_line) const
void fuji_bayer_decode_block (fuji_compressed_block *info, int cur_line) const
Static Private Member Functions
static void fuji_zerobits (BitPumpMSB *pump, int *count)
static int bitDiff (int value1, int value2)
static void fuji_decode_interpolation_even (int line_width, uint16_t *line_buf, int *pos)
static void fuji_extend_generic (std::array< uint16_t *, ltotal > linebuf, int line_width, int start, int end)
static void fuji_extend_red (std::array< uint16_t *, ltotal > linebuf, int line_width)
static void fuji_extend_green (std::array< uint16_t *, ltotal > linebuf, int line_width)
static void fuji_extend_blue (std::array< uint16_t *, ltotal > linebuf, int line_width)
Private Attributes
RawImage mRaw
ByteStream input
std::array< std::array< CFAColor, 6 >, 6 > CFA
std::vector< FujiStrip > strips
Detailed Description
Definition at line 37 of file FujiDecompressor.h.
Member Enumeration Documentation
xt_lines
enum rawspeed::FujiDecompressor::xt_lines protected
Enumerator
R0
R1
R2
R3
R4
G0
G1
G2
G3
G4
G5
G6
G7
B0
B1
B2
B3
B4
ltotal
Definition at line 136 of file FujiDecompressor.h.
Constructor & Destructor Documentation
FujiDecompressor()
rawspeed::FujiDecompressor::FujiDecompressor (const RawImage & img, ByteStream input)
Definition at line 42 of file FujiDecompressor.cpp.
References rawspeed::big, fuji_compressed_load_raw(), FujiDecompressor(), rawspeed::FujiDecompressor::FujiHeader::FujiHeader(), header, input, mRaw, rawspeed::FujiDecompressor::FujiHeader::raw_bits, and rawspeed::RawImage::RawImage().
Referenced by FujiDecompressor(), and LLVMFuzzerTestOneInput().
Member Function Documentation
bitDiff()
static int rawspeed::FujiDecompressor::bitDiff (int value1, int value2) static private
copy_line()
template<typename T > void rawspeed::FujiDecompressor::copy_line (fuji_compressed_block * info, const FujiStrip & strip, int cur_line, T && idx) const private
Definition at line 181 of file FujiDecompressor.cpp.
References rawspeed::FujiDecompressor::FujiStrip::lineHeight(), and rawspeed::FujiDecompressor::FujiStrip::width().
copy_line_to_bayer()
void rawspeed::FujiDecompressor::copy_line_to_bayer (fuji_compressed_block * info, const FujiStrip & strip, int cur_line) const private
Definition at line 237 of file FujiDecompressor.cpp.
Referenced by fuji_decode_strip().
copy_line_to_xtrans()
void rawspeed::FujiDecompressor::copy_line_to_xtrans (fuji_compressed_block * info, const FujiStrip & strip, int cur_line) const private
Definition at line 226 of file FujiDecompressor.cpp.
Referenced by fuji_decode_strip().
decompress()
void rawspeed::FujiDecompressor::decompress () const
Definition at line 788 of file FujiDecompressor.cpp.
References decompressThread().
Referenced by LLVMFuzzerTestOneInput().
decompressThread()
void rawspeed::FujiDecompressor::decompressThread () const private noexcept
Definition at line 770 of file FujiDecompressor.cpp.
Referenced by decompress().
fuji_bayer_decode_block()
void rawspeed::FujiDecompressor::fuji_bayer_decode_block (fuji_compressed_block * info, int cur_line) const private
Definition at line 624 of file FujiDecompressor.cpp.
References B2, B3, B4, G2, G3, G4, G5, G6, G7, R2, R3, and R4.
Referenced by fuji_decode_strip().
fuji_compressed_load_raw()
void rawspeed::FujiDecompressor::fuji_compressed_load_raw ()
Definition at line 744 of file FujiDecompressor.cpp.
References rawspeed::FujiDecompressor::FujiHeader::blocks_in_row, header, input, and rawspeed::ByteStream::skipBytes().
Referenced by FujiDecompressor().
fuji_decode_interpolation_even()
void rawspeed::FujiDecompressor::fuji_decode_interpolation_even (int line_width, uint16_t * line_buf, int * pos) static private
Definition at line 424 of file FujiDecompressor.cpp.
fuji_decode_sample()
template<typename T1 , typename T2 > void rawspeed::FujiDecompressor::fuji_decode_sample (T1 && func_0, T2 && func_1, fuji_compressed_block * info, uint16_t * line_buf, int * pos, std::array< int_pair, 41 > * grads) const private
Definition at line 280 of file FujiDecompressor.cpp.
fuji_decode_sample_even()
void rawspeed::FujiDecompressor::fuji_decode_sample_even (fuji_compressed_block * info, uint16_t * line_buf, int * pos, std::array< int_pair, 41 > * grads) const private
Definition at line 346 of file FujiDecompressor.cpp.
fuji_decode_sample_odd()
void rawspeed::FujiDecompressor::fuji_decode_sample_odd (fuji_compressed_block * info, uint16_t * line_buf, int * pos, std::array< int_pair, 41 > * grads) const private
Definition at line 388 of file FujiDecompressor.cpp.
fuji_decode_strip()
void rawspeed::FujiDecompressor::fuji_decode_strip (fuji_compressed_block * info_block, const FujiStrip & strip) const private
Definition at line 702 of file FujiDecompressor.cpp.
References copy_line_to_bayer(), copy_line_to_xtrans(), fuji_bayer_decode_block(), header, rawspeed::FujiDecompressor::FujiStrip::height(), rawspeed::FujiDecompressor::FujiHeader::raw_type, and xtrans_decode_block().
fuji_extend_blue()
void rawspeed::FujiDecompressor::fuji_extend_blue (std::array< uint16_t *, ltotal > linebuf, int line_width) static private
Definition at line 465 of file FujiDecompressor.cpp.
fuji_extend_generic()
void rawspeed::FujiDecompressor::fuji_extend_generic (std::array< uint16_t *, ltotal > linebuf, int line_width, int start, int end) static private
Definition at line 447 of file FujiDecompressor.cpp.
fuji_extend_green()
void rawspeed::FujiDecompressor::fuji_extend_green (std::array< uint16_t *, ltotal > linebuf, int line_width) static private
Definition at line 460 of file FujiDecompressor.cpp.
fuji_extend_red()
void rawspeed::FujiDecompressor::fuji_extend_red (std::array< uint16_t *, ltotal > linebuf, int line_width) static private
Definition at line 455 of file FujiDecompressor.cpp.
fuji_zerobits()
void rawspeed::FujiDecompressor::fuji_zerobits (BitPumpMSB * pump, int * count) inline static private
Definition at line 245 of file FujiDecompressor.cpp.
xtrans_decode_block()
void rawspeed::FujiDecompressor::xtrans_decode_block (fuji_compressed_block * info, int cur_line) const private
Definition at line 470 of file FujiDecompressor.cpp.
Referenced by fuji_decode_strip().
Member Data Documentation
CFA
std::array<std::array<CFAColor, 6>, 6> rawspeed::FujiDecompressor::CFA private
Definition at line 176 of file FujiDecompressor.h.
common_info
fuji_compressed_params rawspeed::FujiDecompressor::common_info protected
Definition at line 129 of file FujiDecompressor.h.
header
FujiHeader rawspeed::FujiDecompressor::header
Definition at line 61 of file FujiDecompressor.h.
Referenced by fuji_compressed_load_raw(), rawspeed::FujiDecompressor::fuji_compressed_params::fuji_compressed_params(), fuji_decode_strip(), and FujiDecompressor().
input
ByteStream rawspeed::FujiDecompressor::input private
Definition at line 174 of file FujiDecompressor.h.
Referenced by fuji_compressed_load_raw(), and FujiDecompressor().
mRaw
RawImage rawspeed::FujiDecompressor::mRaw private
Definition at line 38 of file FujiDecompressor.h.
Referenced by FujiDecompressor().
strips
std::vector<FujiStrip> rawspeed::FujiDecompressor::strips private
Definition at line 178 of file FujiDecompressor.h.
The documentation for this class was generated from the following files:
librawspeed/decompressors/FujiDecompressor.h
librawspeed/decompressors/FujiDecompressor.cpp