RawSpeed: /build/rawspeed/fuzz/libFuzzer_dummy_main.cpp File Reference
libFuzzer_dummy_main.cpp File Reference
#include "rawspeedconfig.h"
#include "io/Buffer.h"
#include "io/FileIOException.h"
#include "io/FileReader.h"
#include <cstdint>
#include <cstdlib>
#include <iostream>
#include <memory>
#include <string>
Functions
int LLVMFuzzerTestOneInput (const uint8_t *Data, size_t Size)
static int usage ()
static void process (const char *filename) noexcept
int main (int argc, char **argv)
Function Documentation
LLVMFuzzerTestOneInput()
int LLVMFuzzerTestOneInput (const uint8_t * Data, size_t Size)
Definition at line 58 of file main.cpp.
References rawspeed::ByteStream::ByteStream(), rawspeed::BitStreamTraits< BitPumpMSB32 >::canUseWithHuffmanTable, rawspeed::RawImageData::checkMemIsInitialized(), rawspeed::Cr2Decompressor::Cr2Decompressor(), rawspeed::RawImageData::createData(), CreateRawImage(), rawspeed::CrwDecompressor::CrwDecompressor(), anonymous_namespace{DummyLJpegDecompressor.cpp}::DummyLJpegDecompressor::decode(), rawspeed::LJpegDecompressor::decode(), rawspeed::Cr2Decompressor::decode(), rawspeed::VC5Decompressor::decode(), rawspeed::SonyArw2Decompressor::decompress(), rawspeed::SonyArw1Decompressor::decompress(), rawspeed::PentaxDecompressor::decompress(), rawspeed::SamsungV1Decompressor::decompress(), rawspeed::SamsungV0Decompressor::decompress(), rawspeed::PanasonicDecompressorV6::decompress(), rawspeed::KodakDecompressor::decompress(), rawspeed::CrwDecompressor::decompress(), rawspeed::PhaseOneDecompressor::decompress(), rawspeed::SamsungV2Decompressor::decompress(), rawspeed::PanasonicDecompressorV4::decompress(), rawspeed::PanasonicDecompressorV5::decompress(), rawspeed::FujiDecompressor::decompress(), anonymous_namespace{DummyLJpegDecompressor.cpp}::DummyLJpegDecompressor::DummyLJpegDecompressor(), rawspeed::FujiDecompressor::FujiDecompressor(), rawspeed::ByteStream::getPosition(), rawspeed::ByteStream::getRemainSize(), rawspeed::ByteStream::getStream(), rawspeed::ByteStream::getU32(), rawspeed::HasselbladDecompressor::HasselbladDecompressor(), rawspeed::KodakDecompressor::KodakDecompressor(), rawspeed::little, rawspeed::LJpegDecompressor::LJpegDecompressor(), rawspeed::RawImage::operator->(), rawspeed::PanasonicDecompressorV6::PanasonicDecompressorV6(), rawspeed::PentaxDecompressor::PentaxDecompressor(), rawspeed::SamsungV0Decompressor::SamsungV0Decompressor(), rawspeed::SonyArw1Decompressor::SonyArw1Decompressor(), and rawspeed::SonyArw2Decompressor::SonyArw2Decompressor().
main()
int main (int argc, char ** argv)
Definition at line 60 of file libFuzzer_dummy_main.cpp.
References process(), and usage().
process()
static void process (const char * filename) static noexcept
Definition at line 45 of file libFuzzer_dummy_main.cpp.
References rawspeed::BitStreamTraits< BitPumpMSB32 >::canUseWithHuffmanTable, and rawspeed::FileReader::FileReader().
Referenced by main().
usage()
static int usage () static
Definition at line 37 of file libFuzzer_dummy_main.cpp.
Referenced by main().