RawSpeed: rawspeed::VC5Decompressor::Wavelet::ReconstructableBand Struct Reference
rawspeed::VC5Decompressor::Wavelet::ReconstructableBand Struct Reference final
#include "decompressors/VC5Decompressor.h"
Public Member Functions
ReconstructableBand (bool clampUint_=false)
void processLow (const Wavelet &wavelet) noexcept
void processHigh (const Wavelet &wavelet) noexcept
void combine (const Wavelet &wavelet) noexcept
void decode (const Wavelet &wavelet) noexcept final
Public Attributes
bool clampUint
std::vector< int16_t, DefaultInitAllocatorAdaptor< int16_t > > lowpass_storage
std::vector< int16_t, DefaultInitAllocatorAdaptor< int16_t > > highpass_storage
std::vector< int16_t, DefaultInitAllocatorAdaptor< int16_t > > data
Detailed Description
Definition at line 127 of file VC5Decompressor.h.
Constructor & Destructor Documentation
ReconstructableBand()
rawspeed::VC5Decompressor::Wavelet::ReconstructableBand::ReconstructableBand (bool clampUint_ = false) inline explicit
Definition at line 133 of file VC5Decompressor.h.
References clampUint.
Member Function Documentation
combine()
void rawspeed::VC5Decompressor::Wavelet::ReconstructableBand::combine (const Wavelet & wavelet) noexcept
Definition at line 291 of file VC5Decompressor.cpp.
References rawspeed::VC5Decompressor::Wavelet::prescale.
Referenced by decode().
decode()
void rawspeed::VC5Decompressor::Wavelet::ReconstructableBand::decode (const Wavelet & wavelet) final virtual noexcept
Implements rawspeed::VC5Decompressor::Wavelet::AbstractBand.
Definition at line 311 of file VC5Decompressor.cpp.
References rawspeed::VC5Decompressor::Wavelet::allBandsValid(), combine(), processHigh(), and processLow().
processHigh()
void rawspeed::VC5Decompressor::Wavelet::ReconstructableBand::processHigh (const Wavelet & wavelet) noexcept
Definition at line 276 of file VC5Decompressor.cpp.
Referenced by decode().
processLow()
void rawspeed::VC5Decompressor::Wavelet::ReconstructableBand::processLow (const Wavelet & wavelet) noexcept
Definition at line 260 of file VC5Decompressor.cpp.
Referenced by decode().
Member Data Documentation
clampUint
bool rawspeed::VC5Decompressor::Wavelet::ReconstructableBand::clampUint
Definition at line 128 of file VC5Decompressor.h.
Referenced by ReconstructableBand().
data
std::vector<int16_t, DefaultInitAllocatorAdaptor<int16_t> > rawspeed::VC5Decompressor::Wavelet::AbstractBand::data inherited
Definition at line 123 of file VC5Decompressor.h.
highpass_storage
std::vector<int16_t, DefaultInitAllocatorAdaptor<int16_t> > rawspeed::VC5Decompressor::Wavelet::ReconstructableBand::highpass_storage
Definition at line 132 of file VC5Decompressor.h.
lowpass_storage
std::vector<int16_t, DefaultInitAllocatorAdaptor<int16_t> > rawspeed::VC5Decompressor::Wavelet::ReconstructableBand::lowpass_storage
Definition at line 130 of file VC5Decompressor.h.
The documentation for this struct was generated from the following files:
librawspeed/decompressors/VC5Decompressor.h
librawspeed/decompressors/VC5Decompressor.cpp