RawSpeed: rawspeed::TiffEntry Class Reference
rawspeed::TiffEntry Class Reference
#include "tiff/TiffEntry.h"
Public Member Functions
TiffEntry (TiffIFD *parent, TiffTag tag, TiffDataType type, uint32_t count, ByteStream &&data)
TiffEntry (TiffIFD *parent, ByteStream *bs)
bool __attribute__ ((pure)) isFloat() const
bool __attribute__ ((pure)) isInt() const
bool __attribute__ ((pure)) isString() const
uint8_t getByte (uint32_t index=0) const
uint32_t getU32 (uint32_t index=0) const
int32_t getI32 (uint32_t index=0) const
uint16_t getU16 (uint32_t index=0) const
int16_t getI16 (uint32_t index=0) const
float getFloat (uint32_t index=0) const
std::string getString () const
std::vector< uint16_t > getU16Array (uint32_t count_) const
std::vector< uint32_t > getU32Array (uint32_t count_) const
std::vector< float > getFloatArray (uint32_t count_) const
ByteStream & getData ()
const uint8_t * getData (uint32_t size)
const DataBuffer & getRootIfdData () const
Public Attributes
TiffTag tag
TiffDataType type
uint32_t count
Static Protected Attributes
static const std::array< uint32_t, 14 > datashifts
Private Member Functions
template<typename T , T(TiffEntry::*)(uint32_t index) const getter>
std::vector< T > getArray (uint32_t count_) const
Private Attributes
TiffIFD * parent
ByteStream data
Friends
class TiffIFD
Detailed Description
Definition at line 60 of file TiffEntry.h.
Constructor & Destructor Documentation
TiffEntry() [1/2]
rawspeed::TiffEntry::TiffEntry (TiffIFD * parent, TiffTag tag, TiffDataType type, uint32_t count, ByteStream && data)
Definition at line 87 of file TiffEntry.cpp.
References count, parent, tag, TiffEntry(), and type.
Referenced by TiffEntry().
TiffEntry() [2/2]
rawspeed::TiffEntry::TiffEntry (TiffIFD * parent, ByteStream * bs)
Definition at line 46 of file TiffEntry.cpp.
References rawspeed::ByteStream::check(), count, data, rawspeed::ByteStream::getPosition(), rawspeed::ByteStream::getSubStream(), rawspeed::ByteStream::getU16(), rawspeed::ByteStream::getU32(), parent, rawspeed::ByteStream::setPosition(), rawspeed::ByteStream::skipBytes(), tag, and type.
Member Function Documentation
__attribute__() [1/3]
bool rawspeed::TiffEntry::__attribute__ ((pure)) const
__attribute__() [2/3]
bool rawspeed::TiffEntry::__attribute__ ((pure)) const
__attribute__() [3/3]
bool rawspeed::TiffEntry::__attribute__ ((pure)) const
getArray()
template<typename T , T(TiffEntry::*)(uint32_t index) const getter> std::vector<T> rawspeed::TiffEntry::getArray (uint32_t count_) const inline private
Definition at line 68 of file TiffEntry.h.
getByte()
uint8_t rawspeed::TiffEntry::getByte (uint32_t index = 0) const
getData() [1/2]
ByteStream& rawspeed::TiffEntry::getData () inline
Definition at line 107 of file TiffEntry.h.
Referenced by rawspeed::DngOpcodes::DngOpcodes(), and rawspeed::TiffIFD::parseMakerNote().
getData() [2/2]
const uint8_t* rawspeed::TiffEntry::getData (uint32_t size) inline
Definition at line 108 of file TiffEntry.h.
getFloat()
float rawspeed::TiffEntry::getFloat (uint32_t index = 0) const
getFloatArray()
std::vector<float> rawspeed::TiffEntry::getFloatArray (uint32_t count_) const inline
Definition at line 103 of file TiffEntry.h.
getI16()
int16_t rawspeed::TiffEntry::getI16 (uint32_t index = 0) const
getI32()
int32_t rawspeed::TiffEntry::getI32 (uint32_t index = 0) const
getRootIfdData()
const DataBuffer& rawspeed::TiffEntry::getRootIfdData () const
getString()
std::string rawspeed::TiffEntry::getString () const
getU16()
uint16_t rawspeed::TiffEntry::getU16 (uint32_t index = 0) const
getU16Array()
std::vector<uint16_t> rawspeed::TiffEntry::getU16Array (uint32_t count_) const inline
Definition at line 95 of file TiffEntry.h.
getU32()
uint32_t rawspeed::TiffEntry::getU32 (uint32_t index = 0) const
getU32Array()
std::vector<uint32_t> rawspeed::TiffEntry::getU32Array (uint32_t count_) const inline
Definition at line 99 of file TiffEntry.h.
Friends And Related Function Documentation
TiffIFD
friend class TiffIFD friend
Definition at line 65 of file TiffEntry.h.
Member Data Documentation
count
uint32_t rawspeed::TiffEntry::count
Definition at line 78 of file TiffEntry.h.
Referenced by TiffEntry().
data
ByteStream rawspeed::TiffEntry::data private
Definition at line 63 of file TiffEntry.h.
Referenced by TiffEntry().
datashifts
const std::array< uint32_t, 14 > rawspeed::TiffEntry::datashifts static protected
Initial value:
= {0, 0, 0, 1, 2, 3, 0,
                                                        0, 1, 2, 3, 2, 3, 2}
Definition at line 113 of file TiffEntry.h.
parent
TiffIFD* rawspeed::TiffEntry::parent private
Definition at line 62 of file TiffEntry.h.
Referenced by TiffEntry().
tag
TiffTag rawspeed::TiffEntry::tag
Definition at line 76 of file TiffEntry.h.
Referenced by TiffEntry().
type
TiffDataType rawspeed::TiffEntry::type
Definition at line 77 of file TiffEntry.h.
Referenced by TiffEntry().
The documentation for this class was generated from the following files:
librawspeed/tiff/TiffEntry.h
librawspeed/tiff/TiffEntry.cpp