RawSpeed: rawspeed::Cr2sRawInterpolator Class Reference
rawspeed::Cr2sRawInterpolator Class Reference final
#include "interpolators/Cr2sRawInterpolator.h"
Classes
struct YCbCr
Public Member Functions
Cr2sRawInterpolator (const RawImage &mRaw_, Array2DRef< const uint16_t > input_, std::array< int, 3 > sraw_coeffs_, int hue_)
void interpolate (int version)
Protected Member Functions
template<int version>
void YUV_TO_RGB (const YCbCr &p, uint16_t *X)
template<int version>
void interpolate_422_row (int row)
template<int version>
void interpolate_422 ()
template<int version>
void interpolate_420_row (int row)
template<int version>
void interpolate_420 ()
template<>
void YUV_TO_RGB (const YCbCr &p, uint16_t *X)
template<>
void YUV_TO_RGB (const YCbCr &p, uint16_t *X)
template<>
void YUV_TO_RGB (const YCbCr &p, uint16_t *X)
Static Protected Member Functions
static void STORE_RGB (uint16_t *X, int r, int g, int b)
Private Attributes
const RawImage & mRaw
const Array2DRef< const uint16_t > input
std::array< int, 3 > sraw_coeffs
int hue
Detailed Description
Definition at line 31 of file Cr2sRawInterpolator.h.
Constructor & Destructor Documentation
Cr2sRawInterpolator()
rawspeed::Cr2sRawInterpolator::Cr2sRawInterpolator (const RawImage & mRaw_, Array2DRef< const uint16_t > input_, std::array< int, 3 > sraw_coeffs_, int hue_) inline
Definition at line 41 of file Cr2sRawInterpolator.h.
References Cr2sRawInterpolator(), hue, and mRaw.
Referenced by Cr2sRawInterpolator().
Member Function Documentation
interpolate()
void rawspeed::Cr2sRawInterpolator::interpolate (int version)
Definition at line 498 of file Cr2sRawInterpolator.cpp.
interpolate_420()
template<int version> void rawspeed::Cr2sRawInterpolator::interpolate_420 () protected
Definition at line 340 of file Cr2sRawInterpolator.cpp.
interpolate_420_row()
template<int version> void rawspeed::Cr2sRawInterpolator::interpolate_420_row (int row) protected
Definition at line 189 of file Cr2sRawInterpolator.cpp.
interpolate_422()
template<int version> void rawspeed::Cr2sRawInterpolator::interpolate_422 () protected
Definition at line 178 of file Cr2sRawInterpolator.cpp.
interpolate_422_row()
template<int version> void rawspeed::Cr2sRawInterpolator::interpolate_422_row (int row) protected
Definition at line 95 of file Cr2sRawInterpolator.cpp.
STORE_RGB()
void rawspeed::Cr2sRawInterpolator::STORE_RGB (uint16_t * X, int r, int g, int b) inline static protected
Definition at line 457 of file Cr2sRawInterpolator.cpp.
Referenced by YUV_TO_RGB().
YUV_TO_RGB() [1/4]
template<int version> void rawspeed::Cr2sRawInterpolator::YUV_TO_RGB (const YCbCr & p, uint16_t * X) inline protected
YUV_TO_RGB() [2/4]
template<> void rawspeed::Cr2sRawInterpolator::YUV_TO_RGB (const YCbCr & p, uint16_t * X) inline protected
Definition at line 467 of file Cr2sRawInterpolator.cpp.
References STORE_RGB().
YUV_TO_RGB() [3/4]
template<> void rawspeed::Cr2sRawInterpolator::YUV_TO_RGB (const YCbCr & p, uint16_t * X) inline protected
Definition at line 477 of file Cr2sRawInterpolator.cpp.
References STORE_RGB().
YUV_TO_RGB() [4/4]
template<> void rawspeed::Cr2sRawInterpolator::YUV_TO_RGB (const YCbCr & p, uint16_t * X) inline protected
Definition at line 488 of file Cr2sRawInterpolator.cpp.
References STORE_RGB().
Member Data Documentation
hue
int rawspeed::Cr2sRawInterpolator::hue private
Definition at line 36 of file Cr2sRawInterpolator.h.
Referenced by Cr2sRawInterpolator().
input
const Array2DRef<const uint16_t> rawspeed::Cr2sRawInterpolator::input private
Definition at line 34 of file Cr2sRawInterpolator.h.
mRaw
const RawImage& rawspeed::Cr2sRawInterpolator::mRaw private
Definition at line 32 of file Cr2sRawInterpolator.h.
Referenced by Cr2sRawInterpolator().
sraw_coeffs
std::array<int, 3> rawspeed::Cr2sRawInterpolator::sraw_coeffs private
Definition at line 35 of file Cr2sRawInterpolator.h.
The documentation for this class was generated from the following files:
librawspeed/interpolators/Cr2sRawInterpolator.h
librawspeed/interpolators/Cr2sRawInterpolator.cpp