RawSpeed: rawspeed::PanasonicDecompressorV6 Class Reference
rawspeed::PanasonicDecompressorV6 Class Reference final
#include "decompressors/PanasonicDecompressorV6.h"
Public Member Functions
PanasonicDecompressorV6 (const RawImage &img, const ByteStream &input_)
void decompress () const
Private Member Functions
void __attribute__ ((always_inline)) decompressBlock(ByteStream *rowInput
void decompressRow (int row) const noexcept
Private Attributes
RawImage mRaw
ByteStream input
void int row
void int int const col noexcept
Static Private Attributes
static constexpr int PixelsPerBlock = 11
static constexpr int BytesPerBlock = 16
Detailed Description
Definition at line 29 of file PanasonicDecompressorV6.h.
Constructor & Destructor Documentation
PanasonicDecompressorV6()
rawspeed::PanasonicDecompressorV6::PanasonicDecompressorV6 (const RawImage & img, const ByteStream & input_)
Definition at line 90 of file PanasonicDecompressorV6.cpp.
References rawspeed::iPoint2D::__attribute__(), BytesPerBlock, rawspeed::RawImageData::dim, rawspeed::ByteStream::getRemainSize(), rawspeed::iPoint2D::hasPositiveArea(), input, mRaw, rawspeed::RawImage::operator->(), rawspeed::ByteStream::peekStream(), PixelsPerBlock, rawspeed::RawImage::RawImage(), and rawspeed::iPoint2D::x.
Referenced by LLVMFuzzerTestOneInput().
Member Function Documentation
__attribute__()
void rawspeed::PanasonicDecompressorV6::__attribute__ ((always_inline)) inline private
decompress()
void rawspeed::PanasonicDecompressorV6::decompress () const
Referenced by LLVMFuzzerTestOneInput().
decompressRow()
void rawspeed::PanasonicDecompressorV6::decompressRow (int row) const private noexcept
Member Data Documentation
BytesPerBlock
constexpr int rawspeed::PanasonicDecompressorV6::BytesPerBlock = 16 static constexpr private
Definition at line 35 of file PanasonicDecompressorV6.h.
Referenced by PanasonicDecompressorV6().
input
ByteStream rawspeed::PanasonicDecompressorV6::input private
Definition at line 32 of file PanasonicDecompressorV6.h.
Referenced by PanasonicDecompressorV6().
mRaw
RawImage rawspeed::PanasonicDecompressorV6::mRaw private
Definition at line 30 of file PanasonicDecompressorV6.h.
Referenced by PanasonicDecompressorV6().
noexcept
void int int const col rawspeed::PanasonicDecompressorV6::noexcept private
Definition at line 39 of file PanasonicDecompressorV6.h.
PixelsPerBlock
constexpr int rawspeed::PanasonicDecompressorV6::PixelsPerBlock = 11 static constexpr private
Definition at line 34 of file PanasonicDecompressorV6.h.
Referenced by PanasonicDecompressorV6().
row
void int rawspeed::PanasonicDecompressorV6::row private
Definition at line 39 of file PanasonicDecompressorV6.h.
The documentation for this class was generated from the following files:
librawspeed/decompressors/PanasonicDecompressorV6.h
librawspeed/decompressors/PanasonicDecompressorV6.cpp