RawSpeed: rawspeed::KodakDecompressor Class Reference
rawspeed::KodakDecompressor Class Reference final
#include "decompressors/KodakDecompressor.h"
Public Member Functions
KodakDecompressor (const RawImage &img, ByteStream bs, int bps, bool uncorrectedRawValues_)
void decompress ()
Private Types
using segment = std::array< int16_t, segment_size >
Private Member Functions
segment decodeSegment (uint32_t bsize)
Private Attributes
RawImage mRaw
ByteStream input
int bps
bool uncorrectedRawValues
Static Private Attributes
static constexpr int segment_size = 256
Detailed Description
Definition at line 33 of file KodakDecompressor.h.
Member Typedef Documentation
segment
using rawspeed::KodakDecompressor::segment = std::array<int16_t, segment_size> private
Definition at line 40 of file KodakDecompressor.h.
Constructor & Destructor Documentation
KodakDecompressor()
rawspeed::KodakDecompressor::KodakDecompressor (const RawImage & img, ByteStream bs, int bps, bool uncorrectedRawValues_)
Definition at line 41 of file KodakDecompressor.cpp.
References rawspeed::iPoint2D::__attribute__(), bps, rawspeed::ByteStream::check(), rawspeed::RawImageData::dim, input, KodakDecompressor(), mRaw, rawspeed::RawImage::operator->(), rawspeed::RawImage::RawImage(), and uncorrectedRawValues.
Referenced by KodakDecompressor(), and LLVMFuzzerTestOneInput().
Member Function Documentation
decodeSegment()
KodakDecompressor::segment rawspeed::KodakDecompressor::decodeSegment (uint32_t bsize) private
Definition at line 63 of file KodakDecompressor.cpp.
References rawspeed::ByteStream::getByte(), input, and segment_size.
decompress()
void rawspeed::KodakDecompressor::decompress ()
Definition at line 114 of file KodakDecompressor.cpp.
Referenced by LLVMFuzzerTestOneInput().
Member Data Documentation
bps
int rawspeed::KodakDecompressor::bps private
Definition at line 36 of file KodakDecompressor.h.
Referenced by KodakDecompressor().
input
ByteStream rawspeed::KodakDecompressor::input private
Definition at line 35 of file KodakDecompressor.h.
Referenced by decodeSegment(), and KodakDecompressor().
mRaw
RawImage rawspeed::KodakDecompressor::mRaw private
Definition at line 34 of file KodakDecompressor.h.
Referenced by KodakDecompressor().
segment_size
constexpr int rawspeed::KodakDecompressor::segment_size = 256 static constexpr private
Definition at line 39 of file KodakDecompressor.h.
Referenced by decodeSegment().
uncorrectedRawValues
bool rawspeed::KodakDecompressor::uncorrectedRawValues private
Definition at line 37 of file KodakDecompressor.h.
Referenced by KodakDecompressor().
The documentation for this class was generated from the following files:
librawspeed/decompressors/KodakDecompressor.h
librawspeed/decompressors/KodakDecompressor.cpp