RawSpeed: rawspeed::DngOpcodes Class Reference
rawspeed::DngOpcodes Class Reference
#include "common/DngOpcodes.h"
Classes
class DeltaRowOrCol
class DeltaRowOrColBase
class DngOpcode
class DummyROIOpcode
class FixBadPixelsConstant
class FixBadPixelsList
class LookupOpcode
class OffsetPerRowOrCol
class PixelOpcode
class PolynomialMap
class ROIOpcode
class ScalePerRowOrCol
class TableMap
class TrimBounds
Public Member Functions
DngOpcodes (const RawImage &ri, TiffEntry *entry)
~DngOpcodes ()
void applyOpCodes (const RawImage &ri)
Protected Types
using constructor_t = std::unique_ptr< DngOpcode >(*)(const RawImage &ri, ByteStream *bs)
Static Protected Member Functions
template<class Opcode >
static std::unique_ptr< DngOpcode > constructor (const RawImage &ri, ByteStream *bs)
Static Protected Attributes
static const std::map< uint32_t, std::pair< const char *, constructor_t > > Map
Private Attributes
std::vector< std::unique_ptr< DngOpcode > > opcodes
Detailed Description
Definition at line 38 of file DngOpcodes.h.
Member Typedef Documentation
constructor_t
using rawspeed::DngOpcodes::constructor_t = std::unique_ptr<DngOpcode> (*)(const RawImage& ri, ByteStream* bs) protected
Definition at line 69 of file DngOpcodes.h.
Constructor & Destructor Documentation
DngOpcodes()
rawspeed::DngOpcodes::DngOpcodes (const RawImage & ri, TiffEntry * entry)
Definition at line 473 of file DngOpcodes.cpp.
References rawspeed::big, rawspeed::TiffEntry::getData(), rawspeed::ByteStream::getPosition(), rawspeed::ByteStream::getStream(), rawspeed::ByteStream::getU32(), rawspeed::ByteStream::setPosition(), and rawspeed::ByteStream::skipBytes().
~DngOpcodes()
rawspeed::DngOpcodes::~DngOpcodes () default
Member Function Documentation
applyOpCodes()
void rawspeed::DngOpcodes::applyOpCodes (const RawImage & ri)
Definition at line 538 of file DngOpcodes.cpp.
constructor()
template<class Opcode > std::unique_ptr< DngOpcodes::DngOpcode > rawspeed::DngOpcodes::constructor (const RawImage & ri, ByteStream * bs) static protected
Definition at line 547 of file DngOpcodes.cpp.
Member Data Documentation
Map
const std::map< uint32_t, std::pair< const char *, DngOpcodes::constructor_t > > rawspeed::DngOpcodes::Map static protected
Definition at line 70 of file DngOpcodes.h.
opcodes
std::vector<std::unique_ptr<DngOpcode> > rawspeed::DngOpcodes::opcodes private
Definition at line 46 of file DngOpcodes.h.
The documentation for this class was generated from the following files:
librawspeed/common/DngOpcodes.h
librawspeed/common/DngOpcodes.cpp