RawSpeed: rawspeed::NikonDecompressor Class Reference
rawspeed::NikonDecompressor Class Reference final
#include "decompressors/NikonDecompressor.h"
Public Member Functions
NikonDecompressor (const RawImage &raw, ByteStream metadata, uint32_t bitsPS)
void decompress (const ByteStream &data, bool uncorrectedRawValues)
Private Member Functions
template<typename Huffman >
void decompress (BitPumpMSB *bits, int start_y, int end_y)
Static Private Member Functions
static std::vector< uint16_t > createCurve (ByteStream *metadata, uint32_t bitsPS, uint32_t v0, uint32_t v1, uint32_t *split)
template<typename Huffman >
static Huffman createHuffmanTable (uint32_t huffSelect)
Private Attributes
RawImage mRaw
uint32_t bitsPS
uint32_t huffSelect = 0
uint32_t split = 0
std::array< std::array< int, 2 >, 2 > pUp
std::vector< uint16_t > curve
uint32_t random
Static Private Attributes
static const std::array< std::array< std::array< uint8_t, 16 >, 2 >, 6 > nikon_tree
Detailed Description
Definition at line 36 of file NikonDecompressor.h.
Constructor & Destructor Documentation
NikonDecompressor()
rawspeed::NikonDecompressor::NikonDecompressor (const RawImage & raw, ByteStream metadata, uint32_t bitsPS)
Definition at line 438 of file NikonDecompressor.cpp.
References bitsPS, rawspeed::DEBUG_PRIO_EXTRA, rawspeed::RawImageData::dim, rawspeed::ByteStream::getByte(), huffSelect, mRaw, rawspeed::RawImage::operator->(), rawspeed::RawImage::RawImage(), rawspeed::ByteStream::skipBytes(), split, rawspeed::writeLog(), and rawspeed::iPoint2D::y.
Member Function Documentation
createCurve()
std::vector< uint16_t > rawspeed::NikonDecompressor::createCurve (ByteStream * metadata, uint32_t bitsPS, uint32_t v0, uint32_t v1, uint32_t * split) static private
Definition at line 363 of file NikonDecompressor.cpp.
References rawspeed::ByteStream::getU16(), and rawspeed::ByteStream::setPosition().
createHuffmanTable()
template<typename Huffman > Huffman rawspeed::NikonDecompressor::createHuffmanTable (uint32_t huffSelect) static private
Definition at line 429 of file NikonDecompressor.cpp.
decompress() [1/2]
template<typename Huffman > void rawspeed::NikonDecompressor::decompress (BitPumpMSB * bits, int start_y, int end_y) private
Definition at line 484 of file NikonDecompressor.cpp.
References rawspeed::RawImage::get(), huffSelect, and mRaw.
decompress() [2/2]
void rawspeed::NikonDecompressor::decompress (const ByteStream & data, bool uncorrectedRawValues)
Definition at line 507 of file NikonDecompressor.cpp.
References rawspeed::RawImageData::dim, huffSelect, mRaw, rawspeed::RawImage::operator->(), split, and rawspeed::iPoint2D::y.
Member Data Documentation
bitsPS
uint32_t rawspeed::NikonDecompressor::bitsPS private
Definition at line 38 of file NikonDecompressor.h.
Referenced by NikonDecompressor().
curve
std::vector<uint16_t> rawspeed::NikonDecompressor::curve private
Definition at line 45 of file NikonDecompressor.h.
huffSelect
uint32_t rawspeed::NikonDecompressor::huffSelect = 0 private
Definition at line 40 of file NikonDecompressor.h.
Referenced by decompress(), and NikonDecompressor().
mRaw
RawImage rawspeed::NikonDecompressor::mRaw private
Definition at line 37 of file NikonDecompressor.h.
Referenced by decompress(), and NikonDecompressor().
nikon_tree
const std::array< std::array< std::array< uint8_t, 16 >, 2 >, 6 > rawspeed::NikonDecompressor::nikon_tree static private
Initial value:
= {{
        {{
          {0, 1, 5, 1, 1, 1, 1, 1, 1, 2, 0, 0, 0, 0, 0, 0},
          {5, 4, 3, 6, 2, 7, 1, 0, 8, 9, 11, 10, 12}}},
        {{
          {0, 1, 5, 1, 1, 1, 1, 1, 1, 2, 0, 0, 0, 0, 0, 0},
          {0x39, 0x5a, 0x38, 0x27, 0x16, 5, 4, 3, 2, 1, 0, 11, 12, 12}}},
        {{
          {0, 1, 4, 2, 3, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0},
          {5, 4, 6, 3, 7, 2, 8, 1, 9, 0, 10, 11, 12}}},
        {{
          {0, 1, 4, 3, 1, 1, 1, 1, 1, 2, 0, 0, 0, 0, 0, 0},
          {5, 6, 4, 7, 8, 3, 9, 2, 1, 0, 10, 11, 12, 13, 14}}},
        {{
          {0, 1, 5, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0, 0, 0, 0},
          {8, 0x5c, 0x4b, 0x3a, 0x29, 7, 6, 5, 4, 3, 2, 1, 0, 13, 14}}},
        {{
          {0, 1, 4, 2, 2, 3, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0},
          {7, 6, 8, 5, 9, 4, 10, 3, 11, 12, 2, 0, 1, 13, 14}}},
    }}
Definition at line 55 of file NikonDecompressor.h.
pUp
std::array<std::array<int, 2>, 2> rawspeed::NikonDecompressor::pUp private
Definition at line 43 of file NikonDecompressor.h.
random
uint32_t rawspeed::NikonDecompressor::random private
Definition at line 47 of file NikonDecompressor.h.
split
uint32_t rawspeed::NikonDecompressor::split = 0 private
Definition at line 41 of file NikonDecompressor.h.
Referenced by decompress(), and NikonDecompressor().
The documentation for this class was generated from the following files:
librawspeed/decompressors/NikonDecompressor.h
librawspeed/decompressors/NikonDecompressor.cpp