RawSpeed: rawspeed::RawImageDataFloat Class Reference
rawspeed::RawImageDataFloat Class Reference final abstract
#include "common/RawImage.h"
Public Member Functions
void scaleBlackWhite () override
void calculateBlackAreas () override
void setWithLookUp (uint16_t value, uint8_t *dst, uint32_t *random) override
uint32_t getCpp () const
uint32_t getBpp () const
void setCpp (uint32_t val)
void createData ()
void poisonPadding ()
void unpoisonPadding ()
void checkRowIsInitialized (int row)
void checkMemIsInitialized ()
void destroyData ()
void blitFrom (const RawImage &src, const iPoint2D &srcPos, const iPoint2D &size, const iPoint2D &destPos)
rawspeed::RawImageType getDataType () const
Array2DRef< uint16_t > getU16DataAsUncroppedArray2DRef () const noexcept
uint8_t * getData () const
uint8_t * getData (uint32_t x, uint32_t y)
uint8_t * getDataUncropped (uint32_t x, uint32_t y)
void subFrame (iRectangle2D cropped)
void clearArea (iRectangle2D area, uint8_t value=0)
iPoint2D __attribute__ ((pure)) getUncroppedDim() const
iPoint2D __attribute__ ((pure)) getCropOffset() const
void sixteenBitLookup ()
void transferBadPixelsToMap () REQUIRES(!mBadPixelMutex)
void fixBadPixels () REQUIRES(!mBadPixelMutex)
void expandBorder (iRectangle2D validData)
void setTable (const std::vector< uint16_t > &table_, bool dither)
void setTable (std::unique_ptr< TableLookUp > t)
bool isAllocated ()
void createBadPixelMap ()
std::vector< uint32_t > mBadPixelPositions GUARDED_BY (mBadPixelMutex)
void setError (const std::string &err) REQUIRES(!mutex)
bool isTooManyErrors (unsigned many, std::string *firstErr=nullptr) REQUIRES(!mutex)
std::vector< std::string > && getErrors () REQUIRES(!mutex)
Public Attributes
iPoint2D dim
int pitch = 0
uint32_t padding = 0
bool isCFA {true}
ColorFilterArray cfa
int blackLevel = -1
std::array< int, 4 > blackLevelSeparate
int whitePoint = 65536
std::vector< BlackArea > blackAreas
uint8_t * mBadPixelMap = nullptr
uint32_t mBadPixelMapPitch = 0
bool mDitherScale
ImageMetaData metadata
Mutex mBadPixelMutex
Protected Member Functions
void scaleValues (int start_y, int end_y) override
void fixBadPixel (uint32_t x, uint32_t y, int component=0) override
void doLookup (int start_y, int end_y) override
RawImageDataFloat ()
RawImageDataFloat (const iPoint2D &dim_, uint32_t cpp_=1)
void fixBadPixelsThread (int start_y, int end_y)
void startWorker (RawImageWorker::RawImageWorkerTask task, bool cropped)
Protected Attributes
RawImageType dataType
uint8_t * data = nullptr
int cpp = 1
int bpp = 0
iPoint2D mOffset
iPoint2D uncropped_dim
std::unique_ptr< TableLookUp > table
Mutex mymutex
Private Member Functions
uint32_t dataRefCount GUARDED_BY (mymutex)=0
Private Attributes
Mutex mutex
Friends
class RawImage
Detailed Description
Definition at line 205 of file RawImage.h.
Constructor & Destructor Documentation
RawImageDataFloat() [1/2]
rawspeed::RawImageDataFloat::RawImageDataFloat () protected
Definition at line 37 of file RawImageDataFloat.cpp.
References rawspeed::RawImageData::bpp, rawspeed::RawImageData::dataType, and rawspeed::TYPE_FLOAT32.
RawImageDataFloat() [2/2]
rawspeed::RawImageDataFloat::RawImageDataFloat (const iPoint2D & dim_, uint32_t cpp_ = 1) explicit protected
Definition at line 42 of file RawImageDataFloat.cpp.
References rawspeed::RawImageData::dataType, rawspeed::RawImageData::RawImageData(), and rawspeed::TYPE_FLOAT32.
Member Function Documentation
__attribute__() [1/2]
iPoint2D rawspeed::RawImageData::__attribute__ ((pure)) const inherited
Referenced by rawspeed::DngOpcodes::FixBadPixelsConstant::apply(), and main().
__attribute__() [2/2]
iPoint2D rawspeed::RawImageData::__attribute__ ((pure)) const inherited
Referenced by rawspeed::DngOpcodes::FixBadPixelsList::FixBadPixelsList(), rawspeed::rstest::imgDataHash(), main(), rawspeed::rstest::writePFM(), and rawspeed::rstest::writePPM().
blitFrom()
void rawspeed::RawImageData::blitFrom (const RawImage & src, const iPoint2D & srcPos, const iPoint2D & size, const iPoint2D & destPos) inherited
Definition at line 432 of file RawImage.cpp.
References rawspeed::iPoint2D::__attribute__(), rawspeed::RawImageData::bpp, rawspeed::copyPixels(), rawspeed::RawImageData::dim, rawspeed::RawImageData::getData(), rawspeed::iRectangle2D::getOverlap(), rawspeed::iPoint2D::iPoint2D(), rawspeed::iRectangle2D::iRectangle2D(), rawspeed::RawImage::operator->(), rawspeed::RawImageData::pitch, rawspeed::iRectangle2D::pos, rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
calculateBlackAreas()
void rawspeed::RawImageDataFloat::calculateBlackAreas () override virtual
Implements rawspeed::RawImageData.
Definition at line 47 of file RawImageDataFloat.cpp.
References rawspeed::RawImageData::isCFA.
Referenced by scaleBlackWhite().
checkMemIsInitialized()
void rawspeed::RawImageData::checkMemIsInitialized () inherited
Definition at line 179 of file RawImage.cpp.
Referenced by LLVMFuzzerTestOneInput().
checkRowIsInitialized()
void rawspeed::RawImageData::checkRowIsInitialized (int row) inherited
Definition at line 163 of file RawImage.cpp.
References rawspeed::RawImageData::bpp, rawspeed::RawImageData::getDataUncropped(), rawspeed::RawImageData::uncropped_dim, and rawspeed::iPoint2D::x.
clearArea()
void rawspeed::RawImageData::clearArea (iRectangle2D area, uint8_t value = 0) inherited
Definition at line 496 of file RawImage.cpp.
References rawspeed::iRectangle2D::area(), rawspeed::RawImageData::dim, rawspeed::iRectangle2D::getOverlap(), rawspeed::iPoint2D::iPoint2D(), and rawspeed::iRectangle2D::iRectangle2D().
createBadPixelMap()
void rawspeed::RawImageData::createBadPixelMap () inherited
Definition at line 273 of file RawImage.cpp.
Referenced by rawspeed::RawImageData::transferBadPixelsToMap().
createData()
void rawspeed::RawImageData::createData () inherited
Definition at line 69 of file RawImage.cpp.
References rawspeed::RawImageData::bpp, rawspeed::RawImageData::dim, rawspeed::RawImageData::getData(), rawspeed::RawImageData::padding, rawspeed::RawImageData::pitch, rawspeed::RawImageData::poisonPadding(), rawspeed::RawImageData::uncropped_dim, rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
Referenced by LLVMFuzzerTestOneInput(), and rawspeed::RawImageData::RawImageData().
destroyData()
void rawspeed::RawImageData::destroyData () inherited
Definition at line 186 of file RawImage.cpp.
References rawspeed::alignedFree(), rawspeed::RawImageData::data, and rawspeed::RawImageData::mBadPixelMap.
Referenced by rawspeed::RawImageData::~RawImageData().
doLookup()
void rawspeed::RawImageDataFloat::doLookup (int start_y, int end_y) override protected virtual
Implements rawspeed::RawImageData.
Definition at line 378 of file RawImageDataFloat.cpp.
expandBorder()
void rawspeed::RawImageData::expandBorder (iRectangle2D validData) inherited
Definition at line 450 of file RawImage.cpp.
References rawspeed::RawImageData::bpp, rawspeed::RawImageData::dim, rawspeed::iRectangle2D::getBottom(), rawspeed::RawImageData::getData(), rawspeed::iRectangle2D::getOverlap(), rawspeed::iRectangle2D::getRight(), rawspeed::iRectangle2D::iRectangle2D(), rawspeed::iRectangle2D::pos, rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
fixBadPixel()
void rawspeed::RawImageDataFloat::fixBadPixel (uint32_t x, uint32_t y, int component = 0) override protected virtual
Implements rawspeed::RawImageData.
Definition at line 292 of file RawImageDataFloat.cpp.
References rawspeed::RawImageData::cpp, fixBadPixel(), rawspeed::RawImageData::isCFA, rawspeed::RawImageData::mBadPixelMap, and rawspeed::RawImageData::mBadPixelMapPitch.
Referenced by fixBadPixel().
fixBadPixels()
void rawspeed::RawImageData::fixBadPixels () inherited
Definition at line 331 of file RawImage.cpp.
References rawspeed::RawImageWorker::FIX_BAD_PIXELS, rawspeed::RawImageData::mBadPixelMap, rawspeed::RawImageData::startWorker(), and rawspeed::RawImageData::transferBadPixelsToMap().
fixBadPixelsThread()
void rawspeed::RawImageData::fixBadPixelsThread (int start_y, int end_y) protected inherited
Definition at line 408 of file RawImage.cpp.
References rawspeed::RawImageData::fixBadPixel(), rawspeed::RawImageData::mBadPixelMap, rawspeed::RawImageData::mBadPixelMapPitch, rawspeed::RawImageData::uncropped_dim, and rawspeed::iPoint2D::x.
Referenced by rawspeed::RawImageWorker::performTask().
getBpp()
uint32_t rawspeed::RawImageData::getBpp () const inline inherited
Definition at line 101 of file RawImage.h.
References rawspeed::RawImageData::bpp.
Referenced by main(), and rawspeed::UncompressedDecompressor::readUncompressedRaw().
getCpp()
uint32_t rawspeed::RawImageData::getCpp () const inline inherited
Definition at line 100 of file RawImage.h.
References rawspeed::RawImageData::cpp.
Referenced by rawspeed::DngOpcodes::PixelOpcode::applyOP(), rawspeed::LJpegDecompressor::decodeN(), rawspeed::LJpegDecompressor::decodeScan(), main(), rawspeed::AbstractLJpegDecompressor::parseSOF(), rawspeed::DngOpcodes::PixelOpcode::PixelOpcode(), rawspeed::UncompressedDecompressor::readUncompressedRaw(), rawspeed::rstest::writePFM(), and rawspeed::rstest::writePPM().
getData() [1/2]
uint8_t * rawspeed::RawImageData::getData () const inherited
Definition at line 209 of file RawImage.cpp.
References rawspeed::RawImageData::bpp, rawspeed::RawImageData::data, rawspeed::RawImageData::mOffset, rawspeed::RawImageData::pitch, rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
Referenced by rawspeed::UncompressedDecompressor::decode12BitRaw(), rawspeed::UncompressedDecompressor::decode12BitRawUnpackedLeftAligned(), rawspeed::UncompressedDecompressor::decode8BitRaw(), rawspeed::UncompressedDecompressor::decodeRawUnpacked(), and rawspeed::UncompressedDecompressor::readUncompressedRaw().
getData() [2/2]
uint8_t * rawspeed::RawImageData::getData (uint32_t x, uint32_t y) inherited
Definition at line 215 of file RawImage.cpp.
References rawspeed::RawImageData::bpp, rawspeed::RawImageData::data, rawspeed::RawImageData::mOffset, rawspeed::RawImageData::pitch, rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
Referenced by rawspeed::DngOpcodes::FixBadPixelsConstant::apply(), rawspeed::DngOpcodes::PixelOpcode::applyOP(), rawspeed::RawImageData::blitFrom(), rawspeed::RawImageData::createData(), and rawspeed::RawImageData::expandBorder().
getDataType()
rawspeed::RawImageType rawspeed::RawImageData::getDataType () const inline inherited
Definition at line 111 of file RawImage.h.
References rawspeed::RawImageData::dataType.
Referenced by rawspeed::DngOpcodes::OffsetPerRowOrCol< S >::apply(), rawspeed::DngOpcodes::ScalePerRowOrCol< S >::apply(), main(), rawspeed::UncompressedDecompressor::readUncompressedRaw(), rawspeed::DngOpcodes::DeltaRowOrCol< S >::setup(), and rawspeed::rstest::writeImage().
getDataUncropped()
uint8_t * rawspeed::RawImageData::getDataUncropped (uint32_t x, uint32_t y) inherited
Definition at line 230 of file RawImage.cpp.
References rawspeed::RawImageData::bpp, rawspeed::RawImageData::data, and rawspeed::RawImageData::pitch.
Referenced by rawspeed::RawImageData::checkRowIsInitialized(), rawspeed::LJpegDecompressor::decodeN(), rawspeed::rstest::imgDataHash(), main(), rawspeed::rstest::writePFM(), and rawspeed::rstest::writePPM().
getErrors()
std::vector< std::string > && rawspeed::ErrorLog::getErrors () inherited
Definition at line 45 of file ErrorLog.cpp.
getU16DataAsUncroppedArray2DRef()
Array2DRef< uint16_t > rawspeed::RawImageData::getU16DataAsUncroppedArray2DRef () const inline noexcept inherited
Definition at line 267 of file RawImage.h.
References rawspeed::RawImageData::data, rawspeed::RawImageData::dataType, and rawspeed::TYPE_USHORT16.
GUARDED_BY() [1/2]
std::vector<uint32_t> mBadPixelPositions rawspeed::RawImageData::GUARDED_BY (mBadPixelMutex) inherited
GUARDED_BY() [2/2]
uint32_t dataRefCount rawspeed::RawImageData::GUARDED_BY (mymutex) private pure virtual inherited
isAllocated()
bool rawspeed::RawImageData::isAllocated () inline inherited
Definition at line 134 of file RawImage.h.
References rawspeed::RawImageData::data.
isTooManyErrors()
bool rawspeed::ErrorLog::isTooManyErrors (unsigned many, std::string * firstErr = nullptr) inherited
Definition at line 32 of file ErrorLog.cpp.
poisonPadding()
void rawspeed::RawImageData::poisonPadding () inherited
Definition at line 135 of file RawImage.cpp.
Referenced by rawspeed::RawImageData::createData().
scaleBlackWhite()
void rawspeed::RawImageDataFloat::scaleBlackWhite () override virtual
Implements rawspeed::RawImageData.
Definition at line 117 of file RawImageDataFloat.cpp.
References rawspeed::RawImageData::blackLevel, calculateBlackAreas(), rawspeed::RawImageData::cpp, rawspeed::DEBUG_PRIO_INFO, rawspeed::RawImageData::dim, rawspeed::RawImageData::whitePoint, rawspeed::writeLog(), rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
scaleValues()
void rawspeed::RawImageDataFloat::scaleValues (int start_y, int end_y) override protected virtual
Implements rawspeed::RawImageData.
Definition at line 261 of file RawImageDataFloat.cpp.
References rawspeed::RawImageData::cpp, rawspeed::RawImageData::dim, rawspeed::RawImageData::mOffset, rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
setCpp()
void rawspeed::RawImageData::setCpp (uint32_t val) inherited
Definition at line 195 of file RawImage.cpp.
References rawspeed::RawImageData::bpp, and rawspeed::RawImageData::cpp.
Referenced by CreateRawImage().
setError()
void rawspeed::ErrorLog::setError (const std::string & err) inherited
Definition at line 27 of file ErrorLog.cpp.
setTable() [1/2]
void rawspeed::RawImageData::setTable (const std::vector< uint16_t > & table_, bool dither) inherited
Definition at line 568 of file RawImage.cpp.
setTable() [2/2]
void rawspeed::RawImageData::setTable (std::unique_ptr< TableLookUp > t) inherited
Definition at line 564 of file RawImage.cpp.
setWithLookUp()
void rawspeed::RawImageDataFloat::setWithLookUp (uint16_t value, uint8_t * dst, uint32_t * random) override virtual
Implements rawspeed::RawImageData.
Definition at line 382 of file RawImageDataFloat.cpp.
sixteenBitLookup()
void rawspeed::RawImageData::sixteenBitLookup () inherited
Definition at line 557 of file RawImage.cpp.
References rawspeed::RawImageWorker::APPLY_LOOKUP.
startWorker()
void rawspeed::RawImageData::startWorker (RawImageWorker::RawImageWorkerTask task, bool cropped) protected inherited
Definition at line 382 of file RawImage.cpp.
References __attribute__(), rawspeed::RawImageData::dim, rawspeed::RawImageWorker::FULL_IMAGE, rawspeed::RawImageWorker::RawImageWorker(), rawspeed::RawImageData::uncropped_dim, and rawspeed::iPoint2D::y.
Referenced by rawspeed::RawImageData::fixBadPixels().
subFrame()
void rawspeed::RawImageData::subFrame (iRectangle2D cropped) inherited
Referenced by rawspeed::DngOpcodes::TrimBounds::apply().
transferBadPixelsToMap()
void rawspeed::RawImageData::transferBadPixelsToMap () inherited
Definition at line 310 of file RawImage.cpp.
References rawspeed::RawImageData::createBadPixelMap(), and rawspeed::RawImageData::mBadPixelMap.
Referenced by rawspeed::RawImageData::fixBadPixels().
unpoisonPadding()
void rawspeed::RawImageData::unpoisonPadding () inherited
Definition at line 156 of file RawImage.cpp.
Friends And Related Function Documentation
RawImage
friend class RawImage friend
Definition at line 217 of file RawImage.h.
Member Data Documentation
blackAreas
std::vector<BlackArea> rawspeed::RawImageData::blackAreas inherited
Definition at line 148 of file RawImage.h.
blackLevel
int rawspeed::RawImageData::blackLevel = -1 inherited
Definition at line 145 of file RawImage.h.
Referenced by main(), rawspeed::RawImageDataU16::scaleBlackWhite(), and scaleBlackWhite().
blackLevelSeparate
std::array<int, 4> rawspeed::RawImageData::blackLevelSeparate inherited
Definition at line 146 of file RawImage.h.
bpp
int rawspeed::RawImageData::bpp = 0 protected inherited
Definition at line 177 of file RawImage.h.
Referenced by rawspeed::RawImageData::blitFrom(), rawspeed::RawImageData::checkRowIsInitialized(), rawspeed::RawImageData::createData(), rawspeed::RawImageData::expandBorder(), rawspeed::RawImageData::getBpp(), rawspeed::RawImageData::getData(), rawspeed::RawImageData::getDataUncropped(), rawspeed::RawImageData::RawImageData(), RawImageDataFloat(), rawspeed::RawImageDataU16::RawImageDataU16(), and rawspeed::RawImageData::setCpp().
cfa
ColorFilterArray rawspeed::RawImageData::cfa inherited
Definition at line 144 of file RawImage.h.
cpp
int rawspeed::RawImageData::cpp = 1 protected inherited
Definition at line 176 of file RawImage.h.
Referenced by rawspeed::RawImageDataU16::doLookup(), rawspeed::RawImageDataU16::fixBadPixel(), fixBadPixel(), rawspeed::RawImageData::getCpp(), rawspeed::RawImageData::RawImageData(), rawspeed::RawImageDataU16::scaleBlackWhite(), scaleBlackWhite(), scaleValues(), rawspeed::RawImageDataU16::scaleValues_plain(), and rawspeed::RawImageData::setCpp().
data
uint8_t* rawspeed::RawImageData::data = nullptr protected inherited
Definition at line 175 of file RawImage.h.
Referenced by rawspeed::RawImageData::destroyData(), rawspeed::RawImageData::getData(), rawspeed::RawImageData::getDataUncropped(), rawspeed::RawImageData::getU16DataAsUncroppedArray2DRef(), and rawspeed::RawImageData::isAllocated().
dataType
RawImageType rawspeed::RawImageData::dataType protected inherited
Definition at line 167 of file RawImage.h.
Referenced by rawspeed::RawImageData::getDataType(), rawspeed::RawImageData::getU16DataAsUncroppedArray2DRef(), RawImageDataFloat(), and rawspeed::RawImageDataU16::RawImageDataU16().
dim
iPoint2D rawspeed::RawImageData::dim inherited
Definition at line 136 of file RawImage.h.
Referenced by rawspeed::DngOpcodes::FixBadPixelsConstant::apply(), rawspeed::RawImageData::blitFrom(), rawspeed::PanasonicDecompressorV4::chopInputIntoBlocks(), rawspeed::PanasonicDecompressorV5::chopInputIntoBlocks(), rawspeed::RawImageData::clearArea(), compressChunk(), rawspeed::SamsungV0Decompressor::computeStripes(), rawspeed::Cr2Decompressor::Cr2Decompressor(), rawspeed::RawImageData::createData(), CreateRawImage(), rawspeed::CrwDecompressor::CrwDecompressor(), rawspeed::LJpegDecompressor::decodeN(), rawspeed::Cr2Decompressor::decodeN_X_Y(), rawspeed::LJpegDecompressor::decodeScan(), rawspeed::NikonDecompressor::decompress(), rawspeed::OlympusDecompressor::decompress(), rawspeed::OlympusDecompressor::decompressRow(), rawspeed::SonyArw2Decompressor::decompressThread(), rawspeed::RawImageData::expandBorder(), rawspeed::HasselbladDecompressor::HasselbladDecompressor(), rawspeed::KodakDecompressor::KodakDecompressor(), main(), rawspeed::NikonDecompressor::NikonDecompressor(), rawspeed::OlympusDecompressor::OlympusDecompressor(), rawspeed::PanasonicDecompressorV4::PanasonicDecompressorV4(), rawspeed::PanasonicDecompressorV5::PanasonicDecompressorV5(), rawspeed::PanasonicDecompressorV6::PanasonicDecompressorV6(), rawspeed::AbstractLJpegDecompressor::parseSOF(), rawspeed::VC5Decompressor::parseVC5(), rawspeed::PentaxDecompressor::PentaxDecompressor(), rawspeed::PhaseOneDecompressor::PhaseOneDecompressor(), rawspeed::PanasonicDecompressorV4::processBlock(), rawspeed::PanasonicDecompressorV5::processBlock(), rawspeed::RawImageData::RawImageData(), rawspeed::DngOpcodes::ROIOpcode::ROIOpcode(), rawspeed::SamsungV0Decompressor::SamsungV0Decompressor(), rawspeed::SamsungV1Decompressor::SamsungV1Decompressor(), rawspeed::RawImageDataU16::scaleBlackWhite(), scaleBlackWhite(), scaleValues(), rawspeed::RawImageDataU16::scaleValues_plain(), rawspeed::SonyArw1Decompressor::SonyArw1Decompressor(), rawspeed::SonyArw2Decompressor::SonyArw2Decompressor(), and rawspeed::RawImageData::startWorker().
isCFA
bool rawspeed::RawImageData::isCFA {true} inherited
Definition at line 143 of file RawImage.h.
Referenced by rawspeed::RawImageDataU16::calculateBlackAreas(), calculateBlackAreas(), CreateRawImage(), rawspeed::RawImageDataU16::fixBadPixel(), fixBadPixel(), main(), and rawspeed::RawImageData::RawImageData().
mBadPixelMap
uint8_t* rawspeed::RawImageData::mBadPixelMap = nullptr inherited
Definition at line 154 of file RawImage.h.
Referenced by rawspeed::RawImageData::destroyData(), rawspeed::RawImageDataU16::fixBadPixel(), fixBadPixel(), rawspeed::RawImageData::fixBadPixels(), rawspeed::RawImageData::fixBadPixelsThread(), and rawspeed::RawImageData::transferBadPixelsToMap().
mBadPixelMapPitch
uint32_t rawspeed::RawImageData::mBadPixelMapPitch = 0 inherited
Definition at line 155 of file RawImage.h.
Referenced by rawspeed::RawImageDataU16::fixBadPixel(), fixBadPixel(), and rawspeed::RawImageData::fixBadPixelsThread().
mBadPixelMutex
Mutex rawspeed::RawImageData::mBadPixelMutex inherited
Definition at line 160 of file RawImage.h.
mDitherScale
bool rawspeed::RawImageData::mDitherScale inherited
Initial value:
=
      true
Definition at line 156 of file RawImage.h.
Referenced by rawspeed::RawImageDataU16::scaleValues_plain().
metadata
ImageMetaData rawspeed::RawImageData::metadata inherited
Definition at line 158 of file RawImage.h.
mOffset
iPoint2D rawspeed::RawImageData::mOffset protected inherited
Definition at line 179 of file RawImage.h.
Referenced by rawspeed::RawImageData::getData(), scaleValues(), rawspeed::RawImageDataU16::scaleValues_plain(), and rawspeed::RawImageData::~RawImageData().
mutex
Mutex rawspeed::ErrorLog::mutex private inherited
Definition at line 31 of file ErrorLog.h.
mymutex
Mutex rawspeed::RawImageData::mymutex protected inherited
Definition at line 182 of file RawImage.h.
padding
uint32_t rawspeed::RawImageData::padding = 0 inherited
Definition at line 141 of file RawImage.h.
Referenced by rawspeed::RawImageData::createData().
pitch
int rawspeed::RawImageData::pitch = 0 inherited
Definition at line 137 of file RawImage.h.
Referenced by rawspeed::RawImageData::blitFrom(), rawspeed::RawImageData::createData(), rawspeed::UncompressedDecompressor::decode12BitRaw(), rawspeed::UncompressedDecompressor::decode12BitRawUnpackedLeftAligned(), rawspeed::UncompressedDecompressor::decode8BitRaw(), rawspeed::UncompressedDecompressor::decodeRawUnpacked(), rawspeed::RawImageData::getData(), rawspeed::RawImageData::getDataUncropped(), and rawspeed::UncompressedDecompressor::readUncompressedRaw().
table
std::unique_ptr<TableLookUp> rawspeed::RawImageData::table protected inherited
Definition at line 181 of file RawImage.h.
uncropped_dim
iPoint2D rawspeed::RawImageData::uncropped_dim protected inherited
Definition at line 180 of file RawImage.h.
Referenced by rawspeed::RawImageData::checkRowIsInitialized(), rawspeed::RawImageData::createData(), rawspeed::RawImageDataU16::doLookup(), rawspeed::RawImageData::fixBadPixelsThread(), and rawspeed::RawImageData::startWorker().
whitePoint
int rawspeed::RawImageData::whitePoint = 65536 inherited
Definition at line 147 of file RawImage.h.
Referenced by main(), rawspeed::RawImageDataU16::scaleBlackWhite(), scaleBlackWhite(), and rawspeed::VC5Decompressor::VC5Decompressor().
The documentation for this class was generated from the following files:
librawspeed/common/RawImage.h
librawspeed/common/RawImageDataFloat.cpp