RawSpeed: rawspeed::AbstractLJpegDecompressor Class Reference
rawspeed::AbstractLJpegDecompressor Class Reference
#include "decompressors/AbstractLJpegDecompressor.h"
Public Member Functions
AbstractLJpegDecompressor (ByteStream bs, const RawImage &img)
virtual ~AbstractLJpegDecompressor ()=default
Protected Member Functions
void decode ()
void parseSOF (ByteStream data, SOFInfo *i)
void parseSOS (ByteStream data)
void parseDHT (ByteStream data)
JpegMarker getNextMarker (bool allowskip)
template<int N_COMP>
std::array< HuffmanTable *, N_COMP > getHuffmanTables () const
Protected Attributes
bool fixDng16Bug = false
bool fullDecodeHT = true
template<int N_COMP>
__attribute__((pure)) std ByteStream input
RawImage mRaw
SOFInfo frame
uint32_t predictorMode = 0
Private Attributes
std::vector< std::unique_ptr< HuffmanTable > > huffmanTableStore
HuffmanTable ht_
uint32_t Pt = 0
std::array< HuffmanTable *, 4 > huff {{}}
Detailed Description
Definition at line 139 of file AbstractLJpegDecompressor.h.
Constructor & Destructor Documentation
AbstractLJpegDecompressor()
rawspeed::AbstractLJpegDecompressor::AbstractLJpegDecompressor (ByteStream bs, const RawImage & img)
Definition at line 38 of file AbstractLJpegDecompressor.cpp.
References AbstractLJpegDecompressor(), rawspeed::big, input, mRaw, and rawspeed::RawImage::RawImage().
Referenced by AbstractLJpegDecompressor(), rawspeed::Cr2Decompressor::Cr2Decompressor(), anonymous_namespace{DummyLJpegDecompressor.cpp}::DummyLJpegDecompressor::DummyLJpegDecompressor(), rawspeed::HasselbladDecompressor::HasselbladDecompressor(), and rawspeed::LJpegDecompressor::LJpegDecompressor().
~AbstractLJpegDecompressor()
virtual rawspeed::AbstractLJpegDecompressor::~AbstractLJpegDecompressor () virtual default
Member Function Documentation
decode()
void rawspeed::AbstractLJpegDecompressor::decode () protected
Definition at line 55 of file AbstractLJpegDecompressor.cpp.
References getNextMarker(), rawspeed::ByteStream::getStream(), input, rawspeed::M_EOI, parseDHT(), parseSOS(), rawspeed::ByteStream::peekU16(), and rawspeed::ByteStream::skipBytes().
getHuffmanTables()
template<int N_COMP> std::array<HuffmanTable*, N_COMP> rawspeed::AbstractLJpegDecompressor::getHuffmanTables () const inline protected
Definition at line 163 of file AbstractLJpegDecompressor.h.
getNextMarker()
JpegMarker rawspeed::AbstractLJpegDecompressor::getNextMarker (bool allowskip) protected
Definition at line 254 of file AbstractLJpegDecompressor.cpp.
References rawspeed::ByteStream::getByte(), and input.
Referenced by decode().
parseDHT()
void rawspeed::AbstractLJpegDecompressor::parseDHT (ByteStream data) protected
Definition at line 214 of file AbstractLJpegDecompressor.cpp.
References rawspeed::ByteStream::getByte(), and rawspeed::ByteStream::getRemainSize().
Referenced by decode().
parseSOF()
void rawspeed::AbstractLJpegDecompressor::parseSOF (ByteStream data, SOFInfo * i) protected
Definition at line 114 of file AbstractLJpegDecompressor.cpp.
References rawspeed::SOFInfo::cps, rawspeed::RawImageData::dim, rawspeed::ByteStream::getByte(), rawspeed::RawImageData::getCpp(), rawspeed::ByteStream::getU16(), rawspeed::SOFInfo::h, rawspeed::SOFInfo::initialized, mRaw, rawspeed::RawImage::operator->(), rawspeed::SOFInfo::prec, rawspeed::SOFInfo::w, and rawspeed::iPoint2D::x.
parseSOS()
void rawspeed::AbstractLJpegDecompressor::parseSOS (ByteStream data) protected
Definition at line 168 of file AbstractLJpegDecompressor.cpp.
References rawspeed::ByteStream::getByte(), predictorMode, and Pt.
Referenced by decode().
Member Data Documentation
fixDng16Bug
bool rawspeed::AbstractLJpegDecompressor::fixDng16Bug = false protected
Definition at line 153 of file AbstractLJpegDecompressor.h.
Referenced by rawspeed::LJpegDecompressor::decode().
frame
SOFInfo rawspeed::AbstractLJpegDecompressor::frame protected
Definition at line 195 of file AbstractLJpegDecompressor.h.
fullDecodeHT
bool rawspeed::AbstractLJpegDecompressor::fullDecodeHT = true protected
Definition at line 154 of file AbstractLJpegDecompressor.h.
Referenced by rawspeed::HasselbladDecompressor::decode().
ht_
HuffmanTable rawspeed::AbstractLJpegDecompressor::ht_ private
Definition at line 142 of file AbstractLJpegDecompressor.h.
huff
std::array<HuffmanTable*, 4> rawspeed::AbstractLJpegDecompressor::huff {{}} private
Definition at line 145 of file AbstractLJpegDecompressor.h.
huffmanTableStore
std::vector<std::unique_ptr<HuffmanTable> > rawspeed::AbstractLJpegDecompressor::huffmanTableStore private
Definition at line 141 of file AbstractLJpegDecompressor.h.
input
template<int N_COMP> __attribute__ ((pure)) std ByteStream rawspeed::AbstractLJpegDecompressor::input protected
Definition at line 179 of file AbstractLJpegDecompressor.h.
Referenced by AbstractLJpegDecompressor(), decode(), and getNextMarker().
mRaw
RawImage rawspeed::AbstractLJpegDecompressor::mRaw protected
Definition at line 193 of file AbstractLJpegDecompressor.h.
Referenced by AbstractLJpegDecompressor(), rawspeed::Cr2Decompressor::Cr2Decompressor(), rawspeed::LJpegDecompressor::decodeN(), rawspeed::Cr2Decompressor::decodeN_X_Y(), rawspeed::LJpegDecompressor::decodeScan(), rawspeed::HasselbladDecompressor::HasselbladDecompressor(), and parseSOF().
predictorMode
uint32_t rawspeed::AbstractLJpegDecompressor::predictorMode = 0 protected
Definition at line 196 of file AbstractLJpegDecompressor.h.
Referenced by parseSOS().
Pt
uint32_t rawspeed::AbstractLJpegDecompressor::Pt = 0 private
Definition at line 144 of file AbstractLJpegDecompressor.h.
Referenced by parseSOS().
The documentation for this class was generated from the following files:
librawspeed/decompressors/AbstractLJpegDecompressor.h
librawspeed/decompressors/AbstractLJpegDecompressor.cpp