RawSpeed: rawspeed::PhaseOneDecompressor Class Reference
rawspeed::PhaseOneDecompressor Class Reference final
#include "decompressors/PhaseOneDecompressor.h"
Public Member Functions
PhaseOneDecompressor (const RawImage &img, std::vector< PhaseOneStrip > &&strips_)
void decompress () const
Private Member Functions
void decompressStrip (const PhaseOneStrip &strip) const
void decompressThread () const noexcept
void prepareStrips ()
Private Attributes
RawImage mRaw
std::vector< PhaseOneStrip > strips
Detailed Description
Definition at line 41 of file PhaseOneDecompressor.h.
Constructor & Destructor Documentation
PhaseOneDecompressor()
rawspeed::PhaseOneDecompressor::PhaseOneDecompressor (const RawImage & img, std::vector< PhaseOneStrip > && strips_)
Definition at line 43 of file PhaseOneDecompressor.cpp.
References rawspeed::RawImageData::dim, rawspeed::iPoint2D::hasPositiveArea(), mRaw, rawspeed::RawImage::operator->(), PhaseOneDecompressor(), prepareStrips(), rawspeed::RawImage::RawImage(), rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
Referenced by PhaseOneDecompressor().
Member Function Documentation
decompress()
void rawspeed::PhaseOneDecompressor::decompress () const
Definition at line 151 of file PhaseOneDecompressor.cpp.
References decompressThread().
Referenced by LLVMFuzzerTestOneInput().
decompressStrip()
void rawspeed::PhaseOneDecompressor::decompressStrip (const PhaseOneStrip & strip) const private
Definition at line 85 of file PhaseOneDecompressor.cpp.
References rawspeed::PhaseOneStrip::n.
decompressThread()
void rawspeed::PhaseOneDecompressor::decompressThread () const private noexcept
Definition at line 137 of file PhaseOneDecompressor.cpp.
Referenced by decompress().
prepareStrips()
void rawspeed::PhaseOneDecompressor::prepareStrips () private
Definition at line 61 of file PhaseOneDecompressor.cpp.
Referenced by PhaseOneDecompressor().
Member Data Documentation
mRaw
RawImage rawspeed::PhaseOneDecompressor::mRaw private
Definition at line 42 of file PhaseOneDecompressor.h.
Referenced by PhaseOneDecompressor().
strips
std::vector<PhaseOneStrip> rawspeed::PhaseOneDecompressor::strips private
Definition at line 44 of file PhaseOneDecompressor.h.
The documentation for this class was generated from the following files:
librawspeed/decompressors/PhaseOneDecompressor.h
librawspeed/decompressors/PhaseOneDecompressor.cpp