RawSpeed: rawspeed::OlympusDecompressor Class Reference
rawspeed::OlympusDecompressor Class Reference final
#include "decompressors/OlympusDecompressor.h"
Public Member Functions
OlympusDecompressor (const RawImage &img)
void decompress (ByteStream input) const
Private Member Functions
__attribute__ ((always_inline)) int parseCarry(BitPumpMSB *bits
void decompressRow (BitPumpMSB *bits, int row) const
Static Private Member Functions
static int getPred (Array2DRef< uint16_t > out, int row, int col)
Private Attributes
RawImage mRaw
const SimpleLUT< char, 12 > bittable
std::array< int, 3 > *carry const
Detailed Description
Definition at line 38 of file OlympusDecompressor.h.
Constructor & Destructor Documentation
OlympusDecompressor()
rawspeed::OlympusDecompressor::OlympusDecompressor (const RawImage & img) explicit
Definition at line 51 of file OlympusDecompressor.cpp.
References rawspeed::RawImageData::dim, mRaw, rawspeed::RawImage::operator->(), rawspeed::RawImage::RawImage(), rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
Member Function Documentation
__attribute__()
rawspeed::OlympusDecompressor::__attribute__ ((always_inline)) inline private
decompress()
void rawspeed::OlympusDecompressor::decompress (ByteStream input) const
Definition at line 156 of file OlympusDecompressor.cpp.
References rawspeed::RawImageData::dim, mRaw, rawspeed::RawImage::operator->(), rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
decompressRow()
void rawspeed::OlympusDecompressor::decompressRow (BitPumpMSB * bits, int row) const private
Definition at line 135 of file OlympusDecompressor.cpp.
References rawspeed::RawImageData::dim, mRaw, rawspeed::RawImage::operator->(), rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
getPred()
static int rawspeed::OlympusDecompressor::getPred (Array2DRef< uint16_t > out, int row, int col) inline static private
Member Data Documentation
bittable
const SimpleLUT<char, 12> rawspeed::OlympusDecompressor::bittable private
Initial value:
{[](unsigned i, unsigned tableSize) {
    int high;
    for (high = 0; high < 12; high++)
      if (extractHighBits(i, high, 11) & 1)
        break;
    return std::min(12, high);
  }}
Definition at line 42 of file OlympusDecompressor.h.
const
std::array<int, 3>* carry rawspeed::OlympusDecompressor::const private
Definition at line 51 of file OlympusDecompressor.h.
mRaw
RawImage rawspeed::OlympusDecompressor::mRaw private
Definition at line 39 of file OlympusDecompressor.h.
Referenced by decompress(), decompressRow(), and OlympusDecompressor().
The documentation for this class was generated from the following files:
librawspeed/decompressors/OlympusDecompressor.h
librawspeed/decompressors/OlympusDecompressor.cpp