RawSpeed: rawspeed::VC5Decompressor::Wavelet::HighPassBand Struct Reference
rawspeed::VC5Decompressor::Wavelet::HighPassBand Struct Reference final
#include "decompressors/VC5Decompressor.h"
Public Member Functions
HighPassBand (ByteStream bs_, int16_t quant_)
void decode (const Wavelet &wavelet) final
Public Attributes
int16_t quant
ByteStream bs
std::vector< int16_t, DefaultInitAllocatorAdaptor< int16_t > > data
Detailed Description
Definition at line 150 of file VC5Decompressor.h.
Constructor & Destructor Documentation
HighPassBand()
rawspeed::VC5Decompressor::Wavelet::HighPassBand::HighPassBand (ByteStream bs_, int16_t quant_) inline
Definition at line 152 of file VC5Decompressor.h.
References HighPassBand(), and quant.
Referenced by HighPassBand().
Member Function Documentation
decode()
void rawspeed::VC5Decompressor::Wavelet::HighPassBand::decode (const Wavelet & wavelet) final virtual
Implements rawspeed::VC5Decompressor::Wavelet::AbstractBand.
Definition at line 541 of file VC5Decompressor.cpp.
References anonymous_namespace{VC5Decompressor.cpp}::decompand(), rawspeed::VC5Decompressor::Wavelet::height, quant, and rawspeed::VC5Decompressor::Wavelet::width.
Member Data Documentation
bs
ByteStream rawspeed::VC5Decompressor::Wavelet::AbstractDecodeableBand::bs inherited
Definition at line 141 of file VC5Decompressor.h.
data
std::vector<int16_t, DefaultInitAllocatorAdaptor<int16_t> > rawspeed::VC5Decompressor::Wavelet::AbstractBand::data inherited
Definition at line 123 of file VC5Decompressor.h.
quant
int16_t rawspeed::VC5Decompressor::Wavelet::HighPassBand::quant
Definition at line 151 of file VC5Decompressor.h.
Referenced by decode(), and HighPassBand().
The documentation for this struct was generated from the following files:
librawspeed/decompressors/VC5Decompressor.h
librawspeed/decompressors/VC5Decompressor.cpp