RawSpeed: litsupport_rawspeed.modules.rsbench Namespace Reference
litsupport_rawspeed.modules.rsbench Namespace Reference
Functions
def _mutateCommandLine (context, commandline)
def _mutateScript (context, script)
def _collectMicrobenchmarkTime (context, microbenchfiles)
def mutatePlan (context, plan)
Detailed Description
Test module to collect google benchmark results.
Function Documentation
_collectMicrobenchmarkTime()
def litsupport_rawspeed.modules.rsbench._collectMicrobenchmarkTime (context, microbenchfiles) private
Definition at line 30 of file rsbench.py.
Referenced by litsupport_rawspeed.modules.rsbench.mutatePlan().
_mutateCommandLine()
def litsupport_rawspeed.modules.rsbench._mutateCommandLine (context, commandline) private
Definition at line 12 of file rsbench.py.
_mutateScript()
def litsupport_rawspeed.modules.rsbench._mutateScript (context, script) private
Definition at line 26 of file rsbench.py.
Referenced by litsupport_rawspeed.modules.rsbench.mutatePlan().
mutatePlan()
def litsupport_rawspeed.modules.rsbench.mutatePlan (context, plan)
Definition at line 68 of file rsbench.py.
References litsupport_rawspeed.modules.rsbench._collectMicrobenchmarkTime(), and litsupport_rawspeed.modules.rsbench._mutateScript().