RawSpeed: rawspeed::SonyArw1Decompressor Class Reference
rawspeed::SonyArw1Decompressor Class Reference final
#include "decompressors/SonyArw1Decompressor.h"
Public Member Functions
SonyArw1Decompressor (const RawImage &img)
void decompress (const ByteStream &input) const
Static Private Member Functions
static int getDiff (BitPumpMSB *bs, uint32_t len)
Private Attributes
RawImage mRaw
Detailed Description
Definition at line 32 of file SonyArw1Decompressor.h.
Constructor & Destructor Documentation
SonyArw1Decompressor()
rawspeed::SonyArw1Decompressor::SonyArw1Decompressor (const RawImage & img) explicit
Definition at line 35 of file SonyArw1Decompressor.cpp.
References rawspeed::RawImageData::dim, mRaw, rawspeed::RawImage::operator->(), rawspeed::RawImage::RawImage(), rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
Referenced by LLVMFuzzerTestOneInput().
Member Function Documentation
decompress()
void rawspeed::SonyArw1Decompressor::decompress (const ByteStream & input) const
Definition at line 54 of file SonyArw1Decompressor.cpp.
Referenced by LLVMFuzzerTestOneInput().
getDiff()
int rawspeed::SonyArw1Decompressor::getDiff (BitPumpMSB * bs, uint32_t len) inline static private
Definition at line 47 of file SonyArw1Decompressor.cpp.
References rawspeed::AbstractHuffmanTable::__attribute__().
Member Data Documentation
mRaw
RawImage rawspeed::SonyArw1Decompressor::mRaw private
Definition at line 33 of file SonyArw1Decompressor.h.
Referenced by SonyArw1Decompressor().
The documentation for this class was generated from the following files:
librawspeed/decompressors/SonyArw1Decompressor.h
librawspeed/decompressors/SonyArw1Decompressor.cpp