RawSpeed: rawspeed::RawImage Class Reference
rawspeed::RawImage Class Reference
#include "common/RawImage.h"
Public Member Functions
RawImageData * operator-> () const
RawImageData & operator* () const
RawImage (RawImageData *p)
~RawImage ()
RawImage (const RawImage &p)
RawImage & operator= (const RawImage &p) noexcept
RawImage & operator= (RawImage &&p) noexcept
RawImageData * get ()
Static Public Member Functions
static RawImage create (RawImageType type=TYPE_USHORT16)
static RawImage create (const iPoint2D &dim, RawImageType type=TYPE_USHORT16, uint32_t componentsPerPixel=1)
Private Attributes
RawImageData * p_
Detailed Description
Definition at line 220 of file RawImage.h.
Constructor & Destructor Documentation
RawImage() [1/2]
rawspeed::RawImage::RawImage (RawImageData * p) explicit
Definition at line 286 of file RawImage.cpp.
References p_.
~RawImage()
rawspeed::RawImage::~RawImage ()
Definition at line 296 of file RawImage.cpp.
References p_.
RawImage() [2/2]
rawspeed::RawImage::RawImage (const RawImage & p)
Definition at line 291 of file RawImage.cpp.
References p_.
Referenced by rawspeed::AbstractLJpegDecompressor::AbstractLJpegDecompressor(), rawspeed::AbstractSamsungDecompressor::AbstractSamsungDecompressor(), rawspeed::CrwDecompressor::CrwDecompressor(), rawspeed::FujiDecompressor::FujiDecompressor(), rawspeed::KodakDecompressor::KodakDecompressor(), rawspeed::NikonDecompressor::NikonDecompressor(), rawspeed::OlympusDecompressor::OlympusDecompressor(), operator=(), rawspeed::PanasonicDecompressorV4::PanasonicDecompressorV4(), rawspeed::PanasonicDecompressorV5::PanasonicDecompressorV5(), rawspeed::PanasonicDecompressorV6::PanasonicDecompressorV6(), rawspeed::PentaxDecompressor::PentaxDecompressor(), rawspeed::PhaseOneDecompressor::PhaseOneDecompressor(), rawspeed::SonyArw1Decompressor::SonyArw1Decompressor(), rawspeed::SonyArw2Decompressor::SonyArw2Decompressor(), and rawspeed::VC5Decompressor::VC5Decompressor().
Member Function Documentation
create() [1/2]
RawImage rawspeed::RawImage::create (const iPoint2D & dim, RawImageType type = TYPE_USHORT16, uint32_t componentsPerPixel = 1) inline static
Definition at line 253 of file RawImage.h.
References rawspeed::DEBUG_PRIO_ERROR, and rawspeed::writeLog().
Referenced by BM_Cr2sRawInterpolator().
create() [2/2]
RawImage rawspeed::RawImage::create (RawImageType type = TYPE_USHORT16) inline static
Definition at line 239 of file RawImage.h.
References rawspeed::DEBUG_PRIO_ERROR, and rawspeed::writeLog().
Referenced by CreateRawImage().
get()
RawImageData* rawspeed::RawImage::get () inline
Definition at line 234 of file RawImage.h.
References p_.
Referenced by rawspeed::NikonDecompressor::decompress().
operator*()
RawImageData& rawspeed::RawImage::operator* () const inline
Definition at line 227 of file RawImage.h.
References p_.
Referenced by rawspeed::SonyArw2Decompressor::decompressRow().
operator->()
RawImageData* rawspeed::RawImage::operator-> () const inline
Definition at line 226 of file RawImage.h.
References p_.
Referenced by rawspeed::DngOpcodes::FixBadPixelsConstant::apply(), rawspeed::DngOpcodes::TrimBounds::apply(), rawspeed::DngOpcodes::OffsetPerRowOrCol< S >::apply(), rawspeed::DngOpcodes::ScalePerRowOrCol< S >::apply(), rawspeed::DngOpcodes::PixelOpcode::applyOP(), rawspeed::RawImageData::blitFrom(), rawspeed::PanasonicDecompressorV4::chopInputIntoBlocks(), rawspeed::PanasonicDecompressorV5::chopInputIntoBlocks(), compressChunk(), rawspeed::SamsungV0Decompressor::computeStripes(), rawspeed::Cr2Decompressor::Cr2Decompressor(), CreateRawImage(), rawspeed::CrwDecompressor::CrwDecompressor(), rawspeed::UncompressedDecompressor::decode12BitRaw(), rawspeed::UncompressedDecompressor::decode12BitRawUnpackedLeftAligned(), rawspeed::UncompressedDecompressor::decode8BitRaw(), rawspeed::LJpegDecompressor::decodeN(), rawspeed::Cr2Decompressor::decodeN_X_Y(), rawspeed::UncompressedDecompressor::decodeRawUnpacked(), rawspeed::LJpegDecompressor::decodeScan(), rawspeed::NikonDecompressor::decompress(), rawspeed::OlympusDecompressor::decompress(), rawspeed::OlympusDecompressor::decompressRow(), rawspeed::SonyArw2Decompressor::decompressThread(), rawspeed::DngOpcodes::FixBadPixelsList::FixBadPixelsList(), rawspeed::HasselbladDecompressor::HasselbladDecompressor(), rawspeed::rstest::imgDataHash(), rawspeed::KodakDecompressor::KodakDecompressor(), LLVMFuzzerTestOneInput(), main(), rawspeed::NikonDecompressor::NikonDecompressor(), rawspeed::OlympusDecompressor::OlympusDecompressor(), rawspeed::PanasonicDecompressorV4::PanasonicDecompressorV4(), rawspeed::PanasonicDecompressorV5::PanasonicDecompressorV5(), rawspeed::PanasonicDecompressorV6::PanasonicDecompressorV6(), rawspeed::AbstractLJpegDecompressor::parseSOF(), rawspeed::VC5Decompressor::parseVC5(), rawspeed::PentaxDecompressor::PentaxDecompressor(), rawspeed::PhaseOneDecompressor::PhaseOneDecompressor(), rawspeed::DngOpcodes::PixelOpcode::PixelOpcode(), rawspeed::PanasonicDecompressorV4::processBlock(), rawspeed::PanasonicDecompressorV5::processBlock(), rawspeed::UncompressedDecompressor::readUncompressedRaw(), rawspeed::DngOpcodes::ROIOpcode::ROIOpcode(), rawspeed::SamsungV0Decompressor::SamsungV0Decompressor(), rawspeed::SamsungV1Decompressor::SamsungV1Decompressor(), rawspeed::DngOpcodes::DeltaRowOrCol< S >::setup(), rawspeed::SonyArw1Decompressor::SonyArw1Decompressor(), rawspeed::SonyArw2Decompressor::SonyArw2Decompressor(), rawspeed::VC5Decompressor::VC5Decompressor(), rawspeed::rstest::writeImage(), rawspeed::rstest::writePFM(), and rawspeed::rstest::writePPM().
operator=() [1/2]
RawImage & rawspeed::RawImage::operator= (const RawImage & p) noexcept
Definition at line 516 of file RawImage.cpp.
References RawImage().
operator=() [2/2]
RawImage & rawspeed::RawImage::operator= (RawImage && p) noexcept
Definition at line 507 of file RawImage.cpp.
Member Data Documentation
p_
RawImageData* rawspeed::RawImage::p_ private
Definition at line 236 of file RawImage.h.
Referenced by get(), operator*(), operator->(), RawImage(), and ~RawImage().
The documentation for this class was generated from the following files:
librawspeed/common/RawImage.h
librawspeed/common/RawImage.cpp