RawSpeed: rawspeed::VC5Decompressor::Wavelet::LowPassBand Struct Reference
rawspeed::VC5Decompressor::Wavelet::LowPassBand Struct Reference final
#include "decompressors/VC5Decompressor.h"
Public Member Functions
LowPassBand (const Wavelet &wavelet, ByteStream bs_, uint16_t lowpassPrecision_)
void decode (const Wavelet &wavelet) final
Public Attributes
uint16_t lowpassPrecision
ByteStream bs
std::vector< int16_t, DefaultInitAllocatorAdaptor< int16_t > > data
Detailed Description
Definition at line 144 of file VC5Decompressor.h.
Constructor & Destructor Documentation
LowPassBand()
rawspeed::VC5Decompressor::Wavelet::LowPassBand::LowPassBand (const Wavelet & wavelet, ByteStream bs_, uint16_t lowpassPrecision_)
Definition at line 516 of file VC5Decompressor.cpp.
References rawspeed::iPoint2D::__attribute__(), rawspeed::VC5Decompressor::Wavelet::height, rawspeed::iPoint2D::iPoint2D(), LowPassBand(), lowpassPrecision, and rawspeed::VC5Decompressor::Wavelet::width.
Referenced by LowPassBand().
Member Function Documentation
decode()
void rawspeed::VC5Decompressor::Wavelet::LowPassBand::decode (const Wavelet & wavelet) final virtual
Implements rawspeed::VC5Decompressor::Wavelet::AbstractBand.
Definition at line 530 of file VC5Decompressor.cpp.
Member Data Documentation
bs
ByteStream rawspeed::VC5Decompressor::Wavelet::AbstractDecodeableBand::bs inherited
Definition at line 141 of file VC5Decompressor.h.
data
std::vector<int16_t, DefaultInitAllocatorAdaptor<int16_t> > rawspeed::VC5Decompressor::Wavelet::AbstractBand::data inherited
Definition at line 123 of file VC5Decompressor.h.
lowpassPrecision
uint16_t rawspeed::VC5Decompressor::Wavelet::LowPassBand::lowpassPrecision
Definition at line 145 of file VC5Decompressor.h.
Referenced by LowPassBand().
The documentation for this struct was generated from the following files:
librawspeed/decompressors/VC5Decompressor.h
librawspeed/decompressors/VC5Decompressor.cpp