RawSpeed: rawspeed::PanasonicDecompressorV5::ProxyStream Class Reference
rawspeed::PanasonicDecompressorV5::ProxyStream Class Reference
Public Member Functions
ProxyStream (ByteStream block_)
ByteStream & getStream ()
Private Member Functions
void parseBlock ()
Private Attributes
ByteStream block
std::vector< uint8_t > buf
ByteStream input
Detailed Description
Definition at line 140 of file PanasonicDecompressorV5.cpp.
Constructor & Destructor Documentation
ProxyStream()
rawspeed::PanasonicDecompressorV5::ProxyStream::ProxyStream (ByteStream block_) inline explicit
Definition at line 172 of file PanasonicDecompressorV5.cpp.
Referenced by rawspeed::PanasonicDecompressorV5::processBlock().
Member Function Documentation
getStream()
ByteStream& rawspeed::PanasonicDecompressorV5::ProxyStream::getStream () inline
Definition at line 174 of file PanasonicDecompressorV5.cpp.
References input, and parseBlock().
parseBlock()
void rawspeed::PanasonicDecompressorV5::ProxyStream::parseBlock () inline private
Definition at line 145 of file PanasonicDecompressorV5.cpp.
References block, rawspeed::PanasonicDecompressorV5::BlockSize, rawspeed::ByteStream::getBuffer(), rawspeed::ByteStream::getRemainSize(), and rawspeed::PanasonicDecompressorV5::sectionSplitOffset.
Referenced by getStream().
Member Data Documentation
block
ByteStream rawspeed::PanasonicDecompressorV5::ProxyStream::block private
Definition at line 141 of file PanasonicDecompressorV5.cpp.
Referenced by parseBlock().
buf
std::vector<uint8_t> rawspeed::PanasonicDecompressorV5::ProxyStream::buf private
Definition at line 142 of file PanasonicDecompressorV5.cpp.
input
ByteStream rawspeed::PanasonicDecompressorV5::ProxyStream::input private
Definition at line 143 of file PanasonicDecompressorV5.cpp.
Referenced by getStream().
The documentation for this class was generated from the following file:
librawspeed/decompressors/PanasonicDecompressorV5.cpp