var namespacerawspeed__test =
[
    [ "AbstractGetByteSwappedTest", "d0/d4c/classrawspeed__test_1_1_abstract_get_byte_swapped_test.html", "d0/d4c/classrawspeed__test_1_1_abstract_get_byte_swapped_test" ],
    [ "AbstractReferenceTest", "d8/dda/classrawspeed__test_1_1_abstract_reference_test.html", "d8/dda/classrawspeed__test_1_1_abstract_reference_test" ],
    [ "AlignedMallocDeathTest", "dd/dd5/classrawspeed__test_1_1_aligned_malloc_death_test.html", "dd/dd5/classrawspeed__test_1_1_aligned_malloc_death_test" ],
    [ "AlignedMallocTest", "d3/df4/classrawspeed__test_1_1_aligned_malloc_test.html", "d3/df4/classrawspeed__test_1_1_aligned_malloc_test" ],
    [ "AreaTest", "d6/dff/classrawspeed__test_1_1_area_test.html", "d6/dff/classrawspeed__test_1_1_area_test" ],
    [ "BitPumpPatternTest", "d1/d78/structrawspeed__test_1_1_bit_pump_pattern_test.html", null ],
    [ "BitPumpPatternTest< T, TestGetBitsNoFillTag >", "db/d6a/structrawspeed__test_1_1_bit_pump_pattern_test_3_01_t_00_01_test_get_bits_no_fill_tag_01_4.html", "db/d6a/structrawspeed__test_1_1_bit_pump_pattern_test_3_01_t_00_01_test_get_bits_no_fill_tag_01_4" ],
    [ "BitPumpPatternTest< T, TestGetBitsTag >", "db/dbf/structrawspeed__test_1_1_bit_pump_pattern_test_3_01_t_00_01_test_get_bits_tag_01_4.html", "db/dbf/structrawspeed__test_1_1_bit_pump_pattern_test_3_01_t_00_01_test_get_bits_tag_01_4" ],
    [ "BitPumpPatternTest< T, TestIncreasingPeekLengthNoFillTag >", "dd/d06/structrawspeed__test_1_1_bit_pump_pattern_test_3_01_t_00_01_test_increasing_peek_length_no_fill_tag_01_4.html", "dd/d06/structrawspeed__test_1_1_bit_pump_pattern_test_3_01_t_00_01_test_increasing_peek_length_no_fill_tag_01_4" ],
    [ "BitPumpPatternTest< T, TestIncreasingPeekLengthTag >", "d9/de4/structrawspeed__test_1_1_bit_pump_pattern_test_3_01_t_00_01_test_increasing_peek_length_tag_01_4.html", "d9/de4/structrawspeed__test_1_1_bit_pump_pattern_test_3_01_t_00_01_test_increasing_peek_length_tag_01_4" ],
    [ "BitPumpPatternTest< T, TestPeekBitsNoFillTag >", "d3/db7/structrawspeed__test_1_1_bit_pump_pattern_test_3_01_t_00_01_test_peek_bits_no_fill_tag_01_4.html", "d3/db7/structrawspeed__test_1_1_bit_pump_pattern_test_3_01_t_00_01_test_peek_bits_no_fill_tag_01_4" ],
    [ "BitPumpPatternTest< T, TestPeekBitsTag >", "dd/de5/structrawspeed__test_1_1_bit_pump_pattern_test_3_01_t_00_01_test_peek_bits_tag_01_4.html", "dd/de5/structrawspeed__test_1_1_bit_pump_pattern_test_3_01_t_00_01_test_peek_bits_tag_01_4" ],
    [ "BitPumpTest", "d1/dee/classrawspeed__test_1_1_bit_pump_test.html", "d1/dee/classrawspeed__test_1_1_bit_pump_test" ],
    [ "BlackAreaTest", "dd/d43/classrawspeed__test_1_1_black_area_test.html", "dd/d43/classrawspeed__test_1_1_black_area_test" ],
    [ "BoolHintTest", "d0/d52/classrawspeed__test_1_1_bool_hint_test.html", "d0/d52/classrawspeed__test_1_1_bool_hint_test" ],
    [ "CalculateStepsEdgesTest", "db/dcc/classrawspeed__test_1_1_calculate_steps_edges_test.html", "db/dcc/classrawspeed__test_1_1_calculate_steps_edges_test" ],
    [ "CalculateStepsTest", "df/d94/classrawspeed__test_1_1_calculate_steps_test.html", "df/d94/classrawspeed__test_1_1_calculate_steps_test" ],
    [ "CameraSensorInfoTest", "d4/d6e/classrawspeed__test_1_1_camera_sensor_info_test.html", "d4/d6e/classrawspeed__test_1_1_camera_sensor_info_test" ],
    [ "CameraSensorInfoTestDumb", "dc/ddd/classrawspeed__test_1_1_camera_sensor_info_test_dumb.html", "dc/ddd/classrawspeed__test_1_1_camera_sensor_info_test_dumb" ],
    [ "ClampBitsTest", "da/dd9/classrawspeed__test_1_1_clamp_bits_test.html", "da/dd9/classrawspeed__test_1_1_clamp_bits_test" ],
    [ "CodeSymbolDeathTest", "d5/d5a/classrawspeed__test_1_1_code_symbol_death_test.html", "d5/d5a/classrawspeed__test_1_1_code_symbol_death_test" ],
    [ "CodeSymbolHaveCommonPrefixTest", "d7/d00/classrawspeed__test_1_1_code_symbol_have_common_prefix_test.html", "d7/d00/classrawspeed__test_1_1_code_symbol_have_common_prefix_test" ],
    [ "CodeSymbolPrintTest", "d9/d6c/classrawspeed__test_1_1_code_symbol_print_test.html", "d9/d6c/classrawspeed__test_1_1_code_symbol_print_test" ],
    [ "ColorFilterArrayShiftTest", "d2/d2c/classrawspeed__test_1_1_color_filter_array_shift_test.html", "d2/d2c/classrawspeed__test_1_1_color_filter_array_shift_test" ],
    [ "ColorFilterArrayTest", "d3/d87/classrawspeed__test_1_1_color_filter_array_test.html", "d3/d87/classrawspeed__test_1_1_color_filter_array_test" ],
    [ "ConstantTest", "d5/dd9/classrawspeed__test_1_1_constant_test.html", "d5/dd9/classrawspeed__test_1_1_constant_test" ],
    [ "CopyPixelsTest", "de/d71/classrawspeed__test_1_1_copy_pixels_test.html", "de/d71/classrawspeed__test_1_1_copy_pixels_test" ],
    [ "doubleTest", "df/d36/classrawspeed__test_1_1double_test.html", "df/d36/classrawspeed__test_1_1double_test" ],
    [ "DummyHuffmanTableTest", "dc/d6e/classrawspeed__test_1_1_dummy_huffman_table_test.html", "dc/d6e/classrawspeed__test_1_1_dummy_huffman_table_test" ],
    [ "ExceptionsTest", "d0/d7b/classrawspeed__test_1_1_exceptions_test.html", null ],
    [ "floatTest", "d7/d9c/classrawspeed__test_1_1float_test.html", "d7/d9c/classrawspeed__test_1_1float_test" ],
    [ "generateCodeSymbolsTest", "d3/d05/classrawspeed__test_1_1generate_code_symbols_test.html", "d3/d05/classrawspeed__test_1_1generate_code_symbols_test" ],
    [ "HasPositiveAreaTest", "dc/dfc/classrawspeed__test_1_1_has_positive_area_test.html", "dc/dfc/classrawspeed__test_1_1_has_positive_area_test" ],
    [ "HexEquals", "d0/db1/structrawspeed__test_1_1_hex_equals.html", "d0/db1/structrawspeed__test_1_1_hex_equals" ],
    [ "IdentityTest", "d8/d77/classrawspeed__test_1_1_identity_test.html", "d8/d77/classrawspeed__test_1_1_identity_test" ],
    [ "int32Test", "de/d0c/classrawspeed__test_1_1int32_test.html", "de/d0c/classrawspeed__test_1_1int32_test" ],
    [ "intPair", "dd/d0f/structrawspeed__test_1_1int_pair.html", "dd/d0f/structrawspeed__test_1_1int_pair" ],
    [ "IsAlignedTest", "d1/da6/classrawspeed__test_1_1_is_aligned_test.html", "d1/da6/classrawspeed__test_1_1_is_aligned_test" ],
    [ "IsInTest", "d5/d3d/classrawspeed__test_1_1_is_in_test.html", "d5/d3d/classrawspeed__test_1_1_is_in_test" ],
    [ "IsoExpectationsT", "da/d38/structrawspeed__test_1_1_iso_expectations_t.html", "da/d38/structrawspeed__test_1_1_iso_expectations_t" ],
    [ "OperatorsTest", "d2/ddb/classrawspeed__test_1_1_operators_test.html", "d2/ddb/classrawspeed__test_1_1_operators_test" ],
    [ "Pattern", "dc/deb/structrawspeed__test_1_1_pattern.html", "dc/deb/structrawspeed__test_1_1_pattern" ],
    [ "Pattern< Pump, InvOnesTag >", "d7/df4/structrawspeed__test_1_1_pattern_3_01_pump_00_01_inv_ones_tag_01_4.html", "d7/df4/structrawspeed__test_1_1_pattern_3_01_pump_00_01_inv_ones_tag_01_4" ],
    [ "Pattern< Pump, OnesTag >", "d5/d12/structrawspeed__test_1_1_pattern_3_01_pump_00_01_ones_tag_01_4.html", "d5/d12/structrawspeed__test_1_1_pattern_3_01_pump_00_01_ones_tag_01_4" ],
    [ "Pattern< Pump, SaturatedTag >", "df/d90/structrawspeed__test_1_1_pattern_3_01_pump_00_01_saturated_tag_01_4.html", "df/d90/structrawspeed__test_1_1_pattern_3_01_pump_00_01_saturated_tag_01_4" ],
    [ "Pattern< Pump, ZerosTag >", "d6/dc1/structrawspeed__test_1_1_pattern_3_01_pump_00_01_zeros_tag_01_4.html", "d6/dc1/structrawspeed__test_1_1_pattern_3_01_pump_00_01_zeros_tag_01_4" ],
    [ "PointTest", "df/d4d/classrawspeed__test_1_1_point_test.html", "df/d4d/classrawspeed__test_1_1_point_test" ],
    [ "PowerOfTwoTest", "d5/d67/classrawspeed__test_1_1_power_of_two_test.html", "d5/d67/classrawspeed__test_1_1_power_of_two_test" ],
    [ "PumpAndPattern", "de/dbe/structrawspeed__test_1_1_pump_and_pattern.html", "de/dbe/structrawspeed__test_1_1_pump_and_pattern" ],
    [ "ReferenceTest", "dd/d5c/classrawspeed__test_1_1_reference_test.html", "dd/d5c/classrawspeed__test_1_1_reference_test" ],
    [ "RoundDownTest", "de/db3/classrawspeed__test_1_1_round_down_test.html", "de/db3/classrawspeed__test_1_1_round_down_test" ],
    [ "RoundUpDivisionTest", "dc/dc7/classrawspeed__test_1_1_round_up_division_test.html", "dc/dc7/classrawspeed__test_1_1_round_up_division_test" ],
    [ "RoundUpTest", "d4/dd5/classrawspeed__test_1_1_round_up_test.html", "d4/dd5/classrawspeed__test_1_1_round_up_test" ],
    [ "short16Test", "d0/d67/classrawspeed__test_1_1short16_test.html", "d0/d67/classrawspeed__test_1_1short16_test" ],
    [ "SignExtendTest", "da/da9/classrawspeed__test_1_1_sign_extend_test.html", "da/da9/classrawspeed__test_1_1_sign_extend_test" ],
    [ "SinReferenceTest", "d6/d9b/classrawspeed__test_1_1_sin_reference_test.html", "d6/d9b/classrawspeed__test_1_1_sin_reference_test" ],
    [ "SmallestTest", "de/db1/classrawspeed__test_1_1_smallest_test.html", "de/db1/classrawspeed__test_1_1_smallest_test" ],
    [ "SplitStringTest", "df/da4/classrawspeed__test_1_1_split_string_test.html", "df/da4/classrawspeed__test_1_1_split_string_test" ],
    [ "TrimSpacesTest", "db/da7/classrawspeed__test_1_1_trim_spaces_test.html", "db/da7/classrawspeed__test_1_1_trim_spaces_test" ],
    [ "TwoRangesTest", "d6/d38/classrawspeed__test_1_1_two_ranges_test.html", "d6/d38/classrawspeed__test_1_1_two_ranges_test" ],
    [ "uint32Test", "dd/db8/classrawspeed__test_1_1uint32_test.html", "dd/db8/classrawspeed__test_1_1uint32_test" ],
    [ "uint64Test", "d5/d5a/classrawspeed__test_1_1uint64_test.html", "d5/d5a/classrawspeed__test_1_1uint64_test" ],
    [ "ushort16Test", "d8/d0a/classrawspeed__test_1_1ushort16_test.html", "d8/d0a/classrawspeed__test_1_1ushort16_test" ]
];