RawSpeed: rawspeed_test Namespace Reference
rawspeed_test Namespace Reference
Classes
class AbstractGetByteSwappedTest
class AbstractReferenceTest
class AlignedMallocDeathTest
class AlignedMallocTest
class AreaTest
struct BitPumpPatternTest
struct BitPumpPatternTest< T, TestGetBitsNoFillTag >
struct BitPumpPatternTest< T, TestGetBitsTag >
struct BitPumpPatternTest< T, TestIncreasingPeekLengthNoFillTag >
struct BitPumpPatternTest< T, TestIncreasingPeekLengthTag >
struct BitPumpPatternTest< T, TestPeekBitsNoFillTag >
struct BitPumpPatternTest< T, TestPeekBitsTag >
class BitPumpTest
class BlackAreaTest
class BoolHintTest
class CalculateStepsEdgesTest
class CalculateStepsTest
class CameraSensorInfoTest
class CameraSensorInfoTestDumb
class ClampBitsTest
class CodeSymbolDeathTest
class CodeSymbolHaveCommonPrefixTest
class CodeSymbolPrintTest
class ColorFilterArrayShiftTest
class ColorFilterArrayTest
class ConstantTest
class CopyPixelsTest
class doubleTest
class DummyHuffmanTableTest
class ExceptionsTest
class floatTest
class generateCodeSymbolsTest
class HasPositiveAreaTest
struct HexEquals
class IdentityTest
class int32Test
struct intPair
class IsAlignedTest
class IsInTest
struct IsoExpectationsT
class OperatorsTest
struct Pattern
struct Pattern< Pump, InvOnesTag >
struct Pattern< Pump, OnesTag >
struct Pattern< Pump, SaturatedTag >
struct Pattern< Pump, ZerosTag >
class PointTest
class PowerOfTwoTest
struct PumpAndPattern
class ReferenceTest
class RoundDownTest
class RoundUpDivisionTest
class RoundUpTest
class short16Test
class SignExtendTest
class SinReferenceTest
class SmallestTest
class SplitStringTest
class TrimSpacesTest
class TwoRangesTest
class uint32Test
class uint64Test
class ushort16Test
Typedefs
using powerOfTwoType = std::tuple< int, bool >
using RoundDownType = std::tuple< size_t, size_t, size_t >
using RoundUpType = std::tuple< size_t, size_t, size_t >
using RoundUpDivisionType = std::tuple< size_t, size_t, size_t >
using IsAlignedType = std::tuple< int, int >
using IsInType = std::tuple< string, bool >
using ClampBitsType = std::tuple< int, int, uint16_t >
using TrimSpacesType = std::tuple< string, string >
using splitStringType = std::tuple< string, char, vector< string > >
using copyPixelsType = std::tuple< int, int, int, int >
using Classes = testing::Types< int, unsigned int, int8_t, uint8_t, int16_t, uint16_t, int32_t, uint32_t, int64_t, uint64_t, float, double >
using twoRangesType = std::tuple< int, unsigned, int, unsigned >
using IntPair = pair< int, int >
using Six = std::tuple< IntPair, IntPair, IntPair >
using hasPositiveAreaType = std::tuple< int, int >
using areaType = tuple< IntPair, iPoint2D::area_type >
using operatorsType = std::tuple< IntPair, IntPair, bool, bool, bool, bool, bool >
using identityType = std::tuple< std::array< rawspeed::iPoint2D, 2 >, std::vector< std::array< double, 4 > >>
using IntegerIdentityTest = IdentityTest< uint16_t >
using DoubleIdentityTest = IdentityTest< double >
using calculateStepsType = std::tuple< int, std::vector< int > >
using DoubleCalculateStepsTest = CalculateStepsTest< double >
using IntegerCalculateStepsTest = CalculateStepsTest< int >
using constantType = std::tuple< int, int >
using IntegerConstantTest = ConstantTest< uint16_t >
using DoubleConstantTest = ConstantTest< double >
using referenceType = std::tuple< int, long double >
using Sin2PiRefTest = ReferenceTest< SinReferenceTest< 2, 1 > >
using SinPiRefTest = ReferenceTest< SinReferenceTest< 1, 1 > >
using CodeSymbolType = std::tuple< int, int, bool >
using CodeSymbolPrintDataType = std::tuple< int, int, std::string >
using CodeSymbolHaveCommonPrefixDataType = std::tuple< AbstractHuffmanTable::CodeSymbol, AbstractHuffmanTable::CodeSymbol >
using SignExtendDataType = std::tuple< uint32_t, uint32_t, int >
using generateCodeSymbolsDataType = std::tuple< std::vector< uint8_t >, std::vector< AbstractHuffmanTable::CodeSymbol > >
using DummyHuffmanTableDeathTest = DummyHuffmanTableTest
template<typename Pump >
using Patterns = ::testing::Types< PumpAndPattern< Pump, Pattern< Pump, ZerosTag > >, PumpAndPattern< Pump, Pattern< Pump, OnesTag > >, PumpAndPattern< Pump, Pattern< Pump, InvOnesTag > >, PumpAndPattern< Pump, Pattern< Pump, SaturatedTag > >>
using ushort16Type = intPair< uint16_t >
using ushort16TType = std::tuple< ushort16Type, bool >
using uint32Type = intPair< uint32_t >
using uint32TType = std::tuple< uint32Type, bool >
using uint64Type = intPair< uint64_t >
using uint64TType = std::tuple< uint64Type, bool >
using Bayer2x2 = std::tuple< CFAColor, CFAColor, CFAColor, CFAColor >
Functions
TEST (ParseChecksumFileContentTest, Empty)
TEST (ParseChecksumFileContentTest, ShortLine)
TEST (ParseChecksumFileContentTest, Lines)
TEST (ParseChecksumFileContentTest, TheTest)
INSTANTIATE_TEST_CASE_P (PowerOfTwoTest, PowerOfTwoTest, ::testing::ValuesIn(powerOfTwoValues))
TEST_P (PowerOfTwoTest, PowerOfTwoTest)
INSTANTIATE_TEST_CASE_P (RoundDownTest, RoundDownTest, ::testing::ValuesIn(RoundDownValues))
TEST_P (RoundDownTest, RoundDownTest)
INSTANTIATE_TEST_CASE_P (RoundUpTest, RoundUpTest, ::testing::ValuesIn(RoundUpValues))
TEST_P (RoundUpTest, RoundUpTest)
INSTANTIATE_TEST_CASE_P (RoundUpDivisionTest, RoundUpDivisionTest, ::testing::ValuesIn(RoundUpDivisionValues))
TEST_P (RoundUpDivisionTest, RoundUpDivisionTest)
INSTANTIATE_TEST_CASE_P (IsAlignedTest, IsAlignedTest, ::testing::Combine(::testing::Range(0, 32), ::testing::Range(0, 32)))
TEST_P (IsAlignedTest, IsAlignedAfterRoundUpTest)
INSTANTIATE_TEST_CASE_P (IsInTest, IsInTest, ::testing::ValuesIn(IsInValues))
TEST_P (IsInTest, IsInTest)
INSTANTIATE_TEST_CASE_P (ClampBitsTest, ClampBitsTest, ::testing::ValuesIn(ClampBitsValues))
TEST_P (ClampBitsTest, ClampBitsTest)
TEST (ClampBitsDeathTest, Only16Bit)
TEST (ClampBitsUnsignedDeathTest, NoNopClamps)
INSTANTIATE_TEST_CASE_P (TrimSpacesTest, TrimSpacesTest, ::testing::ValuesIn(TrimSpacesValues))
TEST_P (TrimSpacesTest, TrimSpacesTest)
INSTANTIATE_TEST_CASE_P (SplitStringTest, SplitStringTest, ::testing::ValuesIn(splitStringValues))
TEST_P (SplitStringTest, SplitStringTest)
TEST (UnrollLoopTest, Test)
template<int iterations>
static void UnrollLoopTestIsMonotonicallyPositiveTest ()
TEST (UnrollLoopTest, IsMonotonicallyPositiveTest)
TEST (MakeUniqueTest, Test)
INSTANTIATE_TEST_CASE_P (CopyPixelsTest, CopyPixelsTest, testing::Combine(testing::Range(0, 4, 1), testing::Range(0, 4, 1), testing::Range(0, 4, 1), testing::Range(0, 4, 1)))
TEST_P (CopyPixelsTest, CopyPixelsTest)
TEST (CpuidDeathTest, SSE2Test)
TYPED_TEST_CASE (AlignedMallocTest, Classes)
TYPED_TEST_CASE (AlignedMallocDeathTest, Classes)
TYPED_TEST (AlignedMallocTest, BasicTest)
TYPED_TEST (AlignedMallocTest, UniquePtrTest)
TYPED_TEST (AlignedMallocDeathTest, AlignedMallocAssertions)
TEST (AlignedMallocDeathTest, AlignedFreeHandlesNullptr)
TYPED_TEST (AlignedMallocTest, TemplateTest)
TYPED_TEST (AlignedMallocTest, TemplatUniquePtrTest)
TYPED_TEST (AlignedMallocTest, TemplateArrayTest)
TYPED_TEST (AlignedMallocTest, TemplateArrayHandlesOverflowTest)
TYPED_TEST (AlignedMallocTest, TemplateUniquePtrArrayTest)
TYPED_TEST (AlignedMallocDeathTest, TemplateArrayAssertions)
TYPED_TEST (AlignedMallocTest, TemplateArrayRoundUp)
TYPED_TEST (AlignedMallocTest, TemplateArraySizeTest)
TYPED_TEST (AlignedMallocTest, TemplateUniquePtrArraySizeTest)
TEST (AlignedMallocDeathTest, TemplateArraySizeAssertions)
TEST (AlignedMallocTest, TemplateArraySizeRoundUp)
TYPED_TEST (AlignedMallocTest, TemplateArraySizeRoundUpTest)
TEST_P (TwoRangesTest, NORangesSetDataSelfTest)
TEST_P (TwoRangesTest, NORangesSetDataTest)
template<typename T >
::testing::AssertionResult RangeContains (const char *range_expr, const char *pos_expr, const Range< T > &r, const T &pos)
template<typename T >
::testing::AssertionResult RangeDoesntContain (const char *range_expr, const char *pos_expr, const Range< T > &r, const T &pos)
template<typename T >
::testing::AssertionResult RangesOverlap (const char *m_expr, const char *n_expr, const T &lhs, const T &rhs)
template<typename T >
::testing::AssertionResult RangesDontOverlap (const char *m_expr, const char *n_expr, const T &lhs, const T &rhs)
INSTANTIATE_TEST_CASE_P (Unsigned, TwoRangesTest, testing::Combine(testing::Range(0, 3), testing::Range(0U, 3U), testing::Range(0, 3), testing::Range(0U, 3U)))
TEST (PointTest, Constructor)
TEST (PointTest, AssignmentConstructor)
TEST (PointTest, EqualityOperator)
TEST (PointTest, NonEqualityOperator)
INSTANTIATE_TEST_CASE_P (SumTest, PointTest, ::testing::ValuesIn(valueSum))
TEST_P (PointTest, InPlaceAddTest1)
TEST_P (PointTest, InPlaceAddTest2)
TEST_P (PointTest, AddTest1)
TEST_P (PointTest, AddTest2)
TEST_P (PointTest, InPlaceSubTest1)
TEST_P (PointTest, InPlaceSubTest2)
TEST_P (PointTest, SubTest1)
TEST_P (PointTest, SubTest2)
INSTANTIATE_TEST_CASE_P (HasPositiveAreaTest, HasPositiveAreaTest, ::testing::Combine(::testing::Range(-2, 3), ::testing::Range(-2, 3)))
TEST_P (HasPositiveAreaTest, HasPositiveAreaTest)
INSTANTIATE_TEST_CASE_P (AreaTest, AreaTest, ::testing::ValuesIn(valueArea))
TEST_P (AreaTest, AreaTest)
INSTANTIATE_TEST_CASE_P (OperatorsTests, OperatorsTest, ::testing::ValuesIn(operatorsValues))
TEST_P (OperatorsTest, OperatorEQTest)
TEST_P (OperatorsTest, OperatorNETest)
TEST_P (OperatorsTest, OperatorLTTest)
TEST_P (OperatorsTest, OperatorGTest)
TEST_P (OperatorsTest, OperatorLETest)
TEST_P (OperatorsTest, OperatorGEest)
TEST_P (OperatorsTest, OperatorsTest)
INSTANTIATE_TEST_CASE_P (GetSmallestTest, SmallestTest, ::testing::ValuesIn(smallestValues))
TEST_P (SmallestTest, GetSmallestTest)
TEST (RangeTest, BasicSignedRangeForTest)
TEST (RangeTest, BasicSignedContainsTest)
TEST (RangeTest, BasicSignedCrossoverContainsTest)
TEST (RangeTest, BasicUnsignedContainsTest)
TEST (RangeTest, SignedZeroSizeContainsTest)
TEST (RangeTest, UnsignedZeroSizeContainsTest)
TEST_P (TwoRangesTest, OverlapDataTest)
TEST (SplineStaticTest, DefaultIsUshort16)
TEST (SplineDeathTest, AtLeastTwoPoints)
TEST (SplineDeathTest, XIsFullRange)
TEST (SplineDeathTest, YIsLimited)
TEST (SplineDeathTest, XIsStrictlyIncreasing)
TEST (SplineDeathTest, ClampUshort16Min)
TEST (SplineDeathTest, ClampUshort16Max)
INSTANTIATE_TEST_CASE_P (IntegerIdentityTest, IntegerIdentityTest, ::testing::ValuesIn(identityValues))
TEST_P (IntegerIdentityTest, ValuesAreLinearlyInterpolated)
TEST_P (IntegerIdentityTest, SegmentCoeffients)
INSTANTIATE_TEST_CASE_P (DoubleIdentityTest, DoubleIdentityTest, ::testing::ValuesIn(identityValues))
TEST_P (DoubleIdentityTest, ValuesAreLinearlyInterpolated)
TEST_P (DoubleIdentityTest, SegmentCoeffients)
template<typename T >
T lerp (T v0, T v1, T t)
template<typename T = int, typename = std::enable_if_t<std::is_arithmetic<T>::value>>
std::vector< T > calculateSteps (int numCp)
TEST (CalculateStepsEdgesTest, IdentityTest)
INSTANTIATE_TEST_CASE_P (CalculateStepsEdgesTest, CalculateStepsEdgesTest, ::testing::Range(0, 254))
TEST_P (CalculateStepsEdgesTest, Count)
TEST_P (CalculateStepsEdgesTest, EdgesAreProper)
INSTANTIATE_TEST_CASE_P (CalculateStepsTest, DoubleCalculateStepsTest, ::testing::ValuesIn(calculateStepsValues))
TEST_P (DoubleCalculateStepsTest, Count)
TEST_P (DoubleCalculateStepsTest, GotExpectedOutput)
INSTANTIATE_TEST_CASE_P (CalculateStepsTest, IntegerCalculateStepsTest, ::testing::ValuesIn(calculateStepsValues))
TEST_P (IntegerCalculateStepsTest, Count)
TEST_P (IntegerCalculateStepsTest, GotExpectedOutput)
INSTANTIATE_TEST_CASE_P (IntegerConstantTest, IntegerConstantTest, constantValues)
TEST_P (IntegerConstantTest, AllValuesAreEqual)
TEST_P (IntegerConstantTest, SegmentCoeffients)
INSTANTIATE_TEST_CASE_P (DoubleConstantTest, DoubleConstantTest, constantValues)
TEST_P (DoubleConstantTest, AllValuesAreEqual)
TEST_P (DoubleConstantTest, SegmentCoeffients)
INSTANTIATE_TEST_CASE_P (Sin2Pi, Sin2PiRefTest, ::testing::ValuesIn(sin2PiRefValues))
TEST_P (Sin2PiRefTest, NearlyMatchesReference)
INSTANTIATE_TEST_CASE_P (SinPi, SinPiRefTest, ::testing::ValuesIn(sinPiRefValues))
TEST_P (SinPiRefTest, NearlyMatchesReference)
TEST (AbstractHuffmanTableCodeSymbolTest, Equality)
TEST (CodeSymbolDeathTest, CodeSymbolLength)
INSTANTIATE_TEST_CASE_P (CodeSymbolDeathTest, CodeSymbolDeathTest, ::testing::ValuesIn(CodeSymbolData))
TEST_P (CodeSymbolDeathTest, CodeSymbolDeathTest)
INSTANTIATE_TEST_CASE_P (CodeSymbolPrintTest, CodeSymbolPrintTest, ::testing::ValuesIn(CodeSymbolPrintData))
TEST_P (CodeSymbolPrintTest, CodeSymbolPrintTest)
std::vector< AbstractHuffmanTable::CodeSymbol > GenerateAllPossibleCodeSymbols ()
INSTANTIATE_TEST_CASE_P (CodeSymbolHaveCommonPrefixTest, CodeSymbolHaveCommonPrefixTest, ::testing::Combine(::testing::ValuesIn(allPossibleCodeSymbols), ::testing::ValuesIn(allPossibleCodeSymbols)))
TEST_P (CodeSymbolHaveCommonPrefixTest, CodeSymbolHaveCommonPrefixTest)
TEST (CodeSymbolHaveCommonPrefixTest, BasicTest)
TEST (CodeSymbolHaveCommonPrefixDeathTest, AsymmetricalDeathTest)
TEST (AbstractHuffmanTableDeathTest, setNCodesPerLengthRequires16Lengths)
TEST (AbstractHuffmanTableTest, setNCodesPerLengthEqualCompareAndTrimming)
TEST (AbstractHuffmanTableTest, setNCodesPerLengthEmptyIsBad)
TEST (AbstractHuffmanTableTest, setNCodesPerLengthTooManyCodesTotal)
TEST (AbstractHuffmanTableTest, setNCodesPerLengthTooManyCodesForLength)
TEST (AbstractHuffmanTableTest, setNCodesPerLengthCodeSymbolOverflow)
TEST (AbstractHuffmanTableTest, setNCodesPerLengthCounts)
TEST (AbstractHuffmanTableDeathTest, setCodeValuesRequiresCount)
TEST (AbstractHuffmanTableDeathTest, setCodeValuesRequiresLessThan162)
TEST (AbstractHuffmanTableTest, setCodeValuesValueLessThan16)
TEST (AbstractHuffmanTableTest, EqualCompareAndTrimming)
INSTANTIATE_TEST_CASE_P (SignExtendTest, SignExtendTest, ::testing::ValuesIn(signExtendData))
TEST_P (SignExtendTest, SignExtendTest)
INSTANTIATE_TEST_CASE_P (generateCodeSymbolsTest, generateCodeSymbolsTest, ::testing::ValuesIn(generateCodeSymbolsData))
TEST_P (generateCodeSymbolsTest, generateCodeSymbolsTest)
TEST_F (DummyHuffmanTableDeathTest, VerifyCodeSymbolsTest)
TEST (BinaryHuffmanTreeTest, EmptyByDefault)
TEST (BinaryHuffmanTreeDeathTest, getAllBranchesOfNegativeDepth)
TEST (BinaryHuffmanTreeTest, getAllBranchesOfDepth_0_Base)
TEST (BinaryHuffmanTreeTest, getAllBranchesOfDepth_1_Base)
TEST (BinaryHuffmanTreeDeathTest, getAllNodesAtZeroDepth)
TEST (BinaryHuffmanTreeTest, getAllVacantNodesAtDepth_1_Base)
TEST (BinaryHuffmanTreeTest, getAllVacantNodesAtDepth_2_fills_depth_1_with_branches)
TEST (BinaryHuffmanTreeTest, getAllVacantNodesAtDepth_2_Base)
TEST (BinaryHuffmanTreeTest, pruneLeaflessBranches_purges_all)
TEST (BinaryHuffmanTreeTest, getAllVacantNodesAtDepth_1_after_adding_1_depth_1_leaf)
TEST (BinaryHuffmanTreeTest, getAllVacantNodesAtDepth_2_after_adding_1_depth_1_leaf)
TEST (BinaryHuffmanTreeTest, getAllVacantNodesAtDepth_2_after_adding_1_depth_1_and_1_depth_2_leaf)
TEST (HuffmanTableTest, decodeCodeValueIdentityTest)
TEST (HuffmanTableTest, decodeDifferenceIdentityTest)
TEST (HuffmanTableTest, decodeCodeValueBadCodeTest)
TEST (HuffmanTableTest, decodeDifferenceBadCodeTest)
INSTANTIATE_TYPED_TEST_CASE_P (JPEG, BitPumpTest, Patterns< BitPumpJPEG >)
TEST (BitPumpJPEGTest, 0xFF0x00Is0xFFTest)
TEST (BitPumpJPEGTest, 0xFF0xXXIsTheEndTest)
TYPED_TEST_CASE_P (BitPumpTest)
TYPED_TEST_P (BitPumpTest, GetTest)
TYPED_TEST_P (BitPumpTest, GetNoFillTest)
TYPED_TEST_P (BitPumpTest, PeekTest)
TYPED_TEST_P (BitPumpTest, PeekNoFillTest)
TYPED_TEST_P (BitPumpTest, IncreasingPeekLengthTest)
TYPED_TEST_P (BitPumpTest, IncreasingPeekLengthNoFillTest)
REGISTER_TYPED_TEST_CASE_P (BitPumpTest, GetTest, GetNoFillTest, PeekTest, PeekNoFillTest, IncreasingPeekLengthTest, IncreasingPeekLengthNoFillTest)
INSTANTIATE_TYPED_TEST_CASE_P (LSB, BitPumpTest, Patterns< BitPumpLSB >)
INSTANTIATE_TYPED_TEST_CASE_P (MSB16, BitPumpTest, Patterns< BitPumpMSB16 >)
INSTANTIATE_TYPED_TEST_CASE_P (MSB32, BitPumpTest, Patterns< BitPumpMSB32 >)
INSTANTIATE_TYPED_TEST_CASE_P (MSB, BitPumpTest, Patterns< BitPumpMSB >)
TEST (EndiannessTest, getHostEndiannessTests)
template<typename T >
::std::ostream & operator<< (::std::ostream &os, const intPair< T > &p)
INSTANTIATE_TEST_CASE_P (ushort16Test, ushort16Test, ::testing::Combine(::testing::ValuesIn(ushort16Values), ::testing::Bool()))
TEST_P (ushort16Test, swap)
TEST_P (ushort16Test, NOP)
TEST_P (ushort16Test, typedSwap)
TEST_P (ushort16Test, get)
TEST_P (ushort16Test, getNOP)
TEST_P (ushort16Test, getU16)
TEST_P (ushort16Test, getU16NOP)
INSTANTIATE_TEST_CASE_P (short16Test, short16Test, ::testing::Combine(::testing::ValuesIn(ushort16Values), ::testing::Bool()))
TEST_P (short16Test, swap)
TEST_P (short16Test, NOP)
TEST_P (short16Test, typedSwap)
TEST_P (short16Test, get)
TEST_P (short16Test, getNOP)
INSTANTIATE_TEST_CASE_P (uint32Test, uint32Test, ::testing::Combine(::testing::ValuesIn(uint32Values), ::testing::Bool()))
TEST_P (uint32Test, swap)
TEST_P (uint32Test, NOP)
TEST_P (uint32Test, typedSwap)
TEST_P (uint32Test, get)
TEST_P (uint32Test, getNOP)
TEST_P (uint32Test, getU32)
TEST_P (uint32Test, getU32NOP)
INSTANTIATE_TEST_CASE_P (int32Test, int32Test, ::testing::Combine(::testing::ValuesIn(uint32Values), ::testing::Bool()))
TEST_P (int32Test, swap)
TEST_P (int32Test, NOP)
TEST_P (int32Test, typedSwap)
TEST_P (int32Test, get)
TEST_P (int32Test, getNOP)
INSTANTIATE_TEST_CASE_P (uint64Test, uint64Test, ::testing::Combine(::testing::ValuesIn(uint64Values), ::testing::Bool()))
TEST_P (uint64Test, swap)
TEST_P (uint64Test, NOP)
TEST_P (uint64Test, typedSwap)
TEST_P (uint64Test, get)
TEST_P (uint64Test, getNOP)
INSTANTIATE_TEST_CASE_P (floatTest, floatTest, ::testing::Combine(::testing::ValuesIn(uint32Values), ::testing::Bool()))
TEST_P (floatTest, swap)
TEST_P (floatTest, NOP)
TEST_P (floatTest, typedSwap)
TEST_P (floatTest, get)
TEST_P (floatTest, getNOP)
INSTANTIATE_TEST_CASE_P (doubleTest, doubleTest, ::testing::Combine(::testing::ValuesIn(uint64Values), ::testing::Bool()))
TEST_P (doubleTest, swap)
TEST_P (doubleTest, NOP)
TEST_P (doubleTest, typedSwap)
TEST_P (doubleTest, get)
TEST_P (doubleTest, getNOP)
INSTANTIATE_TEST_CASE_P (BlackAreas, BlackAreaTest, testing::Combine(testing::Range(0, 1000, 250), testing::Range(0, 1000, 250), testing::Bool()))
TEST_P (BlackAreaTest, Constructor)
TEST_P (BlackAreaTest, Getters)
TEST_P (BlackAreaTest, AssignmentConstructor)
TEST_P (BlackAreaTest, AssignmentConstructorGetters)
TEST_P (BlackAreaTest, Assignment)
TEST_P (BlackAreaTest, AssignmentGetters)
std::vector< int > ISOList (6)
INSTANTIATE_TEST_CASE_P (MinMax, CameraSensorInfoTestDumb, testing::Combine(testing::ValuesIn(ISOList), testing::ValuesIn(ISOList)))
TEST_P (CameraSensorInfoTestDumb, Constructor)
TEST_P (CameraSensorInfoTestDumb, Getters)
TEST_P (CameraSensorInfoTestDumb, AssignmentConstructor)
TEST_P (CameraSensorInfoTestDumb, AssignmentConstructorGetters)
TEST_P (CameraSensorInfoTestDumb, Assignment)
TEST_P (CameraSensorInfoTestDumb, AssignmentGetters)
INSTANTIATE_TEST_CASE_P (Expectations, CameraSensorInfoTest, testing::ValuesIn(CameraSensorIsoInfos))
TEST_P (CameraSensorInfoTest, IsDefault)
TEST_P (CameraSensorInfoTest, isIsoWithin)
TEST (CameraTest, HintsEmpty)
TEST (CameraTest, HintsGetDefault)
TEST (CameraTest, HintsAssignmentConstructor)
TEST (CameraTest, HintsAssignment)
TEST (CameraTest, HintsAdd)
TEST (CameraTest, HintsInt)
TEST (CameraTest, HintsUInt)
TEST (CameraTest, HintsFloat)
TEST (CameraTest, HintsDouble)
TEST (BoolHintTest, HintsBoolTrue)
INSTANTIATE_TEST_CASE_P (NotTrue, BoolHintTest, ::testing::Values("True", "false", "False", "", "_"))
TEST_P (BoolHintTest, HintsBool)
TEST (ColorFilterArrayTestBasic, Constructor)
TEST (ColorFilterArrayTestBasic, SetSize)
TEST (ColorFilterArrayTestBasic, DISABLED_SetTooBigSize)
TEST (ColorFilterArrayTestBasic, ToDcraw)
TEST (ColorFilterArrayTestBasic, HandlesEmptyCFA)
TEST (ColorFilterArrayTestBasic, HandlesOutOfBounds)
INSTANTIATE_TEST_CASE_P (RGGB, ColorFilterArrayTest, testing::Combine(Bayer_RGB, Bayer_RGB, Bayer_RGB, Bayer_RGB))
INSTANTIATE_TEST_CASE_P (CYGM, ColorFilterArrayTest, testing::Combine(Bayer_CYGM, Bayer_CYGM, Bayer_CYGM, Bayer_CYGM))
static void setHelper (ColorFilterArray *cfa, Bayer2x2 param)
static void check (ColorFilterArray *cfa, Bayer2x2 param)
TEST_P (ColorFilterArrayTest, Constructor)
TEST_P (ColorFilterArrayTest, AssignmentConstructor)
TEST_P (ColorFilterArrayTest, SetColorAt)
TEST_P (ColorFilterArrayTest, ToDcraw)
TEST_P (ColorFilterArrayTest, AsString)
INSTANTIATE_TEST_CASE_P (RGGB, ColorFilterArrayShiftTest, testing::Combine(Bayer_RGB, Bayer_RGB, Bayer_RGB, Bayer_RGB, testing::Range(-2, 2), testing::Range(-2, 2)))
INSTANTIATE_TEST_CASE_P (CYGM, ColorFilterArrayShiftTest, testing::Combine(Bayer_CYGM, Bayer_CYGM, Bayer_CYGM, Bayer_CYGM, testing::Range(-2, 2), testing::Range(-2, 2)))
TEST (ColorFilterArrayTestBasic, shiftDcrawFilter)
TEST_P (ColorFilterArrayShiftTest, shiftEqualityTest)
template<typename T >
static void * MetaHelper (const char *str)
template<>
void * MetaHelper< RawspeedException > (const char *str)
template<>
void * MetaHelper< CameraMetadataException > (const char *str)
template<>
void * MetaHelper< CiffParserException > (const char *str)
template<>
void * MetaHelper< FileIOException > (const char *str)
template<>
void * MetaHelper< IOException > (const char *str)
template<>
void * MetaHelper< RawDecoderException > (const char *str)
template<>
void * MetaHelper< RawParserException > (const char *str)
template<>
void * MetaHelper< TiffParserException > (const char *str)
template<>
void * MetaHelper< FiffParserException > (const char *str)
TYPED_TEST_CASE (ExceptionsTest, Classes)
TYPED_TEST (ExceptionsTest, Constructor)
TYPED_TEST (ExceptionsTest, AssignmentConstructor)
TYPED_TEST (ExceptionsTest, Throw)
TYPED_TEST (ExceptionsTest, ThrowMessage)
TYPED_TEST (ExceptionsTest, ThrowHelperTest)
TYPED_TEST (ExceptionsTest, ThrowHelperTestMessage)
Variables
static const powerOfTwoType powerOfTwoValues []
static const RoundDownType RoundDownValues []
static const RoundUpType RoundUpValues []
static const RoundUpDivisionType RoundUpDivisionValues []
static const IsInType IsInValues []
static const ClampBitsType ClampBitsValues []
static const TrimSpacesType TrimSpacesValues []
static const splitStringType splitStringValues []
static constexpr const size_t alloc_alignment = 16
static const std::set< twoRangesType > AllOverlapped
static constexpr iPoint2D::area_type maxVal
static constexpr iPoint2D::area_type minVal
static constexpr iPoint2D::area_type absMinVal = -minVal
static constexpr iPoint2D::area_type maxAreaVal = maxVal * maxVal
static constexpr iPoint2D::area_type minAreaVal = absMinVal * absMinVal
static constexpr iPoint2D::area_type mixAreaVal = maxVal * absMinVal
static const Six valueSum []
static const iPoint2D PositiveAreaData []
static const areaType valueArea []
static const operatorsType operatorsValues []
static const Six smallestValues []
static const identityType identityValues []
static const calculateStepsType calculateStepsValues []
constexpr auto NumExtraSteps = 3
static const auto constantValues
static const referenceType sin2PiRefValues []
static const referenceType sinPiRefValues []
static const CodeSymbolType CodeSymbolData []
static const CodeSymbolPrintDataType CodeSymbolPrintData []
static const auto allPossibleCodeSymbols = GenerateAllPossibleCodeSymbols()
auto genHT
auto genHTCount
auto genHTFull
auto zeroDiff = [](int len) { return make_tuple(0, len, -((1 << len) - 1)); }
auto passthrough
auto one = [](int len) { return make_tuple((1 << len), len, 1); }
static const SignExtendDataType signExtendData []
static const generateCodeSymbolsDataType generateCodeSymbolsData []
auto GenOnesLE
auto GenOnesBE
static const ushort16Type ushort16Values []
static const uint32Type uint32Values []
static const uint64Type uint64Values []
static const struct IsoExpectationsT CameraSensorIsoInfos []
static const iPoint2D square (2, 2)
static const auto Bayer_RGB = ::testing::Values(CFA_RED, CFA_GREEN, CFA_BLUE)
static const auto Bayer_CYGM
static const char * msg = "my very Smart error Message #1 !"
Typedef Documentation
areaType
using rawspeed_test::areaType = typedef tuple<IntPair, iPoint2D::area_type>
Definition at line 356 of file PointTest.cpp.
Bayer2x2
using rawspeed_test::Bayer2x2 = typedef std::tuple<CFAColor, CFAColor, CFAColor, CFAColor>
Definition at line 52 of file ColorFilterArrayTest.cpp.
calculateStepsType
using rawspeed_test::calculateStepsType = typedef std::tuple<int, std::vector<int> >
Definition at line 291 of file SplineTest.cpp.
ClampBitsType
using rawspeed_test::ClampBitsType = typedef std::tuple<int, int, uint16_t>
Definition at line 229 of file CommonTest.cpp.
Classes
typedef testing::Types< RawspeedException, CameraMetadataException, CiffParserException, FileIOException, IOException, RawDecoderException, TiffParserException, FiffParserException, RawParserException > rawspeed_test::Classes
Definition at line 75 of file MemoryTest.cpp.
CodeSymbolHaveCommonPrefixDataType
using rawspeed_test::CodeSymbolHaveCommonPrefixDataType = typedef std::tuple<AbstractHuffmanTable::CodeSymbol, AbstractHuffmanTable::CodeSymbol>
Definition at line 166 of file AbstractHuffmanTableTest.cpp.
CodeSymbolPrintDataType
using rawspeed_test::CodeSymbolPrintDataType = typedef std::tuple<int, int, std::string>
Definition at line 129 of file AbstractHuffmanTableTest.cpp.
CodeSymbolType
using rawspeed_test::CodeSymbolType = typedef std::tuple<int, int, bool>
Definition at line 84 of file AbstractHuffmanTableTest.cpp.
constantType
using rawspeed_test::constantType = typedef std::tuple<int, int>
Definition at line 351 of file SplineTest.cpp.
copyPixelsType
using rawspeed_test::copyPixelsType = typedef std::tuple<int, int, int, int>
Definition at line 422 of file CommonTest.cpp.
DoubleCalculateStepsTest
using rawspeed_test::DoubleCalculateStepsTest = typedef CalculateStepsTest<double>
Definition at line 323 of file SplineTest.cpp.
DoubleConstantTest
using rawspeed_test::DoubleConstantTest = typedef ConstantTest<double>
Definition at line 417 of file SplineTest.cpp.
DoubleIdentityTest
using rawspeed_test::DoubleIdentityTest = typedef IdentityTest<double>
Definition at line 228 of file SplineTest.cpp.
DummyHuffmanTableDeathTest
using rawspeed_test::DummyHuffmanTableDeathTest = typedef DummyHuffmanTableTest
Definition at line 596 of file AbstractHuffmanTableTest.cpp.
generateCodeSymbolsDataType
using rawspeed_test::generateCodeSymbolsDataType = typedef std::tuple<std::vector<uint8_t>, std::vector<AbstractHuffmanTable::CodeSymbol> >
Definition at line 532 of file AbstractHuffmanTableTest.cpp.
hasPositiveAreaType
using rawspeed_test::hasPositiveAreaType = typedef std::tuple<int, int>
Definition at line 325 of file PointTest.cpp.
identityType
using rawspeed_test::identityType = typedef std::tuple<std::array<rawspeed::iPoint2D, 2>, std::vector<std::array<double, 4> >>
Definition at line 176 of file SplineTest.cpp.
IntegerCalculateStepsTest
using rawspeed_test::IntegerCalculateStepsTest = typedef CalculateStepsTest<int>
Definition at line 340 of file SplineTest.cpp.
IntegerConstantTest
using rawspeed_test::IntegerConstantTest = typedef ConstantTest<uint16_t>
Definition at line 408 of file SplineTest.cpp.
IntegerIdentityTest
using rawspeed_test::IntegerIdentityTest = typedef IdentityTest<uint16_t>
Definition at line 219 of file SplineTest.cpp.
IntPair
using rawspeed_test::IntPair = typedef pair<int, int>
Definition at line 150 of file PointTest.cpp.
IsAlignedType
using rawspeed_test::IsAlignedType = typedef std::tuple<int, int>
Definition at line 185 of file CommonTest.cpp.
IsInType
using rawspeed_test::IsInType = typedef std::tuple<string, bool>
Definition at line 204 of file CommonTest.cpp.
operatorsType
using rawspeed_test::operatorsType = typedef std::tuple<IntPair, IntPair, bool, bool, bool, bool, bool>
Definition at line 425 of file PointTest.cpp.
Patterns
template<typename Pump > using rawspeed_test::Patterns = typedef ::testing::Types<PumpAndPattern<Pump, Pattern<Pump, ZerosTag> >, PumpAndPattern<Pump, Pattern<Pump, OnesTag> >, PumpAndPattern<Pump, Pattern<Pump, InvOnesTag> >, PumpAndPattern<Pump, Pattern<Pump, SaturatedTag> >>
Definition at line 248 of file BitPumpTest.h.
powerOfTwoType
using rawspeed_test::powerOfTwoType = typedef std::tuple<int, bool>
Definition at line 55 of file CommonTest.cpp.
referenceType
using rawspeed_test::referenceType = typedef std::tuple<int, long double>
Definition at line 452 of file SplineTest.cpp.
RoundDownType
using rawspeed_test::RoundDownType = typedef std::tuple<size_t, size_t, size_t>
Definition at line 80 of file CommonTest.cpp.
RoundUpDivisionType
using rawspeed_test::RoundUpDivisionType = typedef std::tuple<size_t, size_t, size_t>
Definition at line 134 of file CommonTest.cpp.
RoundUpType
using rawspeed_test::RoundUpType = typedef std::tuple<size_t, size_t, size_t>
Definition at line 108 of file CommonTest.cpp.
SignExtendDataType
using rawspeed_test::SignExtendDataType = typedef std::tuple<uint32_t, uint32_t, int>
Definition at line 435 of file AbstractHuffmanTableTest.cpp.
Sin2PiRefTest
using rawspeed_test::Sin2PiRefTest = typedef ReferenceTest<SinReferenceTest<2, 1> >
Definition at line 501 of file SplineTest.cpp.
SinPiRefTest
using rawspeed_test::SinPiRefTest = typedef ReferenceTest<SinReferenceTest<1, 1> >
Definition at line 525 of file SplineTest.cpp.
Six
using rawspeed_test::Six = typedef std::tuple<IntPair, IntPair, IntPair>
Definition at line 151 of file PointTest.cpp.
splitStringType
using rawspeed_test::splitStringType = typedef std::tuple<string, char, vector<string> >
Definition at line 325 of file CommonTest.cpp.
TrimSpacesType
using rawspeed_test::TrimSpacesType = typedef std::tuple<string, string>
Definition at line 289 of file CommonTest.cpp.
twoRangesType
using rawspeed_test::twoRangesType = typedef std::tuple<int, unsigned, int, unsigned>
Definition at line 102 of file RangeTest.h.
uint32TType
using rawspeed_test::uint32TType = typedef std::tuple<uint32Type, bool>
Definition at line 103 of file EndiannessTest.h.
uint32Type
using rawspeed_test::uint32Type = typedef intPair<uint32_t>
Definition at line 102 of file EndiannessTest.h.
uint64TType
using rawspeed_test::uint64TType = typedef std::tuple<uint64Type, bool>
Definition at line 236 of file EndiannessTest.h.
uint64Type
using rawspeed_test::uint64Type = typedef intPair<uint64_t>
Definition at line 235 of file EndiannessTest.h.
ushort16TType
using rawspeed_test::ushort16TType = typedef std::tuple<ushort16Type, bool>
Definition at line 34 of file EndiannessTest.h.
ushort16Type
using rawspeed_test::ushort16Type = typedef intPair<uint16_t>
Definition at line 33 of file EndiannessTest.h.
Function Documentation
calculateSteps()
template<typename T = int, typename = std::enable_if_t<std::is_arithmetic<T>::value>> std::vector<T> rawspeed_test::calculateSteps (int numCp)
Definition at line 245 of file SplineTest.cpp.
check()
static void rawspeed_test::check (ColorFilterArray * cfa, Bayer2x2 param) static
Definition at line 172 of file ColorFilterArrayTest.cpp.
GenerateAllPossibleCodeSymbols()
std::vector<AbstractHuffmanTable::CodeSymbol> rawspeed_test::GenerateAllPossibleCodeSymbols ()
Definition at line 181 of file AbstractHuffmanTableTest.cpp.
INSTANTIATE_TEST_CASE_P() [1/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (AreaTest , AreaTest , ::testing::ValuesIn(valueArea))
INSTANTIATE_TEST_CASE_P() [2/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (BlackAreas , BlackAreaTest , testing::Combine(testing::Range(0, 1000, 250), testing::Range(0, 1000, 250), testing::Bool()))
INSTANTIATE_TEST_CASE_P() [3/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (CalculateStepsEdgesTest , CalculateStepsEdgesTest , ::testing::Range(0, 254))
INSTANTIATE_TEST_CASE_P() [4/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (CalculateStepsTest , DoubleCalculateStepsTest , ::testing::ValuesIn(calculateStepsValues))
INSTANTIATE_TEST_CASE_P() [5/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (CalculateStepsTest , IntegerCalculateStepsTest , ::testing::ValuesIn(calculateStepsValues))
INSTANTIATE_TEST_CASE_P() [6/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (ClampBitsTest , ClampBitsTest , ::testing::ValuesIn(ClampBitsValues))
INSTANTIATE_TEST_CASE_P() [7/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (CodeSymbolDeathTest , CodeSymbolDeathTest , ::testing::ValuesIn(CodeSymbolData))
INSTANTIATE_TEST_CASE_P() [8/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (CodeSymbolHaveCommonPrefixTest , CodeSymbolHaveCommonPrefixTest , ::testing::Combine(::testing::ValuesIn(allPossibleCodeSymbols), ::testing::ValuesIn(allPossibleCodeSymbols)))
INSTANTIATE_TEST_CASE_P() [9/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (CodeSymbolPrintTest , CodeSymbolPrintTest , ::testing::ValuesIn(CodeSymbolPrintData))
INSTANTIATE_TEST_CASE_P() [10/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (CopyPixelsTest , CopyPixelsTest , testing::Combine(testing::Range(0, 4, 1), testing::Range(0, 4, 1), testing::Range(0, 4, 1), testing::Range(0, 4, 1)))
INSTANTIATE_TEST_CASE_P() [11/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (CYGM , ColorFilterArrayShiftTest , testing::Combine(Bayer_CYGM, Bayer_CYGM, Bayer_CYGM, Bayer_CYGM, testing::Range(-2, 2), testing::Range(-2, 2)))
INSTANTIATE_TEST_CASE_P() [12/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (CYGM , ColorFilterArrayTest , testing::Combine(Bayer_CYGM, Bayer_CYGM, Bayer_CYGM, Bayer_CYGM))
INSTANTIATE_TEST_CASE_P() [13/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (DoubleConstantTest , DoubleConstantTest , constantValues)
INSTANTIATE_TEST_CASE_P() [14/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (DoubleIdentityTest , DoubleIdentityTest , ::testing::ValuesIn(identityValues))
INSTANTIATE_TEST_CASE_P() [15/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (doubleTest , doubleTest , ::testing::Combine(::testing::ValuesIn(uint64Values), ::testing::Bool()))
INSTANTIATE_TEST_CASE_P() [16/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (Expectations , CameraSensorInfoTest , testing::ValuesIn(CameraSensorIsoInfos))
INSTANTIATE_TEST_CASE_P() [17/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (floatTest , floatTest , ::testing::Combine(::testing::ValuesIn(uint32Values), ::testing::Bool()))
INSTANTIATE_TEST_CASE_P() [18/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (generateCodeSymbolsTest , generateCodeSymbolsTest , ::testing::ValuesIn(generateCodeSymbolsData))
INSTANTIATE_TEST_CASE_P() [19/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (GetSmallestTest , SmallestTest , ::testing::ValuesIn(smallestValues))
INSTANTIATE_TEST_CASE_P() [20/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (HasPositiveAreaTest , HasPositiveAreaTest , ::testing::Combine(::testing::Range(-2, 3), ::testing::Range(-2, 3)))
INSTANTIATE_TEST_CASE_P() [21/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (int32Test , int32Test , ::testing::Combine(::testing::ValuesIn(uint32Values), ::testing::Bool()))
INSTANTIATE_TEST_CASE_P() [22/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (IntegerConstantTest , IntegerConstantTest , constantValues)
INSTANTIATE_TEST_CASE_P() [23/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (IntegerIdentityTest , IntegerIdentityTest , ::testing::ValuesIn(identityValues))
INSTANTIATE_TEST_CASE_P() [24/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (IsAlignedTest , IsAlignedTest , ::testing::Combine(::testing::Range(0, 32), ::testing::Range(0, 32)))
INSTANTIATE_TEST_CASE_P() [25/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (IsInTest , IsInTest , ::testing::ValuesIn(IsInValues))
INSTANTIATE_TEST_CASE_P() [26/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (MinMax , CameraSensorInfoTestDumb , testing::Combine(testing::ValuesIn(ISOList), testing::ValuesIn(ISOList)))
INSTANTIATE_TEST_CASE_P() [27/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (NotTrue , BoolHintTest , ::testing::Values("True", "false", "False", "", "_"))
INSTANTIATE_TEST_CASE_P() [28/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (OperatorsTests , OperatorsTest , ::testing::ValuesIn(operatorsValues))
INSTANTIATE_TEST_CASE_P() [29/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (PowerOfTwoTest , PowerOfTwoTest , ::testing::ValuesIn(powerOfTwoValues))
INSTANTIATE_TEST_CASE_P() [30/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (RGGB , ColorFilterArrayShiftTest , testing::Combine(Bayer_RGB, Bayer_RGB, Bayer_RGB, Bayer_RGB, testing::Range(-2, 2), testing::Range(-2, 2)))
INSTANTIATE_TEST_CASE_P() [31/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (RGGB , ColorFilterArrayTest , testing::Combine(Bayer_RGB, Bayer_RGB, Bayer_RGB, Bayer_RGB))
INSTANTIATE_TEST_CASE_P() [32/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (RoundDownTest , RoundDownTest , ::testing::ValuesIn(RoundDownValues))
INSTANTIATE_TEST_CASE_P() [33/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (RoundUpDivisionTest , RoundUpDivisionTest , ::testing::ValuesIn(RoundUpDivisionValues))
INSTANTIATE_TEST_CASE_P() [34/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (RoundUpTest , RoundUpTest , ::testing::ValuesIn(RoundUpValues))
INSTANTIATE_TEST_CASE_P() [35/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (short16Test , short16Test , ::testing::Combine(::testing::ValuesIn(ushort16Values), ::testing::Bool()))
INSTANTIATE_TEST_CASE_P() [36/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (SignExtendTest , SignExtendTest , ::testing::ValuesIn(signExtendData))
INSTANTIATE_TEST_CASE_P() [37/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (Sin2Pi , Sin2PiRefTest , ::testing::ValuesIn(sin2PiRefValues))
INSTANTIATE_TEST_CASE_P() [38/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (SinPi , SinPiRefTest , ::testing::ValuesIn(sinPiRefValues))
INSTANTIATE_TEST_CASE_P() [39/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (SplitStringTest , SplitStringTest , ::testing::ValuesIn(splitStringValues))
INSTANTIATE_TEST_CASE_P() [40/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (SumTest , PointTest , ::testing::ValuesIn(valueSum))
INSTANTIATE_TEST_CASE_P() [41/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (TrimSpacesTest , TrimSpacesTest , ::testing::ValuesIn(TrimSpacesValues))
INSTANTIATE_TEST_CASE_P() [42/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (uint32Test , uint32Test , ::testing::Combine(::testing::ValuesIn(uint32Values), ::testing::Bool()))
INSTANTIATE_TEST_CASE_P() [43/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (uint64Test , uint64Test , ::testing::Combine(::testing::ValuesIn(uint64Values), ::testing::Bool()))
INSTANTIATE_TEST_CASE_P() [44/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (Unsigned , TwoRangesTest , testing::Combine(testing::Range(0, 3), testing::Range(0U, 3U), testing::Range(0, 3), testing::Range(0U, 3U)))
INSTANTIATE_TEST_CASE_P() [45/45]
rawspeed_test::INSTANTIATE_TEST_CASE_P (ushort16Test , ushort16Test , ::testing::Combine(::testing::ValuesIn(ushort16Values), ::testing::Bool()))
INSTANTIATE_TYPED_TEST_CASE_P() [1/5]
rawspeed_test::INSTANTIATE_TYPED_TEST_CASE_P (JPEG , BitPumpTest , Patterns< BitPumpJPEG >)
INSTANTIATE_TYPED_TEST_CASE_P() [2/5]
rawspeed_test::INSTANTIATE_TYPED_TEST_CASE_P (LSB , BitPumpTest , Patterns< BitPumpLSB >)
INSTANTIATE_TYPED_TEST_CASE_P() [3/5]
rawspeed_test::INSTANTIATE_TYPED_TEST_CASE_P (MSB , BitPumpTest , Patterns< BitPumpMSB >)
INSTANTIATE_TYPED_TEST_CASE_P() [4/5]
rawspeed_test::INSTANTIATE_TYPED_TEST_CASE_P (MSB16 , BitPumpTest , Patterns< BitPumpMSB16 >)
INSTANTIATE_TYPED_TEST_CASE_P() [5/5]
rawspeed_test::INSTANTIATE_TYPED_TEST_CASE_P (MSB32 , BitPumpTest , Patterns< BitPumpMSB32 >)
ISOList()
std::vector<int> rawspeed_test::ISOList (6)
lerp()
template<typename T > T rawspeed_test::lerp (T v0, T v1, T t)
Definition at line 239 of file SplineTest.cpp.
MetaHelper()
template<typename T > static void* rawspeed_test::MetaHelper (const char * str) static
Definition at line 53 of file ExceptionsTest.cpp.
MetaHelper< CameraMetadataException >()
template<> void* rawspeed_test::MetaHelper< CameraMetadataException > (const char * str)
Definition at line 62 of file ExceptionsTest.cpp.
MetaHelper< CiffParserException >()
template<> void* rawspeed_test::MetaHelper< CiffParserException > (const char * str)
Definition at line 66 of file ExceptionsTest.cpp.
MetaHelper< FiffParserException >()
template<> void* rawspeed_test::MetaHelper< FiffParserException > (const char * str)
Definition at line 90 of file ExceptionsTest.cpp.
MetaHelper< FileIOException >()
template<> void* rawspeed_test::MetaHelper< FileIOException > (const char * str)
Definition at line 70 of file ExceptionsTest.cpp.
MetaHelper< IOException >()
template<> void* rawspeed_test::MetaHelper< IOException > (const char * str)
Definition at line 74 of file ExceptionsTest.cpp.
MetaHelper< RawDecoderException >()
template<> void* rawspeed_test::MetaHelper< RawDecoderException > (const char * str)
Definition at line 78 of file ExceptionsTest.cpp.
MetaHelper< RawParserException >()
template<> void* rawspeed_test::MetaHelper< RawParserException > (const char * str)
Definition at line 82 of file ExceptionsTest.cpp.
MetaHelper< RawspeedException >()
template<> void* rawspeed_test::MetaHelper< RawspeedException > (const char * str)
Definition at line 58 of file ExceptionsTest.cpp.
MetaHelper< TiffParserException >()
template<> void* rawspeed_test::MetaHelper< TiffParserException > (const char * str)
Definition at line 86 of file ExceptionsTest.cpp.
operator<<()
template<typename T > ::std::ostream& rawspeed_test::operator<< (::std::ostream & os, const intPair< T > & p)
Definition at line 77 of file EndiannessTest.cpp.
RangeContains()
template<typename T > ::testing::AssertionResult rawspeed_test::RangeContains (const char * range_expr, const char * pos_expr, const Range< T > & r, const T & pos)
Definition at line 44 of file RangeTest.h.
RangeDoesntContain()
template<typename T > ::testing::AssertionResult rawspeed_test::RangeDoesntContain (const char * range_expr, const char * pos_expr, const Range< T > & r, const T & pos)
Definition at line 59 of file RangeTest.h.
RangesDontOverlap()
template<typename T > ::testing::AssertionResult rawspeed_test::RangesDontOverlap (const char * m_expr, const char * n_expr, const T & lhs, const T & rhs)
Definition at line 88 of file RangeTest.h.
RangesOverlap()
template<typename T > ::testing::AssertionResult rawspeed_test::RangesOverlap (const char * m_expr, const char * n_expr, const T & lhs, const T & rhs)
Definition at line 74 of file RangeTest.h.
REGISTER_TYPED_TEST_CASE_P()
rawspeed_test::REGISTER_TYPED_TEST_CASE_P (BitPumpTest , GetTest , GetNoFillTest , PeekTest , PeekNoFillTest , IncreasingPeekLengthTest , IncreasingPeekLengthNoFillTest)
setHelper()
static void rawspeed_test::setHelper (ColorFilterArray * cfa, Bayer2x2 param) static
Definition at line 167 of file ColorFilterArrayTest.cpp.
TEST() [1/82]
rawspeed_test::TEST (AbstractHuffmanTableCodeSymbolTest , Equality)
Definition at line 66 of file AbstractHuffmanTableTest.cpp.
TEST() [2/82]
rawspeed_test::TEST (AbstractHuffmanTableDeathTest , setCodeValuesRequiresCount)
Definition at line 373 of file AbstractHuffmanTableTest.cpp.
TEST() [3/82]
rawspeed_test::TEST (AbstractHuffmanTableDeathTest , setCodeValuesRequiresLessThan162)
Definition at line 400 of file AbstractHuffmanTableTest.cpp.
TEST() [4/82]
rawspeed_test::TEST (AbstractHuffmanTableDeathTest , setNCodesPerLengthRequires16Lengths)
Definition at line 278 of file AbstractHuffmanTableTest.cpp.
TEST() [5/82]
rawspeed_test::TEST (AbstractHuffmanTableTest , EqualCompareAndTrimming)
Definition at line 419 of file AbstractHuffmanTableTest.cpp.
TEST() [6/82]
rawspeed_test::TEST (AbstractHuffmanTableTest , setCodeValuesValueLessThan16)
Definition at line 408 of file AbstractHuffmanTableTest.cpp.
TEST() [7/82]
rawspeed_test::TEST (AbstractHuffmanTableTest , setNCodesPerLengthCodeSymbolOverflow)
Definition at line 351 of file AbstractHuffmanTableTest.cpp.
TEST() [8/82]
rawspeed_test::TEST (AbstractHuffmanTableTest , setNCodesPerLengthCounts)
Definition at line 362 of file AbstractHuffmanTableTest.cpp.
TEST() [9/82]
rawspeed_test::TEST (AbstractHuffmanTableTest , setNCodesPerLengthEmptyIsBad)
Definition at line 325 of file AbstractHuffmanTableTest.cpp.
TEST() [10/82]
rawspeed_test::TEST (AbstractHuffmanTableTest , setNCodesPerLengthEqualCompareAndTrimming)
Definition at line 303 of file AbstractHuffmanTableTest.cpp.
TEST() [11/82]
rawspeed_test::TEST (AbstractHuffmanTableTest , setNCodesPerLengthTooManyCodesForLength)
Definition at line 337 of file AbstractHuffmanTableTest.cpp.
TEST() [12/82]
rawspeed_test::TEST (AbstractHuffmanTableTest , setNCodesPerLengthTooManyCodesTotal)
Definition at line 331 of file AbstractHuffmanTableTest.cpp.
TEST() [13/82]
rawspeed_test::TEST (AlignedMallocDeathTest , AlignedFreeHandlesNullptr)
Definition at line 141 of file MemoryTest.cpp.
TEST() [14/82]
rawspeed_test::TEST (AlignedMallocDeathTest , TemplateArraySizeAssertions)
Definition at line 238 of file MemoryTest.cpp.
TEST() [15/82]
rawspeed_test::TEST (AlignedMallocTest , TemplateArraySizeRoundUp)
Definition at line 251 of file MemoryTest.cpp.
TEST() [16/82]
rawspeed_test::TEST (BinaryHuffmanTreeDeathTest , getAllBranchesOfNegativeDepth)
Definition at line 51 of file BinaryHuffmanTreeTest.cpp.
TEST() [17/82]
rawspeed_test::TEST (BinaryHuffmanTreeDeathTest , getAllNodesAtZeroDepth)
Definition at line 93 of file BinaryHuffmanTreeTest.cpp.
TEST() [18/82]
rawspeed_test::TEST (BinaryHuffmanTreeTest , EmptyByDefault)
Definition at line 32 of file BinaryHuffmanTreeTest.cpp.
TEST() [19/82]
rawspeed_test::TEST (BinaryHuffmanTreeTest , getAllBranchesOfDepth_0_Base)
Definition at line 62 of file BinaryHuffmanTreeTest.cpp.
TEST() [20/82]
rawspeed_test::TEST (BinaryHuffmanTreeTest , getAllBranchesOfDepth_1_Base)
Definition at line 76 of file BinaryHuffmanTreeTest.cpp.
TEST() [21/82]
rawspeed_test::TEST (BinaryHuffmanTreeTest , getAllVacantNodesAtDepth_1_after_adding_1_depth_1_leaf)
Definition at line 146 of file BinaryHuffmanTreeTest.cpp.
TEST() [22/82]
rawspeed_test::TEST (BinaryHuffmanTreeTest , getAllVacantNodesAtDepth_1_Base)
Definition at line 104 of file BinaryHuffmanTreeTest.cpp.
TEST() [23/82]
rawspeed_test::TEST (BinaryHuffmanTreeTest , getAllVacantNodesAtDepth_2_after_adding_1_depth_1_and_1_depth_2_leaf)
Definition at line 210 of file BinaryHuffmanTreeTest.cpp.
TEST() [24/82]
rawspeed_test::TEST (BinaryHuffmanTreeTest , getAllVacantNodesAtDepth_2_after_adding_1_depth_1_leaf)
Definition at line 169 of file BinaryHuffmanTreeTest.cpp.
TEST() [25/82]
rawspeed_test::TEST (BinaryHuffmanTreeTest , getAllVacantNodesAtDepth_2_Base)
Definition at line 128 of file BinaryHuffmanTreeTest.cpp.
TEST() [26/82]
rawspeed_test::TEST (BinaryHuffmanTreeTest , getAllVacantNodesAtDepth_2_fills_depth_1_with_branches)
Definition at line 112 of file BinaryHuffmanTreeTest.cpp.
TEST() [27/82]
rawspeed_test::TEST (BinaryHuffmanTreeTest , pruneLeaflessBranches_purges_all)
Definition at line 138 of file BinaryHuffmanTreeTest.cpp.
TEST() [28/82]
rawspeed_test::TEST (BitPumpJPEGTest , 0xFF0x00Is0xFFTest)
Definition at line 69 of file BitPumpJPEGTest.cpp.
References TYPED_TEST_CASE_P().
TEST() [29/82]
rawspeed_test::TEST (BitPumpJPEGTest , 0xFF0xXXIsTheEndTest)
Definition at line 89 of file BitPumpJPEGTest.cpp.
References TYPED_TEST_CASE_P().
TEST() [30/82]
rawspeed_test::TEST (BoolHintTest , HintsBoolTrue)
Definition at line 130 of file CameraTest.cpp.
TEST() [31/82]
rawspeed_test::TEST (CalculateStepsEdgesTest , IdentityTest)
Definition at line 263 of file SplineTest.cpp.
TEST() [32/82]
rawspeed_test::TEST (CameraTest , HintsAdd)
Definition at line 81 of file CameraTest.cpp.
TEST() [33/82]
rawspeed_test::TEST (CameraTest , HintsAssignment)
Definition at line 65 of file CameraTest.cpp.
TEST() [34/82]
rawspeed_test::TEST (CameraTest , HintsAssignmentConstructor)
Definition at line 49 of file CameraTest.cpp.
TEST() [35/82]
rawspeed_test::TEST (CameraTest , HintsDouble)
Definition at line 120 of file CameraTest.cpp.
TEST() [36/82]
rawspeed_test::TEST (CameraTest , HintsEmpty)
Definition at line 32 of file CameraTest.cpp.
TEST() [37/82]
rawspeed_test::TEST (CameraTest , HintsFloat)
Definition at line 110 of file CameraTest.cpp.
TEST() [38/82]
rawspeed_test::TEST (CameraTest , HintsGetDefault)
Definition at line 37 of file CameraTest.cpp.
TEST() [39/82]
rawspeed_test::TEST (CameraTest , HintsInt)
Definition at line 90 of file CameraTest.cpp.
TEST() [40/82]
rawspeed_test::TEST (CameraTest , HintsUInt)
Definition at line 100 of file CameraTest.cpp.
TEST() [41/82]
rawspeed_test::TEST (ClampBitsDeathTest , Only16Bit)
Definition at line 276 of file CommonTest.cpp.
TEST() [42/82]
rawspeed_test::TEST (ClampBitsUnsignedDeathTest , NoNopClamps)
Definition at line 282 of file CommonTest.cpp.
TEST() [43/82]
rawspeed_test::TEST (CodeSymbolDeathTest , CodeSymbolLength)
Definition at line 77 of file AbstractHuffmanTableTest.cpp.
TEST() [44/82]
rawspeed_test::TEST (CodeSymbolHaveCommonPrefixDeathTest , AsymmetricalDeathTest)
Definition at line 232 of file AbstractHuffmanTableTest.cpp.
TEST() [45/82]
rawspeed_test::TEST (CodeSymbolHaveCommonPrefixTest , BasicTest)
Definition at line 215 of file AbstractHuffmanTableTest.cpp.
TEST() [46/82]
rawspeed_test::TEST (ColorFilterArrayTestBasic , Constructor)
Definition at line 56 of file ColorFilterArrayTest.cpp.
TEST() [47/82]
rawspeed_test::TEST (ColorFilterArrayTestBasic , DISABLED_SetTooBigSize)
Definition at line 78 of file ColorFilterArrayTest.cpp.
TEST() [48/82]
rawspeed_test::TEST (ColorFilterArrayTestBasic , HandlesEmptyCFA)
Definition at line 117 of file ColorFilterArrayTest.cpp.
TEST() [49/82]
rawspeed_test::TEST (ColorFilterArrayTestBasic , HandlesOutOfBounds)
Definition at line 127 of file ColorFilterArrayTest.cpp.
References rawspeed::ColorFilterArray::ColorFilterArray(), and square.
TEST() [50/82]
rawspeed_test::TEST (ColorFilterArrayTestBasic , SetSize)
Definition at line 63 of file ColorFilterArrayTest.cpp.
TEST() [51/82]
rawspeed_test::TEST (ColorFilterArrayTestBasic , shiftDcrawFilter)
Definition at line 266 of file ColorFilterArrayTest.cpp.
TEST() [52/82]
rawspeed_test::TEST (ColorFilterArrayTestBasic , ToDcraw)
Definition at line 85 of file ColorFilterArrayTest.cpp.
TEST() [53/82]
rawspeed_test::TEST (CpuidDeathTest , SSE2Test)
Definition at line 31 of file CpuidTest.cpp.
TEST() [54/82]
rawspeed_test::TEST (EndiannessTest , getHostEndiannessTests)
Definition at line 43 of file EndiannessTest.cpp.
TEST() [55/82]
rawspeed_test::TEST (HuffmanTableTest , decodeCodeValueBadCodeTest)
Definition at line 102 of file HuffmanTableTest.cpp.
References rawspeed::ByteStream::ByteStream(), and rawspeed::little.
TEST() [56/82]
rawspeed_test::TEST (HuffmanTableTest , decodeCodeValueIdentityTest)
Definition at line 67 of file HuffmanTableTest.cpp.
References rawspeed::ByteStream::ByteStream(), and rawspeed::little.
TEST() [57/82]
rawspeed_test::TEST (HuffmanTableTest , decodeDifferenceBadCodeTest)
Definition at line 117 of file HuffmanTableTest.cpp.
References rawspeed::ByteStream::ByteStream(), and rawspeed::little.
TEST() [58/82]
rawspeed_test::TEST (HuffmanTableTest , decodeDifferenceIdentityTest)
Definition at line 85 of file HuffmanTableTest.cpp.
References rawspeed::ByteStream::ByteStream(), and rawspeed::little.
TEST() [59/82]
rawspeed_test::TEST (MakeUniqueTest , Test)
Definition at line 411 of file CommonTest.cpp.
TEST() [60/82]
rawspeed_test::TEST (ParseChecksumFileContentTest , Empty)
Definition at line 32 of file ChecksumFileTest.cpp.
TEST() [61/82]
rawspeed_test::TEST (ParseChecksumFileContentTest , Lines)
Definition at line 46 of file ChecksumFileTest.cpp.
TEST() [62/82]
rawspeed_test::TEST (ParseChecksumFileContentTest , ShortLine)
Definition at line 37 of file ChecksumFileTest.cpp.
TEST() [63/82]
rawspeed_test::TEST (ParseChecksumFileContentTest , TheTest)
Definition at line 63 of file ChecksumFileTest.cpp.
TEST() [64/82]
rawspeed_test::TEST (PointTest , AssignmentConstructor)
Definition at line 95 of file PointTest.cpp.
TEST() [65/82]
rawspeed_test::TEST (PointTest , Constructor)
Definition at line 57 of file PointTest.cpp.
TEST() [66/82]
rawspeed_test::TEST (PointTest , EqualityOperator)
Definition at line 127 of file PointTest.cpp.
TEST() [67/82]
rawspeed_test::TEST (PointTest , NonEqualityOperator)
Definition at line 136 of file PointTest.cpp.
TEST() [68/82]
rawspeed_test::TEST (RangeTest , BasicSignedContainsTest)
Definition at line 44 of file RangeTest.cpp.
TEST() [69/82]
rawspeed_test::TEST (RangeTest , BasicSignedCrossoverContainsTest)
Definition at line 61 of file RangeTest.cpp.
TEST() [70/82]
rawspeed_test::TEST (RangeTest , BasicSignedRangeForTest)
Definition at line 32 of file RangeTest.cpp.
TEST() [71/82]
rawspeed_test::TEST (RangeTest , BasicUnsignedContainsTest)
Definition at line 78 of file RangeTest.cpp.
TEST() [72/82]
rawspeed_test::TEST (RangeTest , SignedZeroSizeContainsTest)
Definition at line 95 of file RangeTest.cpp.
TEST() [73/82]
rawspeed_test::TEST (RangeTest , UnsignedZeroSizeContainsTest)
Definition at line 106 of file RangeTest.cpp.
TEST() [74/82]
rawspeed_test::TEST (SplineDeathTest , AtLeastTwoPoints)
Definition at line 56 of file SplineTest.cpp.
TEST() [75/82]
rawspeed_test::TEST (SplineDeathTest , ClampUshort16Max)
Definition at line 155 of file SplineTest.cpp.
TEST() [76/82]
rawspeed_test::TEST (SplineDeathTest , ClampUshort16Min)
Definition at line 136 of file SplineTest.cpp.
TEST() [77/82]
rawspeed_test::TEST (SplineDeathTest , XIsFullRange)
Definition at line 78 of file SplineTest.cpp.
TEST() [78/82]
rawspeed_test::TEST (SplineDeathTest , XIsStrictlyIncreasing)
Definition at line 108 of file SplineTest.cpp.
TEST() [79/82]
rawspeed_test::TEST (SplineDeathTest , YIsLimited)
Definition at line 93 of file SplineTest.cpp.
TEST() [80/82]
rawspeed_test::TEST (SplineStaticTest , DefaultIsUshort16)
Definition at line 50 of file SplineTest.cpp.
TEST() [81/82]
rawspeed_test::TEST (UnrollLoopTest , IsMonotonicallyPositiveTest)
Definition at line 403 of file CommonTest.cpp.
TEST() [82/82]
rawspeed_test::TEST (UnrollLoopTest , Test)
Definition at line 354 of file CommonTest.cpp.
TEST_F()
rawspeed_test::TEST_F (DummyHuffmanTableDeathTest , VerifyCodeSymbolsTest)
Definition at line 599 of file AbstractHuffmanTableTest.cpp.
TEST_P() [1/112]
rawspeed_test::TEST_P (AreaTest , AreaTest)
Definition at line 420 of file PointTest.cpp.
TEST_P() [2/112]
rawspeed_test::TEST_P (BlackAreaTest , Assignment)
Definition at line 129 of file BlackAreaTest.cpp.
TEST_P() [3/112]
rawspeed_test::TEST_P (BlackAreaTest , AssignmentConstructor)
Definition at line 87 of file BlackAreaTest.cpp.
TEST_P() [4/112]
rawspeed_test::TEST_P (BlackAreaTest , AssignmentConstructorGetters)
Definition at line 119 of file BlackAreaTest.cpp.
TEST_P() [5/112]
rawspeed_test::TEST_P (BlackAreaTest , AssignmentGetters)
Definition at line 161 of file BlackAreaTest.cpp.
TEST_P() [6/112]
rawspeed_test::TEST_P (BlackAreaTest , Constructor)
Definition at line 65 of file BlackAreaTest.cpp.
TEST_P() [7/112]
rawspeed_test::TEST_P (BlackAreaTest , Getters)
Definition at line 72 of file BlackAreaTest.cpp.
TEST_P() [8/112]
rawspeed_test::TEST_P (BoolHintTest , HintsBool)
Definition at line 148 of file CameraTest.cpp.
TEST_P() [9/112]
rawspeed_test::TEST_P (CalculateStepsEdgesTest , Count)
Definition at line 283 of file SplineTest.cpp.
TEST_P() [10/112]
rawspeed_test::TEST_P (CalculateStepsEdgesTest , EdgesAreProper)
Definition at line 286 of file SplineTest.cpp.
TEST_P() [11/112]
rawspeed_test::TEST_P (CameraSensorInfoTest , IsDefault)
Definition at line 284 of file CameraSensorInfoTest.cpp.
TEST_P() [12/112]
rawspeed_test::TEST_P (CameraSensorInfoTest , isIsoWithin)
Definition at line 296 of file CameraSensorInfoTest.cpp.
TEST_P() [13/112]
rawspeed_test::TEST_P (CameraSensorInfoTestDumb , Assignment)
Definition at line 177 of file CameraSensorInfoTest.cpp.
TEST_P() [14/112]
rawspeed_test::TEST_P (CameraSensorInfoTestDumb , AssignmentConstructor)
Definition at line 113 of file CameraSensorInfoTest.cpp.
TEST_P() [15/112]
rawspeed_test::TEST_P (CameraSensorInfoTestDumb , AssignmentConstructorGetters)
Definition at line 139 of file CameraSensorInfoTest.cpp.
TEST_P() [16/112]
rawspeed_test::TEST_P (CameraSensorInfoTestDumb , AssignmentGetters)
Definition at line 211 of file CameraSensorInfoTest.cpp.
TEST_P() [17/112]
rawspeed_test::TEST_P (CameraSensorInfoTestDumb , Constructor)
Definition at line 85 of file CameraSensorInfoTest.cpp.
TEST_P() [18/112]
rawspeed_test::TEST_P (CameraSensorInfoTestDumb , Getters)
Definition at line 97 of file CameraSensorInfoTest.cpp.
TEST_P() [19/112]
rawspeed_test::TEST_P (ClampBitsTest , ClampBitsTest)
Definition at line 275 of file CommonTest.cpp.
TEST_P() [20/112]
rawspeed_test::TEST_P (CodeSymbolDeathTest , CodeSymbolDeathTest)
Definition at line 114 of file AbstractHuffmanTableTest.cpp.
TEST_P() [21/112]
rawspeed_test::TEST_P (CodeSymbolHaveCommonPrefixTest , CodeSymbolHaveCommonPrefixTest)
Definition at line 200 of file AbstractHuffmanTableTest.cpp.
TEST_P() [22/112]
rawspeed_test::TEST_P (CodeSymbolPrintTest , CodeSymbolPrintTest)
Definition at line 158 of file AbstractHuffmanTableTest.cpp.
TEST_P() [23/112]
rawspeed_test::TEST_P (ColorFilterArrayShiftTest , shiftEqualityTest)
Definition at line 288 of file ColorFilterArrayTest.cpp.
TEST_P() [24/112]
rawspeed_test::TEST_P (ColorFilterArrayTest , AssignmentConstructor)
Definition at line 187 of file ColorFilterArrayTest.cpp.
TEST_P() [25/112]
rawspeed_test::TEST_P (ColorFilterArrayTest , AsString)
Definition at line 227 of file ColorFilterArrayTest.cpp.
TEST_P() [26/112]
rawspeed_test::TEST_P (ColorFilterArrayTest , Constructor)
Definition at line 179 of file ColorFilterArrayTest.cpp.
TEST_P() [27/112]
rawspeed_test::TEST_P (ColorFilterArrayTest , SetColorAt)
Definition at line 208 of file ColorFilterArrayTest.cpp.
TEST_P() [28/112]
rawspeed_test::TEST_P (ColorFilterArrayTest , ToDcraw)
Definition at line 219 of file ColorFilterArrayTest.cpp.
TEST_P() [29/112]
rawspeed_test::TEST_P (CopyPixelsTest , CopyPixelsTest)
Definition at line 476 of file CommonTest.cpp.
TEST_P() [30/112]
rawspeed_test::TEST_P (DoubleCalculateStepsTest , Count)
Definition at line 326 of file SplineTest.cpp.
TEST_P() [31/112]
rawspeed_test::TEST_P (DoubleCalculateStepsTest , GotExpectedOutput)
Definition at line 330 of file SplineTest.cpp.
TEST_P() [32/112]
rawspeed_test::TEST_P (DoubleConstantTest , AllValuesAreEqual)
Definition at line 419 of file SplineTest.cpp.
TEST_P() [33/112]
rawspeed_test::TEST_P (DoubleConstantTest , SegmentCoeffients)
Definition at line 425 of file SplineTest.cpp.
TEST_P() [34/112]
rawspeed_test::TEST_P (DoubleIdentityTest , SegmentCoeffients)
Definition at line 237 of file SplineTest.cpp.
TEST_P() [35/112]
rawspeed_test::TEST_P (DoubleIdentityTest , ValuesAreLinearlyInterpolated)
Definition at line 231 of file SplineTest.cpp.
TEST_P() [36/112]
rawspeed_test::TEST_P (doubleTest , get)
Definition at line 353 of file EndiannessTest.cpp.
TEST_P() [37/112]
rawspeed_test::TEST_P (doubleTest , getNOP)
Definition at line 360 of file EndiannessTest.cpp.
TEST_P() [38/112]
rawspeed_test::TEST_P (doubleTest , NOP)
Definition at line 347 of file EndiannessTest.cpp.
TEST_P() [39/112]
rawspeed_test::TEST_P (doubleTest , swap)
Definition at line 344 of file EndiannessTest.cpp.
TEST_P() [40/112]
rawspeed_test::TEST_P (doubleTest , typedSwap)
Definition at line 350 of file EndiannessTest.cpp.
TEST_P() [41/112]
rawspeed_test::TEST_P (floatTest , get)
Definition at line 325 of file EndiannessTest.cpp.
TEST_P() [42/112]
rawspeed_test::TEST_P (floatTest , getNOP)
Definition at line 332 of file EndiannessTest.cpp.
TEST_P() [43/112]
rawspeed_test::TEST_P (floatTest , NOP)
Definition at line 319 of file EndiannessTest.cpp.
TEST_P() [44/112]
rawspeed_test::TEST_P (floatTest , swap)
Definition at line 316 of file EndiannessTest.cpp.
TEST_P() [45/112]
rawspeed_test::TEST_P (floatTest , typedSwap)
Definition at line 322 of file EndiannessTest.cpp.
TEST_P() [46/112]
rawspeed_test::TEST_P (generateCodeSymbolsTest , generateCodeSymbolsTest)
Definition at line 584 of file AbstractHuffmanTableTest.cpp.
TEST_P() [47/112]
rawspeed_test::TEST_P (HasPositiveAreaTest , HasPositiveAreaTest)
Definition at line 346 of file PointTest.cpp.
TEST_P() [48/112]
rawspeed_test::TEST_P (int32Test , get)
Definition at line 266 of file EndiannessTest.cpp.
TEST_P() [49/112]
rawspeed_test::TEST_P (int32Test , getNOP)
Definition at line 273 of file EndiannessTest.cpp.
TEST_P() [50/112]
rawspeed_test::TEST_P (int32Test , NOP)
Definition at line 260 of file EndiannessTest.cpp.
TEST_P() [51/112]
rawspeed_test::TEST_P (int32Test , swap)
Definition at line 257 of file EndiannessTest.cpp.
TEST_P() [52/112]
rawspeed_test::TEST_P (int32Test , typedSwap)
Definition at line 263 of file EndiannessTest.cpp.
TEST_P() [53/112]
rawspeed_test::TEST_P (IntegerCalculateStepsTest , Count)
Definition at line 343 of file SplineTest.cpp.
TEST_P() [54/112]
rawspeed_test::TEST_P (IntegerCalculateStepsTest , GotExpectedOutput)
Definition at line 347 of file SplineTest.cpp.
TEST_P() [55/112]
rawspeed_test::TEST_P (IntegerConstantTest , AllValuesAreEqual)
Definition at line 411 of file SplineTest.cpp.
TEST_P() [56/112]
rawspeed_test::TEST_P (IntegerConstantTest , SegmentCoeffients)
Definition at line 415 of file SplineTest.cpp.
TEST_P() [57/112]
rawspeed_test::TEST_P (IntegerIdentityTest , SegmentCoeffients)
Definition at line 226 of file SplineTest.cpp.
TEST_P() [58/112]
rawspeed_test::TEST_P (IntegerIdentityTest , ValuesAreLinearlyInterpolated)
Definition at line 222 of file SplineTest.cpp.
TEST_P() [59/112]
rawspeed_test::TEST_P (IsAlignedTest , IsAlignedAfterRoundUpTest)
Definition at line 200 of file CommonTest.cpp.
TEST_P() [60/112]
rawspeed_test::TEST_P (IsInTest , IsInTest)
Definition at line 225 of file CommonTest.cpp.
TEST_P() [61/112]
rawspeed_test::TEST_P (OperatorsTest , OperatorEQTest)
Definition at line 674 of file PointTest.cpp.
TEST_P() [62/112]
rawspeed_test::TEST_P (OperatorsTest , OperatorGEest)
Definition at line 696 of file PointTest.cpp.
TEST_P() [63/112]
rawspeed_test::TEST_P (OperatorsTest , OperatorGTest)
Definition at line 687 of file PointTest.cpp.
TEST_P() [64/112]
rawspeed_test::TEST_P (OperatorsTest , OperatorLETest)
Definition at line 692 of file PointTest.cpp.
TEST_P() [65/112]
rawspeed_test::TEST_P (OperatorsTest , OperatorLTTest)
Definition at line 683 of file PointTest.cpp.
TEST_P() [66/112]
rawspeed_test::TEST_P (OperatorsTest , OperatorNETest)
Definition at line 678 of file PointTest.cpp.
TEST_P() [67/112]
rawspeed_test::TEST_P (OperatorsTest , OperatorsTest)
Definition at line 701 of file PointTest.cpp.
TEST_P() [68/112]
rawspeed_test::TEST_P (PointTest , AddTest1)
Definition at line 287 of file PointTest.cpp.
TEST_P() [69/112]
rawspeed_test::TEST_P (PointTest , AddTest2)
Definition at line 293 of file PointTest.cpp.
TEST_P() [70/112]
rawspeed_test::TEST_P (PointTest , InPlaceAddTest1)
Definition at line 275 of file PointTest.cpp.
TEST_P() [71/112]
rawspeed_test::TEST_P (PointTest , InPlaceAddTest2)
Definition at line 281 of file PointTest.cpp.
TEST_P() [72/112]
rawspeed_test::TEST_P (PointTest , InPlaceSubTest1)
Definition at line 300 of file PointTest.cpp.
TEST_P() [73/112]
rawspeed_test::TEST_P (PointTest , InPlaceSubTest2)
Definition at line 306 of file PointTest.cpp.
TEST_P() [74/112]
rawspeed_test::TEST_P (PointTest , SubTest1)
Definition at line 312 of file PointTest.cpp.
TEST_P() [75/112]
rawspeed_test::TEST_P (PointTest , SubTest2)
Definition at line 318 of file PointTest.cpp.
TEST_P() [76/112]
rawspeed_test::TEST_P (PowerOfTwoTest , PowerOfTwoTest)
Definition at line 76 of file CommonTest.cpp.
TEST_P() [77/112]
rawspeed_test::TEST_P (RoundDownTest , RoundDownTest)
Definition at line 104 of file CommonTest.cpp.
TEST_P() [78/112]
rawspeed_test::TEST_P (RoundUpDivisionTest , RoundUpDivisionTest)
Definition at line 181 of file CommonTest.cpp.
TEST_P() [79/112]
rawspeed_test::TEST_P (RoundUpTest , RoundUpTest)
Definition at line 132 of file CommonTest.cpp.
TEST_P() [80/112]
rawspeed_test::TEST_P (short16Test , get)
Definition at line 192 of file EndiannessTest.cpp.
TEST_P() [81/112]
rawspeed_test::TEST_P (short16Test , getNOP)
Definition at line 199 of file EndiannessTest.cpp.
TEST_P() [82/112]
rawspeed_test::TEST_P (short16Test , NOP)
Definition at line 186 of file EndiannessTest.cpp.
TEST_P() [83/112]
rawspeed_test::TEST_P (short16Test , swap)
Definition at line 183 of file EndiannessTest.cpp.
TEST_P() [84/112]
rawspeed_test::TEST_P (short16Test , typedSwap)
Definition at line 189 of file EndiannessTest.cpp.
TEST_P() [85/112]
rawspeed_test::TEST_P (SignExtendTest , SignExtendTest)
Definition at line 526 of file AbstractHuffmanTableTest.cpp.
TEST_P() [86/112]
rawspeed_test::TEST_P (Sin2PiRefTest , NearlyMatchesReference)
Definition at line 523 of file SplineTest.cpp.
TEST_P() [87/112]
rawspeed_test::TEST_P (SinPiRefTest , NearlyMatchesReference)
Definition at line 545 of file SplineTest.cpp.
TEST_P() [88/112]
rawspeed_test::TEST_P (SmallestTest , GetSmallestTest)
Definition at line 810 of file PointTest.cpp.
TEST_P() [89/112]
rawspeed_test::TEST_P (SplitStringTest , SplitStringTest)
Definition at line 348 of file CommonTest.cpp.
TEST_P() [90/112]
rawspeed_test::TEST_P (TrimSpacesTest , TrimSpacesTest)
Definition at line 323 of file CommonTest.cpp.
TEST_P() [91/112]
rawspeed_test::TEST_P (TwoRangesTest , NORangesSetDataSelfTest)
Definition at line 33 of file NORangesSetTest.cpp.
TEST_P() [92/112]
rawspeed_test::TEST_P (TwoRangesTest , NORangesSetDataTest)
Definition at line 56 of file NORangesSetTest.cpp.
TEST_P() [93/112]
rawspeed_test::TEST_P (TwoRangesTest , OverlapDataTest)
Definition at line 119 of file RangeTest.cpp.
TEST_P() [94/112]
rawspeed_test::TEST_P (uint32Test , get)
Definition at line 223 of file EndiannessTest.cpp.
TEST_P() [95/112]
rawspeed_test::TEST_P (uint32Test , getNOP)
Definition at line 230 of file EndiannessTest.cpp.
TEST_P() [96/112]
rawspeed_test::TEST_P (uint32Test , getU32)
Definition at line 238 of file EndiannessTest.cpp.
TEST_P() [97/112]
rawspeed_test::TEST_P (uint32Test , getU32NOP)
Definition at line 245 of file EndiannessTest.cpp.
TEST_P() [98/112]
rawspeed_test::TEST_P (uint32Test , NOP)
Definition at line 217 of file EndiannessTest.cpp.
TEST_P() [99/112]
rawspeed_test::TEST_P (uint32Test , swap)
Definition at line 214 of file EndiannessTest.cpp.
TEST_P() [100/112]
rawspeed_test::TEST_P (uint32Test , typedSwap)
Definition at line 220 of file EndiannessTest.cpp.
TEST_P() [101/112]
rawspeed_test::TEST_P (uint64Test , get)
Definition at line 297 of file EndiannessTest.cpp.
TEST_P() [102/112]
rawspeed_test::TEST_P (uint64Test , getNOP)
Definition at line 304 of file EndiannessTest.cpp.
TEST_P() [103/112]
rawspeed_test::TEST_P (uint64Test , NOP)
Definition at line 291 of file EndiannessTest.cpp.
TEST_P() [104/112]
rawspeed_test::TEST_P (uint64Test , swap)
Definition at line 288 of file EndiannessTest.cpp.
TEST_P() [105/112]
rawspeed_test::TEST_P (uint64Test , typedSwap)
Definition at line 294 of file EndiannessTest.cpp.
TEST_P() [106/112]
rawspeed_test::TEST_P (ushort16Test , get)
Definition at line 148 of file EndiannessTest.cpp.
TEST_P() [107/112]
rawspeed_test::TEST_P (ushort16Test , getNOP)
Definition at line 155 of file EndiannessTest.cpp.
TEST_P() [108/112]
rawspeed_test::TEST_P (ushort16Test , getU16)
Definition at line 163 of file EndiannessTest.cpp.
TEST_P() [109/112]
rawspeed_test::TEST_P (ushort16Test , getU16NOP)
Definition at line 170 of file EndiannessTest.cpp.
TEST_P() [110/112]
rawspeed_test::TEST_P (ushort16Test , NOP)
Definition at line 142 of file EndiannessTest.cpp.
TEST_P() [111/112]
rawspeed_test::TEST_P (ushort16Test , swap)
Definition at line 139 of file EndiannessTest.cpp.
TEST_P() [112/112]
rawspeed_test::TEST_P (ushort16Test , typedSwap)
Definition at line 145 of file EndiannessTest.cpp.
TYPED_TEST() [1/19]
rawspeed_test::TYPED_TEST (AlignedMallocDeathTest , AlignedMallocAssertions)
Definition at line 110 of file MemoryTest.cpp.
TYPED_TEST() [2/19]
rawspeed_test::TYPED_TEST (AlignedMallocDeathTest , TemplateArrayAssertions)
Definition at line 199 of file MemoryTest.cpp.
TYPED_TEST() [3/19]
rawspeed_test::TYPED_TEST (AlignedMallocTest , BasicTest)
Definition at line 83 of file MemoryTest.cpp.
TYPED_TEST() [4/19]
rawspeed_test::TYPED_TEST (AlignedMallocTest , TemplateArrayHandlesOverflowTest)
Definition at line 180 of file MemoryTest.cpp.
TYPED_TEST() [5/19]
rawspeed_test::TYPED_TEST (AlignedMallocTest , TemplateArrayRoundUp)
Definition at line 212 of file MemoryTest.cpp.
TYPED_TEST() [6/19]
rawspeed_test::TYPED_TEST (AlignedMallocTest , TemplateArraySizeRoundUpTest)
Definition at line 260 of file MemoryTest.cpp.
TYPED_TEST() [7/19]
rawspeed_test::TYPED_TEST (AlignedMallocTest , TemplateArraySizeTest)
Definition at line 221 of file MemoryTest.cpp.
TYPED_TEST() [8/19]
rawspeed_test::TYPED_TEST (AlignedMallocTest , TemplateArrayTest)
Definition at line 171 of file MemoryTest.cpp.
TYPED_TEST() [9/19]
rawspeed_test::TYPED_TEST (AlignedMallocTest , TemplateTest)
Definition at line 156 of file MemoryTest.cpp.
TYPED_TEST() [10/19]
rawspeed_test::TYPED_TEST (AlignedMallocTest , TemplateUniquePtrArraySizeTest)
Definition at line 230 of file MemoryTest.cpp.
TYPED_TEST() [11/19]
rawspeed_test::TYPED_TEST (AlignedMallocTest , TemplateUniquePtrArrayTest)
Definition at line 191 of file MemoryTest.cpp.
TYPED_TEST() [12/19]
rawspeed_test::TYPED_TEST (AlignedMallocTest , TemplatUniquePtrTest)
Definition at line 165 of file MemoryTest.cpp.
TYPED_TEST() [13/19]
rawspeed_test::TYPED_TEST (AlignedMallocTest , UniquePtrTest)
Definition at line 103 of file MemoryTest.cpp.
TYPED_TEST() [14/19]
rawspeed_test::TYPED_TEST (ExceptionsTest , AssignmentConstructor)
Definition at line 109 of file ExceptionsTest.cpp.
TYPED_TEST() [15/19]
rawspeed_test::TYPED_TEST (ExceptionsTest , Constructor)
Definition at line 104 of file ExceptionsTest.cpp.
TYPED_TEST() [16/19]
rawspeed_test::TYPED_TEST (ExceptionsTest , Throw)
Definition at line 131 of file ExceptionsTest.cpp.
TYPED_TEST() [17/19]
rawspeed_test::TYPED_TEST (ExceptionsTest , ThrowHelperTest)
Definition at line 192 of file ExceptionsTest.cpp.
TYPED_TEST() [18/19]
rawspeed_test::TYPED_TEST (ExceptionsTest , ThrowHelperTestMessage)
Definition at line 199 of file ExceptionsTest.cpp.
TYPED_TEST() [19/19]
rawspeed_test::TYPED_TEST (ExceptionsTest , ThrowMessage)
Definition at line 161 of file ExceptionsTest.cpp.
TYPED_TEST_CASE() [1/3]
rawspeed_test::TYPED_TEST_CASE (AlignedMallocDeathTest , Classes)
TYPED_TEST_CASE() [2/3]
rawspeed_test::TYPED_TEST_CASE (AlignedMallocTest , Classes)
TYPED_TEST_CASE() [3/3]
rawspeed_test::TYPED_TEST_CASE (ExceptionsTest , Classes)
TYPED_TEST_CASE_P()
rawspeed_test::TYPED_TEST_CASE_P (BitPumpTest)
Referenced by rawspeed_test::Pattern< Pump, PatternTag >::Data(), and TEST().
TYPED_TEST_P() [1/6]
rawspeed_test::TYPED_TEST_P (BitPumpTest , GetNoFillTest)
Definition at line 143 of file BitPumpTest.h.
TYPED_TEST_P() [2/6]
rawspeed_test::TYPED_TEST_P (BitPumpTest , GetTest)
Definition at line 139 of file BitPumpTest.h.
TYPED_TEST_P() [3/6]
rawspeed_test::TYPED_TEST_P (BitPumpTest , IncreasingPeekLengthNoFillTest)
Definition at line 159 of file BitPumpTest.h.
TYPED_TEST_P() [4/6]
rawspeed_test::TYPED_TEST_P (BitPumpTest , IncreasingPeekLengthTest)
Definition at line 155 of file BitPumpTest.h.
TYPED_TEST_P() [5/6]
rawspeed_test::TYPED_TEST_P (BitPumpTest , PeekNoFillTest)
Definition at line 151 of file BitPumpTest.h.
TYPED_TEST_P() [6/6]
rawspeed_test::TYPED_TEST_P (BitPumpTest , PeekTest)
Definition at line 147 of file BitPumpTest.h.
UnrollLoopTestIsMonotonicallyPositiveTest()
template<int iterations> static void rawspeed_test::UnrollLoopTestIsMonotonicallyPositiveTest () static
Definition at line 369 of file CommonTest.cpp.
Variable Documentation
absMinVal
constexpr iPoint2D::area_type rawspeed_test::absMinVal = -minVal static constexpr
Definition at line 52 of file PointTest.cpp.
alloc_alignment
constexpr const size_t rawspeed_test::alloc_alignment = 16 static constexpr
Definition at line 36 of file MemoryTest.cpp.
AllOverlapped
const std::set<twoRangesType> rawspeed_test::AllOverlapped static
Initial value:
{
    std::make_tuple(0, 0, 0, 0), std::make_tuple(0, 0, 0, 1),
    std::make_tuple(0, 0, 0, 2), std::make_tuple(0, 1, 0, 0),
    std::make_tuple(0, 1, 0, 1), std::make_tuple(0, 1, 0, 2),
    std::make_tuple(0, 2, 0, 0), std::make_tuple(0, 2, 0, 1),
    std::make_tuple(0, 2, 0, 2), std::make_tuple(0, 2, 1, 0),
    std::make_tuple(0, 2, 1, 1), std::make_tuple(0, 2, 1, 2),
    std::make_tuple(1, 0, 0, 2), std::make_tuple(1, 0, 1, 0),
    std::make_tuple(1, 0, 1, 1), std::make_tuple(1, 0, 1, 2),
    std::make_tuple(1, 1, 0, 2), std::make_tuple(1, 1, 1, 0),
    std::make_tuple(1, 1, 1, 1), std::make_tuple(1, 1, 1, 2),
    std::make_tuple(1, 2, 0, 2), std::make_tuple(1, 2, 1, 0),
    std::make_tuple(1, 2, 1, 1), std::make_tuple(1, 2, 1, 2),
    std::make_tuple(1, 2, 2, 0), std::make_tuple(1, 2, 2, 1),
    std::make_tuple(1, 2, 2, 2), std::make_tuple(2, 0, 1, 2),
    std::make_tuple(2, 0, 2, 0), std::make_tuple(2, 0, 2, 1),
    std::make_tuple(2, 0, 2, 2), std::make_tuple(2, 1, 1, 2),
    std::make_tuple(2, 1, 2, 0), std::make_tuple(2, 1, 2, 1),
    std::make_tuple(2, 1, 2, 2), std::make_tuple(2, 2, 1, 2),
    std::make_tuple(2, 2, 2, 0), std::make_tuple(2, 2, 2, 1),
    std::make_tuple(2, 2, 2, 2),
}
Definition at line 120 of file RangeTest.h.
allPossibleCodeSymbols
const auto rawspeed_test::allPossibleCodeSymbols = GenerateAllPossibleCodeSymbols() static
Definition at line 195 of file AbstractHuffmanTableTest.cpp.
Bayer_CYGM
const auto rawspeed_test::Bayer_CYGM static
Initial value:
=
    ::testing::Values(CFA_CYAN, CFA_MAGENTA, CFA_YELLOW, CFA_FUJI_GREEN)
Definition at line 156 of file ColorFilterArrayTest.cpp.
Bayer_RGB
const auto rawspeed_test::Bayer_RGB = ::testing::Values(CFA_RED, CFA_GREEN, CFA_BLUE) static
Definition at line 155 of file ColorFilterArrayTest.cpp.
calculateStepsValues
const calculateStepsType rawspeed_test::calculateStepsValues[] static
Initial value:
= {
    make_tuple(0, std::vector<int>{0, 65535}),
    make_tuple(1, std::vector<int>{0, 32768, 65535}),
    make_tuple(2, std::vector<int>{0, 21845, 43690, 65535}),
    make_tuple(3, std::vector<int>{0, 16384, 32768, 49151, 65535}),
    make_tuple(4, std::vector<int>{0, 13107, 26214, 39321, 52428, 65535}),
    make_tuple(5, std::vector<int>{0, 10923, 21845, 32768, 43690, 54613, 65535}),
    make_tuple(6, std::vector<int>{0, 9362, 18724, 28086, 37449, 46811, 56173, 65535}),
    make_tuple(7, std::vector<int>{0, 8192, 16384, 24576, 32768, 40959, 49151, 57343, 65535}),
    make_tuple(8, std::vector<int>{0, 7282, 14563, 21845, 29127, 36408, 43690, 50972, 58253, 65535}),
}
Definition at line 309 of file SplineTest.cpp.
CameraSensorIsoInfos
const struct IsoExpectationsT rawspeed_test::CameraSensorIsoInfos[] static
Initial value:
= {
    IsoExpectationsT{0, 0, 0, true, true},
    IsoExpectationsT{100, 0, 200, false, false},
    IsoExpectationsT{100, 99, 200, false, false},
    IsoExpectationsT{100, 100, 200, true, false},
    IsoExpectationsT{100, 160, 200, true, false},
    IsoExpectationsT{100, 200, 200, true, false},
    IsoExpectationsT{100, 201, 200, false, false},
    IsoExpectationsT{100, std::numeric_limits<int>::max(), 200, false, false},
    IsoExpectationsT{100, 0, 0, false, false},
    IsoExpectationsT{100, 99, 0, false, false},
    IsoExpectationsT{100, 100, 0, true, false},
    IsoExpectationsT{100, std::numeric_limits<int>::max(), 0, true, false},
}
Definition at line 242 of file CameraSensorInfoTest.cpp.
ClampBitsValues
const ClampBitsType rawspeed_test::ClampBitsValues[] static
Initial value:
= {
    make_tuple(0, 0, 0),    make_tuple(0, 16, 0),
    make_tuple(32, 0, 0),   make_tuple(32, 16, 32),
    make_tuple(32, 2, 3),   make_tuple(-32, 0, 0),
    make_tuple(-32, 16, 0), GENERATE()}
Definition at line 268 of file CommonTest.cpp.
CodeSymbolData
const CodeSymbolType rawspeed_test::CodeSymbolData[] static
Initial value:
{
    make_tuple(0b00, 1, false),
    make_tuple(0b00, 2, false),
    make_tuple(0b01, 1, false),
    make_tuple(0b01, 2, false),
    make_tuple(0b10, 1, true),
    make_tuple(0b10, 2, false),
    make_tuple(0b11, 1, true),
    make_tuple(0b11, 2, false),
}
Definition at line 100 of file AbstractHuffmanTableTest.cpp.
CodeSymbolPrintData
const CodeSymbolPrintDataType rawspeed_test::CodeSymbolPrintData[] static
Initial value:
{
    make_tuple(0b00, 1, "0b0"),
    make_tuple(0b00, 2, "0b00"),
    make_tuple(0b01, 1, "0b1"),
    make_tuple(0b01, 2, "0b01"),
    make_tuple(0b10, 2, "0b10"),
    make_tuple(0b11, 2, "0b11"),
}
Definition at line 146 of file AbstractHuffmanTableTest.cpp.
constantValues
const auto rawspeed_test::constantValues static
Initial value:
=
    ::testing::Combine(::testing::ValuesIn(calculateSteps(NumExtraSteps)),
                       ::testing::Range(0, 1 + NumExtraSteps))
Definition at line 404 of file SplineTest.cpp.
generateCodeSymbolsData
const generateCodeSymbolsDataType rawspeed_test::generateCodeSymbolsData[] static
Definition at line 549 of file AbstractHuffmanTableTest.cpp.
genHT
auto rawspeed_test::genHT
Initial value:
= [](std::initializer_list<uint8_t>&& nCodesPerLength)
    -> AbstractHuffmanTable {
  AbstractHuffmanTable ht;
  std::vector<uint8_t> v(nCodesPerLength.begin(), nCodesPerLength.end());
  v.resize(16);
  Buffer b(v.data(), v.size());
  ht.setNCodesPerLength(b);
  return ht;
}
Definition at line 247 of file AbstractHuffmanTableTest.cpp.
genHTCount
auto rawspeed_test::genHTCount
Initial value:
=
    [](std::initializer_list<uint8_t>&& nCodesPerLength) -> uint32_t {
  AbstractHuffmanTable ht;
  std::vector<uint8_t> v(nCodesPerLength.begin(), nCodesPerLength.end());
  v.resize(16);
  Buffer b(v.data(), v.size());
  return ht.setNCodesPerLength(b);
}
Definition at line 258 of file AbstractHuffmanTableTest.cpp.
genHTFull
auto rawspeed_test::genHTFull
Initial value:
=
    [](std::initializer_list<uint8_t>&& nCodesPerLength,
       std::initializer_list<uint8_t>&& codeValues) -> AbstractHuffmanTable {
  auto ht = genHT(std::move(nCodesPerLength));
  std::vector<uint8_t> v(codeValues.begin(), codeValues.end());
  Buffer b(v.data(), v.size());
  ht.setCodeValues(b);
  return ht;
}
Definition at line 267 of file AbstractHuffmanTableTest.cpp.
GenOnesBE
auto rawspeed_test::GenOnesBE
Initial value:
= [](int zerosToOutput,
                    int zerosOutputted) -> std::array<uint32_t, 29> {
  std::array<uint32_t, 29> v;
  uint32_t bits = 0;
  for (auto& value : v) {
    if (zerosToOutput == zerosOutputted) {
      bits |= 0b1;
      zerosToOutput++;
      zerosOutputted = 0;
    }
    value = bits;
    zerosOutputted++;
    bits <<= 1;
  }
  return v;
}
Definition at line 221 of file BitPumpTest.h.
GenOnesLE
auto rawspeed_test::GenOnesLE
Initial value:
= [](int zerosToOutput,
                    int zerosOutputted) -> std::array<uint32_t, 29> {
  std::array<uint32_t, 29> v;
  uint32_t bits = 0;
  int currBit = -1;
  for (auto& value : v) {
    if (zerosToOutput == zerosOutputted) {
      assert(currBit < 32);
      bits |= 0b1 << currBit;
      zerosToOutput++;
      zerosOutputted = 0;
    }
    value = bits;
    zerosOutputted++;
    currBit++;
  }
  return v;
}
Definition at line 203 of file BitPumpTest.h.
identityValues
const identityType rawspeed_test::identityValues[] static
Initial value:
= {
    make_tuple(std::array<rawspeed::iPoint2D, 2>{{{0, 0}, {65535, 65535}}},
               std::vector<std::array<double, 4>>{{{0.0, 1.0, 0.0, 0.0}}}),
    make_tuple(
        std::array<rawspeed::iPoint2D, 2>{{{0, 65535}, {65535, 0}}},
        std::vector<std::array<double, 4>>{{{65535.0, -1.0, 0.0, 0.0}}})}
Definition at line 212 of file SplineTest.cpp.
IsInValues
const IsInType rawspeed_test::IsInValues[] static
Initial value:
= {
    make_tuple("foo", true),    make_tuple("foo2", true),
    make_tuple("bar", true),    make_tuple("baz", true),
    make_tuple("foo1", false),  make_tuple("bar2", false),
    make_tuple("baz-1", false), make_tuple("quz", false),
}
Definition at line 217 of file CommonTest.cpp.
maxAreaVal
constexpr iPoint2D::area_type rawspeed_test::maxAreaVal = maxVal * maxVal static constexpr
Definition at line 53 of file PointTest.cpp.
maxVal
constexpr iPoint2D::area_type rawspeed_test::maxVal static constexpr
Initial value:
=
    numeric_limits<iPoint2D::value_type>::max()
Definition at line 48 of file PointTest.cpp.
minAreaVal
constexpr iPoint2D::area_type rawspeed_test::minAreaVal = absMinVal * absMinVal static constexpr
Definition at line 54 of file PointTest.cpp.
minVal
constexpr iPoint2D::area_type rawspeed_test::minVal static constexpr
Initial value:
=
    numeric_limits<iPoint2D::value_type>::min()
Definition at line 50 of file PointTest.cpp.
mixAreaVal
constexpr iPoint2D::area_type rawspeed_test::mixAreaVal = maxVal * absMinVal static constexpr
Definition at line 55 of file PointTest.cpp.
msg
const char* rawspeed_test::msg = "my very Smart error Message #1 !" static
Definition at line 49 of file ExceptionsTest.cpp.
NumExtraSteps
constexpr auto rawspeed_test::NumExtraSteps = 3 constexpr
Definition at line 403 of file SplineTest.cpp.
one
auto rawspeed_test::one = [](int len) { return make_tuple((1 << len), len, 1); }
Definition at line 456 of file AbstractHuffmanTableTest.cpp.
operatorsValues
const operatorsType rawspeed_test::operatorsValues[] static
Definition at line 507 of file PointTest.cpp.
passthrough
auto rawspeed_test::passthrough
Initial value:
= [](int len) {
  return make_tuple(((1 << len) - 1), len, ((1 << len) - 1));
}
Definition at line 453 of file AbstractHuffmanTableTest.cpp.
PositiveAreaData
const iPoint2D rawspeed_test::PositiveAreaData[] static
Initial value:
= {
    {1, 1},
    {1, 2},
    {2, 1},
    {2, 2},
}
Definition at line 340 of file PointTest.cpp.
powerOfTwoValues
const powerOfTwoType rawspeed_test::powerOfTwoValues[] static
Initial value:
= {
    make_tuple(0, true),  make_tuple(1, true),   make_tuple(2, true),
    make_tuple(3, false), make_tuple(4, true),   make_tuple(5, false),
    make_tuple(6, false), make_tuple(7, false),  make_tuple(8, true),
    make_tuple(9, false), make_tuple(10, false), make_tuple(11, false),
}
Definition at line 67 of file CommonTest.cpp.
RoundDownValues
const RoundDownType rawspeed_test::RoundDownValues[] static
Initial value:
= {
    make_tuple(0, 0, 0),    make_tuple(0, 10, 0),  make_tuple(10, 0, 10),
    make_tuple(10, 10, 10), make_tuple(10, 1, 10), make_tuple(10, 2, 10),
    make_tuple(10, 3, 9),   make_tuple(10, 4, 8),  make_tuple(10, 5, 10),
    make_tuple(10, 6, 6),   make_tuple(10, 7, 7),  make_tuple(10, 8, 8),
    make_tuple(10, 9, 9),   make_tuple(10, 11, 0), make_tuple(10, 12, 0),
}
Definition at line 94 of file CommonTest.cpp.
RoundUpDivisionValues
const RoundUpDivisionType rawspeed_test::RoundUpDivisionValues[] static
Initial value:
= {
    make_tuple(0, 10, 0),
    make_tuple(10, 10, 1),
    make_tuple(10, 1, 10),
    make_tuple(10, 2, 5),
    make_tuple(10, 3, 4),
    make_tuple(10, 4, 3),
    make_tuple(10, 5, 2),
    make_tuple(10, 6, 2),
    make_tuple(10, 7, 2),
    make_tuple(10, 8, 2),
    make_tuple(10, 9, 2),
    make_tuple(0, 1, 0),
    make_tuple(1, 1, 1),
    make_tuple(numeric_limits<size_t>::max() - 1, 1,
               numeric_limits<size_t>::max() - 1),
    make_tuple(numeric_limits<size_t>::max(), 1, numeric_limits<size_t>::max()),
    make_tuple(0, numeric_limits<size_t>::max() - 1, 0),
    make_tuple(1, numeric_limits<size_t>::max() - 1, 1),
    make_tuple(numeric_limits<size_t>::max() - 1,
               numeric_limits<size_t>::max() - 1, 1),
    make_tuple(numeric_limits<size_t>::max(), numeric_limits<size_t>::max() - 1,
               2),
    make_tuple(0, numeric_limits<size_t>::max(), 0),
    make_tuple(1, numeric_limits<size_t>::max(), 1),
    make_tuple(numeric_limits<size_t>::max() - 1, numeric_limits<size_t>::max(),
               1),
    make_tuple(numeric_limits<size_t>::max(), numeric_limits<size_t>::max(), 1),
}
Definition at line 149 of file CommonTest.cpp.
RoundUpValues
const RoundUpType rawspeed_test::RoundUpValues[] static
Initial value:
= {
    make_tuple(0, 0, 0),    make_tuple(0, 10, 0),   make_tuple(10, 0, 10),
    make_tuple(10, 10, 10), make_tuple(10, 1, 10),  make_tuple(10, 2, 10),
    make_tuple(10, 3, 12),  make_tuple(10, 4, 12),  make_tuple(10, 5, 10),
    make_tuple(10, 6, 12),  make_tuple(10, 7, 14),  make_tuple(10, 8, 16),
    make_tuple(10, 9, 18),  make_tuple(10, 11, 11), make_tuple(10, 12, 12),
}
Definition at line 122 of file CommonTest.cpp.
signExtendData
const SignExtendDataType rawspeed_test::signExtendData[] static
Definition at line 457 of file AbstractHuffmanTableTest.cpp.
sin2PiRefValues
const referenceType rawspeed_test::sin2PiRefValues[] static
Initial value:
= {
    make_tuple(0,    1.0E-00),
    make_tuple(1,    1.0E+01),
    make_tuple(2,    1.0E-00),
    make_tuple(3,    1.0E-01),
    make_tuple(4,    1.0E-02),
    make_tuple(5,    1.0E-02),
    make_tuple(6,    1.0E-02),
    make_tuple(7,    1.0E-02),
    make_tuple(8,    1.0E-03),
    make_tuple(9,    1.0E-03),
    make_tuple(10,   1.0E-03),
    make_tuple(11,   1.0E-03),
    make_tuple(12,   1.0E-03),
    make_tuple(13,   1.0E-03),
    make_tuple(14,   1.0E-04),
}
Definition at line 502 of file SplineTest.cpp.
sinPiRefValues
const referenceType rawspeed_test::sinPiRefValues[] static
Initial value:
= {
    make_tuple(0,  1.0E-00),
    make_tuple(1,  1.0E-01),
    make_tuple(2,  1.0E-02),
    make_tuple(3,  1.0E-02),
    make_tuple(4,  1.0E-03),
    make_tuple(5,  1.0E-03),
    make_tuple(6,  1.0E-03),
    make_tuple(7,  1.0E-04),
    make_tuple(8,  1.0E-04),
    make_tuple(9,  1.0E-04),
    make_tuple(10, 1.0E-04),
    make_tuple(11, 1.0E-04),
    make_tuple(12, 1.0E-05),
}
Definition at line 526 of file SplineTest.cpp.
smallestValues
const Six rawspeed_test::smallestValues[] static
Definition at line 722 of file PointTest.cpp.
splitStringValues
const splitStringType rawspeed_test::splitStringValues[] static
Initial value:
= {
    make_tuple(" ini mi,ni  moe ", ' ',
               vector<string>({"ini", "mi,ni", "moe"})),
    make_tuple(" 412, 542,732 , ", ',',
               vector<string>({" 412", " 542", "732 ", " "})),
}
Definition at line 339 of file CommonTest.cpp.
square
const iPoint2D rawspeed_test::square(2, 2) static
Referenced by TEST().
TrimSpacesValues
const TrimSpacesType rawspeed_test::TrimSpacesValues[] static
Initial value:
= {
#define STR
    make_tuple("foo", "foo"),
    make_tuple(STR, STR),
    make_tuple("  " STR, STR),
    make_tuple("\t" STR, STR),
    make_tuple(" \t " STR, STR),
    make_tuple(STR "  ", STR),
    make_tuple(STR "\t", STR),
    make_tuple(STR "  \t  ", STR),
    make_tuple("  " STR "  ", STR),
    make_tuple("\t" STR "\t", STR),
    make_tuple("  \t  " STR "  \t  ", STR),
    make_tuple("    ", ""),
    make_tuple("  \t", ""),
    make_tuple("  \t  ", ""),
    make_tuple("\t  ", ""),
}
Definition at line 302 of file CommonTest.cpp.
uint32Values
const uint32Type rawspeed_test::uint32Values[] static
Definition at line 104 of file EndiannessTest.h.
uint64Values
const uint64Type rawspeed_test::uint64Values[] static
Definition at line 237 of file EndiannessTest.h.
ushort16Values
const ushort16Type rawspeed_test::ushort16Values[] static
Definition at line 35 of file EndiannessTest.h.
valueArea
const areaType rawspeed_test::valueArea[] static
Definition at line 388 of file PointTest.cpp.
valueSum
const Six rawspeed_test::valueSum[] static
Definition at line 190 of file PointTest.cpp.
zeroDiff
auto rawspeed_test::zeroDiff = [](int len) { return make_tuple(0, len, -((1 << len) - 1)); }
Definition at line 452 of file AbstractHuffmanTableTest.cpp.