RawSpeed: rawspeed::FujiDecompressor::FujiStrip Struct Reference
rawspeed::FujiDecompressor::FujiStrip Struct Reference
#include "decompressors/FujiDecompressor.h"
Public Member Functions
FujiStrip (const FujiHeader &h_, int block, ByteStream bs_)
int height () const
int width () const
int offsetY (int line=0) const
int offsetX () const
Static Public Member Functions
static int lineHeight ()
Public Attributes
const FujiHeader & h
const int n
const ByteStream bs
Detailed Description
Definition at line 63 of file FujiDecompressor.h.
Constructor & Destructor Documentation
FujiStrip()
rawspeed::FujiDecompressor::FujiStrip::FujiStrip (const FujiHeader & h_, int block, ByteStream bs_) inline
Definition at line 73 of file FujiDecompressor.h.
References rawspeed::FujiDecompressor::FujiHeader::blocks_in_row, FujiStrip(), h, and n.
Referenced by FujiStrip().
Member Function Documentation
height()
int rawspeed::FujiDecompressor::FujiStrip::height () const inline
Definition at line 82 of file FujiDecompressor.h.
References h, and rawspeed::FujiDecompressor::FujiHeader::total_lines.
Referenced by rawspeed::FujiDecompressor::fuji_decode_strip(), and offsetY().
lineHeight()
static int rawspeed::FujiDecompressor::FujiStrip::lineHeight () inline static
Definition at line 79 of file FujiDecompressor.h.
Referenced by rawspeed::FujiDecompressor::copy_line(), and offsetY().
offsetX()
int rawspeed::FujiDecompressor::FujiStrip::offsetX () const inline
Definition at line 104 of file FujiDecompressor.h.
References rawspeed::FujiDecompressor::FujiHeader::block_size, h, and n.
Referenced by width().
offsetY()
int rawspeed::FujiDecompressor::FujiStrip::offsetY (int line = 0) const inline
Definition at line 97 of file FujiDecompressor.h.
References height(), and lineHeight().
width()
int rawspeed::FujiDecompressor::FujiStrip::width () const inline
Definition at line 85 of file FujiDecompressor.h.
References rawspeed::FujiDecompressor::FujiHeader::block_size, rawspeed::FujiDecompressor::FujiHeader::blocks_in_row, h, n, offsetX(), and rawspeed::FujiDecompressor::FujiHeader::raw_width.
Referenced by rawspeed::FujiDecompressor::copy_line().
Member Data Documentation
bs
const ByteStream rawspeed::FujiDecompressor::FujiStrip::bs
Definition at line 71 of file FujiDecompressor.h.
h
const FujiHeader& rawspeed::FujiDecompressor::FujiStrip::h
Definition at line 65 of file FujiDecompressor.h.
Referenced by FujiStrip(), height(), offsetX(), and width().
n
const int rawspeed::FujiDecompressor::FujiStrip::n
Definition at line 68 of file FujiDecompressor.h.
Referenced by FujiStrip(), offsetX(), and width().
The documentation for this struct was generated from the following file:
librawspeed/decompressors/FujiDecompressor.h