RawSpeed: rawspeed::PentaxDecompressor Class Reference
rawspeed::PentaxDecompressor Class Reference final
#include "decompressors/PentaxDecompressor.h"
Public Member Functions
PentaxDecompressor (const RawImage &img, ByteStream *metaData)
void decompress (const ByteStream &data) const
Static Private Member Functions
static HuffmanTable SetupHuffmanTable_Legacy ()
static HuffmanTable SetupHuffmanTable_Modern (ByteStream stream)
static HuffmanTable SetupHuffmanTable (ByteStream *metaData)
Private Attributes
RawImage mRaw
const HuffmanTable ht
Static Private Attributes
static const std::array< std::array< std::array< uint8_t, 16 >, 2 >, 1 > pentax_tree
Detailed Description
Definition at line 34 of file PentaxDecompressor.h.
Constructor & Destructor Documentation
PentaxDecompressor()
rawspeed::PentaxDecompressor::PentaxDecompressor (const RawImage & img, ByteStream * metaData)
Definition at line 45 of file PentaxDecompressor.cpp.
References rawspeed::RawImageData::dim, mRaw, rawspeed::RawImage::operator->(), PentaxDecompressor(), rawspeed::RawImage::RawImage(), rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
Referenced by LLVMFuzzerTestOneInput(), and PentaxDecompressor().
Member Function Documentation
decompress()
void rawspeed::PentaxDecompressor::decompress (const ByteStream & data) const
Definition at line 141 of file PentaxDecompressor.cpp.
Referenced by LLVMFuzzerTestOneInput().
SetupHuffmanTable()
HuffmanTable rawspeed::PentaxDecompressor::SetupHuffmanTable (ByteStream * metaData) static private
Definition at line 128 of file PentaxDecompressor.cpp.
References rawspeed::HuffmanTableLUT::setup(), SetupHuffmanTable_Legacy(), and SetupHuffmanTable_Modern().
SetupHuffmanTable_Legacy()
HuffmanTable rawspeed::PentaxDecompressor::SetupHuffmanTable_Legacy () static private
Definition at line 59 of file PentaxDecompressor.cpp.
Referenced by SetupHuffmanTable().
SetupHuffmanTable_Modern()
HuffmanTable rawspeed::PentaxDecompressor::SetupHuffmanTable_Modern (ByteStream stream) static private
Definition at line 70 of file PentaxDecompressor.cpp.
References rawspeed::ByteStream::getU16(), and rawspeed::ByteStream::skipBytes().
Referenced by SetupHuffmanTable().
Member Data Documentation
ht
const HuffmanTable rawspeed::PentaxDecompressor::ht private
Definition at line 36 of file PentaxDecompressor.h.
mRaw
RawImage rawspeed::PentaxDecompressor::mRaw private
Definition at line 35 of file PentaxDecompressor.h.
Referenced by PentaxDecompressor().
pentax_tree
const std::array< std::array< std::array< uint8_t, 16 >, 2 >, 1 > rawspeed::PentaxDecompressor::pentax_tree static private
Initial value:
= {{
        {{{0, 2, 3, 1, 1, 1, 1, 1, 1, 2, 0, 0, 0, 0, 0, 0},
          {3, 4, 2, 5, 1, 6, 0, 7, 8, 9, 10, 11, 12}}},
    }}
Definition at line 49 of file PentaxDecompressor.h.
The documentation for this class was generated from the following files:
librawspeed/decompressors/PentaxDecompressor.h
librawspeed/decompressors/PentaxDecompressor.cpp