RawSpeed: rawspeed::TiffRootIFD Class Reference
rawspeed::TiffRootIFD Class Reference final
#include "tiff/TiffIFD.h"
Public Member Functions
TiffRootIFD (TiffIFD *parent_, NORangesSet< Buffer > *ifds, const DataBuffer &data, uint32_t offset)
TiffID getID () const
uint32_t getNextIFD () const
std::vector< const TiffIFD * > getIFDsWithTag (TiffTag tag) const
const TiffIFD * getIFDWithTag (TiffTag tag, uint32_t index=0) const
TiffEntry * getEntry (TiffTag tag) const
TiffEntry * __attribute__ ((pure)) getEntryRecursive(TiffTag tag) const
bool __attribute__ ((pure)) hasEntry(TiffTag tag) const
bool hasEntryRecursive (TiffTag tag) const
const std::vector< TiffIFDOwner > & getSubIFDs () const
Public Attributes
const DataBuffer rootBuffer
Private Member Functions
void recursivelyIncrementSubIFDCount ()
void checkSubIFDs (int headroom) const
void recursivelyCheckSubIFDs (int headroom) const
void add (TiffIFDOwner subIFD)
void add (TiffEntryOwner entry)
TiffRootIFDOwner parseMakerNote (NORangesSet< Buffer > *ifds, TiffEntry *t)
void parseIFDEntry (NORangesSet< Buffer > *ifds, ByteStream *bs)
Private Attributes
uint32_t nextIFD = 0
TiffIFD *const parent
std::vector< TiffIFDOwner > subIFDs
int subIFDCount = 0
int subIFDCountRecursive = 0
std::map< TiffTag, TiffEntryOwner > entries
Detailed Description
Definition at line 129 of file TiffIFD.h.
Constructor & Destructor Documentation
TiffRootIFD()
rawspeed::TiffRootIFD::TiffRootIFD (TiffIFD * parent_, NORangesSet< Buffer > * ifds, const DataBuffer & data, uint32_t offset) inline
Definition at line 133 of file TiffIFD.h.
Member Function Documentation
__attribute__() [1/2]
TiffEntry* rawspeed::TiffIFD::__attribute__ ((pure)) const inherited
Referenced by rawspeed::TiffIFD::parseMakerNote().
__attribute__() [2/2]
bool rawspeed::TiffIFD::__attribute__ ((pure)) const inline inherited
Definition at line 114 of file TiffIFD.h.
add() [1/2]
void rawspeed::TiffIFD::add (TiffEntryOwner entry) private inherited
Definition at line 286 of file TiffIFD.cpp.
add() [2/2]
void rawspeed::TiffIFD::add (TiffIFDOwner subIFD) private inherited
Definition at line 277 of file TiffIFD.cpp.
checkSubIFDs()
void rawspeed::TiffIFD::checkSubIFDs (int headroom) const private inherited
Definition at line 247 of file TiffIFD.cpp.
References rawspeed::TiffIFD::Limits::RecursiveSubIFDCount, rawspeed::TiffIFD::subIFDCount, rawspeed::TiffIFD::Limits::SubIFDCount, and rawspeed::TiffIFD::subIFDCountRecursive.
Referenced by rawspeed::TiffIFD::recursivelyCheckSubIFDs().
getEntry()
TiffEntry * rawspeed::TiffIFD::getEntry (TiffTag tag) const inherited
Definition at line 291 of file TiffIFD.cpp.
getID()
TiffID rawspeed::TiffRootIFD::getID () const
Definition at line 298 of file TiffIFD.cpp.
getIFDsWithTag()
std::vector< const TiffIFD * > rawspeed::TiffIFD::getIFDsWithTag (TiffTag tag) const inherited
Definition at line 204 of file TiffIFD.cpp.
getIFDWithTag()
const TiffIFD * rawspeed::TiffIFD::getIFDWithTag (TiffTag tag, uint32_t index = 0) const inherited
Definition at line 216 of file TiffIFD.cpp.
getNextIFD()
uint32_t rawspeed::TiffIFD::getNextIFD () const inline inherited
Definition at line 109 of file TiffIFD.h.
getSubIFDs()
const std::vector<TiffIFDOwner>& rawspeed::TiffIFD::getSubIFDs () const inline inherited
Definition at line 119 of file TiffIFD.h.
hasEntryRecursive()
bool rawspeed::TiffIFD::hasEntryRecursive (TiffTag tag) const inline inherited
Definition at line 117 of file TiffIFD.h.
parseIFDEntry()
void rawspeed::TiffIFD::parseIFDEntry (NORangesSet< Buffer > * ifds, ByteStream * bs) private inherited
Definition at line 43 of file TiffIFD.cpp.
References rawspeed::ByteStream::getPosition(), and rawspeed::ByteStream::setPosition().
parseMakerNote()
TiffRootIFDOwner rawspeed::TiffIFD::parseMakerNote (NORangesSet< Buffer > * ifds, TiffEntry * t) private inherited
Definition at line 130 of file TiffIFD.cpp.
References rawspeed::TiffIFD::__attribute__(), rawspeed::big, rawspeed::TiffEntry::getData(), rawspeed::ByteStream::getPosition(), rawspeed::ByteStream::getRemainSize(), rawspeed::ByteStream::getSubStream(), rawspeed::getTiffByteOrder(), rawspeed::ByteStream::hasPatternAt(), rawspeed::ByteStream::hasPrefix(), rawspeed::little, rawspeed::TiffIFD::parent, rawspeed::ByteStream::skipBytes(), and rawspeed::ByteStream::skipPrefix().
recursivelyCheckSubIFDs()
void rawspeed::TiffIFD::recursivelyCheckSubIFDs (int headroom) const private inherited
Definition at line 261 of file TiffIFD.cpp.
References rawspeed::TiffIFD::checkSubIFDs(), rawspeed::TiffIFD::Limits::Depth, and rawspeed::TiffIFD::parent.
Referenced by rawspeed::TiffIFD::TiffIFD().
recursivelyIncrementSubIFDCount()
void rawspeed::TiffIFD::recursivelyIncrementSubIFDCount () private inherited
Referenced by rawspeed::TiffIFD::TiffIFD().
Member Data Documentation
entries
std::map<TiffTag, TiffEntryOwner> rawspeed::TiffIFD::entries private inherited
Definition at line 59 of file TiffIFD.h.
nextIFD
uint32_t rawspeed::TiffIFD::nextIFD = 0 private inherited
Definition at line 50 of file TiffIFD.h.
Referenced by rawspeed::TiffIFD::TiffIFD().
parent
TiffIFD* const rawspeed::TiffIFD::parent private inherited
Definition at line 52 of file TiffIFD.h.
Referenced by rawspeed::TiffIFD::parseMakerNote(), rawspeed::TiffIFD::recursivelyCheckSubIFDs(), and rawspeed::TiffIFD::TiffIFD().
rootBuffer
const DataBuffer rawspeed::TiffRootIFD::rootBuffer
Definition at line 131 of file TiffIFD.h.
subIFDCount
int rawspeed::TiffIFD::subIFDCount = 0 private inherited
Definition at line 56 of file TiffIFD.h.
Referenced by rawspeed::TiffIFD::checkSubIFDs().
subIFDCountRecursive
int rawspeed::TiffIFD::subIFDCountRecursive = 0 private inherited
Definition at line 57 of file TiffIFD.h.
Referenced by rawspeed::TiffIFD::checkSubIFDs().
subIFDs
std::vector<TiffIFDOwner> rawspeed::TiffIFD::subIFDs private inherited
Definition at line 54 of file TiffIFD.h.
The documentation for this class was generated from the following files:
librawspeed/tiff/TiffIFD.h
librawspeed/tiff/TiffIFD.cpp