RawSpeed: rawspeed::DngOpcodes::TrimBounds Class Reference
rawspeed::DngOpcodes::TrimBounds Class Reference final
Public Member Functions
TrimBounds (const RawImage &ri, ByteStream *bs)
void apply (const RawImage &ri) override
virtual void setup (const RawImage &ri)
Protected Member Functions
const iRectangle2D & __attribute__ ((pure)) getRoi() const
Private Attributes
iRectangle2D roi
Detailed Description
Definition at line 208 of file DngOpcodes.cpp.
Constructor & Destructor Documentation
TrimBounds()
rawspeed::DngOpcodes::TrimBounds::TrimBounds (const RawImage & ri, ByteStream * bs) inline explicit
Definition at line 210 of file DngOpcodes.cpp.
References rawspeed::DngOpcodes::ROIOpcode::ROIOpcode().
Member Function Documentation
__attribute__()
const iRectangle2D& rawspeed::DngOpcodes::ROIOpcode::__attribute__ ((pure)) const inline protected inherited
Definition at line 129 of file DngOpcodes.cpp.
References rawspeed::DngOpcodes::ROIOpcode::roi.
Referenced by rawspeed::DngOpcodes::DummyROIOpcode::__attribute__(), apply(), rawspeed::DngOpcodes::PixelOpcode::applyOP(), rawspeed::DngOpcodes::DeltaRowOrCol< S >::DeltaRowOrCol(), and rawspeed::DngOpcodes::PixelOpcode::PixelOpcode().
apply()
void rawspeed::DngOpcodes::TrimBounds::apply (const RawImage & ri) inline override virtual
Implements rawspeed::DngOpcodes::DngOpcode.
Definition at line 213 of file DngOpcodes.cpp.
References rawspeed::DngOpcodes::ROIOpcode::__attribute__(), rawspeed::RawImage::operator->(), and rawspeed::RawImageData::subFrame().
setup()
virtual void rawspeed::DngOpcodes::DngOpcode::setup (const RawImage & ri) inline virtual inherited
Reimplemented in rawspeed::DngOpcodes::DeltaRowOrCol< S >, rawspeed::DngOpcodes::LookupOpcode, and rawspeed::DngOpcodes::FixBadPixelsConstant.
Definition at line 54 of file DngOpcodes.cpp.
Referenced by rawspeed::DngOpcodes::DeltaRowOrCol< S >::setup().
Member Data Documentation
roi
iRectangle2D rawspeed::DngOpcodes::ROIOpcode::roi private inherited
Definition at line 99 of file DngOpcodes.cpp.
Referenced by rawspeed::DngOpcodes::ROIOpcode::__attribute__(), and rawspeed::DngOpcodes::ROIOpcode::ROIOpcode().
The documentation for this class was generated from the following file:
librawspeed/common/DngOpcodes.cpp