RawSpeed: rawspeed::SamsungV1Decompressor Class Reference
rawspeed::SamsungV1Decompressor Class Reference final
#include "decompressors/SamsungV1Decompressor.h"
Classes
struct encTableItem
Public Member Functions
SamsungV1Decompressor (const RawImage &image, const ByteStream *bs_, int bit)
void decompress ()
Protected Attributes
RawImage mRaw
Static Private Member Functions
static int32_t samsungDiff (BitPumpMSB *pump, const std::vector< encTableItem > &tbl)
Private Attributes
const ByteStream * bs
Static Private Attributes
static constexpr int bits = 12
Detailed Description
Definition at line 34 of file SamsungV1Decompressor.h.
Constructor & Destructor Documentation
SamsungV1Decompressor()
rawspeed::SamsungV1Decompressor::SamsungV1Decompressor (const RawImage & image, const ByteStream * bs_, int bit)
Definition at line 43 of file SamsungV1Decompressor.cpp.
References bs, rawspeed::RawImageData::dim, rawspeed::RawImage::operator->(), rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
Member Function Documentation
decompress()
void rawspeed::SamsungV1Decompressor::decompress ()
Definition at line 83 of file SamsungV1Decompressor.cpp.
Referenced by LLVMFuzzerTestOneInput().
samsungDiff()
int32_t rawspeed::SamsungV1Decompressor::samsungDiff (BitPumpMSB * pump, const std::vector< encTableItem > & tbl) inline static private
Definition at line 66 of file SamsungV1Decompressor.cpp.
References rawspeed::AbstractHuffmanTable::__attribute__().
Member Data Documentation
bits
constexpr int rawspeed::SamsungV1Decompressor::bits = 12 static constexpr private
Definition at line 41 of file SamsungV1Decompressor.h.
bs
const ByteStream* rawspeed::SamsungV1Decompressor::bs private
Definition at line 40 of file SamsungV1Decompressor.h.
Referenced by SamsungV1Decompressor().
mRaw
RawImage rawspeed::AbstractSamsungDecompressor::mRaw protected inherited
Definition at line 30 of file AbstractSamsungDecompressor.h.
The documentation for this class was generated from the following files:
librawspeed/decompressors/SamsungV1Decompressor.h
librawspeed/decompressors/SamsungV1Decompressor.cpp