RawSpeed: rawspeed_test::DummyHuffmanTableTest Class Reference
rawspeed_test::DummyHuffmanTableTest Class Reference
Public Member Functions
void verifyCodeSymbolsAreValidDiffLenghts () const
bool operator== (const AbstractHuffmanTable &other) const
uint32_t setNCodesPerLength (const Buffer &data)
void setCodeValues (const Buffer &data)
template<typename BIT_STREAM , bool FULL_DECODE>
int processSymbol (BIT_STREAM &bs, CodeSymbol symbol, int codeValue) const
if ((diff &(1<<(len - 1)))==0) ret -
Static Public Member Functions
static int __attribute__ ((const)) extend(uint32_t diff
Public Attributes
static int uint32_t len
auto ret = static_cast<int32_t>(diff)
return ret
Protected Member Functions
size_t __attribute__ ((pure)) maxCodePlusDiffLength() const
unsigned int __attribute__ ((pure)) maxCodesCount() const
void setup (bool fullDecode_, bool fixDNGBug16_)
std::vector< CodeSymbol > generateCodeSymbols () const
Static Protected Member Functions
static void VerifyCodeSymbols (const std::vector< CodeSymbol > &symbols)
Protected Attributes
bool fullDecode = true
bool fixDNGBug16 = false
std::vector< unsigned int > nCodesPerLength
std::vector< uint8_t > codeValues
Detailed Description
Definition at line 594 of file AbstractHuffmanTableTest.cpp.
Member Function Documentation
__attribute__() [1/3]
static int rawspeed::AbstractHuffmanTable::__attribute__ ((const)) inline static inherited
Referenced by rawspeed::CrwDecompressor::decodeBlock(), rawspeed::HasselbladDecompressor::getBits(), rawspeed::SonyArw1Decompressor::getDiff(), rawspeed::AbstractHuffmanTable::processSymbol(), and rawspeed::SamsungV1Decompressor::samsungDiff().
__attribute__() [2/3]
size_t rawspeed::AbstractHuffmanTable::__attribute__ ((pure)) const inline protected inherited
Definition at line 79 of file AbstractHuffmanTable.h.
__attribute__() [3/3]
unsigned int rawspeed::AbstractHuffmanTable::__attribute__ ((pure)) const inline protected inherited
Definition at line 90 of file AbstractHuffmanTable.h.
Referenced by rawspeed::AbstractHuffmanTable::generateCodeSymbols(), rawspeed::AbstractHuffmanTable::setCodeValues(), and rawspeed::AbstractHuffmanTable::setNCodesPerLength().
generateCodeSymbols()
std::vector<CodeSymbol> rawspeed::AbstractHuffmanTable::generateCodeSymbols () const inline protected inherited
Definition at line 138 of file AbstractHuffmanTable.h.
References rawspeed::AbstractHuffmanTable::__attribute__().
if()
rawspeed::AbstractHuffmanTable::if ((diff &(1<<(len - 1))) = =0) inherited
operator==()
bool rawspeed::AbstractHuffmanTable::operator== (const AbstractHuffmanTable & other) const inline inherited
Definition at line 171 of file AbstractHuffmanTable.h.
processSymbol()
template<typename BIT_STREAM , bool FULL_DECODE> int rawspeed::AbstractHuffmanTable::processSymbol (BIT_STREAM & bs, CodeSymbol symbol, int codeValue) const inline inherited
Definition at line 241 of file AbstractHuffmanTable.h.
References rawspeed::AbstractHuffmanTable::__attribute__(), rawspeed::AbstractHuffmanTable::CodeSymbol::code_len, and rawspeed::AbstractHuffmanTable::fixDNGBug16.
setCodeValues()
void rawspeed::AbstractHuffmanTable::setCodeValues (const Buffer & data) inline inherited
Definition at line 228 of file AbstractHuffmanTable.h.
References rawspeed::AbstractHuffmanTable::__attribute__().
setNCodesPerLength()
uint32_t rawspeed::AbstractHuffmanTable::setNCodesPerLength (const Buffer & data) inline inherited
Definition at line 176 of file AbstractHuffmanTable.h.
References rawspeed::AbstractHuffmanTable::__attribute__().
setup()
void rawspeed::AbstractHuffmanTable::setup (bool fullDecode_, bool fixDNGBug16_) inline protected inherited
Definition at line 100 of file AbstractHuffmanTable.h.
References rawspeed::AbstractHuffmanTable::fixDNGBug16, rawspeed::AbstractHuffmanTable::fullDecode, and rawspeed::AbstractHuffmanTable::verifyCodeSymbolsAreValidDiffLenghts().
VerifyCodeSymbols()
static void rawspeed::AbstractHuffmanTable::VerifyCodeSymbols (const std::vector< CodeSymbol > & symbols) inline static protected inherited
Definition at line 113 of file AbstractHuffmanTable.h.
verifyCodeSymbolsAreValidDiffLenghts()
void rawspeed::AbstractHuffmanTable::verifyCodeSymbolsAreValidDiffLenghts () const inline inherited
Definition at line 65 of file AbstractHuffmanTable.h.
Referenced by rawspeed::AbstractHuffmanTable::setup().
Member Data Documentation
codeValues
std::vector<uint8_t> rawspeed::AbstractHuffmanTable::codeValues protected inherited
Definition at line 98 of file AbstractHuffmanTable.h.
fixDNGBug16
bool rawspeed::AbstractHuffmanTable::fixDNGBug16 = false protected inherited
Definition at line 77 of file AbstractHuffmanTable.h.
Referenced by rawspeed::AbstractHuffmanTable::processSymbol(), and rawspeed::AbstractHuffmanTable::setup().
fullDecode
bool rawspeed::AbstractHuffmanTable::fullDecode = true protected inherited
Definition at line 76 of file AbstractHuffmanTable.h.
Referenced by rawspeed::HuffmanTableLUT::__attribute__(), rawspeed::HuffmanTableVector::decode(), rawspeed::HuffmanTableTree::decode(), rawspeed::HuffmanTableLookup::decode(), rawspeed::HuffmanTableLookup::decodeCodeValue(), rawspeed::HuffmanTableVector::decodeCodeValue(), rawspeed::HuffmanTableTree::decodeCodeValue(), rawspeed::HuffmanTableLookup::decodeDifference(), rawspeed::HuffmanTableVector::decodeDifference(), rawspeed::HuffmanTableTree::decodeDifference(), and rawspeed::AbstractHuffmanTable::setup().
len
int uint32_t rawspeed::AbstractHuffmanTable::len inherited
Initial value:
{
    assert(len > 0)
Definition at line 266 of file AbstractHuffmanTable.h.
nCodesPerLength
std::vector<unsigned int> rawspeed::AbstractHuffmanTable::nCodesPerLength protected inherited
Definition at line 88 of file AbstractHuffmanTable.h.
ret [1/2]
auto rawspeed::AbstractHuffmanTable::ret = static_cast<int32_t>(diff) inherited
Definition at line 268 of file AbstractHuffmanTable.h.
ret [2/2]
return rawspeed::AbstractHuffmanTable::ret inherited
Definition at line 271 of file AbstractHuffmanTable.h.
The documentation for this class was generated from the following file:
/build/rawspeed/test/librawspeed/decompressors/AbstractHuffmanTableTest.cpp