RawSpeed: rawspeed::PanasonicDecompressorV5 Class Reference
rawspeed::PanasonicDecompressorV5 Class Reference final
#include "decompressors/PanasonicDecompressorV5.h"
Classes
struct Block
struct PacketDsc
class ProxyStream
Public Member Functions
PanasonicDecompressorV5 (const RawImage &img, const ByteStream &input_, uint32_t bps_)
void decompress () const noexcept
Private Member Functions
void chopInputIntoBlocks (const PacketDsc &dsc)
template<const PacketDsc & dsc>
void processPixelPacket (BitPumpLSB *bs, int row, int col) const
template<const PacketDsc & dsc>
void processBlock (const Block &block) const
template<const PacketDsc & dsc>
void decompressInternal () const noexcept
Private Attributes
RawImage mRaw
ByteStream input
const uint32_t bps
size_t numBlocks
std::vector< Block > blocks
Static Private Attributes
static constexpr uint32_t BlockSize = 0x4000
static constexpr uint32_t sectionSplitOffset = 0x1FF8
static constexpr uint32_t bytesPerPacket = 16
static constexpr uint32_t bitsPerPacket = 8 * bytesPerPacket
static constexpr uint32_t PacketsPerBlock = BlockSize / bytesPerPacket
static const PacketDsc TwelveBitPacket
static const PacketDsc FourteenBitPacket
Detailed Description
Definition at line 36 of file PanasonicDecompressorV5.h.
Constructor & Destructor Documentation
PanasonicDecompressorV5()
rawspeed::PanasonicDecompressorV5::PanasonicDecompressorV5 (const RawImage & img, const ByteStream & input_, uint32_t bps_)
Definition at line 62 of file PanasonicDecompressorV5.cpp.
References rawspeed::iPoint2D::__attribute__(), BlockSize, bps, chopInputIntoBlocks(), rawspeed::RawImageData::dim, FourteenBitPacket, rawspeed::ByteStream::getRemainSize(), rawspeed::iPoint2D::hasPositiveArea(), mRaw, rawspeed::RawImage::operator->(), rawspeed::PanasonicDecompressorV5::PacketDsc::pixelsPerPacket, rawspeed::RawImage::RawImage(), TwelveBitPacket, and rawspeed::iPoint2D::x.
Member Function Documentation
chopInputIntoBlocks()
void rawspeed::PanasonicDecompressorV5::chopInputIntoBlocks (const PacketDsc & dsc) private
Definition at line 109 of file PanasonicDecompressorV5.cpp.
References rawspeed::iPoint2D::__attribute__(), rawspeed::RawImageData::dim, rawspeed::ByteStream::getRemainSize(), input, rawspeed::iPoint2D::iPoint2D(), mRaw, rawspeed::RawImage::operator->(), PacketsPerBlock, rawspeed::PanasonicDecompressorV5::PacketDsc::pixelsPerPacket, and rawspeed::iPoint2D::x.
Referenced by PanasonicDecompressorV5().
decompress()
void rawspeed::PanasonicDecompressorV5::decompress () const noexcept
Definition at line 238 of file PanasonicDecompressorV5.cpp.
References bps.
Referenced by LLVMFuzzerTestOneInput().
decompressInternal()
template<const PanasonicDecompressorV5::PacketDsc & dsc> void rawspeed::PanasonicDecompressorV5::decompressInternal () const private noexcept
Definition at line 226 of file PanasonicDecompressorV5.cpp.
processBlock()
template<const PanasonicDecompressorV5::PacketDsc & dsc> void rawspeed::PanasonicDecompressorV5::processBlock (const Block & block) const private
Definition at line 199 of file PanasonicDecompressorV5.cpp.
References rawspeed::PanasonicDecompressorV5::Block::beginCoord, BlockSize, rawspeed::PanasonicDecompressorV5::Block::bs, bytesPerPacket, rawspeed::RawImageData::dim, rawspeed::PanasonicDecompressorV5::Block::endCoord, mRaw, rawspeed::RawImage::operator->(), rawspeed::PanasonicDecompressorV5::PacketDsc::pixelsPerPacket, rawspeed::PanasonicDecompressorV5::ProxyStream::ProxyStream(), rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
processPixelPacket()
template<const PanasonicDecompressorV5::PacketDsc & dsc> void rawspeed::PanasonicDecompressorV5::processPixelPacket (BitPumpLSB * bs, int row, int col) const inline private
Definition at line 181 of file PanasonicDecompressorV5.cpp.
References rawspeed::PanasonicDecompressorV5::PacketDsc::bps, and rawspeed::PanasonicDecompressorV5::PacketDsc::pixelsPerPacket.
Member Data Documentation
bitsPerPacket
constexpr uint32_t rawspeed::PanasonicDecompressorV5::bitsPerPacket = 8 * bytesPerPacket static constexpr private
Definition at line 52 of file PanasonicDecompressorV5.h.
Referenced by rawspeed::PanasonicDecompressorV5::PacketDsc::PacketDsc().
blocks
std::vector<Block> rawspeed::PanasonicDecompressorV5::blocks private
Definition at line 89 of file PanasonicDecompressorV5.h.
BlockSize
constexpr uint32_t rawspeed::PanasonicDecompressorV5::BlockSize = 0x4000 static constexpr private
Definition at line 39 of file PanasonicDecompressorV5.h.
Referenced by PanasonicDecompressorV5(), rawspeed::PanasonicDecompressorV5::ProxyStream::parseBlock(), and processBlock().
bps
const uint32_t rawspeed::PanasonicDecompressorV5::bps private
Definition at line 71 of file PanasonicDecompressorV5.h.
Referenced by decompress(), and PanasonicDecompressorV5().
bytesPerPacket
constexpr uint32_t rawspeed::PanasonicDecompressorV5::bytesPerPacket = 16 static constexpr private
Definition at line 51 of file PanasonicDecompressorV5.h.
Referenced by processBlock().
FourteenBitPacket
constexpr PanasonicDecompressorV5::PacketDsc rawspeed::PanasonicDecompressorV5::FourteenBitPacket static constexpr private
Initial value:
=
        PanasonicDecompressorV5::PacketDsc(14)
Definition at line 61 of file PanasonicDecompressorV5.h.
Referenced by PanasonicDecompressorV5().
input
ByteStream rawspeed::PanasonicDecompressorV5::input private
Definition at line 69 of file PanasonicDecompressorV5.h.
Referenced by chopInputIntoBlocks().
mRaw
RawImage rawspeed::PanasonicDecompressorV5::mRaw private
Definition at line 64 of file PanasonicDecompressorV5.h.
Referenced by chopInputIntoBlocks(), PanasonicDecompressorV5(), and processBlock().
numBlocks
size_t rawspeed::PanasonicDecompressorV5::numBlocks private
Definition at line 73 of file PanasonicDecompressorV5.h.
PacketsPerBlock
constexpr uint32_t rawspeed::PanasonicDecompressorV5::PacketsPerBlock = BlockSize / bytesPerPacket static constexpr private
Definition at line 54 of file PanasonicDecompressorV5.h.
Referenced by chopInputIntoBlocks().
sectionSplitOffset
constexpr uint32_t rawspeed::PanasonicDecompressorV5::sectionSplitOffset = 0x1FF8 static constexpr private
Definition at line 47 of file PanasonicDecompressorV5.h.
Referenced by rawspeed::PanasonicDecompressorV5::ProxyStream::parseBlock().
TwelveBitPacket
constexpr PanasonicDecompressorV5::PacketDsc rawspeed::PanasonicDecompressorV5::TwelveBitPacket static constexpr private
Initial value:
=
        PanasonicDecompressorV5::PacketDsc(12)
Definition at line 57 of file PanasonicDecompressorV5.h.
Referenced by PanasonicDecompressorV5().
The documentation for this class was generated from the following files:
librawspeed/decompressors/PanasonicDecompressorV5.h
librawspeed/decompressors/PanasonicDecompressorV5.cpp