RawSpeed: /build/rawspeed/fuzz/librawspeed/decompressors/PhaseOneDecompressor.cpp File Reference
PhaseOneDecompressor.cpp File Reference
#include "decompressors/PhaseOneDecompressor.h"
#include "common/RawImage.h"
#include "common/RawspeedException.h"
#include "fuzz/Common.h"
#include "io/Buffer.h"
#include "io/ByteStream.h"
#include "io/Endianness.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <cstdio>
#include <iterator>
Functions
int LLVMFuzzerTestOneInput (const uint8_t *Data, size_t Size)
Function Documentation
LLVMFuzzerTestOneInput()
int LLVMFuzzerTestOneInput (const uint8_t * Data, size_t Size)
Definition at line 36 of file PhaseOneDecompressor.cpp.
References rawspeed::ByteStream::ByteStream(), rawspeed::BitStreamTraits< BitPumpMSB32 >::canUseWithHuffmanTable, rawspeed::RawImageData::checkMemIsInitialized(), rawspeed::RawImageData::createData(), CreateRawImage(), rawspeed::PhaseOneDecompressor::decompress(), rawspeed::ByteStream::getU32(), rawspeed::little, and rawspeed::RawImage::operator->().