RawSpeed: rawspeed::LJpegDecompressor Class Reference
rawspeed::LJpegDecompressor Class Reference final
#include "decompressors/LJpegDecompressor.h"
Public Member Functions
LJpegDecompressor (const ByteStream &bs, const RawImage &img)
void decode (uint32_t offsetX, uint32_t offsetY, uint32_t width, uint32_t height, bool fixDng16Bug_)
Protected Member Functions
void decode ()
void parseSOF (ByteStream data, SOFInfo *i)
void parseSOS (ByteStream data)
void parseDHT (ByteStream data)
JpegMarker getNextMarker (bool allowskip)
template<int N_COMP>
std::array< HuffmanTable *, N_COMP > getHuffmanTables () const
Protected Attributes
bool fixDng16Bug = false
bool fullDecodeHT = true
template<int N_COMP>
__attribute__((pure)) std ByteStream input
RawImage mRaw
SOFInfo frame
uint32_t predictorMode = 0
Private Member Functions
void decodeScan () override
template<int N_COMP, bool WeirdWidth = false>
void decodeN ()
Private Attributes
uint32_t offX = 0
uint32_t offY = 0
uint32_t w = 0
uint32_t h = 0
uint32_t fullBlocks = 0
uint32_t trailingPixels = 0
std::vector< std::unique_ptr< HuffmanTable > > huffmanTableStore
HuffmanTable ht_
uint32_t Pt = 0
std::array< HuffmanTable *, 4 > huff {{}}
Detailed Description
Definition at line 33 of file LJpegDecompressor.h.
Constructor & Destructor Documentation
LJpegDecompressor()
rawspeed::LJpegDecompressor::LJpegDecompressor (const ByteStream & bs, const RawImage & img)
Definition at line 36 of file LJpegDecompressor.cpp.
References rawspeed::AbstractLJpegDecompressor::AbstractLJpegDecompressor().
Referenced by LLVMFuzzerTestOneInput().
Member Function Documentation
decode() [1/2]
void rawspeed::AbstractLJpegDecompressor::decode () protected inherited
Definition at line 55 of file AbstractLJpegDecompressor.cpp.
References rawspeed::AbstractLJpegDecompressor::getNextMarker(), rawspeed::ByteStream::getStream(), rawspeed::AbstractLJpegDecompressor::input, rawspeed::M_EOI, rawspeed::AbstractLJpegDecompressor::parseDHT(), rawspeed::AbstractLJpegDecompressor::parseSOS(), rawspeed::ByteStream::peekU16(), and rawspeed::ByteStream::skipBytes().
decode() [2/2]
void rawspeed::LJpegDecompressor::decode (uint32_t offsetX, uint32_t offsetY, uint32_t width, uint32_t height, bool fixDng16Bug_)
Definition at line 58 of file LJpegDecompressor.cpp.
References rawspeed::AbstractLJpegDecompressor::fixDng16Bug, h, offX, offY, and w.
Referenced by LLVMFuzzerTestOneInput().
decodeN()
template<int N_COMP, bool WeirdWidth> void rawspeed::LJpegDecompressor::decodeN () private
Definition at line 156 of file LJpegDecompressor.cpp.
References rawspeed::RawImageData::dim, fullBlocks, rawspeed::RawImageData::getCpp(), rawspeed::RawImageData::getDataUncropped(), h, rawspeed::AbstractLJpegDecompressor::mRaw, offX, offY, rawspeed::RawImage::operator->(), trailingPixels, w, rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
decodeScan()
void rawspeed::LJpegDecompressor::decodeScan () override private
Definition at line 86 of file LJpegDecompressor.cpp.
References rawspeed::RawImageData::dim, rawspeed::RawImageData::getCpp(), rawspeed::AbstractLJpegDecompressor::mRaw, offX, rawspeed::RawImage::operator->(), trailingPixels, w, and rawspeed::iPoint2D::x.
getHuffmanTables()
template<int N_COMP> std::array<HuffmanTable*, N_COMP> rawspeed::AbstractLJpegDecompressor::getHuffmanTables () const inline protected inherited
Definition at line 163 of file AbstractLJpegDecompressor.h.
getNextMarker()
JpegMarker rawspeed::AbstractLJpegDecompressor::getNextMarker (bool allowskip) protected inherited
Definition at line 254 of file AbstractLJpegDecompressor.cpp.
References rawspeed::ByteStream::getByte(), and rawspeed::AbstractLJpegDecompressor::input.
Referenced by rawspeed::AbstractLJpegDecompressor::decode().
parseDHT()
void rawspeed::AbstractLJpegDecompressor::parseDHT (ByteStream data) protected inherited
Definition at line 214 of file AbstractLJpegDecompressor.cpp.
References rawspeed::ByteStream::getByte(), and rawspeed::ByteStream::getRemainSize().
Referenced by rawspeed::AbstractLJpegDecompressor::decode().
parseSOF()
void rawspeed::AbstractLJpegDecompressor::parseSOF (ByteStream data, SOFInfo * i) protected inherited
Definition at line 114 of file AbstractLJpegDecompressor.cpp.
References rawspeed::SOFInfo::cps, rawspeed::RawImageData::dim, rawspeed::ByteStream::getByte(), rawspeed::RawImageData::getCpp(), rawspeed::ByteStream::getU16(), rawspeed::SOFInfo::h, rawspeed::SOFInfo::initialized, rawspeed::AbstractLJpegDecompressor::mRaw, rawspeed::RawImage::operator->(), rawspeed::SOFInfo::prec, rawspeed::SOFInfo::w, and rawspeed::iPoint2D::x.
parseSOS()
void rawspeed::AbstractLJpegDecompressor::parseSOS (ByteStream data) protected inherited
Definition at line 168 of file AbstractLJpegDecompressor.cpp.
References rawspeed::ByteStream::getByte(), rawspeed::AbstractLJpegDecompressor::predictorMode, and rawspeed::AbstractLJpegDecompressor::Pt.
Referenced by rawspeed::AbstractLJpegDecompressor::decode().
Member Data Documentation
fixDng16Bug
bool rawspeed::AbstractLJpegDecompressor::fixDng16Bug = false protected inherited
Definition at line 153 of file AbstractLJpegDecompressor.h.
Referenced by decode().
frame
SOFInfo rawspeed::AbstractLJpegDecompressor::frame protected inherited
Definition at line 195 of file AbstractLJpegDecompressor.h.
fullBlocks
uint32_t rawspeed::LJpegDecompressor::fullBlocks = 0 private
Definition at line 43 of file LJpegDecompressor.h.
Referenced by decodeN().
fullDecodeHT
bool rawspeed::AbstractLJpegDecompressor::fullDecodeHT = true protected inherited
Definition at line 154 of file AbstractLJpegDecompressor.h.
Referenced by rawspeed::HasselbladDecompressor::decode().
h
uint32_t rawspeed::LJpegDecompressor::h = 0 private
Definition at line 41 of file LJpegDecompressor.h.
Referenced by decode(), and decodeN().
ht_
HuffmanTable rawspeed::AbstractLJpegDecompressor::ht_ private inherited
Definition at line 142 of file AbstractLJpegDecompressor.h.
huff
std::array<HuffmanTable*, 4> rawspeed::AbstractLJpegDecompressor::huff {{}} private inherited
Definition at line 145 of file AbstractLJpegDecompressor.h.
huffmanTableStore
std::vector<std::unique_ptr<HuffmanTable> > rawspeed::AbstractLJpegDecompressor::huffmanTableStore private inherited
Definition at line 141 of file AbstractLJpegDecompressor.h.
input
template<int N_COMP> __attribute__ ((pure)) std ByteStream rawspeed::AbstractLJpegDecompressor::input protected inherited
Definition at line 179 of file AbstractLJpegDecompressor.h.
Referenced by rawspeed::AbstractLJpegDecompressor::AbstractLJpegDecompressor(), rawspeed::AbstractLJpegDecompressor::decode(), and rawspeed::AbstractLJpegDecompressor::getNextMarker().
mRaw
RawImage rawspeed::AbstractLJpegDecompressor::mRaw protected inherited
Definition at line 193 of file AbstractLJpegDecompressor.h.
Referenced by rawspeed::AbstractLJpegDecompressor::AbstractLJpegDecompressor(), rawspeed::Cr2Decompressor::Cr2Decompressor(), decodeN(), rawspeed::Cr2Decompressor::decodeN_X_Y(), decodeScan(), rawspeed::HasselbladDecompressor::HasselbladDecompressor(), and rawspeed::AbstractLJpegDecompressor::parseSOF().
offX
uint32_t rawspeed::LJpegDecompressor::offX = 0 private
Definition at line 38 of file LJpegDecompressor.h.
Referenced by decode(), decodeN(), and decodeScan().
offY
uint32_t rawspeed::LJpegDecompressor::offY = 0 private
Definition at line 39 of file LJpegDecompressor.h.
Referenced by decode(), and decodeN().
predictorMode
uint32_t rawspeed::AbstractLJpegDecompressor::predictorMode = 0 protected inherited
Definition at line 196 of file AbstractLJpegDecompressor.h.
Referenced by rawspeed::AbstractLJpegDecompressor::parseSOS().
Pt
uint32_t rawspeed::AbstractLJpegDecompressor::Pt = 0 private inherited
Definition at line 144 of file AbstractLJpegDecompressor.h.
Referenced by rawspeed::AbstractLJpegDecompressor::parseSOS().
trailingPixels
uint32_t rawspeed::LJpegDecompressor::trailingPixels = 0 private
Definition at line 44 of file LJpegDecompressor.h.
Referenced by decodeN(), and decodeScan().
w
uint32_t rawspeed::LJpegDecompressor::w = 0 private
Definition at line 40 of file LJpegDecompressor.h.
Referenced by decode(), decodeN(), and decodeScan().
The documentation for this class was generated from the following files:
librawspeed/decompressors/LJpegDecompressor.h
librawspeed/decompressors/LJpegDecompressor.cpp