RawSpeed: rawspeed::SonyArw2Decompressor Class Reference
rawspeed::SonyArw2Decompressor Class Reference final
#include "decompressors/SonyArw2Decompressor.h"
Public Member Functions
SonyArw2Decompressor (const RawImage &img, const ByteStream &input)
void decompress () const
Private Member Functions
void decompressRow (int row) const
void decompressThread () const noexcept
Private Attributes
RawImage mRaw
ByteStream input
Detailed Description
Definition at line 29 of file SonyArw2Decompressor.h.
Constructor & Destructor Documentation
SonyArw2Decompressor()
rawspeed::SonyArw2Decompressor::SonyArw2Decompressor (const RawImage & img, const ByteStream & input)
Definition at line 38 of file SonyArw2Decompressor.cpp.
References rawspeed::RawImageData::dim, input, mRaw, rawspeed::RawImage::operator->(), rawspeed::ByteStream::peekStream(), rawspeed::RawImage::RawImage(), rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
Referenced by LLVMFuzzerTestOneInput().
Member Function Documentation
decompress()
void rawspeed::SonyArw2Decompressor::decompress () const
Definition at line 131 of file SonyArw2Decompressor.cpp.
References decompressThread().
Referenced by LLVMFuzzerTestOneInput().
decompressRow()
void rawspeed::SonyArw2Decompressor::decompressRow (int row) const private
Definition at line 55 of file SonyArw2Decompressor.cpp.
References input, mRaw, and rawspeed::RawImage::operator*().
Referenced by decompressThread().
decompressThread()
void rawspeed::SonyArw2Decompressor::decompressThread () const private noexcept
Definition at line 110 of file SonyArw2Decompressor.cpp.
References decompressRow(), rawspeed::RawImageData::dim, mRaw, rawspeed::RawImage::operator->(), rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
Referenced by decompress().
Member Data Documentation
input
ByteStream rawspeed::SonyArw2Decompressor::input private
Definition at line 34 of file SonyArw2Decompressor.h.
Referenced by decompressRow(), and SonyArw2Decompressor().
mRaw
RawImage rawspeed::SonyArw2Decompressor::mRaw private
Definition at line 33 of file SonyArw2Decompressor.h.
Referenced by decompressRow(), decompressThread(), and SonyArw2Decompressor().
The documentation for this class was generated from the following files:
librawspeed/decompressors/SonyArw2Decompressor.h
librawspeed/decompressors/SonyArw2Decompressor.cpp