RawSpeed: rawspeed Namespace Reference
rawspeed Namespace Reference
Namespaces
anonymous_namespace{ChecksumFile.cpp}
anonymous_namespace{NikonDecompressor.cpp}
anonymous_namespace{PanasonicDecompressorV6.cpp}
anonymous_namespace{VC5Decompressor.cpp}
identify
ieee_754_2008
md5
rstest
Classes
class AbstractDecompressor
class AbstractDngDecompressor
class AbstractHuffmanTable
class AbstractLJpegDecompressor
class AbstractSamsungDecompressor
class AbstractTiffDecoder
class Array2DRef
class ArwDecoder
struct ASan
class BinaryHuffmanTree
class BitStream
struct BitStreamCacheBase
struct BitStreamCacheLeftInRightOut
struct BitStreamCacheRightInLeftOut
struct BitStreamForwardSequentialReplenisher
struct BitStreamReplenisherBase
struct BitStreamTraits
struct BitStreamTraits< BitPumpJPEG >
struct BitStreamTraits< BitPumpMSB >
struct BitStreamTraits< BitPumpMSB32 >
class BlackArea
class Buffer
class ByteStream
class Camera
struct CameraId
class CameraMetaData
class CameraMetadataException
class CameraSensorInfo
struct ChecksumFileEntry
class CiffEntry
class CiffIFD
class CiffParser
class CiffParserException
class ColorFilterArray
class Cpuid
class Cr2Decoder
class Cr2Decompressor
class Cr2Slicing
class Cr2sRawInterpolator
class CrwDecoder
class CrwDecompressor
class DataBuffer
class DcrDecoder
class DcsDecoder
class DefaultInitAllocatorAdaptor
class DngDecoder
class DngOpcodes
struct DngSliceElement
struct DngTilingDescription
class ErfDecoder
class ErrorLog
class FiffParser
class FiffParserException
class FileIOException
class FileReader
class FileWriter
class FujiDecompressor
class HasselbladDecompressor
class Hints
class HuffmanTableLookup
class HuffmanTableLUT
class HuffmanTableTree
class HuffmanTableVector
class IiqDecoder
class ImageMetaData
class IOException
class iPoint2D
class iRectangle2D
struct JpegComponentInfo
class KdcDecoder
class KodakDecompressor
class LJpegDecompressor
class MefDecoder
class MosDecoder
class MrwDecoder
struct MSan
class MutexLocker
class NakedDecoder
class NefDecoder
class NikonDecompressor
class OlympusDecompressor
class Optional
class OrfDecoder
class PanasonicDecompressorV4
class PanasonicDecompressorV5
class PanasonicDecompressorV6
class PefDecoder
class PentaxDecompressor
class PhaseOneDecompressor
struct PhaseOneStrip
class RafDecoder
class Range
struct RangesOverlapCmp
class RawDecoder
class RawDecoderException
class RawImage
class RawImageCurveGuard
class RawImageData
class RawImageDataFloat
class RawImageDataU16
class RawImageWorker
class RawParser
class RawParserException
class RawspeedException
class Rw2Decoder
class SamsungV0Decompressor
class SamsungV1Decompressor
class SamsungV2Decompressor
class SimpleLUT
class SimpleTiffDecoder
class SOFInfo
class SonyArw1Decompressor
class SonyArw2Decompressor
class Spline
class SrwDecoder
class TableLookUp
class ThreefrDecoder
class TiffEntry
struct TiffID
class TiffIFD
class TiffParser
class TiffParserException
class TiffRootIFD
class UncompressedDecompressor
struct unroll_loop_t
struct unroll_loop_t< Lambda, 0 >
class VC5Decompressor
Typedefs
using BitPumpJPEG = BitStream< JPEGBitPumpTag, BitStreamCacheRightInLeftOut >
using BitPumpLSB = BitStream< LSBBitPumpTag, BitStreamCacheLeftInRightOut >
using BitPumpMSB = BitStream< MSBBitPumpTag, BitStreamCacheRightInLeftOut >
using BitPumpMSB16 = BitStream< MSB16BitPumpTag, BitStreamCacheRightInLeftOut >
using BitPumpMSB32 = BitStream< MSB32BitPumpTag, BitStreamCacheRightInLeftOut >
using HuffmanTable = HuffmanTableLUT
using TiffIFDOwner = std::unique_ptr< TiffIFD >
using TiffRootIFDOwner = std::unique_ptr< TiffRootIFD >
using TiffEntryOwner = std::unique_ptr< TiffEntry >
template<typename T >
using NORangesSet = std::set< T, RangesOverlapCmp< T > >
Enumerations
enum DEBUG_PRIO { DEBUG_PRIO_ERROR = 0x10, DEBUG_PRIO_WARNING = 0x100, DEBUG_PRIO_INFO = 0x1000, DEBUG_PRIO_EXTRA = 0x10000 }
enum RawImageType { TYPE_USHORT16, TYPE_FLOAT32 }
enum Endianness { Endianness::little = 0xDEAD, Endianness::big = 0xBEEF, Endianness::unknown = 0x0BAD }
enum CFAColor : uint8_t {
CFA_RED = 0, CFA_GREEN = 1, CFA_BLUE = 2, CFA_CYAN = 3,
CFA_MAGENTA = 4, CFA_YELLOW = 5, CFA_WHITE = 6, CFA_FUJI_GREEN = 7,
CFA_END, CFA_UNKNOWN = 255
}
enum JpegMarker {
M_STUFF = 0x00, M_SOF0 = 0xc0, M_SOF1 = 0xc1, M_SOF2 = 0xc2,
M_SOF3 = 0xc3, M_SOF5 = 0xc5, M_SOF6 = 0xc6, M_SOF7 = 0xc7,
M_JPG = 0xc8, M_SOF9 = 0xc9, M_SOF10 = 0xca, M_SOF11 = 0xcb,
M_SOF13 = 0xcd, M_SOF14 = 0xce, M_SOF15 = 0xcf, M_DHT = 0xc4,
M_DAC = 0xcc, M_RST0 = 0xd0, M_RST1 = 0xd1, M_RST2 = 0xd2,
M_RST3 = 0xd3, M_RST4 = 0xd4, M_RST5 = 0xd5, M_RST6 = 0xd6,
M_RST7 = 0xd7, M_SOI = 0xd8, M_EOI = 0xd9, M_SOS = 0xda,
M_DQT = 0xdb, M_DNL = 0xdc, M_DRI = 0xdd, M_DHP = 0xde,
M_EXP = 0xdf, M_APP0 = 0xe0, M_APP1 = 0xe1, M_APP2 = 0xe2,
M_APP3 = 0xe3, M_APP4 = 0xe4, M_APP5 = 0xe5, M_APP6 = 0xe6,
M_APP7 = 0xe7, M_APP8 = 0xe8, M_APP9 = 0xe9, M_APP10 = 0xea,
M_APP11 = 0xeb, M_APP12 = 0xec, M_APP13 = 0xed, M_APP14 = 0xee,
M_APP15 = 0xef, M_JPG0 = 0xf0, M_JPG13 = 0xfd, M_COM = 0xfe,
M_TEM = 0x01, M_FILL = 0xFF
}
enum VC5Tag : int16_t {
VC5Tag::NoTag = 0x0, VC5Tag::ChannelCount = 0x000c, VC5Tag::ImageWidth = 0x0014, VC5Tag::ImageHeight = 0x0015,
VC5Tag::LowpassPrecision = 0x0023, VC5Tag::SubbandCount = 0x000E, VC5Tag::SubbandNumber = 0x0030, VC5Tag::Quantization = 0x0035,
VC5Tag::ChannelNumber = 0x003e, VC5Tag::ImageFormat = 0x0054, VC5Tag::MaxBitsPerComponent = 0x0066, VC5Tag::PatternWidth = 0x006a,
VC5Tag::PatternHeight = 0x006b, VC5Tag::ComponentsPerSample = 0x006c, VC5Tag::PrescaleShift = 0x006d, VC5Tag::LARGE_CHUNK = 0x2000,
VC5Tag::SMALL_CHUNK = 0x4000, VC5Tag::UniqueImageIdentifier = 0x4004, VC5Tag::LargeCodeblock = 0x6000, VC5Tag::Optional = int16_t(0x8000U)
}
enum TiffDataType {
TIFF_NOTYPE = 0, TIFF_BYTE = 1, TIFF_ASCII = 2, TIFF_SHORT = 3,
TIFF_LONG = 4, TIFF_RATIONAL = 5, TIFF_SBYTE = 6, TIFF_UNDEFINED = 7,
TIFF_SSHORT = 8, TIFF_SLONG = 9, TIFF_SRATIONAL = 10, TIFF_FLOAT = 11,
TIFF_DOUBLE = 12, TIFF_OFFSET = 13
}
enum TiffTag {
INTEROPERABILITYINDEX = 0x0001, INTEROPERABILITYVERSION = 0x0002, CANONSHOTINFO = 0x0004, CANONPOWERSHOTG9WB = 0x0029,
PANASONIC_ISO_SPEED = 23, PANASONIC_CFAPATTERN = 0x0009, NEWSUBFILETYPE = 0x00FE, SUBFILETYPE = 0x00FF,
PANASONIC_BITSPERSAMPLE = 0xa, PANASONIC_RAWFORMAT = 0x2d, MAKERNOTE_ALT = 0x2e, IMAGEWIDTH = 0x0100,
IMAGELENGTH = 0x0101, BITSPERSAMPLE = 0x0102, COMPRESSION = 0x0103, PHOTOMETRICINTERPRETATION = 0x0106,
FILLORDER = 0x010A, DOCUMENTNAME = 0x010D, IMAGEDESCRIPTION = 0x010E, MAKE = 0x010F,
MODEL = 0x0110, STRIPOFFSETS = 0x0111, ORIENTATION = 0x0112, SAMPLESPERPIXEL = 0x0115,
ROWSPERSTRIP = 0x0116, STRIPBYTECOUNTS = 0x0117, PANASONIC_STRIPOFFSET = 0x118, XRESOLUTION = 0x011A,
YRESOLUTION = 0x011B, PLANARCONFIGURATION = 0x011C, GRAYRESPONSECURVE = 0x0123, T4OPTIONS = 0x0124,
T6OPTIONS = 0x0125, RESOLUTIONUNIT = 0x0128, TRANSFERFUNCTION = 0x012D, FUJI_LAYOUT = 0x0130,
SOFTWARE = 0x0131, DATETIME = 0x0132, ARTIST = 0x013B, PREDICTOR = 0x013D,
WHITEPOINT = 0x013E, PRIMARYCHROMATICITIES = 0x013F, HALFTONEHINTS = 0x0141, TILEWIDTH = 0x0142,
TILELENGTH = 0x0143, TILEOFFSETS = 0x0144, TILEBYTECOUNTS = 0x0145, SUBIFDS = 0x014A,
INKSET = 0x014C, NUMBEROFINKS = 0x014E, INKNAMES = 0x014D, DOTRANGE = 0x0150,
TARGETPRINTER = 0x0151, EXTRASAMPLES = 0x0152, SAMPLEFORMAT = 0x0153, SMINSAMPLEVALUE = 0x0154,
SMAXSAMPLEVALUE = 0x0155, TRANSFERRANGE = 0x0156, CLIPPATH = 0x0157, JPEGTABLES = 0x015B,
JPEGPROC = 0x0200, JPEGINTERCHANGEFORMAT = 0x0201, JPEGINTERCHANGEFORMATLENGTH = 0x0202, JPEGRESTARTINTERVAL = 0x0203,
JPEGLOSSLESSPREDICTORS = 0x0205, JPEGPOINTTRANSFORMS = 0x0206, JPEGQTABLES = 0x0207, JPEGDCTABLES = 0x0208,
JPEGACTABLES = 0x0209, YCBCRCOEFFICIENTS = 0x0211, YCBCRSUBSAMPLING = 0x0212, YCBCRPOSITIONING = 0x0213,
REFERENCEBLACKWHITE = 0x0214, KODAKWB = 0x0F00, EPSONWB = 0x0E80, RELATEDIMAGEFILEFORMAT = 0x1000,
RELATEDIMAGEWIDTH = 0x1001, RELATEDIMAGELENGTH = 0x1002, OLYMPUSREDMULTIPLIER = 0x1017, OLYMPUSBLUEMULTIPLIER = 0x1018,
OLYMPUSIMAGEPROCESSING = 0x2040, FUJIOLDWB = 0x2ff0, CANONCOLORDATA = 0x4001, SONYGRBGLEVELS = 0x7303,
SONYRGGBLEVELS = 0x7313, CFAREPEATPATTERNDIM = 0x828D, CFAPATTERN = 0x828E, BATTERYLEVEL = 0x828F,
COPYRIGHT = 0x8298, EXPOSURETIME = 0x829A, FNUMBER = 0x829D, ROTATION = 0x82B9,
NAVYCOMPRESSION = 0x82BA, TILEINDEX = 0x82BB, IPTCNAA = 0x83BB, LEAFMETADATA = 0x8606,
PHOTOSHOPPRIVATE = 0x8649, EXIFIFDPOINTER = 0x8769, INTERCOLORPROFILE = 0x8773, EXPOSUREPROGRAM = 0x8822,
SPECTRALSENSITIVITY = 0x8824, GPSINFOIFDPOINTER = 0x8825, ISOSPEEDRATINGS = 0x8827, OECF = 0x8828,
EXIFVERSION = 0x9000, DATETIMEORIGINAL = 0x9003, DATETIMEDIGITIZED = 0x9004, COMPONENTSCONFIGURATION = 0x9101,
COMPRESSEDBITSPERPIXEL = 0x9102, SHUTTERSPEEDVALUE = 0x9201, APERTUREVALUE = 0x9202, BRIGHTNESSVALUE = 0x9203,
EXPOSUREBIASVALUE = 0x9204, MAXAPERTUREVALUE = 0x9205, SUBJECTDISTANCE = 0x9206, METERINGMODE = 0x9207,
LIGHTSOURCE = 0x9208, FLASH = 0x9209, FOCALLENGTH = 0x920A, FLASHENERGY_TIFFEP = 0x920B,
SPACIALFREQUENCYRESPONSE = 0x920C, NOISE = 0x920D, FOCALPLANEXRESOLUTION_TIFFEP = 0x920E, FOCALPLANEYRESOLUTION_TIFFEP = 0x920F,
FOCALPLANERESOLUTIONUNIT_TIFFEP = 0x9210, IMAGENAME = 0x9211, SECURITYCLASSIFICATION = 0x9212, IMAGEHISTORY = 0x9213,
SUBJECTAREA = 0x9214, EXPOSUREINDEX_TIFFEP = 0x9215, TIFFEPSTANDARDID = 0x9216, SENSINGMETHOD_TIFFEP = 0x9217,
MAKERNOTE = 0x927C, USERCOMMENT = 0x9286, SUBSECTIME = 0x9290, SUBSECTIMEORIGINAL = 0x9291,
SUBSECTIMEDIGITIZED = 0x9292, FLASHPIXVERSION = 0xA000, COLORSPACE = 0xA001, PIXELXDIMENSION = 0xA002,
PIXELYDIMENSION = 0xA003, RELATEDSOUNDFILE = 0xA004, INTEROPERABILITYIFDPOINTER = 0xA005, SAMSUNG_WB_RGGBLEVELSUNCORRECTED = 0xa021,
SAMSUNG_WB_RGGBLEVELSBLACK = 0xa028, FLASHENERGY = 0xA20B, SPATIALFREQUENCYRESPONSE = 0xA20C, FOCALPLANEXRESOLUTION = 0xA20E,
FOCALPLANEYRESOLUTION = 0xA20F, FOCALPLANERESOLUTIONUNIT = 0xA210, SUBJECTLOCATION = 0xA214, EXPOSUREINDEX = 0xA215,
SENSINGMETHOD = 0xA217, FILESOURCE = 0xA300, SCENETYPE = 0xA301, EXIFCFAPATTERN = 0xA302,
CUSTOMRENDERED = 0xA401, EXPOSUREMODE = 0xA402, WHITEBALANCE = 0xA403, DIGITALZOOMRATIO = 0xA404,
FOCALLENGTHIN35MMFILM = 0xA405, SCENECAPTURETYPE = 0xA406, GAINCONTROL = 0xA407, CONTRAST = 0xA408,
SATURATION = 0xA409, SHARPNESS = 0xA40A, DEVICESETTINGDESCRIPTION = 0xA40B, SUBJECTDISTANCERANGE = 0xA40C,
IMAGEUNIQUEID = 0xA420, GAMMA = 0xA500, XMP = 0x02BC, CANON_UNCOMPRESSED = 0xC5D9,
DNGVERSION = 0xC612, DNGBACKWARDVERSION = 0xC613, UNIQUECAMERAMODEL = 0xC614, LOCALIZEDCAMERAMODEL = 0xC615,
CFAPLANECOLOR = 0xC616, CFALAYOUT = 0xC617, LINEARIZATIONTABLE = 0xC618, BLACKLEVELREPEATDIM = 0xC619,
BLACKLEVEL = 0xC61A, BLACKLEVELDELTAH = 0xC61B, BLACKLEVELDELTAV = 0xC61C, WHITELEVEL = 0xC61D,
DEFAULTSCALE = 0xC61E, DEFAULTCROPORIGIN = 0xC61F, DEFAULTCROPSIZE = 0xC620, COLORMATRIX1 = 0xC621,
COLORMATRIX2 = 0xC622, CAMERACALIBRATION1 = 0xC623, CAMERACALIBRATION2 = 0xC624, REDUCTIONMATRIX1 = 0xC625,
REDUCTIONMATRIX2 = 0xC626, ANALOGBALANCE = 0xC627, ASSHOTNEUTRAL = 0xC628, ASSHOTWHITEXY = 0xC629,
BASELINEEXPOSURE = 0xC62A, BASELINENOISE = 0xC62B, BASELINESHARPNESS = 0xC62C, BAYERGREESPIT = 0xC62D,
LINEARRESPONSELIMIT = 0xC62E, CAMERASERIALNUMBER = 0xC62F, LENSINFO = 0xC630, CHROMABLURRADIUS = 0xC631,
ANTIALIASSTRENGTH = 0xC632, DNGPRIVATEDATA = 0xC634, MAKERNOTESAFETY = 0xC635, BESTQUALITYSCALE = 0xC65C,
SHADOWSCALE = 50739, RAWDATAUNIQUEID = 50781, ORIGINALRAWFILENAME = 50827, ORIGINALRAWFILEDATA = 50828,
ACTIVEAREA = 50829, MASKEDAREAS = 50830, ASSHOTICCPROFILE = 50831, ASSHOTPREPROFILEMATRIX = 50832,
CURRENTICCPROFILE = 50833, CURRENTPREPROFILEMATRIX = 50834, COLORIMETRICREFERENCE = 50879, KODAKKDCPRIVATEIFD = 65024,
CAMERACALIBRATIONSIGNATURE = 0xC6F3, PROFILECALIBRATIONSIGNATURE = 0xC6F4, EXTRACAMERAPROFILES = 0xC6F5, ASSHOTPROFILENAME = 0xC6F6,
NOISEREDUCTIONAPPLIED = 0xC6F7, PROFILENAME = 0xC6F8, PROFILEHUESATMAPDIMS = 0xC6F9, PROFILEHUESATMAPDATA1 = 0xC6FA,
PROFILEHUESATMAPDATA2 = 0xC6FB, PROFILETONECURVE = 0xC6FC, PROFILEEMBEDPOLICY = 0xC6FD, PROFILECOPYRIGHT = 0xC6FE,
FORWARDMATRIX1 = 0xC714, FORWARDMATRIX2 = 0xC715, PREVIEWAPPLICATIONNAME = 0xC716, PREVIEWAPPLICATIONVERSION = 0xC717,
PREVIEWSETTINGSNAME = 0xC718, PREVIEWSETTINGSDIGEST = 0xC719, PREVIEWCOLORSPACE = 0xC71A, PREVIEWDATETIME = 0xC71B,
RAWIMAGEDIGEST = 0xC71C, ORIGINALRAWFILEDIGEST = 0xC71D, SUBTILEBLOCKSIZE = 0xC71E, ROWINTERLEAVEFACTOR = 0xC71F,
PROFILELOOKTABLEDIMS = 0xC725, PROFILELOOKTABLEDATA = 0xC726, OPCODELIST1 = 0xC740, OPCODELIST2 = 0xC741,
OPCODELIST3 = 0xC742, NOISEPROFILE = 0xC761, CANONCR2SLICE = 0xC640, CANON_SRAWTYPE = 0xC6C5,
CANON_SRAWQUALITY = 0x002E, CANON_CAMERA_SETTINGS = 0x0001, CANON_SENSOR_INFO = 0x00E0, CANON_RAW_DATA_OFFSET = 0x0081,
CALIBRATIONILLUMINANT1 = 0xC65A, CALIBRATIONILLUMINANT2 = 0xC65B, SONY_CURVE = 28688, SONY_OFFSET = 0x7200,
SONY_LENGTH = 0x7201, SONY_KEY = 0x7221, PIMIFDPOINTER = 0xC4A5, FUJI_RAW_IFD = 0xF000,
FUJI_RAWIMAGEFULLWIDTH = 0xF001, FUJI_RAWIMAGEFULLHEIGHT = 0xF002, FUJI_BITSPERSAMPLE = 0xF003, FUJI_STRIPOFFSETS = 0xF007,
FUJI_STRIPBYTECOUNTS = 0xF008, FUJI_BLACKLEVEL = 0xF00A, FUJI_WB_GRBLEVELS = 0xF00E, KODAK_IFD = 0x8290,
KODAK_LINEARIZATION = 0x090D, KODAK_KDC_WB = 0xFA2A, KODAK_KDC_OFFSET = 0xFD04, KODAK_KDC_WIDTH = 0xFD00,
KODAK_KDC_HEIGHT = 0xFD01, KODAK_KDC_SENSOR_WIDTH = 0xFA13, KODAK_KDC_SENSOR_HEIGHT = 0xFA14, KODAK_IFD2 = 0xFE00
}
enum CiffDataType {
CIFF_BYTE = 0x0000, CIFF_ASCII = 0x0800, CIFF_SHORT = 0x1000, CIFF_LONG = 0x1800,
CIFF_MIX = 0x2000, CIFF_SUB1 = 0x2800, CIFF_SUB2 = 0x3000
}
enum CiffTag {
CIFF_NULL = 0x0000, CIFF_MAKEMODEL = 0x080a, CIFF_SHOTINFO = 0x102a, CIFF_WHITEBALANCE = 0x10a9,
CIFF_SENSORINFO = 0x1031, CIFF_IMAGEINFO = 0x1810, CIFF_DECODERTABLE = 0x1835, CIFF_RAWDATA = 0x2005,
CIFF_SUBIFD = 0x300a, CIFF_EXIF = 0x300b
}
Functions
void writeLog (DEBUG_PRIO priority, const char *format,...) __attribute__((format(printf
void void copyPixels (uint8_t *dest, int dstPitch, const uint8_t *src, int srcPitch, int rowSize, int height)
template<typename T >
constexpr bool isPowerOfTwo (T val)
constexpr size_t __attribute__ ((const)) roundToMultiple(size_t value
if (roundDown) return roundedDown
constexpr size_t std::enable_if< std::is_pointer< T >::value >::type T2 bool __attribute__ ((pure)) isIn(const T value
template<class T >
constexpr unsigned bitwidth (T unused={})
template<size_t N, typename Lambda >
void unroll_loop (const Lambda &f)
template<typename T0 , typename A0 , typename T1 , typename A1 >
bool operator== (DefaultInitAllocatorAdaptor< T0, A0 > const &x, DefaultInitAllocatorAdaptor< T1, A1 > const &y) noexcept
template<typename T0 , typename A0 , typename T1 , typename A1 >
bool operator!= (DefaultInitAllocatorAdaptor< T0, A0 > const &x, DefaultInitAllocatorAdaptor< T1, A1 > const &y) noexcept
void * alignedMalloc (size_t size, size_t alignment) __attribute__((malloc
void alloc_size (1)
void alloc_align (2)
void deprecated ("use alignedMalloc<alignment>(size)")))
template<typename T , size_t alignment>
T * __attribute__ ((malloc, warn_unused_result, alloc_size(1))) alignedMalloc(size_t size)
template<typename T , size_t alignment, bool doRoundUp = false>
T * __attribute__ ((malloc, warn_unused_result)) alignedMallocArray(size_t nmemb
size * if (doRoundUp) size
return alignedMalloc< T, alignment > (size)
template<typename T , size_t alignment, typename T2 , bool doRoundUp = false>
T * __attribute__ ((malloc, warn_unused_result)) alignedMallocArray(size_t nmemb)
void alignedFree (void *ptr)
void alignedFreeConstPtr (const void *ptr)
Endianness getHostEndiannessRuntime ()
Endianness getHostEndianness ()
int16_t getByteSwapped (int16_t v)
uint16_t getByteSwapped (uint16_t v)
int32_t getByteSwapped (int32_t v)
uint32_t getByteSwapped (uint32_t v)
uint64_t getByteSwapped (uint64_t v)
float getByteSwapped (float f)
double getByteSwapped (double d)
template<typename T >
T getByteSwapped (const void *data, bool bswap)
template<typename T >
T getBE (const void *data)
template<typename T >
T getLE (const void *data)
uint16_t getU16BE (const void *data)
uint16_t getU16LE (const void *data)
uint32_t getU32BE (const void *data)
uint32_t getU32LE (const void *data)
class CAPABILITY ("mutex") Mutex final
template<typename T >
void RAWSPEED_UNLIKELY_FUNCTION RAWSPEED_NOINLINE __attribute__ ((noreturn, format(printf, 1, 2))) ThrowException(const char *fmt
va_start (val, fmt)
vsnprintf (buf.data(), sizeof(buf), fmt, val)
va_end (val)
writeLog (DEBUG_PRIO_EXTRA, "EXCEPTION: %s", buf.data())
throw T (buf.data())
bool operator== (const AbstractHuffmanTable::CodeSymbol &lhs, const AbstractHuffmanTable::CodeSymbol &rhs)
VC5Tag operator& (VC5Tag LHS, VC5Tag RHS)
bool matches (VC5Tag LHS, VC5Tag RHS)
bool is (VC5Tag LHS, VC5Tag RHS)
VC5Tag operator- (VC5Tag tag)
Endianness getTiffByteOrder (const ByteStream &bs, uint32_t pos, const char *context="")
std::vector< ChecksumFileEntry > ParseChecksumFileContent (const std::string &ChecksumFileContent, const std::string &RootDir)
std::vector< ChecksumFileEntry > ReadChecksumFile (const std::string &RootDir, const std::string &ChecksumFileBasename)
template<typename Tr , typename Tv >
constexpr bool __attribute__ ((const)) RangeContains(const Tr &r
assert (pos >=r.begin())
return r end () > pos
template<typename T >
constexpr bool __attribute__ ((const)) RangesOverlap(const T &lhs
if (lhs.begin()==rhs.begin()) return true
assert (ordered.first.begin()< ordered.second.begin())
return RangeContains (ordered.first, ordered.second.begin())
template void UncompressedDecompressor::decode12BitRaw< Endianness::little, false, false > (uint32_t w, uint32_t h)
template void UncompressedDecompressor::decode12BitRaw< Endianness::big, false, false > (uint32_t w, uint32_t h)
template void UncompressedDecompressor::decode12BitRaw< Endianness::big, true, false > (uint32_t w, uint32_t h)
template void UncompressedDecompressor::decode12BitRaw< Endianness::little, false, true > (uint32_t w, uint32_t h)
template void UncompressedDecompressor::decode12BitRaw< Endianness::big, false, true > (uint32_t w, uint32_t h)
template void UncompressedDecompressor::decode12BitRawUnpackedLeftAligned< Endianness::big > (uint32_t w, uint32_t h)
template void UncompressedDecompressor::decodeRawUnpacked< 12, Endianness::little > (uint32_t w, uint32_t h)
template void UncompressedDecompressor::decodeRawUnpacked< 12, Endianness::big > (uint32_t w, uint32_t h)
template void UncompressedDecompressor::decodeRawUnpacked< 14, Endianness::big > (uint32_t w, uint32_t h)
template void UncompressedDecompressor::decodeRawUnpacked< 16, Endianness::little > (uint32_t w, uint32_t h)
template void UncompressedDecompressor::decodeRawUnpacked< 16, Endianness::big > (uint32_t w, uint32_t h)
__attribute__ ((always_inline)) int OlympusDecompressor
constexpr SamsungV2Decompressor::OptFlags operator| (SamsungV2Decompressor::OptFlags lhs, SamsungV2Decompressor::OptFlags rhs)
constexpr bool operator& (SamsungV2Decompressor::OptFlags lhs, SamsungV2Decompressor::OptFlags rhs)
template<typename NarrowType , typename WideType >
uint32_t extendBinaryFloatingPoint (uint32_t narrow)
uint32_t fp16ToFloat (uint16_t fp16)
uint32_t fp24ToFloat (uint32_t fp24)
static CameraId getId (const string &make, const string &model, const string &mode)
static uint32_t toDcrawColor (CFAColor c)
template<typename T >
::std::ostream & operator<< (::std::ostream &os, const Range< T > &r)
::std::ostream & operator<< (::std::ostream &os, const iPoint2D p)
bool operator!= (const AbstractHuffmanTable &lhs, const AbstractHuffmanTable &rhs)
::std::ostream & operator<< (::std::ostream &os, const AbstractHuffmanTable::CodeSymbol s)
bool operator!= (const AbstractHuffmanTable::CodeSymbol &lhs, const AbstractHuffmanTable::CodeSymbol &rhs)
::std::ostream & operator<< (::std::ostream &os, const CFAColor c)
std::wstring widenFileName (const char *fileName)
Variables
constexpr size_t size_t multiple
constexpr size_t size_t bool roundDown
size_t roundedDown = value - (value % multiple)
constexpr size_t size_t div
constexpr size_t std::enable_if< std::is_pointer< T >::value >::type T2 bool const std::initializer_list< T2 > & list
constexpr unsigned int nBits
void warn_unused_result
T size_t size
void RAWSPEED_UNLIKELY_FUNCTION RAWSPEED_NOINLINE static char buf [bufSize]
va_list val
const int MAX_NUM_PRESCALE = 8
iPoint2D __attribute__ ((pure)) rawspeed
constexpr int TABLE_MAX_ELTS = std::numeric_limits<uint16_t>::max() + 1
constexpr int TABLE_SIZE = TABLE_MAX_ELTS * 2
constexpr bool Tv pos
constexpr bool const T & rhs
const std::pair< const T &, const T & > ordered
static constexpr std::initializer_list< CiffTag > CiffTagsWeCareAbout
Typedef Documentation
BitPumpJPEG
using rawspeed::BitPumpJPEG = typedef BitStream<JPEGBitPumpTag, BitStreamCacheRightInLeftOut>
Definition at line 35 of file BitPumpJPEG.h.
BitPumpLSB
using rawspeed::BitPumpLSB = typedef BitStream<LSBBitPumpTag, BitStreamCacheLeftInRightOut>
Definition at line 35 of file BitPumpLSB.h.
BitPumpMSB
using rawspeed::BitPumpMSB = typedef BitStream<MSBBitPumpTag, BitStreamCacheRightInLeftOut>
Definition at line 35 of file BitPumpMSB.h.
BitPumpMSB16
using rawspeed::BitPumpMSB16 = typedef BitStream<MSB16BitPumpTag, BitStreamCacheRightInLeftOut>
Definition at line 35 of file BitPumpMSB16.h.
BitPumpMSB32
using rawspeed::BitPumpMSB32 = typedef BitStream<MSB32BitPumpTag, BitStreamCacheRightInLeftOut>
Definition at line 35 of file BitPumpMSB32.h.
HuffmanTable
using rawspeed::HuffmanTable = typedef HuffmanTableLUT
Definition at line 34 of file HuffmanTable.h.
NORangesSet
template<typename T > using rawspeed::NORangesSet = typedef std::set<T, RangesOverlapCmp<T> >
Definition at line 35 of file NORangesSet.h.
TiffEntryOwner
using rawspeed::TiffEntryOwner = typedef std::unique_ptr<TiffEntry>
Definition at line 46 of file TiffIFD.h.
TiffIFDOwner
using rawspeed::TiffIFDOwner = typedef std::unique_ptr<TiffIFD>
Definition at line 44 of file TiffIFD.h.
TiffRootIFDOwner
using rawspeed::TiffRootIFDOwner = typedef std::unique_ptr<TiffRootIFD>
Definition at line 45 of file TiffIFD.h.
Enumeration Type Documentation
CFAColor
enum rawspeed::CFAColor : uint8_t
Enumerator
CFA_RED
CFA_GREEN
CFA_BLUE
CFA_CYAN
CFA_MAGENTA
CFA_YELLOW
CFA_WHITE
CFA_FUJI_GREEN
CFA_END
CFA_UNKNOWN
Definition at line 31 of file ColorFilterArray.h.
CiffDataType
enum rawspeed::CiffDataType
Enumerator
CIFF_BYTE
CIFF_ASCII
CIFF_SHORT
CIFF_LONG
CIFF_MIX
CIFF_SUB1
CIFF_SUB2
Definition at line 40 of file CiffEntry.h.
CiffTag
enum rawspeed::CiffTag
Enumerator
CIFF_NULL
CIFF_MAKEMODEL
CIFF_SHOTINFO
CIFF_WHITEBALANCE
CIFF_SENSORINFO
CIFF_IMAGEINFO
CIFF_DECODERTABLE
CIFF_RAWDATA
CIFF_SUBIFD
CIFF_EXIF
Definition at line 28 of file CiffTag.h.
DEBUG_PRIO
enum rawspeed::DEBUG_PRIO
Enumerator
DEBUG_PRIO_ERROR
DEBUG_PRIO_WARNING
DEBUG_PRIO_INFO
DEBUG_PRIO_EXTRA
Definition at line 37 of file Common.h.
Endianness
enum rawspeed::Endianness strong
Enumerator
little
big
unknown
Definition at line 30 of file Endianness.h.
JpegMarker
enum rawspeed::JpegMarker
Enumerator
M_STUFF
M_SOF0
M_SOF1
M_SOF2
M_SOF3
M_SOF5
M_SOF6
M_SOF7
M_JPG
M_SOF9
M_SOF10
M_SOF11
M_SOF13
M_SOF14
M_SOF15
M_DHT
M_DAC
M_RST0
M_RST1
M_RST2
M_RST3
M_RST4
M_RST5
M_RST6
M_RST7
M_SOI
M_EOI
M_SOS
M_DQT
M_DNL
M_DRI
M_DHP
M_EXP
M_APP0
M_APP1
M_APP2
M_APP3
M_APP4
M_APP5
M_APP6
M_APP7
M_APP8
M_APP9
M_APP10
M_APP11
M_APP12
M_APP13
M_APP14
M_APP15
M_JPG0
M_JPG13
M_COM
M_TEM
M_FILL
Definition at line 41 of file AbstractLJpegDecompressor.h.
RawImageType
enum rawspeed::RawImageType
Enumerator
TYPE_USHORT16
TYPE_FLOAT32
Definition at line 47 of file RawImage.h.
TiffDataType
enum rawspeed::TiffDataType
Enumerator
TIFF_NOTYPE
TIFF_BYTE
TIFF_ASCII
TIFF_SHORT
TIFF_LONG
TIFF_RATIONAL
TIFF_SBYTE
TIFF_UNDEFINED
TIFF_SSHORT
TIFF_SLONG
TIFF_SRATIONAL
TIFF_FLOAT
TIFF_DOUBLE
TIFF_OFFSET
Definition at line 43 of file TiffEntry.h.
TiffTag
enum rawspeed::TiffTag
Enumerator
INTEROPERABILITYINDEX
INTEROPERABILITYVERSION
CANONSHOTINFO
CANONPOWERSHOTG9WB
PANASONIC_ISO_SPEED
PANASONIC_CFAPATTERN
NEWSUBFILETYPE
SUBFILETYPE
PANASONIC_BITSPERSAMPLE
PANASONIC_RAWFORMAT
MAKERNOTE_ALT
IMAGEWIDTH
IMAGELENGTH
BITSPERSAMPLE
COMPRESSION
PHOTOMETRICINTERPRETATION
FILLORDER
DOCUMENTNAME
IMAGEDESCRIPTION
MAKE
MODEL
STRIPOFFSETS
ORIENTATION
SAMPLESPERPIXEL
ROWSPERSTRIP
STRIPBYTECOUNTS
PANASONIC_STRIPOFFSET
XRESOLUTION
YRESOLUTION
PLANARCONFIGURATION
GRAYRESPONSECURVE
T4OPTIONS
T6OPTIONS
RESOLUTIONUNIT
TRANSFERFUNCTION
FUJI_LAYOUT
SOFTWARE
DATETIME
ARTIST
PREDICTOR
WHITEPOINT
PRIMARYCHROMATICITIES
HALFTONEHINTS
TILEWIDTH
TILELENGTH
TILEOFFSETS
TILEBYTECOUNTS
SUBIFDS
INKSET
NUMBEROFINKS
INKNAMES
DOTRANGE
TARGETPRINTER
EXTRASAMPLES
SAMPLEFORMAT
SMINSAMPLEVALUE
SMAXSAMPLEVALUE
TRANSFERRANGE
CLIPPATH
JPEGTABLES
JPEGPROC
JPEGINTERCHANGEFORMAT
JPEGINTERCHANGEFORMATLENGTH
JPEGRESTARTINTERVAL
JPEGLOSSLESSPREDICTORS
JPEGPOINTTRANSFORMS
JPEGQTABLES
JPEGDCTABLES
JPEGACTABLES
YCBCRCOEFFICIENTS
YCBCRSUBSAMPLING
YCBCRPOSITIONING
REFERENCEBLACKWHITE
KODAKWB
EPSONWB
RELATEDIMAGEFILEFORMAT
RELATEDIMAGEWIDTH
RELATEDIMAGELENGTH
OLYMPUSREDMULTIPLIER
OLYMPUSBLUEMULTIPLIER
OLYMPUSIMAGEPROCESSING
FUJIOLDWB
CANONCOLORDATA
SONYGRBGLEVELS
SONYRGGBLEVELS
CFAREPEATPATTERNDIM
CFAPATTERN
BATTERYLEVEL
COPYRIGHT
EXPOSURETIME
FNUMBER
ROTATION
NAVYCOMPRESSION
TILEINDEX
IPTCNAA
LEAFMETADATA
PHOTOSHOPPRIVATE
EXIFIFDPOINTER
INTERCOLORPROFILE
EXPOSUREPROGRAM
SPECTRALSENSITIVITY
GPSINFOIFDPOINTER
ISOSPEEDRATINGS
OECF
EXIFVERSION
DATETIMEORIGINAL
DATETIMEDIGITIZED
COMPONENTSCONFIGURATION
COMPRESSEDBITSPERPIXEL
SHUTTERSPEEDVALUE
APERTUREVALUE
BRIGHTNESSVALUE
EXPOSUREBIASVALUE
MAXAPERTUREVALUE
SUBJECTDISTANCE
METERINGMODE
LIGHTSOURCE
FLASH
FOCALLENGTH
FLASHENERGY_TIFFEP
SPACIALFREQUENCYRESPONSE
NOISE
FOCALPLANEXRESOLUTION_TIFFEP
FOCALPLANEYRESOLUTION_TIFFEP
FOCALPLANERESOLUTIONUNIT_TIFFEP
IMAGENAME
SECURITYCLASSIFICATION
IMAGEHISTORY
SUBJECTAREA
EXPOSUREINDEX_TIFFEP
TIFFEPSTANDARDID
SENSINGMETHOD_TIFFEP
MAKERNOTE
USERCOMMENT
SUBSECTIME
SUBSECTIMEORIGINAL
SUBSECTIMEDIGITIZED
FLASHPIXVERSION
COLORSPACE
PIXELXDIMENSION
PIXELYDIMENSION
RELATEDSOUNDFILE
INTEROPERABILITYIFDPOINTER
SAMSUNG_WB_RGGBLEVELSUNCORRECTED
SAMSUNG_WB_RGGBLEVELSBLACK
FLASHENERGY
SPATIALFREQUENCYRESPONSE
FOCALPLANEXRESOLUTION
FOCALPLANEYRESOLUTION
FOCALPLANERESOLUTIONUNIT
SUBJECTLOCATION
EXPOSUREINDEX
SENSINGMETHOD
FILESOURCE
SCENETYPE
EXIFCFAPATTERN
CUSTOMRENDERED
EXPOSUREMODE
WHITEBALANCE
DIGITALZOOMRATIO
FOCALLENGTHIN35MMFILM
SCENECAPTURETYPE
GAINCONTROL
CONTRAST
SATURATION
SHARPNESS
DEVICESETTINGDESCRIPTION
SUBJECTDISTANCERANGE
IMAGEUNIQUEID
GAMMA
XMP
CANON_UNCOMPRESSED
DNGVERSION
DNGBACKWARDVERSION
UNIQUECAMERAMODEL
LOCALIZEDCAMERAMODEL
CFAPLANECOLOR
CFALAYOUT
LINEARIZATIONTABLE
BLACKLEVELREPEATDIM
BLACKLEVEL
BLACKLEVELDELTAH
BLACKLEVELDELTAV
WHITELEVEL
DEFAULTSCALE
DEFAULTCROPORIGIN
DEFAULTCROPSIZE
COLORMATRIX1
COLORMATRIX2
CAMERACALIBRATION1
CAMERACALIBRATION2
REDUCTIONMATRIX1
REDUCTIONMATRIX2
ANALOGBALANCE
ASSHOTNEUTRAL
ASSHOTWHITEXY
BASELINEEXPOSURE
BASELINENOISE
BASELINESHARPNESS
BAYERGREESPIT
LINEARRESPONSELIMIT
CAMERASERIALNUMBER
LENSINFO
CHROMABLURRADIUS
ANTIALIASSTRENGTH
DNGPRIVATEDATA
MAKERNOTESAFETY
BESTQUALITYSCALE
SHADOWSCALE
RAWDATAUNIQUEID
ORIGINALRAWFILENAME
ORIGINALRAWFILEDATA
ACTIVEAREA
MASKEDAREAS
ASSHOTICCPROFILE
ASSHOTPREPROFILEMATRIX
CURRENTICCPROFILE
CURRENTPREPROFILEMATRIX
COLORIMETRICREFERENCE
KODAKKDCPRIVATEIFD
CAMERACALIBRATIONSIGNATURE
PROFILECALIBRATIONSIGNATURE
EXTRACAMERAPROFILES
ASSHOTPROFILENAME
NOISEREDUCTIONAPPLIED
PROFILENAME
PROFILEHUESATMAPDIMS
PROFILEHUESATMAPDATA1
PROFILEHUESATMAPDATA2
PROFILETONECURVE
PROFILEEMBEDPOLICY
PROFILECOPYRIGHT
FORWARDMATRIX1
FORWARDMATRIX2
PREVIEWAPPLICATIONNAME
PREVIEWAPPLICATIONVERSION
PREVIEWSETTINGSNAME
PREVIEWSETTINGSDIGEST
PREVIEWCOLORSPACE
PREVIEWDATETIME
RAWIMAGEDIGEST
ORIGINALRAWFILEDIGEST
SUBTILEBLOCKSIZE
ROWINTERLEAVEFACTOR
PROFILELOOKTABLEDIMS
PROFILELOOKTABLEDATA
OPCODELIST1
OPCODELIST2
OPCODELIST3
NOISEPROFILE
CANONCR2SLICE
CANON_SRAWTYPE
CANON_SRAWQUALITY
CANON_CAMERA_SETTINGS
CANON_SENSOR_INFO
CANON_RAW_DATA_OFFSET
CALIBRATIONILLUMINANT1
CALIBRATIONILLUMINANT2
SONY_CURVE
SONY_OFFSET
SONY_LENGTH
SONY_KEY
PIMIFDPOINTER
FUJI_RAW_IFD
FUJI_RAWIMAGEFULLWIDTH
FUJI_RAWIMAGEFULLHEIGHT
FUJI_BITSPERSAMPLE
FUJI_STRIPOFFSETS
FUJI_STRIPBYTECOUNTS
FUJI_BLACKLEVEL
FUJI_WB_GRBLEVELS
KODAK_IFD
KODAK_LINEARIZATION
KODAK_KDC_WB
KODAK_KDC_OFFSET
KODAK_KDC_WIDTH
KODAK_KDC_HEIGHT
KODAK_KDC_SENSOR_WIDTH
KODAK_KDC_SENSOR_HEIGHT
KODAK_IFD2
Definition at line 30 of file TiffTag.h.
VC5Tag
enum rawspeed::VC5Tag : int16_t strong
Enumerator
NoTag
ChannelCount
ImageWidth
ImageHeight
LowpassPrecision
SubbandCount
SubbandNumber
Quantization
ChannelNumber
ImageFormat
MaxBitsPerComponent
PatternWidth
PatternHeight
ComponentsPerSample
PrescaleShift
LARGE_CHUNK
SMALL_CHUNK
UniqueImageIdentifier
LargeCodeblock
Optional
Definition at line 45 of file VC5Decompressor.h.
Function Documentation
__attribute__() [1/9]
rawspeed::__attribute__ ((always_inline)) inline
Definition at line 70 of file OlympusDecompressor.cpp.
__attribute__() [2/9]
template<typename Tr , typename Tv > constexpr bool rawspeed::__attribute__ ((const)) const & inline constexpr
__attribute__() [3/9]
template<typename T > constexpr bool rawspeed::__attribute__ ((const)) const & inline constexpr
__attribute__() [4/9]
constexpr size_t rawspeed::__attribute__ ((const)) inline constexpr
Definition at line 107 of file CrwDecoder.cpp.
__attribute__() [5/9]
template<typename T , size_t alignment, bool doRoundUp = false> T* rawspeed::__attribute__ ((malloc, warn_unused_result)) inline
__attribute__() [6/9]
template<typename T , size_t alignment, typename T2 , bool doRoundUp = false> T* rawspeed::__attribute__ ((malloc, warn_unused_result)) inline
Definition at line 83 of file Memory.h.
__attribute__() [7/9]
template<typename T , size_t alignment> T* rawspeed::__attribute__ ((malloc, warn_unused_result, alloc_size(1))) inline
Definition at line 43 of file Memory.h.
__attribute__() [8/9]
template<typename T > void RAWSPEED_UNLIKELY_FUNCTION RAWSPEED_NOINLINE rawspeed::__attribute__ ((noreturn, format(printf, 1, 2))) const
__attribute__() [9/9]
constexpr size_t std::enable_if<std::is_pointer<T>::value>::type T2 bool rawspeed::__attribute__ ((pure)) const
Definition at line 57 of file DngDecoder.cpp.
alignedFree()
void rawspeed::alignedFree (void * ptr)
Definition at line 86 of file Memory.cpp.
Referenced by rawspeed::RawImageData::destroyData().
alignedFreeConstPtr()
void rawspeed::alignedFreeConstPtr (const void * ptr)
Definition at line 96 of file Memory.cpp.
Referenced by rawspeed::Buffer::Buffer().
alignedMalloc()
void * rawspeed::alignedMalloc (size_t size, size_t alignment)
Definition at line 45 of file Memory.cpp.
alignedMalloc< T, alignment >()
return rawspeed::alignedMalloc< T, alignment > (size)
alloc_align()
void rawspeed::alloc_align (2)
alloc_size()
void rawspeed::alloc_size (1)
assert() [1/2]
rawspeed::assert ()
assert() [2/2]
rawspeed::assert (pos >=r. begin())
bitwidth()
template<class T > constexpr unsigned rawspeed::bitwidth (T unused = {}) inline constexpr
Definition at line 117 of file Common.h.
CAPABILITY()
class rawspeed::CAPABILITY ("mutex") final
Definition at line 66 of file Mutex.h.
References rawspeed::BitStreamTraits< BitPumpMSB32 >::canUseWithHuffmanTable.
copyPixels()
void void rawspeed::copyPixels (uint8_t * dest, int dstPitch, const uint8_t * src, int srcPitch, int rowSize, int height) inline
Definition at line 47 of file Common.h.
Referenced by rawspeed::RawImageData::blitFrom(), and rawspeed::UncompressedDecompressor::readUncompressedRaw().
deprecated()
void rawspeed::deprecated ("use alignedMalloc<alignment>(size)")
end()
return r rawspeed::end ()
extendBinaryFloatingPoint()
template<typename NarrowType , typename WideType > uint32_t rawspeed::extendBinaryFloatingPoint (uint32_t narrow) inline
Definition at line 105 of file FloatingPoint.h.
fp16ToFloat()
uint32_t rawspeed::fp16ToFloat (uint16_t fp16) inline
Definition at line 145 of file FloatingPoint.h.
Referenced by rawspeed::UncompressedDecompressor::readUncompressedRaw().
fp24ToFloat()
uint32_t rawspeed::fp24ToFloat (uint32_t fp24) inline
Definition at line 151 of file FloatingPoint.h.
Referenced by rawspeed::UncompressedDecompressor::readUncompressedRaw().
getBE()
template<typename T > T rawspeed::getBE (const void * data) inline
Definition at line 118 of file Endianness.h.
References getHostEndianness(), and little.
getByteSwapped() [1/8]
template<typename T > T rawspeed::getByteSwapped (const void * data, bool bswap) inline
Definition at line 102 of file Endianness.h.
getByteSwapped() [2/8]
double rawspeed::getByteSwapped (double d) inline
Definition at line 94 of file Endianness.h.
References getByteSwapped().
getByteSwapped() [3/8]
float rawspeed::getByteSwapped (float f) inline
Definition at line 87 of file Endianness.h.
References getByteSwapped().
getByteSwapped() [4/8]
int16_t rawspeed::getByteSwapped (int16_t v) inline
Definition at line 69 of file Endianness.h.
getByteSwapped() [5/8]
int32_t rawspeed::getByteSwapped (int32_t v) inline
Definition at line 75 of file Endianness.h.
getByteSwapped() [6/8]
uint16_t rawspeed::getByteSwapped (uint16_t v) inline
Definition at line 72 of file Endianness.h.
getByteSwapped() [7/8]
uint32_t rawspeed::getByteSwapped (uint32_t v) inline
Definition at line 78 of file Endianness.h.
Referenced by getByteSwapped().
getByteSwapped() [8/8]
uint64_t rawspeed::getByteSwapped (uint64_t v) inline
Definition at line 81 of file Endianness.h.
Referenced by getByteSwapped().
getHostEndianness()
Endianness rawspeed::getHostEndianness () inline
Definition at line 46 of file Endianness.h.
References little.
Referenced by rawspeed::DataBuffer::get(), getBE(), getLE(), and rawspeed::UncompressedDecompressor::readUncompressedRaw().
getHostEndiannessRuntime()
Endianness rawspeed::getHostEndiannessRuntime () inline
Definition at line 32 of file Endianness.h.
References big, little, and unknown.
getId()
static CameraId rawspeed::getId (const string & make, const string & model, const string & mode) inline static
Definition at line 72 of file CameraMetaData.cpp.
getLE()
template<typename T > T rawspeed::getLE (const void * data) inline
Definition at line 122 of file Endianness.h.
References big, and getHostEndianness().
getTiffByteOrder()
Endianness rawspeed::getTiffByteOrder (const ByteStream & bs, uint32_t pos, const char * context = "") inline
Definition at line 142 of file TiffIFD.h.
Referenced by rawspeed::TiffIFD::parseMakerNote().
getU16BE()
uint16_t rawspeed::getU16BE (const void * data) inline
Definition at line 126 of file Endianness.h.
getU16LE()
uint16_t rawspeed::getU16LE (const void * data) inline
Definition at line 127 of file Endianness.h.
getU32BE()
uint32_t rawspeed::getU32BE (const void * data) inline
Definition at line 128 of file Endianness.h.
getU32LE()
uint32_t rawspeed::getU32LE (const void * data) inline
Definition at line 129 of file Endianness.h.
if() [1/3]
size* rawspeed::if (doRoundUp)
if() [2/3]
rawspeed::if (lhs. begin() = =rhs.begin())
if() [3/3]
rawspeed::if (roundDown)
is()
bool rawspeed::is (VC5Tag LHS, VC5Tag RHS) inline
Definition at line 79 of file VC5Decompressor.h.
References operator&().
Referenced by rawspeed::VC5Decompressor::parseVC5().
isPowerOfTwo()
template<typename T > constexpr bool rawspeed::isPowerOfTwo (T val) inline constexpr
Definition at line 61 of file Common.h.
matches()
bool rawspeed::matches (VC5Tag LHS, VC5Tag RHS) inline
Definition at line 75 of file VC5Decompressor.h.
References NoTag, and operator&().
Referenced by rawspeed::VC5Decompressor::parseVC5().
operator!=() [1/3]
bool rawspeed::operator!= (const AbstractHuffmanTable & lhs, const AbstractHuffmanTable & rhs)
Definition at line 44 of file AbstractHuffmanTableTest.cpp.
operator!=() [2/3]
bool rawspeed::operator!= (const AbstractHuffmanTable::CodeSymbol & lhs, const AbstractHuffmanTable::CodeSymbol & rhs)
Definition at line 57 of file AbstractHuffmanTableTest.cpp.
operator!=() [3/3]
template<typename T0 , typename A0 , typename T1 , typename A1 > bool rawspeed::operator!= (DefaultInitAllocatorAdaptor< T0, A0 > const & x, DefaultInitAllocatorAdaptor< T1, A1 > const & y) noexcept
Definition at line 97 of file DefaultInitAllocatorAdaptor.h.
operator&() [1/2]
constexpr bool rawspeed::operator& (SamsungV2Decompressor::OptFlags lhs, SamsungV2Decompressor::OptFlags rhs) constexpr
Definition at line 63 of file SamsungV2Decompressor.cpp.
References rawspeed::SamsungV2Decompressor::NONE, and operator&().
Referenced by operator&().
operator&() [2/2]
VC5Tag rawspeed::operator& (VC5Tag LHS, VC5Tag RHS) inline
Definition at line 70 of file VC5Decompressor.h.
References operator&().
Referenced by is(), matches(), and operator&().
operator-()
VC5Tag rawspeed::operator- (VC5Tag tag) inline
Definition at line 83 of file VC5Decompressor.h.
References operator-().
Referenced by operator-(), and rawspeed::VC5Decompressor::parseVC5().
operator<<() [1/4]
::std::ostream& rawspeed::operator<< (::std::ostream & os, const AbstractHuffmanTable::CodeSymbol s)
Definition at line 49 of file AbstractHuffmanTableTest.cpp.
operator<<() [2/4]
::std::ostream& rawspeed::operator<< (::std::ostream & os, const CFAColor c)
Definition at line 44 of file ColorFilterArrayTest.cpp.
operator<<() [3/4]
std::ostream & rawspeed::operator<< (::std::ostream & os, const iPoint2D p)
Definition at line 40 of file PointTest.cpp.
operator<<() [4/4]
template<typename T > ::std::ostream& rawspeed::operator<< (::std::ostream & os, const Range< T > & r)
Definition at line 33 of file RangeTest.h.
operator==() [1/2]
bool rawspeed::operator== (const AbstractHuffmanTable::CodeSymbol & lhs, const AbstractHuffmanTable::CodeSymbol & rhs) inline
Definition at line 275 of file AbstractHuffmanTable.h.
References rawspeed::AbstractHuffmanTable::CodeSymbol::code, and rawspeed::AbstractHuffmanTable::CodeSymbol::code_len.
operator==() [2/2]
template<typename T0 , typename A0 , typename T1 , typename A1 > bool rawspeed::operator== (DefaultInitAllocatorAdaptor< T0, A0 > const & x, DefaultInitAllocatorAdaptor< T1, A1 > const & y) noexcept
Definition at line 91 of file DefaultInitAllocatorAdaptor.h.
operator|()
constexpr SamsungV2Decompressor::OptFlags rawspeed::operator| (SamsungV2Decompressor::OptFlags lhs, SamsungV2Decompressor::OptFlags rhs) constexpr
Definition at line 54 of file SamsungV2Decompressor.cpp.
References operator|().
Referenced by operator|().
ParseChecksumFileContent()
std::vector< ChecksumFileEntry > rawspeed::ParseChecksumFileContent (const std::string & ChecksumFileContent, const std::string & RootDir)
Definition at line 65 of file ChecksumFile.cpp.
RangeContains()
return rawspeed::RangeContains (ordered. first, ordered.second. begin())
ReadChecksumFile()
std::vector< ChecksumFileEntry > rawspeed::ReadChecksumFile (const std::string & RootDir, const std::string & ChecksumFileBasename)
Definition at line 82 of file ChecksumFile.cpp.
T()
throw rawspeed::T (buf. data())
toDcrawColor()
static uint32_t rawspeed::toDcrawColor (CFAColor c) static
Definition at line 185 of file ColorFilterArray.cpp.
References CFA_BLUE, CFA_CYAN, CFA_FUJI_GREEN, CFA_GREEN, CFA_MAGENTA, CFA_RED, CFA_YELLOW, and rawspeed::ColorFilterArray::colorToString().
Referenced by rawspeed::ColorFilterArray::getDcrawFilter().
UncompressedDecompressor::decode12BitRaw< Endianness::big, false, false >()
template void rawspeed::UncompressedDecompressor::decode12BitRaw< Endianness::big, false, false > (uint32_t w, uint32_t h)
UncompressedDecompressor::decode12BitRaw< Endianness::big, false, true >()
template void rawspeed::UncompressedDecompressor::decode12BitRaw< Endianness::big, false, true > (uint32_t w, uint32_t h)
UncompressedDecompressor::decode12BitRaw< Endianness::big, true, false >()
template void rawspeed::UncompressedDecompressor::decode12BitRaw< Endianness::big, true, false > (uint32_t w, uint32_t h)
UncompressedDecompressor::decode12BitRaw< Endianness::little, false, false >()
template void rawspeed::UncompressedDecompressor::decode12BitRaw< Endianness::little, false, false > (uint32_t w, uint32_t h)
UncompressedDecompressor::decode12BitRaw< Endianness::little, false, true >()
template void rawspeed::UncompressedDecompressor::decode12BitRaw< Endianness::little, false, true > (uint32_t w, uint32_t h)
UncompressedDecompressor::decode12BitRawUnpackedLeftAligned< Endianness::big >()
template void rawspeed::UncompressedDecompressor::decode12BitRawUnpackedLeftAligned< Endianness::big > (uint32_t w, uint32_t h)
UncompressedDecompressor::decodeRawUnpacked< 12, Endianness::big >()
template void rawspeed::UncompressedDecompressor::decodeRawUnpacked< 12, Endianness::big > (uint32_t w, uint32_t h)
UncompressedDecompressor::decodeRawUnpacked< 12, Endianness::little >()
template void rawspeed::UncompressedDecompressor::decodeRawUnpacked< 12, Endianness::little > (uint32_t w, uint32_t h)
UncompressedDecompressor::decodeRawUnpacked< 14, Endianness::big >()
template void rawspeed::UncompressedDecompressor::decodeRawUnpacked< 14, Endianness::big > (uint32_t w, uint32_t h)
UncompressedDecompressor::decodeRawUnpacked< 16, Endianness::big >()
template void rawspeed::UncompressedDecompressor::decodeRawUnpacked< 16, Endianness::big > (uint32_t w, uint32_t h)
UncompressedDecompressor::decodeRawUnpacked< 16, Endianness::little >()
template void rawspeed::UncompressedDecompressor::decodeRawUnpacked< 16, Endianness::little > (uint32_t w, uint32_t h)
unroll_loop()
template<size_t N, typename Lambda > void rawspeed::unroll_loop (const Lambda & f) inline
Definition at line 257 of file Common.h.
va_end()
rawspeed::va_end (val)
va_start()
rawspeed::va_start (val , fmt)
vsnprintf()
rawspeed::vsnprintf (buf. data(), sizeof(buf) , fmt , val)
widenFileName()
std::wstring rawspeed::widenFileName (const char * fileName) inline
Definition at line 35 of file FileIO.h.
writeLog() [1/2]
void rawspeed::writeLog (DEBUG_PRIO priority, const char * format, ...)
Definition at line 38 of file Common.cpp.
References DEBUG_PRIO_INFO.
Referenced by rawspeed::RawImage::create(), rawspeed::ColorFilterArray::getDcrawFilter(), rawspeed::RawspeedException::log(), rawspeed::NikonDecompressor::NikonDecompressor(), rawspeed::RawImageDataFloat::scaleBlackWhite(), rawspeed::ColorFilterArray::shiftDown(), and rawspeed::ColorFilterArray::shiftLeft().
writeLog() [2/2]
rawspeed::writeLog (DEBUG_PRIO_EXTRA , "EXCEPTION: %s" , buf. data())
Variable Documentation
__attribute__
TiffEntry * rawspeed::__attribute__ inline constexpr
Definition at line 242 of file RawImage.cpp.
buf
void RAWSPEED_UNLIKELY_FUNCTION RAWSPEED_NOINLINE static char rawspeed::buf[bufSize] static
Initial value:
{
  static constexpr size_t bufSize = 8192
Definition at line 37 of file RawspeedException.h.
CiffTagsWeCareAbout
constexpr std::initializer_list<CiffTag> rawspeed::CiffTagsWeCareAbout static constexpr
Initial value:
= {
    CIFF_DECODERTABLE,
    CIFF_MAKEMODEL,
    CIFF_RAWDATA,
    CIFF_SENSORINFO,
    CIFF_SHOTINFO,
    CIFF_WHITEBALANCE,
    static_cast<CiffTag>(0x0032),
    static_cast<CiffTag>(0x102c),
}
Definition at line 41 of file CiffTag.h.
div
constexpr size_t size_t rawspeed::div
Initial value:
{
  return (value != 0) ? (1 + ((value - 1) / div)) : 0
Definition at line 88 of file Common.h.
list
constexpr size_t std::enable_if<std::is_pointer<T>::value>::type T2 bool const std::initializer_list<T2>& rawspeed::list
Initial value:
{
  return std::any_of(list.begin(), list.end(),
                     [value](const T2& t) { return t == value; })
Definition at line 112 of file Common.h.
Referenced by sphinx-pyexec.ExecDirective::execute_code().
MAX_NUM_PRESCALE
const int rawspeed::MAX_NUM_PRESCALE = 8
Definition at line 41 of file VC5Decompressor.h.
multiple
constexpr size_t rawspeed::multiple
Initial value:
{
  return roundToMultiple(value, multiple, true)
Definition at line 66 of file Common.h.
nBits
constexpr unsigned int rawspeed::nBits
Definition at line 124 of file Common.h.
ordered
const std::pair<const T&, const T&> rawspeed::ordered
Initial value:
=
      std::minmax(lhs, rhs, [](const T& r0, const T& r1) {
        assert(r0.begin() != r1.begin());
        return r0.begin() < r1.begin();
      })
Definition at line 65 of file Range.h.
pos
constexpr bool Tv rawspeed::pos
Initial value:
{
  if (pos < r.begin())
    return false
Definition at line 48 of file Range.h.
rhs
constexpr bool const T& rawspeed::rhs
Initial value:
{
  if (&lhs == &rhs)
    return true
Definition at line 58 of file Range.h.
roundDown
constexpr size_t size_t bool rawspeed::roundDown
Initial value:
{
  if ((multiple == 0) || (value % multiple == 0))
    return value
Definition at line 66 of file Common.h.
roundedDown
size_t rawspeed::roundedDown = value - (value % multiple)
Definition at line 70 of file Common.h.
size
T size_t rawspeed::size
Initial value:
{
  if (size && nmemb > SIZE_MAX / size)
    return nullptr
Definition at line 68 of file Memory.h.
TABLE_MAX_ELTS
constexpr int rawspeed::TABLE_MAX_ELTS = std::numeric_limits<uint16_t>::max() + 1 constexpr
Definition at line 32 of file TableLookUp.cpp.
Referenced by rawspeed::TableLookUp::setTable().
TABLE_SIZE
constexpr int rawspeed::TABLE_SIZE = TABLE_MAX_ELTS * 2 constexpr
Definition at line 33 of file TableLookUp.cpp.
Referenced by rawspeed::TableLookUp::setTable().
val
va_list rawspeed::val
Definition at line 49 of file RawspeedException.h.
warn_unused_result
void rawspeed::warn_unused_result
Definition at line 38 of file Memory.h.