RawSpeed: rawspeed::RawImageWorker Class Reference
rawspeed::RawImageWorker Class Reference
#include "common/RawImage.h"
Public Types
enum RawImageWorkerTask { SCALE_VALUES = 1, FIX_BAD_PIXELS = 2, APPLY_LOOKUP = 3 | 0x1000, FULL_IMAGE = 0x1000 }
Public Member Functions
RawImageWorker (RawImageData *img, RawImageWorkerTask task, int start_y, int end_y) noexcept
Private Member Functions
void performTask () noexcept
Private Attributes
RawImageData * data
RawImageWorkerTask task
int start_y
int end_y
Detailed Description
Definition at line 49 of file RawImage.h.
Member Enumeration Documentation
RawImageWorkerTask
enum rawspeed::RawImageWorker::RawImageWorkerTask
Enumerator
SCALE_VALUES
FIX_BAD_PIXELS
APPLY_LOOKUP
FULL_IMAGE
Definition at line 51 of file RawImage.h.
Constructor & Destructor Documentation
RawImageWorker()
rawspeed::RawImageWorker::RawImageWorker (RawImageData * img, RawImageWorkerTask task, int start_y, int end_y) noexcept
Definition at line 526 of file RawImage.cpp.
References data, end_y, performTask(), start_y, and task.
Referenced by rawspeed::RawImageData::startWorker().
Member Function Documentation
performTask()
void rawspeed::RawImageWorker::performTask () private noexcept
Definition at line 532 of file RawImage.cpp.
References APPLY_LOOKUP, data, rawspeed::RawImageData::doLookup(), end_y, FIX_BAD_PIXELS, rawspeed::RawImageData::fixBadPixelsThread(), SCALE_VALUES, rawspeed::RawImageData::scaleValues(), start_y, and task.
Referenced by RawImageWorker().
Member Data Documentation
data
RawImageData* rawspeed::RawImageWorker::data private
Definition at line 56 of file RawImage.h.
Referenced by performTask(), and RawImageWorker().
end_y
int rawspeed::RawImageWorker::end_y private
Definition at line 59 of file RawImage.h.
Referenced by performTask(), and RawImageWorker().
start_y
int rawspeed::RawImageWorker::start_y private
Definition at line 58 of file RawImage.h.
Referenced by performTask(), and RawImageWorker().
task
RawImageWorkerTask rawspeed::RawImageWorker::task private
Definition at line 57 of file RawImage.h.
Referenced by performTask(), and RawImageWorker().
The documentation for this class was generated from the following files:
librawspeed/common/RawImage.h
librawspeed/common/RawImage.cpp