RawSpeed: rawspeed::DngOpcodes::DeltaRowOrColBase Class Reference
rawspeed::DngOpcodes::DeltaRowOrColBase Class Reference abstract
Classes
struct SelectX
struct SelectY
Public Member Functions
virtual void setup (const RawImage &ri)
virtual void apply (const RawImage &ri)=0
Protected Member Functions
DeltaRowOrColBase (const RawImage &ri, ByteStream *bs)
template<typename T , typename OP >
void applyOP (const RawImage &ri, OP op)
const iRectangle2D & __attribute__ ((pure)) getRoi() const
Private Attributes
uint32_t firstPlane
uint32_t planes
uint32_t rowPitch
uint32_t colPitch
iRectangle2D roi
Detailed Description
Definition at line 334 of file DngOpcodes.cpp.
Constructor & Destructor Documentation
DeltaRowOrColBase()
rawspeed::DngOpcodes::DeltaRowOrColBase::DeltaRowOrColBase (const RawImage & ri, ByteStream * bs) inline protected
Definition at line 345 of file DngOpcodes.cpp.
References rawspeed::DngOpcodes::PixelOpcode::PixelOpcode().
Member Function Documentation
__attribute__()
const iRectangle2D& rawspeed::DngOpcodes::ROIOpcode::__attribute__ ((pure)) const inline protected inherited
Definition at line 129 of file DngOpcodes.cpp.
References rawspeed::DngOpcodes::ROIOpcode::roi.
Referenced by rawspeed::DngOpcodes::DummyROIOpcode::__attribute__(), rawspeed::DngOpcodes::TrimBounds::apply(), rawspeed::DngOpcodes::PixelOpcode::applyOP(), rawspeed::DngOpcodes::DeltaRowOrCol< S >::DeltaRowOrCol(), and rawspeed::DngOpcodes::PixelOpcode::PixelOpcode().
apply()
virtual void rawspeed::DngOpcodes::DngOpcode::apply (const RawImage & ri) pure virtual inherited
Implemented in rawspeed::DngOpcodes::ScalePerRowOrCol< S >, rawspeed::DngOpcodes::OffsetPerRowOrCol< S >, rawspeed::DngOpcodes::LookupOpcode, rawspeed::DngOpcodes::TrimBounds, rawspeed::DngOpcodes::FixBadPixelsList, rawspeed::DngOpcodes::FixBadPixelsConstant, and rawspeed::DngOpcodes::DummyROIOpcode.
applyOP()
template<typename T , typename OP > void rawspeed::DngOpcodes::PixelOpcode::applyOP (const RawImage & ri, OP op) inline protected inherited
Definition at line 248 of file DngOpcodes.cpp.
References rawspeed::DngOpcodes::ROIOpcode::__attribute__(), rawspeed::DngOpcodes::PixelOpcode::colPitch, rawspeed::DngOpcodes::PixelOpcode::firstPlane, rawspeed::iRectangle2D::getBottom(), rawspeed::RawImageData::getCpp(), rawspeed::RawImageData::getData(), rawspeed::iRectangle2D::getLeft(), rawspeed::iRectangle2D::getRight(), rawspeed::iRectangle2D::getTop(), rawspeed::RawImage::operator->(), rawspeed::DngOpcodes::PixelOpcode::planes, and rawspeed::DngOpcodes::PixelOpcode::rowPitch.
setup()
virtual void rawspeed::DngOpcodes::DngOpcode::setup (const RawImage & ri) inline virtual inherited
Reimplemented in rawspeed::DngOpcodes::DeltaRowOrCol< S >, rawspeed::DngOpcodes::LookupOpcode, and rawspeed::DngOpcodes::FixBadPixelsConstant.
Definition at line 54 of file DngOpcodes.cpp.
Referenced by rawspeed::DngOpcodes::DeltaRowOrCol< S >::setup().
Member Data Documentation
colPitch
uint32_t rawspeed::DngOpcodes::PixelOpcode::colPitch private inherited
Definition at line 222 of file DngOpcodes.cpp.
Referenced by rawspeed::DngOpcodes::PixelOpcode::applyOP(), and rawspeed::DngOpcodes::PixelOpcode::PixelOpcode().
firstPlane
uint32_t rawspeed::DngOpcodes::PixelOpcode::firstPlane private inherited
Definition at line 219 of file DngOpcodes.cpp.
Referenced by rawspeed::DngOpcodes::PixelOpcode::applyOP(), and rawspeed::DngOpcodes::PixelOpcode::PixelOpcode().
planes
uint32_t rawspeed::DngOpcodes::PixelOpcode::planes private inherited
Definition at line 220 of file DngOpcodes.cpp.
Referenced by rawspeed::DngOpcodes::PixelOpcode::applyOP(), and rawspeed::DngOpcodes::PixelOpcode::PixelOpcode().
roi
iRectangle2D rawspeed::DngOpcodes::ROIOpcode::roi private inherited
Definition at line 99 of file DngOpcodes.cpp.
Referenced by rawspeed::DngOpcodes::ROIOpcode::__attribute__(), and rawspeed::DngOpcodes::ROIOpcode::ROIOpcode().
rowPitch
uint32_t rawspeed::DngOpcodes::PixelOpcode::rowPitch private inherited
Definition at line 221 of file DngOpcodes.cpp.
Referenced by rawspeed::DngOpcodes::PixelOpcode::applyOP(), and rawspeed::DngOpcodes::PixelOpcode::PixelOpcode().
The documentation for this class was generated from the following file:
librawspeed/common/DngOpcodes.cpp