RawSpeed: rawspeed::ColorFilterArray Class Reference
rawspeed::ColorFilterArray Class Reference
#include "metadata/ColorFilterArray.h"
Public Member Functions
ColorFilterArray ()=default
ColorFilterArray (const iPoint2D &size)
void setSize (const iPoint2D &size)
void setColorAt (iPoint2D pos, CFAColor c)
void setCFA (iPoint2D size,...)
void shiftLeft (int n=1)
void shiftDown (int n=1)
CFAColor getColorAt (int x, int y) const
uint32_t getDcrawFilter () const
std::string asString () const
iPoint2D getSize () const
Static Public Member Functions
static std::string colorToString (CFAColor c)
static uint32_t __attribute__ ((const)) shiftDcrawFilter(uint32_t filter
Public Attributes
static uint32_t int x
static uint32_t int int y
Static Protected Attributes
static const std::map< CFAColor, std::string > color2String
Private Attributes
std::vector< CFAColor > cfa
iPoint2D size
Detailed Description
Definition at line 46 of file ColorFilterArray.h.
Constructor & Destructor Documentation
ColorFilterArray() [1/2]
rawspeed::ColorFilterArray::ColorFilterArray () default
ColorFilterArray() [2/2]
rawspeed::ColorFilterArray::ColorFilterArray (const iPoint2D & size) explicit
Definition at line 40 of file ColorFilterArray.cpp.
References setSize().
Referenced by rawspeed_test::TEST().
Member Function Documentation
__attribute__()
static uint32_t rawspeed::ColorFilterArray::__attribute__ ((const)) static
asString()
string rawspeed::ColorFilterArray::asString () const
Definition at line 122 of file ColorFilterArray.cpp.
References colorToString(), getColorAt(), size, rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
colorToString()
string rawspeed::ColorFilterArray::colorToString (CFAColor c) static
Definition at line 168 of file ColorFilterArray.cpp.
Referenced by asString(), and rawspeed::toDcrawColor().
getColorAt()
CFAColor rawspeed::ColorFilterArray::getColorAt (int x, int y) const
Definition at line 62 of file ColorFilterArray.cpp.
References size, rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
Referenced by asString(), and getDcrawFilter().
getDcrawFilter()
uint32_t rawspeed::ColorFilterArray::getDcrawFilter () const
Definition at line 199 of file ColorFilterArray.cpp.
References rawspeed::DEBUG_PRIO_EXTRA, getColorAt(), size, rawspeed::toDcrawColor(), rawspeed::writeLog(), rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
getSize()
iPoint2D rawspeed::ColorFilterArray::getSize () const inline
Definition at line 64 of file ColorFilterArray.h.
References size.
setCFA()
void rawspeed::ColorFilterArray::setCFA (iPoint2D size, ...)
Definition at line 74 of file ColorFilterArray.cpp.
References rawspeed::iPoint2D::__attribute__(), rawspeed::iPoint2D::operator!=(), setSize(), and size.
setColorAt()
void rawspeed::ColorFilterArray::setColorAt (iPoint2D pos, CFAColor c)
Definition at line 177 of file ColorFilterArray.cpp.
Referenced by CreateCFA().
setSize()
void rawspeed::ColorFilterArray::setSize (const iPoint2D & size)
Definition at line 44 of file ColorFilterArray.cpp.
References rawspeed::iPoint2D::__attribute__(), and size.
Referenced by ColorFilterArray(), CreateCFA(), and setCFA().
shiftDown()
void rawspeed::ColorFilterArray::shiftDown (int n = 1)
Definition at line 105 of file ColorFilterArray.cpp.
References rawspeed::DEBUG_PRIO_EXTRA, size, rawspeed::writeLog(), rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
shiftLeft()
void rawspeed::ColorFilterArray::shiftLeft (int n = 1)
Definition at line 87 of file ColorFilterArray.cpp.
References rawspeed::DEBUG_PRIO_EXTRA, size, rawspeed::writeLog(), rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
Member Data Documentation
cfa
std::vector<CFAColor> rawspeed::ColorFilterArray::cfa private
Definition at line 48 of file ColorFilterArray.h.
color2String
const map< CFAColor, string > rawspeed::ColorFilterArray::color2String static protected
Initial value:
= {
    {CFA_RED, "RED"},         {CFA_GREEN, "GREEN"},
    {CFA_BLUE, "BLUE"},       {CFA_CYAN, "CYAN"},
    {CFA_MAGENTA, "MAGENTA"}, {CFA_YELLOW, "YELLOW"},
    {CFA_WHITE, "WHITE"},     {CFA_FUJI_GREEN, "FUJIGREEN"},
    {CFA_UNKNOWN, "UNKNOWN"}}
Definition at line 71 of file ColorFilterArray.h.
size
iPoint2D rawspeed::ColorFilterArray::size private
Definition at line 49 of file ColorFilterArray.h.
Referenced by asString(), getColorAt(), getDcrawFilter(), getSize(), setCFA(), setSize(), shiftDown(), and shiftLeft().
x
uint32_t int rawspeed::ColorFilterArray::x
Definition at line 68 of file ColorFilterArray.h.
y
uint32_t int int rawspeed::ColorFilterArray::y
Definition at line 68 of file ColorFilterArray.h.
The documentation for this class was generated from the following files:
librawspeed/metadata/ColorFilterArray.h
librawspeed/metadata/ColorFilterArray.cpp