RawSpeed: rawspeed::DngOpcodes::ROIOpcode Class Reference
rawspeed::DngOpcodes::ROIOpcode Class Reference abstract
Public Member Functions
virtual void setup (const RawImage &ri)
virtual void apply (const RawImage &ri)=0
Protected Member Functions
ROIOpcode (const RawImage &ri, ByteStream *bs, bool minusOne)
const iRectangle2D & __attribute__ ((pure)) getRoi() const
Private Attributes
iRectangle2D roi
Detailed Description
Definition at line 98 of file DngOpcodes.cpp.
Constructor & Destructor Documentation
ROIOpcode()
rawspeed::DngOpcodes::ROIOpcode::ROIOpcode (const RawImage & ri, ByteStream * bs, bool minusOne) inline explicit protected
Definition at line 102 of file DngOpcodes.cpp.
References rawspeed::RawImageData::dim, rawspeed::ByteStream::getU32(), rawspeed::iPoint2D::iPoint2D(), rawspeed::iRectangle2D::iRectangle2D(), rawspeed::iRectangle2D::isPointInsideInclusive(), rawspeed::iRectangle2D::isThisInside(), rawspeed::RawImage::operator->(), rawspeed::iPoint2D::operator>=(), roi, rawspeed::iRectangle2D::setBottomRightAbsolute(), rawspeed::iRectangle2D::setTopLeft(), rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
Referenced by rawspeed::DngOpcodes::DummyROIOpcode::DummyROIOpcode(), rawspeed::DngOpcodes::PixelOpcode::PixelOpcode(), and rawspeed::DngOpcodes::TrimBounds::TrimBounds().
Member Function Documentation
__attribute__()
const iRectangle2D& rawspeed::DngOpcodes::ROIOpcode::__attribute__ ((pure)) const inline protected
Definition at line 129 of file DngOpcodes.cpp.
References roi.
Referenced by rawspeed::DngOpcodes::DummyROIOpcode::__attribute__(), rawspeed::DngOpcodes::TrimBounds::apply(), rawspeed::DngOpcodes::PixelOpcode::applyOP(), rawspeed::DngOpcodes::DeltaRowOrCol< S >::DeltaRowOrCol(), and rawspeed::DngOpcodes::PixelOpcode::PixelOpcode().
apply()
virtual void rawspeed::DngOpcodes::DngOpcode::apply (const RawImage & ri) pure virtual inherited
Implemented in rawspeed::DngOpcodes::ScalePerRowOrCol< S >, rawspeed::DngOpcodes::OffsetPerRowOrCol< S >, rawspeed::DngOpcodes::LookupOpcode, rawspeed::DngOpcodes::TrimBounds, rawspeed::DngOpcodes::FixBadPixelsList, rawspeed::DngOpcodes::FixBadPixelsConstant, and rawspeed::DngOpcodes::DummyROIOpcode.
setup()
virtual void rawspeed::DngOpcodes::DngOpcode::setup (const RawImage & ri) inline virtual inherited
Reimplemented in rawspeed::DngOpcodes::DeltaRowOrCol< S >, rawspeed::DngOpcodes::LookupOpcode, and rawspeed::DngOpcodes::FixBadPixelsConstant.
Definition at line 54 of file DngOpcodes.cpp.
Referenced by rawspeed::DngOpcodes::DeltaRowOrCol< S >::setup().
Member Data Documentation
roi
iRectangle2D rawspeed::DngOpcodes::ROIOpcode::roi private
Definition at line 99 of file DngOpcodes.cpp.
Referenced by __attribute__(), and ROIOpcode().
The documentation for this class was generated from the following file:
librawspeed/common/DngOpcodes.cpp