RawSpeed: rawspeed::DngOpcodes::ScalePerRowOrCol< S > Class Template Reference
rawspeed::DngOpcodes::ScalePerRowOrCol< S > Class Template Reference final
#include "common/DngOpcodes.h"
Public Member Functions
ScalePerRowOrCol (const RawImage &ri, ByteStream *bs)
void apply (const RawImage &ri) override
void setup (const RawImage &ri) override
Protected Member Functions
template<typename T , typename OP >
void applyOP (const RawImage &ri, OP op)
const iRectangle2D & __attribute__ ((pure)) getRoi() const
Protected Attributes
const float f2iScale
vector< float > deltaF
vector< int > deltaI
Private Member Functions
bool valueIsOk (float value) final
Private Attributes
const double maxLimit
uint32_t firstPlane
uint32_t planes
uint32_t rowPitch
uint32_t colPitch
iRectangle2D roi
Static Private Attributes
static constexpr const double minLimit = 0.0
static constexpr int rounding = 512
Detailed Description
template<typename S>
class rawspeed::DngOpcodes::ScalePerRowOrCol< S >
Definition at line 434 of file DngOpcodes.cpp.
Constructor & Destructor Documentation
ScalePerRowOrCol()
template<typename S > rawspeed::DngOpcodes::ScalePerRowOrCol< S >::ScalePerRowOrCol (const RawImage & ri, ByteStream * bs) inline explicit
Definition at line 450 of file DngOpcodes.cpp.
References rawspeed::DngOpcodes::ScalePerRowOrCol< S >::maxLimit, and rawspeed::DngOpcodes::ScalePerRowOrCol< S >::rounding.
Member Function Documentation
__attribute__()
const iRectangle2D& rawspeed::DngOpcodes::ROIOpcode::__attribute__ ((pure)) const inline protected inherited
Definition at line 129 of file DngOpcodes.cpp.
References rawspeed::DngOpcodes::ROIOpcode::roi.
Referenced by rawspeed::DngOpcodes::DummyROIOpcode::__attribute__(), rawspeed::DngOpcodes::TrimBounds::apply(), rawspeed::DngOpcodes::PixelOpcode::applyOP(), rawspeed::DngOpcodes::DeltaRowOrCol< S >::DeltaRowOrCol(), and rawspeed::DngOpcodes::PixelOpcode::PixelOpcode().
apply()
template<typename S > void rawspeed::DngOpcodes::ScalePerRowOrCol< S >::apply (const RawImage & ri) inline override virtual
Implements rawspeed::DngOpcodes::DngOpcode.
Definition at line 456 of file DngOpcodes.cpp.
References rawspeed::RawImageData::getDataType(), rawspeed::RawImage::operator->(), and rawspeed::TYPE_USHORT16.
applyOP()
template<typename T , typename OP > void rawspeed::DngOpcodes::PixelOpcode::applyOP (const RawImage & ri, OP op) inline protected inherited
Definition at line 248 of file DngOpcodes.cpp.
References rawspeed::DngOpcodes::ROIOpcode::__attribute__(), rawspeed::DngOpcodes::PixelOpcode::colPitch, rawspeed::DngOpcodes::PixelOpcode::firstPlane, rawspeed::iRectangle2D::getBottom(), rawspeed::RawImageData::getCpp(), rawspeed::RawImageData::getData(), rawspeed::iRectangle2D::getLeft(), rawspeed::iRectangle2D::getRight(), rawspeed::iRectangle2D::getTop(), rawspeed::RawImage::operator->(), rawspeed::DngOpcodes::PixelOpcode::planes, and rawspeed::DngOpcodes::PixelOpcode::rowPitch.
setup()
template<typename S > void rawspeed::DngOpcodes::DeltaRowOrCol< S >::setup (const RawImage & ri) inline override virtual inherited
Reimplemented from rawspeed::DngOpcodes::DngOpcode.
Definition at line 351 of file DngOpcodes.cpp.
References rawspeed::RawImageData::getDataType(), rawspeed::RawImage::operator->(), rawspeed::DngOpcodes::DngOpcode::setup(), and rawspeed::TYPE_USHORT16.
valueIsOk()
template<typename S > bool rawspeed::DngOpcodes::ScalePerRowOrCol< S >::valueIsOk (float value) inline final private virtual
Implements rawspeed::DngOpcodes::DeltaRowOrCol< S >.
Definition at line 445 of file DngOpcodes.cpp.
References rawspeed::DngOpcodes::ScalePerRowOrCol< S >::maxLimit, and rawspeed::DngOpcodes::ScalePerRowOrCol< S >::minLimit.
Member Data Documentation
colPitch
uint32_t rawspeed::DngOpcodes::PixelOpcode::colPitch private inherited
Definition at line 222 of file DngOpcodes.cpp.
Referenced by rawspeed::DngOpcodes::PixelOpcode::applyOP(), and rawspeed::DngOpcodes::PixelOpcode::PixelOpcode().
deltaF
template<typename S > vector<float> rawspeed::DngOpcodes::DeltaRowOrCol< S >::deltaF protected inherited
Definition at line 368 of file DngOpcodes.cpp.
deltaI
template<typename S > vector<int> rawspeed::DngOpcodes::DeltaRowOrCol< S >::deltaI protected inherited
Definition at line 369 of file DngOpcodes.cpp.
f2iScale
template<typename S > const float rawspeed::DngOpcodes::DeltaRowOrCol< S >::f2iScale protected inherited
Definition at line 367 of file DngOpcodes.cpp.
Referenced by rawspeed::DngOpcodes::DeltaRowOrCol< S >::DeltaRowOrCol().
firstPlane
uint32_t rawspeed::DngOpcodes::PixelOpcode::firstPlane private inherited
Definition at line 219 of file DngOpcodes.cpp.
Referenced by rawspeed::DngOpcodes::PixelOpcode::applyOP(), and rawspeed::DngOpcodes::PixelOpcode::PixelOpcode().
maxLimit
template<typename S > const double rawspeed::DngOpcodes::ScalePerRowOrCol< S >::maxLimit private
Definition at line 443 of file DngOpcodes.cpp.
Referenced by rawspeed::DngOpcodes::ScalePerRowOrCol< S >::ScalePerRowOrCol(), and rawspeed::DngOpcodes::ScalePerRowOrCol< S >::valueIsOk().
minLimit
template<typename S > constexpr const double rawspeed::DngOpcodes::ScalePerRowOrCol< S >::minLimit = 0.0 static constexpr private
Definition at line 441 of file DngOpcodes.cpp.
Referenced by rawspeed::DngOpcodes::ScalePerRowOrCol< S >::valueIsOk().
planes
uint32_t rawspeed::DngOpcodes::PixelOpcode::planes private inherited
Definition at line 220 of file DngOpcodes.cpp.
Referenced by rawspeed::DngOpcodes::PixelOpcode::applyOP(), and rawspeed::DngOpcodes::PixelOpcode::PixelOpcode().
roi
iRectangle2D rawspeed::DngOpcodes::ROIOpcode::roi private inherited
Definition at line 99 of file DngOpcodes.cpp.
Referenced by rawspeed::DngOpcodes::ROIOpcode::__attribute__(), and rawspeed::DngOpcodes::ROIOpcode::ROIOpcode().
rounding
template<typename S > constexpr int rawspeed::DngOpcodes::ScalePerRowOrCol< S >::rounding = 512 static constexpr private
Definition at line 442 of file DngOpcodes.cpp.
Referenced by rawspeed::DngOpcodes::ScalePerRowOrCol< S >::ScalePerRowOrCol().
rowPitch
uint32_t rawspeed::DngOpcodes::PixelOpcode::rowPitch private inherited
Definition at line 221 of file DngOpcodes.cpp.
Referenced by rawspeed::DngOpcodes::PixelOpcode::applyOP(), and rawspeed::DngOpcodes::PixelOpcode::PixelOpcode().
The documentation for this class was generated from the following file:
librawspeed/common/DngOpcodes.cpp