RawSpeed: rawspeed::DngOpcodes::FixBadPixelsConstant Class Reference
rawspeed::DngOpcodes::FixBadPixelsConstant Class Reference final
Public Member Functions
FixBadPixelsConstant (const RawImage &ri, ByteStream *bs)
void setup (const RawImage &ri) override
void apply (const RawImage &ri) override
Private Attributes
uint32_t value
Detailed Description
Definition at line 64 of file DngOpcodes.cpp.
Constructor & Destructor Documentation
FixBadPixelsConstant()
rawspeed::DngOpcodes::FixBadPixelsConstant::FixBadPixelsConstant (const RawImage & ri, ByteStream * bs) inline explicit
Definition at line 68 of file DngOpcodes.cpp.
References rawspeed::ByteStream::getU32(), and value.
Member Function Documentation
apply()
void rawspeed::DngOpcodes::FixBadPixelsConstant::apply (const RawImage & ri) inline override virtual
Implements rawspeed::DngOpcodes::DngOpcode.
Definition at line 82 of file DngOpcodes.cpp.
References rawspeed::RawImageData::__attribute__(), rawspeed::RawImageData::dim, rawspeed::RawImageData::getData(), rawspeed::RawImage::operator->(), rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
setup()
void rawspeed::DngOpcodes::FixBadPixelsConstant::setup (const RawImage & ri) inline override virtual
Reimplemented from rawspeed::DngOpcodes::DngOpcode.
Definition at line 73 of file DngOpcodes.cpp.
Member Data Documentation
value
uint32_t rawspeed::DngOpcodes::FixBadPixelsConstant::value private
Definition at line 65 of file DngOpcodes.cpp.
Referenced by FixBadPixelsConstant().
The documentation for this class was generated from the following file:
librawspeed/common/DngOpcodes.cpp