RawSpeed: rawspeed::UncompressedDecompressor Class Reference
rawspeed::UncompressedDecompressor Class Reference final
#include "decompressors/UncompressedDecompressor.h"
Public Member Functions
UncompressedDecompressor (ByteStream input_, const RawImage &img)
void readUncompressedRaw (const iPoint2D &size, const iPoint2D &offset, int inputPitchBytes, int bitPerPixel, BitOrder order)
template<bool uncorrectedRawValues>
void decode8BitRaw (uint32_t w, uint32_t h)
template<Endianness e, bool interlaced = false, bool skips = false>
void decode12BitRaw (uint32_t w, uint32_t h)
template<Endianness e>
void decode12BitRawUnpackedLeftAligned (uint32_t w, uint32_t h)
template<int bits, Endianness e>
void decodeRawUnpacked (uint32_t w, uint32_t h)
Private Member Functions
void sanityCheck (const uint32_t *h, int bytesPerLine)
void sanityCheck (uint32_t w, const uint32_t *h, int bpp)
Static Private Member Functions
static int bytesPerLine (int w, bool skips)
Private Attributes
ByteStream input
RawImage mRaw
Detailed Description
Definition at line 37 of file UncompressedDecompressor.h.
Constructor & Destructor Documentation
UncompressedDecompressor()
rawspeed::UncompressedDecompressor::UncompressedDecompressor (ByteStream input_, const RawImage & img) inline
Definition at line 51 of file UncompressedDecompressor.h.
Member Function Documentation
bytesPerLine()
int rawspeed::UncompressedDecompressor::bytesPerLine (int w, bool skips) static private
Definition at line 78 of file UncompressedDecompressor.cpp.
decode12BitRaw()
template<Endianness e, bool interlaced, bool skips> template void rawspeed::UncompressedDecompressor::decode12BitRaw< Endianness::big, false, true > (uint32_t w, uint32_t h)
Definition at line 300 of file UncompressedDecompressor.cpp.
References rawspeed::big, rawspeed::RawImageData::getData(), rawspeed::ByteStream::getRemainSize(), rawspeed::little, rawspeed::RawImage::operator->(), rawspeed::ByteStream::peekData(), rawspeed::RawImageData::pitch, and rawspeed::ByteStream::skipBytes().
decode12BitRawUnpackedLeftAligned()
template<Endianness e> template void rawspeed::UncompressedDecompressor::decode12BitRawUnpackedLeftAligned< Endianness::big > (uint32_t w, uint32_t h)
Definition at line 376 of file UncompressedDecompressor.cpp.
References rawspeed::big, rawspeed::ByteStream::getData(), rawspeed::RawImageData::getData(), rawspeed::RawImage::operator->(), and rawspeed::RawImageData::pitch.
decode8BitRaw()
template<bool uncorrectedRawValues> template void rawspeed::UncompressedDecompressor::decode8BitRaw< true > (uint32_t w, uint32_t h)
Definition at line 275 of file UncompressedDecompressor.cpp.
References rawspeed::ByteStream::getData(), rawspeed::RawImageData::getData(), rawspeed::RawImage::operator->(), rawspeed::RawImageData::pitch, and rawspeed::RawImageData::setWithLookUp().
decodeRawUnpacked()
template<int bits, Endianness e> template void rawspeed::UncompressedDecompressor::decodeRawUnpacked< 16, Endianness::big > (uint32_t w, uint32_t h)
Definition at line 403 of file UncompressedDecompressor.cpp.
References rawspeed::big, rawspeed::ByteStream::getData(), rawspeed::RawImageData::getData(), rawspeed::little, rawspeed::RawImage::operator->(), and rawspeed::RawImageData::pitch.
readUncompressedRaw()
void rawspeed::UncompressedDecompressor::readUncompressedRaw (const iPoint2D & size, const iPoint2D & offset, int inputPitchBytes, int bitPerPixel, BitOrder order)
Definition at line 96 of file UncompressedDecompressor.cpp.
References rawspeed::copyPixels(), rawspeed::fp16ToFloat(), rawspeed::fp24ToFloat(), rawspeed::RawImageData::getBpp(), rawspeed::RawImageData::getCpp(), rawspeed::ByteStream::getData(), rawspeed::RawImageData::getData(), rawspeed::RawImageData::getDataType(), rawspeed::getHostEndianness(), rawspeed::little, rawspeed::RawImage::operator->(), rawspeed::RawImageData::pitch, rawspeed::TYPE_FLOAT32, rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
sanityCheck() [1/2]
void rawspeed::UncompressedDecompressor::sanityCheck (const uint32_t * h, int bytesPerLine) private
Definition at line 42 of file UncompressedDecompressor.cpp.
References rawspeed::ByteStream::getRemainSize().
sanityCheck() [2/2]
void rawspeed::UncompressedDecompressor::sanityCheck (uint32_t w, const uint32_t * h, int bpp) private
Definition at line 66 of file UncompressedDecompressor.cpp.
Member Data Documentation
input
ByteStream rawspeed::UncompressedDecompressor::input private
Definition at line 38 of file UncompressedDecompressor.h.
mRaw
RawImage rawspeed::UncompressedDecompressor::mRaw private
Definition at line 39 of file UncompressedDecompressor.h.
The documentation for this class was generated from the following files:
librawspeed/decompressors/UncompressedDecompressor.h
librawspeed/decompressors/UncompressedDecompressor.cpp