RawSpeed: anonymous_namespace{DummyLJpegDecompressor.cpp}::DummyLJpegDecompressor Class Reference
anonymous_namespace{DummyLJpegDecompressor.cpp}::DummyLJpegDecompressor Class Reference final
Public Member Functions
DummyLJpegDecompressor (const rawspeed::ByteStream &bs, const rawspeed::RawImage &img)
void decode ()
Protected Member Functions
void parseSOF (ByteStream data, SOFInfo *i)
void parseSOS (ByteStream data)
void parseDHT (ByteStream data)
JpegMarker getNextMarker (bool allowskip)
template<int N_COMP>
std::array< HuffmanTable *, N_COMP > getHuffmanTables () const
Protected Attributes
bool fixDng16Bug = false
bool fullDecodeHT = true
template<int N_COMP>
__attribute__((pure)) std ByteStream input
RawImage mRaw
SOFInfo frame
uint32_t predictorMode = 0
Private Member Functions
void decodeScan () override
Private Attributes
std::vector< std::unique_ptr< HuffmanTable > > huffmanTableStore
HuffmanTable ht_
uint32_t Pt = 0
std::array< HuffmanTable *, 4 > huff {{}}
Detailed Description
Definition at line 36 of file DummyLJpegDecompressor.cpp.
Constructor & Destructor Documentation
DummyLJpegDecompressor()
anonymous_namespace{DummyLJpegDecompressor.cpp}::DummyLJpegDecompressor::DummyLJpegDecompressor (const rawspeed::ByteStream & bs, const rawspeed::RawImage & img) inline
Definition at line 41 of file DummyLJpegDecompressor.cpp.
References rawspeed::AbstractLJpegDecompressor::AbstractLJpegDecompressor().
Referenced by LLVMFuzzerTestOneInput().
Member Function Documentation
decode()
void anonymous_namespace{DummyLJpegDecompressor.cpp}::DummyLJpegDecompressor::decode () inline
Definition at line 45 of file DummyLJpegDecompressor.cpp.
Referenced by LLVMFuzzerTestOneInput().
decodeScan()
void anonymous_namespace{DummyLJpegDecompressor.cpp}::DummyLJpegDecompressor::decodeScan () inline override private
Definition at line 38 of file DummyLJpegDecompressor.cpp.
getHuffmanTables()
template<int N_COMP> std::array<HuffmanTable*, N_COMP> rawspeed::AbstractLJpegDecompressor::getHuffmanTables () const inline protected inherited
Definition at line 163 of file AbstractLJpegDecompressor.h.
getNextMarker()
JpegMarker rawspeed::AbstractLJpegDecompressor::getNextMarker (bool allowskip) protected inherited
Definition at line 254 of file AbstractLJpegDecompressor.cpp.
References rawspeed::ByteStream::getByte(), and rawspeed::AbstractLJpegDecompressor::input.
Referenced by rawspeed::AbstractLJpegDecompressor::decode().
parseDHT()
void rawspeed::AbstractLJpegDecompressor::parseDHT (ByteStream data) protected inherited
Definition at line 214 of file AbstractLJpegDecompressor.cpp.
References rawspeed::ByteStream::getByte(), and rawspeed::ByteStream::getRemainSize().
Referenced by rawspeed::AbstractLJpegDecompressor::decode().
parseSOF()
void rawspeed::AbstractLJpegDecompressor::parseSOF (ByteStream data, SOFInfo * i) protected inherited
Definition at line 114 of file AbstractLJpegDecompressor.cpp.
References rawspeed::SOFInfo::cps, rawspeed::RawImageData::dim, rawspeed::ByteStream::getByte(), rawspeed::RawImageData::getCpp(), rawspeed::ByteStream::getU16(), rawspeed::SOFInfo::h, rawspeed::SOFInfo::initialized, rawspeed::AbstractLJpegDecompressor::mRaw, rawspeed::RawImage::operator->(), rawspeed::SOFInfo::prec, rawspeed::SOFInfo::w, and rawspeed::iPoint2D::x.
parseSOS()
void rawspeed::AbstractLJpegDecompressor::parseSOS (ByteStream data) protected inherited
Definition at line 168 of file AbstractLJpegDecompressor.cpp.
References rawspeed::ByteStream::getByte(), rawspeed::AbstractLJpegDecompressor::predictorMode, and rawspeed::AbstractLJpegDecompressor::Pt.
Referenced by rawspeed::AbstractLJpegDecompressor::decode().
Member Data Documentation
fixDng16Bug
bool rawspeed::AbstractLJpegDecompressor::fixDng16Bug = false protected inherited
Definition at line 153 of file AbstractLJpegDecompressor.h.
Referenced by rawspeed::LJpegDecompressor::decode().
frame
SOFInfo rawspeed::AbstractLJpegDecompressor::frame protected inherited
Definition at line 195 of file AbstractLJpegDecompressor.h.
fullDecodeHT
bool rawspeed::AbstractLJpegDecompressor::fullDecodeHT = true protected inherited
Definition at line 154 of file AbstractLJpegDecompressor.h.
Referenced by rawspeed::HasselbladDecompressor::decode().
ht_
HuffmanTable rawspeed::AbstractLJpegDecompressor::ht_ private inherited
Definition at line 142 of file AbstractLJpegDecompressor.h.
huff
std::array<HuffmanTable*, 4> rawspeed::AbstractLJpegDecompressor::huff {{}} private inherited
Definition at line 145 of file AbstractLJpegDecompressor.h.
huffmanTableStore
std::vector<std::unique_ptr<HuffmanTable> > rawspeed::AbstractLJpegDecompressor::huffmanTableStore private inherited
Definition at line 141 of file AbstractLJpegDecompressor.h.
input
template<int N_COMP> __attribute__ ((pure)) std ByteStream rawspeed::AbstractLJpegDecompressor::input protected inherited
Definition at line 179 of file AbstractLJpegDecompressor.h.
Referenced by rawspeed::AbstractLJpegDecompressor::AbstractLJpegDecompressor(), rawspeed::AbstractLJpegDecompressor::decode(), and rawspeed::AbstractLJpegDecompressor::getNextMarker().
mRaw
RawImage rawspeed::AbstractLJpegDecompressor::mRaw protected inherited
Definition at line 193 of file AbstractLJpegDecompressor.h.
Referenced by rawspeed::AbstractLJpegDecompressor::AbstractLJpegDecompressor(), rawspeed::Cr2Decompressor::Cr2Decompressor(), rawspeed::LJpegDecompressor::decodeN(), rawspeed::Cr2Decompressor::decodeN_X_Y(), rawspeed::LJpegDecompressor::decodeScan(), rawspeed::HasselbladDecompressor::HasselbladDecompressor(), and rawspeed::AbstractLJpegDecompressor::parseSOF().
predictorMode
uint32_t rawspeed::AbstractLJpegDecompressor::predictorMode = 0 protected inherited
Definition at line 196 of file AbstractLJpegDecompressor.h.
Referenced by rawspeed::AbstractLJpegDecompressor::parseSOS().
Pt
uint32_t rawspeed::AbstractLJpegDecompressor::Pt = 0 private inherited
Definition at line 144 of file AbstractLJpegDecompressor.h.
Referenced by rawspeed::AbstractLJpegDecompressor::parseSOS().
The documentation for this class was generated from the following file:
/build/rawspeed/fuzz/librawspeed/decompressors/DummyLJpegDecompressor.cpp