RawSpeed: rawspeed::ByteStream Class Reference
rawspeed::ByteStream Class Reference
#include "io/ByteStream.h"
Public Types
using size_type = uint32_t
Public Member Functions
ByteStream ()=default
ByteStream (const DataBuffer &buffer)
ByteStream getSubStream (size_type offset, size_type size_) const
ByteStream getSubStream (size_type offset) const
size_type check (size_type bytes) const
size_type check (size_type nmemb, size_type size_) const
size_type getPosition () const
void setPosition (size_type newPos)
size_type getRemainSize () const
const uint8_t * peekData (size_type count) const
const uint8_t * getData (size_type count)
Buffer getBuffer (size_type size_)
ByteStream peekStream (size_type size_) const
ByteStream peekStream (size_type nmemb, size_type size_) const
ByteStream getStream (size_type size_)
ByteStream getStream (size_type nmemb, size_type size_)
uint8_t peekByte (size_type i=0) const
void skipBytes (size_type nbytes)
void skipBytes (size_type nmemb, size_type size_)
bool hasPatternAt (const char *pattern, size_type size_, size_type relPos) const
bool hasPrefix (const char *prefix, size_type size_) const
bool skipPrefix (const char *prefix, size_type size_)
uint8_t getByte ()
template<typename T >
T peek (size_type i=0) const
uint16_t peekU16 () const
template<typename T >
T get ()
uint16_t getU16 ()
int32_t getI32 ()
uint32_t getU32 ()
float getFloat ()
const char * peekString () const
const char * getString ()
template<typename T >
T get (size_type offset, size_type index=0) const
template<typename T >
T get (bool inNativeByteOrder, size_type offset, size_type index=0) const
Endianness getByteOrder () const
Endianness setByteOrder (Endianness endianness_)
Buffer getSubView (size_type offset, size_type size_) const
Buffer getSubView (size_type offset) const
const uint8_t * getData (size_type offset, size_type count) const
uint8_t operator[] (size_type offset) const
const uint8_t * begin () const
const uint8_t * end () const
size_type getSize () const
bool isValid (size_type offset, size_type count=1) const
Static Public Member Functions
static ByteStream createCopy (void *data_, size_type size_)
static std::unique_ptr< uint8_t, decltype(&alignedFree)> Create (size_type size)
Protected Attributes
size_type pos = 0
const uint8_t * data = nullptr
size_type size = 0
bool isOwner = false
Private Attributes
Endianness endianness = Endianness::little
Detailed Description
Definition at line 36 of file ByteStream.h.
Member Typedef Documentation
size_type
using rawspeed::Buffer::size_type = uint32_t inherited
Definition at line 54 of file Buffer.h.
Constructor & Destructor Documentation
ByteStream() [1/2]
rawspeed::ByteStream::ByteStream () default
ByteStream() [2/2]
rawspeed::ByteStream::ByteStream (const DataBuffer & buffer) inline explicit
Definition at line 44 of file ByteStream.h.
Referenced by BM_BitStream(), BM_DeflateDecompressor(), getSubStream(), LLVMFuzzerTestOneInput(), rawspeed_test::TEST(), and rawspeed::TiffIFD::TiffIFD().
Member Function Documentation
begin()
const uint8_t* rawspeed::Buffer::begin () const inline inherited
Definition at line 190 of file Buffer.h.
check() [1/2]
size_type rawspeed::ByteStream::check (size_type bytes) const inline
Definition at line 56 of file ByteStream.h.
Referenced by check(), getByte(), getPosition(), getRemainSize(), getString(), rawspeed::KodakDecompressor::KodakDecompressor(), peekByte(), rawspeed::DngOpcodes::PolynomialMap::PolynomialMap(), rawspeed::SamsungV2Decompressor::SamsungV2Decompressor(), setPosition(), skipBytes(), and rawspeed::TiffEntry::TiffEntry().
check() [2/2]
size_type rawspeed::ByteStream::check (size_type nmemb, size_type size_) const inline
Definition at line 63 of file ByteStream.h.
References check().
Referenced by CreateCFA(), rawspeed::DngOpcodes::DeltaRowOrCol< S >::DeltaRowOrCol(), and skipBytes().
Create()
static std::unique_ptr<uint8_t, decltype(&alignedFree)> rawspeed::Buffer::Create (size_type size) inline static inherited
Definition at line 64 of file Buffer.h.
createCopy()
static ByteStream rawspeed::ByteStream::createCopy (void * data_, size_type size_) inline static
Definition at line 191 of file ByteStream.h.
end()
const uint8_t* rawspeed::Buffer::end () const inline inherited
Definition at line 195 of file Buffer.h.
get() [1/3]
template<typename T > T rawspeed::ByteStream::get () inline
Definition at line 157 of file ByteStream.h.
References pos.
get() [2/3]
template<typename T > T rawspeed::Buffer::get (bool inNativeByteOrder, size_type offset, size_type index = 0) const inline inherited
Definition at line 202 of file Buffer.h.
get() [3/3]
template<typename T > T rawspeed::DataBuffer::get (size_type offset, size_type index = 0) const inline inherited
Definition at line 231 of file Buffer.h.
References rawspeed::big, rawspeed::getHostEndianness(), rawspeed::little, and rawspeed::unknown.
getBuffer()
Buffer rawspeed::ByteStream::getBuffer (size_type size_) inline
Definition at line 91 of file ByteStream.h.
References pos.
Referenced by createHuffmanTable(), rawspeed::PanasonicDecompressorV4::ProxyStream::parseBlock(), and rawspeed::PanasonicDecompressorV5::ProxyStream::parseBlock().
getByte()
uint8_t rawspeed::ByteStream::getByte () inline
Definition at line 145 of file ByteStream.h.
References check(), and pos.
Referenced by rawspeed::KodakDecompressor::decodeSegment(), rawspeed::FujiDecompressor::FujiHeader::FujiHeader(), rawspeed::AbstractLJpegDecompressor::getNextMarker(), rawspeed::NikonDecompressor::NikonDecompressor(), rawspeed::AbstractLJpegDecompressor::parseDHT(), rawspeed::AbstractLJpegDecompressor::parseSOF(), and rawspeed::AbstractLJpegDecompressor::parseSOS().
getByteOrder()
Endianness rawspeed::DataBuffer::getByteOrder () const inline inherited
Definition at line 238 of file Buffer.h.
getData() [1/2]
const uint8_t* rawspeed::ByteStream::getData (size_type count) inline
Definition at line 86 of file ByteStream.h.
References pos.
Referenced by rawspeed::UncompressedDecompressor::decode12BitRawUnpackedLeftAligned(), rawspeed::UncompressedDecompressor::decode8BitRaw(), rawspeed::UncompressedDecompressor::decodeRawUnpacked(), and rawspeed::UncompressedDecompressor::readUncompressedRaw().
getData() [2/2]
const uint8_t* rawspeed::Buffer::getData (size_type offset, size_type count) const inline inherited
Definition at line 176 of file Buffer.h.
getFloat()
float rawspeed::ByteStream::getFloat () inline
Definition at line 166 of file ByteStream.h.
getI32()
int32_t rawspeed::ByteStream::getI32 () inline
Definition at line 164 of file ByteStream.h.
getPosition()
size_type rawspeed::ByteStream::getPosition () const inline
Definition at line 69 of file ByteStream.h.
References check(), and pos.
Referenced by rawspeed::BitStream< MSBBitPumpTag, BitStreamCacheRightInLeftOut >::BitStream(), rawspeed::SamsungV2Decompressor::decompressRow(), rawspeed::DngOpcodes::DngOpcodes(), rawspeed::DngOpcodes::FixBadPixelsList::FixBadPixelsList(), LLVMFuzzerTestOneInput(), rawspeed::TiffIFD::parseIFDEntry(), rawspeed::TiffIFD::parseMakerNote(), and rawspeed::TiffEntry::TiffEntry().
getRemainSize()
size_type rawspeed::ByteStream::getRemainSize () const inline
Definition at line 78 of file ByteStream.h.
References check(), and pos.
Referenced by rawspeed::BitStream< MSBBitPumpTag, BitStreamCacheRightInLeftOut >::BitStream(), rawspeed::PanasonicDecompressorV4::chopInputIntoBlocks(), rawspeed::PanasonicDecompressorV5::chopInputIntoBlocks(), rawspeed::CrwDecompressor::CrwDecompressor(), rawspeed::UncompressedDecompressor::decode12BitRaw(), LLVMFuzzerTestOneInput(), rawspeed::PanasonicDecompressorV5::PanasonicDecompressorV5(), rawspeed::PanasonicDecompressorV6::PanasonicDecompressorV6(), rawspeed::PanasonicDecompressorV4::ProxyStream::parseBlock(), rawspeed::PanasonicDecompressorV5::ProxyStream::parseBlock(), rawspeed::AbstractLJpegDecompressor::parseDHT(), rawspeed::TiffIFD::parseMakerNote(), and rawspeed::UncompressedDecompressor::sanityCheck().
getSize()
size_type rawspeed::Buffer::getSize () const inline inherited
Definition at line 209 of file Buffer.h.
getStream() [1/2]
ByteStream rawspeed::ByteStream::getStream (size_type nmemb, size_type size_) inline
Definition at line 109 of file ByteStream.h.
References getStream().
Referenced by rawspeed::CiffIFD::CiffIFD().
getStream() [2/2]
ByteStream rawspeed::ByteStream::getStream (size_type size_) inline
Definition at line 104 of file ByteStream.h.
References peekStream(), and pos.
Referenced by rawspeed::CiffIFD::CiffIFD(), rawspeed::CrwDecompressor::CrwDecompressor(), rawspeed::AbstractLJpegDecompressor::decode(), rawspeed::DngOpcodes::DngOpcodes(), getStream(), LLVMFuzzerTestOneInput(), and rawspeed::CiffIFD::parseIFDEntry().
getString()
const char* rawspeed::ByteStream::getString () inline
Definition at line 177 of file ByteStream.h.
References check(), and pos.
getSubStream() [1/2]
ByteStream rawspeed::ByteStream::getSubStream (size_type offset) const inline
Definition at line 52 of file ByteStream.h.
References ByteStream().
getSubStream() [2/2]
ByteStream rawspeed::ByteStream::getSubStream (size_type offset, size_type size_) const inline
Definition at line 48 of file ByteStream.h.
References ByteStream().
Referenced by rawspeed::TiffIFD::parseMakerNote(), peekStream(), and rawspeed::TiffEntry::TiffEntry().
getSubView() [1/2]
Buffer rawspeed::Buffer::getSubView (size_type offset) const inline inherited
Definition at line 167 of file Buffer.h.
getSubView() [2/2]
Buffer rawspeed::Buffer::getSubView (size_type offset, size_type size_) const inline inherited
Definition at line 160 of file Buffer.h.
getU16()
uint16_t rawspeed::ByteStream::getU16 () inline
Definition at line 163 of file ByteStream.h.
Referenced by rawspeed::CiffIFD::CiffIFD(), rawspeed::NikonDecompressor::createCurve(), rawspeed::FujiDecompressor::FujiHeader::FujiHeader(), rawspeed::AbstractLJpegDecompressor::parseSOF(), rawspeed::PentaxDecompressor::SetupHuffmanTable_Modern(), rawspeed::TiffEntry::TiffEntry(), and rawspeed::TiffIFD::TiffIFD().
getU32()
uint32_t rawspeed::ByteStream::getU32 () inline
Definition at line 165 of file ByteStream.h.
Referenced by rawspeed::CiffIFD::CiffIFD(), CreateCFA(), CreateRawImage(), rawspeed::DngOpcodes::DeltaRowOrCol< S >::DeltaRowOrCol(), rawspeed::DngOpcodes::DngOpcodes(), rawspeed::DngOpcodes::FixBadPixelsConstant::FixBadPixelsConstant(), rawspeed::DngOpcodes::FixBadPixelsList::FixBadPixelsList(), LLVMFuzzerTestOneInput(), rawspeed::DngOpcodes::PixelOpcode::PixelOpcode(), rawspeed::DngOpcodes::PolynomialMap::PolynomialMap(), rawspeed::DngOpcodes::ROIOpcode::ROIOpcode(), rawspeed::DngOpcodes::TableMap::TableMap(), rawspeed::TiffEntry::TiffEntry(), and rawspeed::TiffIFD::TiffIFD().
hasPatternAt()
bool rawspeed::ByteStream::hasPatternAt (const char * pattern, size_type size_, size_type relPos) const inline
Definition at line 126 of file ByteStream.h.
References pos.
Referenced by hasPrefix(), and rawspeed::TiffIFD::parseMakerNote().
hasPrefix()
bool rawspeed::ByteStream::hasPrefix (const char * prefix, size_type size_) const inline
Definition at line 134 of file ByteStream.h.
References hasPatternAt().
Referenced by rawspeed::TiffIFD::parseMakerNote(), and skipPrefix().
isValid()
bool rawspeed::Buffer::isValid (size_type offset, size_type count = 1) const inline inherited
Definition at line 214 of file Buffer.h.
operator[]()
uint8_t rawspeed::Buffer::operator[] (size_type offset) const inline inherited
Definition at line 187 of file Buffer.h.
peek()
template<typename T > T rawspeed::ByteStream::peek (size_type i = 0) const inline
Definition at line 151 of file ByteStream.h.
References pos.
peekByte()
uint8_t rawspeed::ByteStream::peekByte (size_type i = 0) const inline
Definition at line 115 of file ByteStream.h.
References check(), and pos.
peekData()
const uint8_t* rawspeed::ByteStream::peekData (size_type count) const inline
Definition at line 83 of file ByteStream.h.
References pos.
Referenced by rawspeed::UncompressedDecompressor::decode12BitRaw().
peekStream() [1/2]
ByteStream rawspeed::ByteStream::peekStream (size_type nmemb, size_type size_) const inline
Definition at line 99 of file ByteStream.h.
References peekStream().
Referenced by rawspeed::PanasonicDecompressorV6::PanasonicDecompressorV6(), and rawspeed::SamsungV0Decompressor::SamsungV0Decompressor().
peekStream() [2/2]
ByteStream rawspeed::ByteStream::peekStream (size_type size_) const inline
Definition at line 96 of file ByteStream.h.
References getSubStream(), and pos.
Referenced by getStream(), peekStream(), and rawspeed::SonyArw2Decompressor::SonyArw2Decompressor().
peekString()
const char* rawspeed::ByteStream::peekString () const inline
Definition at line 168 of file ByteStream.h.
References pos.
peekU16()
uint16_t rawspeed::ByteStream::peekU16 () const inline
Definition at line 155 of file ByteStream.h.
Referenced by rawspeed::AbstractLJpegDecompressor::decode().
setByteOrder()
Endianness rawspeed::DataBuffer::setByteOrder (Endianness endianness_) inline inherited
Definition at line 240 of file Buffer.h.
setPosition()
void rawspeed::ByteStream::setPosition (size_type newPos) inline
Definition at line 74 of file ByteStream.h.
References check(), and pos.
Referenced by rawspeed::CiffIFD::CiffIFD(), rawspeed::NikonDecompressor::createCurve(), rawspeed::DngOpcodes::DngOpcodes(), rawspeed::DngOpcodes::FixBadPixelsList::FixBadPixelsList(), rawspeed::TiffIFD::parseIFDEntry(), rawspeed::TiffEntry::TiffEntry(), and rawspeed::TiffIFD::TiffIFD().
skipBytes() [1/2]
void rawspeed::ByteStream::skipBytes (size_type nbytes) inline
Definition at line 121 of file ByteStream.h.
References check(), and pos.
Referenced by rawspeed::CrwDecompressor::CrwDecompressor(), rawspeed::AbstractLJpegDecompressor::decode(), rawspeed::UncompressedDecompressor::decode12BitRaw(), rawspeed::SamsungV2Decompressor::decompressRow(), rawspeed::DngOpcodes::DngOpcodes(), rawspeed::FujiDecompressor::fuji_compressed_load_raw(), rawspeed::NikonDecompressor::NikonDecompressor(), rawspeed::TiffIFD::parseMakerNote(), rawspeed::PentaxDecompressor::SetupHuffmanTable_Modern(), and rawspeed::TiffEntry::TiffEntry().
skipBytes() [2/2]
void rawspeed::ByteStream::skipBytes (size_type nmemb, size_type size_) inline
Definition at line 122 of file ByteStream.h.
References check(), and pos.
Referenced by rawspeed::DngOpcodes::FixBadPixelsList::FixBadPixelsList().
skipPrefix()
bool rawspeed::ByteStream::skipPrefix (const char * prefix, size_type size_) inline
Definition at line 138 of file ByteStream.h.
References hasPrefix(), and pos.
Referenced by rawspeed::TiffIFD::parseMakerNote().
Member Data Documentation
data
const uint8_t* rawspeed::Buffer::data = nullptr protected inherited
Definition at line 57 of file Buffer.h.
endianness
Endianness rawspeed::DataBuffer::endianness = Endianness::little private inherited
Definition at line 220 of file Buffer.h.
isOwner
bool rawspeed::Buffer::isOwner = false protected inherited
Definition at line 59 of file Buffer.h.
pos
size_type rawspeed::ByteStream::pos = 0 protected
Definition at line 39 of file ByteStream.h.
Referenced by get(), getBuffer(), getByte(), getData(), getPosition(), getRemainSize(), getStream(), getString(), hasPatternAt(), peek(), peekByte(), peekData(), peekStream(), peekString(), setPosition(), skipBytes(), and skipPrefix().
size
size_type rawspeed::Buffer::size = 0 protected inherited
Definition at line 58 of file Buffer.h.
The documentation for this class was generated from the following file:
librawspeed/io/ByteStream.h