RawSpeed: rawspeed::CiffIFD Class Reference
rawspeed::CiffIFD Class Reference final
#include "tiff/CiffIFD.h"
Classes
struct Limits
Public Member Functions
CiffIFD (CiffIFD *parent)
CiffIFD (CiffIFD *parent, ByteStream directory)
std::vector< const CiffIFD * > __attribute__ ((pure)) getIFDsWithTag(CiffTag tag) const
std::vector< const CiffIFD * > __attribute__ ((pure)) getIFDsWithTagWhere(CiffTag tag
std::vector< const CiffIFD * > __attribute__ ((pure)) getIFDsWithTagWhere(CiffTag tag
bool __attribute__ ((pure)) hasEntry(CiffTag tag) const
bool __attribute__ ((pure)) hasEntryRecursive(CiffTag tag) const
const CiffEntry * __attribute__ ((pure)) getEntry(CiffTag tag) const
const CiffEntry * __attribute__ ((pure)) getEntryRecursive(CiffTag tag) const
const CiffEntry * __attribute__ ((pure)) getEntryRecursiveWhere(CiffTag tag
const CiffEntry * __attribute__ ((pure)) getEntryRecursiveWhere(CiffTag tag
Public Attributes
std::vector< const CiffIFD * > uint32_t isValue const
std::vector< const CiffIFD * > const std::string &isValue const
const CiffEntry uint32_t isValue const
const CiffEntry const std::string &isValue const
Private Member Functions
void recursivelyIncrementSubIFDCount ()
void checkSubIFDs (int headroom) const
void recursivelyCheckSubIFDs (int headroom) const
void add (std::unique_ptr< CiffIFD > subIFD)
void add (std::unique_ptr< CiffEntry > entry)
void parseIFDEntry (NORangesSet< Buffer > *valueDatas, const ByteStream *valueData, ByteStream *dirEntries)
template<typename Lambda >
std::vector< const CiffIFD * > __attribute__ ((pure)) getIFDsWithTagIf(CiffTag tag
template<typename Lambda >
const CiffEntry * __attribute__ ((pure)) getEntryRecursiveIf(CiffTag tag
Private Attributes
CiffIFD *const parent
std::vector< std::unique_ptr< const CiffIFD > > mSubIFD
std::map< CiffTag, std::unique_ptr< const CiffEntry > > mEntry
int subIFDCount = 0
int subIFDCountRecursive = 0
std::vector< const CiffIFD * > const Lambda &f const
const CiffEntry const Lambda &f const
Detailed Description
Definition at line 39 of file CiffIFD.h.
Constructor & Destructor Documentation
CiffIFD() [1/2]
rawspeed::CiffIFD::CiffIFD (CiffIFD * parent) explicit
Definition at line 70 of file CiffIFD.cpp.
CiffIFD() [2/2]
rawspeed::CiffIFD::CiffIFD (CiffIFD * parent, ByteStream directory)
Definition at line 78 of file CiffIFD.cpp.
References rawspeed::ByteStream::getStream(), rawspeed::ByteStream::getU16(), rawspeed::ByteStream::getU32(), and rawspeed::ByteStream::setPosition().
Member Function Documentation
__attribute__() [1/11]
const CiffEntry* rawspeed::CiffIFD::__attribute__ ((pure)) const
__attribute__() [2/11]
const CiffEntry* rawspeed::CiffIFD::__attribute__ ((pure)) const
__attribute__() [3/11]
template<typename Lambda > const CiffEntry* rawspeed::CiffIFD::__attribute__ ((pure)) private
__attribute__() [4/11]
const CiffEntry* rawspeed::CiffIFD::__attribute__ ((pure))
__attribute__() [5/11]
const CiffEntry* rawspeed::CiffIFD::__attribute__ ((pure))
__attribute__() [6/11]
std::vector<const CiffIFD*> rawspeed::CiffIFD::__attribute__ ((pure)) const
__attribute__() [7/11]
template<typename Lambda > std::vector<const CiffIFD*> rawspeed::CiffIFD::__attribute__ ((pure)) private
__attribute__() [8/11]
std::vector<const CiffIFD*> rawspeed::CiffIFD::__attribute__ ((pure))
__attribute__() [9/11]
std::vector<const CiffIFD*> rawspeed::CiffIFD::__attribute__ ((pure))
__attribute__() [10/11]
bool rawspeed::CiffIFD::__attribute__ ((pure)) const
__attribute__() [11/11]
bool rawspeed::CiffIFD::__attribute__ ((pure)) const
add() [1/2]
void rawspeed::CiffIFD::add (std::unique_ptr< CiffEntry > entry) private
Definition at line 163 of file CiffIFD.cpp.
add() [2/2]
void rawspeed::CiffIFD::add (std::unique_ptr< CiffIFD > subIFD) private
Definition at line 154 of file CiffIFD.cpp.
checkSubIFDs()
void rawspeed::CiffIFD::checkSubIFDs (int headroom) const private
Definition at line 124 of file CiffIFD.cpp.
parseIFDEntry()
void rawspeed::CiffIFD::parseIFDEntry (NORangesSet< Buffer > * valueDatas, const ByteStream * valueData, ByteStream * dirEntries) private
Definition at line 44 of file CiffIFD.cpp.
References rawspeed::ByteStream::getStream().
recursivelyCheckSubIFDs()
void rawspeed::CiffIFD::recursivelyCheckSubIFDs (int headroom) const private
Definition at line 138 of file CiffIFD.cpp.
recursivelyIncrementSubIFDCount()
void rawspeed::CiffIFD::recursivelyIncrementSubIFDCount () private
Definition at line 113 of file CiffIFD.cpp.
Member Data Documentation
const [1/6]
std::vector<const CiffIFD*> const Lambda& f rawspeed::CiffIFD::const private
Definition at line 82 of file CiffIFD.h.
const [2/6]
const CiffEntry const Lambda& f rawspeed::CiffIFD::const private
Definition at line 86 of file CiffIFD.h.
const [3/6]
std::vector<const CiffIFD*> uint32_t isValue rawspeed::CiffIFD::const
Definition at line 95 of file CiffIFD.h.
const [4/6]
std::vector<const CiffIFD*> const std::string& isValue rawspeed::CiffIFD::const
Definition at line 97 of file CiffIFD.h.
const [5/6]
const CiffEntry uint32_t isValue rawspeed::CiffIFD::const
Definition at line 105 of file CiffIFD.h.
const [6/6]
const CiffEntry const std::string& isValue rawspeed::CiffIFD::const
Definition at line 107 of file CiffIFD.h.
mEntry
std::map<CiffTag, std::unique_ptr<const CiffEntry> > rawspeed::CiffIFD::mEntry private
Definition at line 43 of file CiffIFD.h.
mSubIFD
std::vector<std::unique_ptr<const CiffIFD> > rawspeed::CiffIFD::mSubIFD private
Definition at line 42 of file CiffIFD.h.
parent
CiffIFD* const rawspeed::CiffIFD::parent private
Definition at line 40 of file CiffIFD.h.
subIFDCount
int rawspeed::CiffIFD::subIFDCount = 0 private
Definition at line 45 of file CiffIFD.h.
subIFDCountRecursive
int rawspeed::CiffIFD::subIFDCountRecursive = 0 private
Definition at line 46 of file CiffIFD.h.
The documentation for this class was generated from the following files:
librawspeed/tiff/CiffIFD.h
librawspeed/tiff/CiffIFD.cpp