RawSpeed: rawspeed::DngOpcodes::DummyROIOpcode Class Reference
rawspeed::DngOpcodes::DummyROIOpcode Class Reference final
Public Member Functions
DummyROIOpcode (const RawImage &ri, ByteStream *bs)
const iRectangle2D & __attribute__ ((pure)) getRoi() const
void apply (const RawImage &ri) final
virtual void setup (const RawImage &ri)
Private Attributes
iRectangle2D roi
Detailed Description
Definition at line 134 of file DngOpcodes.cpp.
Constructor & Destructor Documentation
DummyROIOpcode()
rawspeed::DngOpcodes::DummyROIOpcode::DummyROIOpcode (const RawImage & ri, ByteStream * bs) inline explicit
Definition at line 136 of file DngOpcodes.cpp.
References rawspeed::DngOpcodes::ROIOpcode::ROIOpcode().
Referenced by rawspeed::DngOpcodes::FixBadPixelsList::FixBadPixelsList().
Member Function Documentation
__attribute__()
const iRectangle2D& rawspeed::DngOpcodes::DummyROIOpcode::__attribute__ ((pure)) const inline
Definition at line 139 of file DngOpcodes.cpp.
References rawspeed::DngOpcodes::ROIOpcode::__attribute__().
Referenced by rawspeed::DngOpcodes::FixBadPixelsList::FixBadPixelsList().
apply()
void rawspeed::DngOpcodes::DummyROIOpcode::apply (const RawImage & ri) inline final virtual
Implements rawspeed::DngOpcodes::DngOpcode.
Definition at line 143 of file DngOpcodes.cpp.
setup()
virtual void rawspeed::DngOpcodes::DngOpcode::setup (const RawImage & ri) inline virtual inherited
Reimplemented in rawspeed::DngOpcodes::DeltaRowOrCol< S >, rawspeed::DngOpcodes::LookupOpcode, and rawspeed::DngOpcodes::FixBadPixelsConstant.
Definition at line 54 of file DngOpcodes.cpp.
Referenced by rawspeed::DngOpcodes::DeltaRowOrCol< S >::setup().
Member Data Documentation
roi
iRectangle2D rawspeed::DngOpcodes::ROIOpcode::roi private inherited
Definition at line 99 of file DngOpcodes.cpp.
Referenced by rawspeed::DngOpcodes::ROIOpcode::__attribute__(), and rawspeed::DngOpcodes::ROIOpcode::ROIOpcode().
The documentation for this class was generated from the following file:
librawspeed/common/DngOpcodes.cpp