RawSpeed: rawspeed::SamsungV2Decompressor Class Reference
rawspeed::SamsungV2Decompressor Class Reference final
#include "decompressors/SamsungV2Decompressor.h"
Public Types
enum OptFlags : uint32_t {
OptFlags::NONE = 0U, OptFlags::SKIP = 1U << 0U, OptFlags::MV = 1U << 1U, OptFlags::QP = 1U << 2U,
OptFlags::ALL = SKIP | MV | QP
}
Public Member Functions
SamsungV2Decompressor (const RawImage &image, const ByteStream &bs, unsigned bit)
void decompress ()
Protected Member Functions
__attribute__((always_inline)) std __attribute__((always_inline)) std __attribute__((always_inline)) std __attribute__ ((always_inline)) void processBlock(BitPumpMSB32 *pump
void decompressRow (int row)
Static Protected Member Functions
uint32_t bitDepth int width int height OptFlags optflags uint16_t initVal ByteStream data int motion int scale std::array< std::array< int, 2 >, 3 > static diffBitsMode __attribute__ ((always_inline)) int16_t getDiff(BitPumpMSB32 *pump
Protected Attributes
uint32_t bitDepth int width int height OptFlags optflags uint16_t initVal ByteStream data int motion int scale std::array< std::array< int, 2 >, 3 > static diffBitsMode uint32_t len
__attribute__((always_inline)) std __attribute__((always_inline)) std __attribute__((always_inline)) std int row
__attribute__((always_inline)) std __attribute__((always_inline)) std __attribute__((always_inline)) std int int col
RawImage mRaw
Detailed Description
Definition at line 34 of file SamsungV2Decompressor.h.
Member Enumeration Documentation
OptFlags
enum rawspeed::SamsungV2Decompressor::OptFlags : uint32_t strong
Enumerator
NONE
SKIP
MV
QP
ALL
Definition at line 43 of file SamsungV2Decompressor.cpp.
Constructor & Destructor Documentation
SamsungV2Decompressor()
rawspeed::SamsungV2Decompressor::SamsungV2Decompressor (const RawImage & image, const ByteStream & bs, unsigned bit)
Definition at line 83 of file SamsungV2Decompressor.cpp.
References rawspeed::ByteStream::check().
Member Function Documentation
__attribute__() [1/2]
uint32_t bitDepth int width int height OptFlags optflags uint16_t initVal ByteStream data int motion int scale std::array<std::array<int, 2>, 3> static diffBitsMode rawspeed::SamsungV2Decompressor::__attribute__ ((always_inline)) inline static strong protected
__attribute__() [2/2]
__attribute__ ((always_inline)) std __attribute__ ((always_inline)) std __attribute__ ((always_inline)) std rawspeed::SamsungV2Decompressor::__attribute__ ((always_inline)) inline protected
decompress()
void rawspeed::SamsungV2Decompressor::decompress ()
Definition at line 352 of file SamsungV2Decompressor.cpp.
References decompressRow().
Referenced by LLVMFuzzerTestOneInput().
decompressRow()
void rawspeed::SamsungV2Decompressor::decompressRow (int row) protected
Definition at line 328 of file SamsungV2Decompressor.cpp.
References rawspeed::ByteStream::getPosition(), and rawspeed::ByteStream::skipBytes().
Referenced by decompress().
Member Data Documentation
col
__attribute__ ((always_inline)) std __attribute__ ((always_inline)) std __attribute__ ((always_inline)) std int int rawspeed::SamsungV2Decompressor::col protected
Definition at line 64 of file SamsungV2Decompressor.h.
len
uint32_t bitDepth int width int height OptFlags optflags uint16_t initVal ByteStream data int motion int scale std::array<std::array<int, 2>, 3> static diffBitsMode uint32_t rawspeed::SamsungV2Decompressor::len protected
Definition at line 52 of file SamsungV2Decompressor.h.
mRaw
RawImage rawspeed::AbstractSamsungDecompressor::mRaw protected inherited
Definition at line 30 of file AbstractSamsungDecompressor.h.
row
__attribute__ ((always_inline)) std __attribute__ ((always_inline)) std __attribute__ ((always_inline)) std int rawspeed::SamsungV2Decompressor::row protected
Definition at line 64 of file SamsungV2Decompressor.h.
The documentation for this class was generated from the following files:
librawspeed/decompressors/SamsungV2Decompressor.h
librawspeed/decompressors/SamsungV2Decompressor.cpp