RawSpeed: rawspeed::iRectangle2D Class Reference
rawspeed::iRectangle2D Class Reference
#include "common/Point.h"
Public Member Functions
constexpr iRectangle2D ()=default
constexpr iRectangle2D (const iPoint2D &pos_, const iPoint2D &dim_)
constexpr iRectangle2D (iPoint2D &&pos_, iPoint2D &&dim_)
constexpr iRectangle2D (int w, int h)
constexpr iRectangle2D (int x_pos, int y_pos, int w, int h)
constexpr int getTop () const
constexpr int getBottom () const
constexpr int getLeft () const
constexpr int getRight () const
constexpr int getWidth () const
constexpr int getHeight () const
constexpr iPoint2D getTopLeft () const
constexpr iPoint2D getBottomRight () const
constexpr bool hasPositiveArea () const
constexpr bool isThisInside (const iRectangle2D &otherPoint) const
constexpr bool isPointInsideInclusive (const iPoint2D &checkPoint) const
unsigned int area () const
void offset (const iPoint2D &offset_)
void setTopLeft (const iPoint2D &top_left)
void setTopLeft (iPoint2D &&top_left)
void setBottomRightAbsolute (const iPoint2D &bottom_right)
void setAbsolute (const iPoint2D &top_left, const iPoint2D &bottom_right)
void setAbsolute (iPoint2D &&top_left, iPoint2D &&bottom_right)
void setAbsolute (int x1, int y1, int x2, int y2)
void setSize (const iPoint2D &size)
void setSize (iPoint2D &&size)
bool cropArea ()
bool cropOffsetToZero ()
iRectangle2D getOverlap (const iRectangle2D &other) const
iRectangle2D combine (const iRectangle2D &other) const
Public Attributes
iPoint2D pos {0, 0}
iPoint2D dim {0, 0}
Detailed Description
Definition at line 102 of file Point.h.
Constructor & Destructor Documentation
iRectangle2D() [1/5]
constexpr rawspeed::iRectangle2D::iRectangle2D () constexpr default
iRectangle2D() [2/5]
constexpr rawspeed::iRectangle2D::iRectangle2D (const iPoint2D & pos_, const iPoint2D & dim_) inline constexpr
Definition at line 105 of file Point.h.
References dim, and pos.
Referenced by rawspeed::RawImageData::blitFrom(), and rawspeed::RawImageData::clearArea().
iRectangle2D() [3/5]
constexpr rawspeed::iRectangle2D::iRectangle2D (iPoint2D && pos_, iPoint2D && dim_) inline constexpr
Definition at line 107 of file Point.h.
References dim, and pos.
iRectangle2D() [4/5]
constexpr rawspeed::iRectangle2D::iRectangle2D (int w, int h) inline constexpr
Definition at line 110 of file Point.h.
References dim, and rawspeed::iPoint2D::iPoint2D().
iRectangle2D() [5/5]
constexpr rawspeed::iRectangle2D::iRectangle2D (int x_pos, int y_pos, int w, int h) inline constexpr
Definition at line 111 of file Point.h.
References rawspeed::iPoint2D::iPoint2D(), and pos.
Referenced by rawspeed::RawImageData::expandBorder(), rawspeed::DngOpcodes::FixBadPixelsList::FixBadPixelsList(), and rawspeed::DngOpcodes::ROIOpcode::ROIOpcode().
Member Function Documentation
area()
unsigned int rawspeed::iRectangle2D::area () const inline
Definition at line 133 of file Point.h.
References rawspeed::iPoint2D::__attribute__(), and dim.
Referenced by rawspeed::RawImageData::clearArea().
combine()
iRectangle2D rawspeed::iRectangle2D::combine (const iRectangle2D & other) const inline
Definition at line 196 of file Point.h.
References getBottomRight().
cropArea()
bool rawspeed::iRectangle2D::cropArea () inline
Definition at line 163 of file Point.h.
References hasPositiveArea().
Referenced by cropOffsetToZero().
cropOffsetToZero()
bool rawspeed::iRectangle2D::cropOffsetToZero () inline
Definition at line 172 of file Point.h.
References cropArea(), dim, rawspeed::iPoint2D::operator-=(), pos, rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
getBottom()
constexpr int rawspeed::iRectangle2D::getBottom () const inline constexpr
Definition at line 115 of file Point.h.
References dim, pos, and rawspeed::iPoint2D::y.
Referenced by rawspeed::DngOpcodes::PixelOpcode::applyOP(), rawspeed::RawImageData::expandBorder(), and rawspeed::DngOpcodes::FixBadPixelsList::FixBadPixelsList().
getBottomRight()
constexpr iPoint2D rawspeed::iRectangle2D::getBottomRight () const inline constexpr
Definition at line 121 of file Point.h.
References dim, rawspeed::iPoint2D::operator+(), and pos.
Referenced by combine(), getOverlap(), isPointInsideInclusive(), and isThisInside().
getHeight()
constexpr int rawspeed::iRectangle2D::getHeight () const inline constexpr
Definition at line 119 of file Point.h.
References dim, and rawspeed::iPoint2D::y.
Referenced by rawspeed::DngOpcodes::FixBadPixelsList::FixBadPixelsList().
getLeft()
constexpr int rawspeed::iRectangle2D::getLeft () const inline constexpr
Definition at line 116 of file Point.h.
References pos, and rawspeed::iPoint2D::x.
Referenced by rawspeed::DngOpcodes::PixelOpcode::applyOP(), and rawspeed::DngOpcodes::FixBadPixelsList::FixBadPixelsList().
getOverlap()
iRectangle2D rawspeed::iRectangle2D::getOverlap (const iRectangle2D & other) const inline
Definition at line 186 of file Point.h.
References getBottomRight().
Referenced by rawspeed::RawImageData::blitFrom(), rawspeed::RawImageData::clearArea(), and rawspeed::RawImageData::expandBorder().
getRight()
constexpr int rawspeed::iRectangle2D::getRight () const inline constexpr
Definition at line 117 of file Point.h.
References dim, pos, and rawspeed::iPoint2D::x.
Referenced by rawspeed::DngOpcodes::PixelOpcode::applyOP(), rawspeed::RawImageData::expandBorder(), and rawspeed::DngOpcodes::FixBadPixelsList::FixBadPixelsList().
getTop()
constexpr int rawspeed::iRectangle2D::getTop () const inline constexpr
Definition at line 114 of file Point.h.
References pos, and rawspeed::iPoint2D::y.
Referenced by rawspeed::DngOpcodes::PixelOpcode::applyOP(), and rawspeed::DngOpcodes::FixBadPixelsList::FixBadPixelsList().
getTopLeft()
constexpr iPoint2D rawspeed::iRectangle2D::getTopLeft () const inline constexpr
Definition at line 120 of file Point.h.
References pos.
getWidth()
constexpr int rawspeed::iRectangle2D::getWidth () const inline constexpr
Definition at line 118 of file Point.h.
References dim, and rawspeed::iPoint2D::x.
Referenced by rawspeed::DngOpcodes::FixBadPixelsList::FixBadPixelsList().
hasPositiveArea()
constexpr bool rawspeed::iRectangle2D::hasPositiveArea () const inline constexpr
Definition at line 122 of file Point.h.
References dim, rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
Referenced by cropArea().
isPointInsideInclusive()
constexpr bool rawspeed::iRectangle2D::isPointInsideInclusive (const iPoint2D & checkPoint) const inline constexpr
Definition at line 129 of file Point.h.
References getBottomRight(), rawspeed::iPoint2D::operator<=(), rawspeed::iPoint2D::operator>=(), and pos.
Referenced by rawspeed::DngOpcodes::ROIOpcode::ROIOpcode().
isThisInside()
constexpr bool rawspeed::iRectangle2D::isThisInside (const iRectangle2D & otherPoint) const inline constexpr
Definition at line 124 of file Point.h.
References getBottomRight(), rawspeed::iPoint2D::operator<=(), rawspeed::iPoint2D::operator>=(), and pos.
Referenced by rawspeed::DngOpcodes::FixBadPixelsList::FixBadPixelsList(), and rawspeed::DngOpcodes::ROIOpcode::ROIOpcode().
offset()
void rawspeed::iRectangle2D::offset (const iPoint2D & offset_) inline
Definition at line 135 of file Point.h.
References rawspeed::iPoint2D::operator+=(), and pos.
setAbsolute() [1/3]
void rawspeed::iRectangle2D::setAbsolute (const iPoint2D & top_left, const iPoint2D & bottom_right) inline
Definition at line 146 of file Point.h.
References pos, and setBottomRightAbsolute().
setAbsolute() [2/3]
void rawspeed::iRectangle2D::setAbsolute (int x1, int y1, int x2, int y2) inline
Definition at line 154 of file Point.h.
References rawspeed::iPoint2D::iPoint2D(), and setAbsolute().
setAbsolute() [3/3]
void rawspeed::iRectangle2D::setAbsolute (iPoint2D && top_left, iPoint2D && bottom_right) inline
Definition at line 150 of file Point.h.
References pos, and setBottomRightAbsolute().
Referenced by setAbsolute().
setBottomRightAbsolute()
void rawspeed::iRectangle2D::setBottomRightAbsolute (const iPoint2D & bottom_right) inline
Definition at line 142 of file Point.h.
References dim, rawspeed::iPoint2D::operator-(), and pos.
Referenced by rawspeed::DngOpcodes::ROIOpcode::ROIOpcode(), and setAbsolute().
setSize() [1/2]
void rawspeed::iRectangle2D::setSize (const iPoint2D & size) inline
Definition at line 158 of file Point.h.
References dim.
setSize() [2/2]
void rawspeed::iRectangle2D::setSize (iPoint2D && size) inline
Definition at line 159 of file Point.h.
References dim.
setTopLeft() [1/2]
void rawspeed::iRectangle2D::setTopLeft (const iPoint2D & top_left) inline
Definition at line 138 of file Point.h.
References pos.
Referenced by rawspeed::DngOpcodes::ROIOpcode::ROIOpcode().
setTopLeft() [2/2]
void rawspeed::iRectangle2D::setTopLeft (iPoint2D && top_left) inline
Definition at line 139 of file Point.h.
References pos.
Member Data Documentation
dim
iPoint2D rawspeed::iRectangle2D::dim {0, 0}
Definition at line 207 of file Point.h.
Referenced by area(), cropOffsetToZero(), getBottom(), getBottomRight(), getHeight(), getRight(), getWidth(), hasPositiveArea(), iRectangle2D(), setBottomRightAbsolute(), and setSize().
pos
iPoint2D rawspeed::iRectangle2D::pos {0, 0}
Definition at line 206 of file Point.h.
Referenced by rawspeed::RawImageData::blitFrom(), cropOffsetToZero(), rawspeed::RawImageData::expandBorder(), getBottom(), getBottomRight(), getLeft(), getRight(), getTop(), getTopLeft(), iRectangle2D(), isPointInsideInclusive(), isThisInside(), offset(), setAbsolute(), setBottomRightAbsolute(), and setTopLeft().
The documentation for this class was generated from the following file:
librawspeed/common/Point.h