RawSpeed: rawspeed::Cr2Slicing Class Reference
rawspeed::Cr2Slicing Class Reference
#include "decompressors/Cr2Decompressor.h"
Public Member Functions
Cr2Slicing ()=default
Cr2Slicing (uint16_t numSlices_, uint16_t sliceWidth_, uint16_t lastSliceWidth_)
bool empty () const
unsigned widthOfSlice (int sliceId) const
unsigned totalWidth () const
Private Attributes
int numSlices = 0
int sliceWidth = 0
int lastSliceWidth = 0
Friends
class Cr2Decompressor
Detailed Description
Definition at line 34 of file Cr2Decompressor.h.
Constructor & Destructor Documentation
Cr2Slicing() [1/2]
rawspeed::Cr2Slicing::Cr2Slicing () default
Cr2Slicing() [2/2]
rawspeed::Cr2Slicing::Cr2Slicing (uint16_t numSlices_, uint16_t sliceWidth_, uint16_t lastSliceWidth_) inline
Definition at line 44 of file Cr2Decompressor.h.
References lastSliceWidth, numSlices, and sliceWidth.
Referenced by rawspeed::Cr2Decompressor::decodeScan().
Member Function Documentation
empty()
bool rawspeed::Cr2Slicing::empty () const inline
Definition at line 52 of file Cr2Decompressor.h.
References lastSliceWidth, numSlices, and sliceWidth.
Referenced by rawspeed::Cr2Decompressor::decodeScan().
totalWidth()
unsigned rawspeed::Cr2Slicing::totalWidth () const inline
Definition at line 64 of file Cr2Decompressor.h.
References numSlices, and widthOfSlice().
widthOfSlice()
unsigned rawspeed::Cr2Slicing::widthOfSlice (int sliceId) const inline
Definition at line 56 of file Cr2Decompressor.h.
References lastSliceWidth, numSlices, and sliceWidth.
Referenced by rawspeed::Cr2Decompressor::decode(), rawspeed::Cr2Decompressor::decodeN_X_Y(), and totalWidth().
Friends And Related Function Documentation
Cr2Decompressor
friend class Cr2Decompressor friend
Definition at line 39 of file Cr2Decompressor.h.
Member Data Documentation
lastSliceWidth
int rawspeed::Cr2Slicing::lastSliceWidth = 0 private
Definition at line 37 of file Cr2Decompressor.h.
Referenced by Cr2Slicing(), empty(), and widthOfSlice().
numSlices
int rawspeed::Cr2Slicing::numSlices = 0 private
Definition at line 35 of file Cr2Decompressor.h.
Referenced by Cr2Slicing(), rawspeed::Cr2Decompressor::decode(), rawspeed::Cr2Decompressor::decodeN_X_Y(), empty(), totalWidth(), and widthOfSlice().
sliceWidth
int rawspeed::Cr2Slicing::sliceWidth = 0 private
Definition at line 36 of file Cr2Decompressor.h.
Referenced by Cr2Slicing(), empty(), and widthOfSlice().
The documentation for this class was generated from the following file:
librawspeed/decompressors/Cr2Decompressor.h