RawSpeed: rawspeed::DngOpcodes::FixBadPixelsList Class Reference
rawspeed::DngOpcodes::FixBadPixelsList Class Reference final
Public Member Functions
FixBadPixelsList (const RawImage &ri, ByteStream *bs)
void apply (const RawImage &ri) override
virtual void setup (const RawImage &ri)
Private Attributes
std::vector< uint32_t > badPixels
Detailed Description
Definition at line 151 of file DngOpcodes.cpp.
Constructor & Destructor Documentation
FixBadPixelsList()
rawspeed::DngOpcodes::FixBadPixelsList::FixBadPixelsList (const RawImage & ri, ByteStream * bs) inline explicit
Definition at line 155 of file DngOpcodes.cpp.
References rawspeed::RawImageData::__attribute__(), rawspeed::DngOpcodes::DummyROIOpcode::__attribute__(), rawspeed::DngOpcodes::DummyROIOpcode::DummyROIOpcode(), rawspeed::iRectangle2D::getBottom(), rawspeed::iRectangle2D::getHeight(), rawspeed::iRectangle2D::getLeft(), rawspeed::ByteStream::getPosition(), rawspeed::iRectangle2D::getRight(), rawspeed::iRectangle2D::getTop(), rawspeed::ByteStream::getU32(), rawspeed::iRectangle2D::getWidth(), rawspeed::iPoint2D::iPoint2D(), rawspeed::iRectangle2D::iRectangle2D(), rawspeed::iRectangle2D::isThisInside(), rawspeed::RawImage::operator->(), rawspeed::ByteStream::setPosition(), rawspeed::ByteStream::skipBytes(), rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
Member Function Documentation
apply()
void rawspeed::DngOpcodes::FixBadPixelsList::apply (const RawImage & ri) inline override virtual
Implements rawspeed::DngOpcodes::DngOpcode.
Definition at line 199 of file DngOpcodes.cpp.
setup()
virtual void rawspeed::DngOpcodes::DngOpcode::setup (const RawImage & ri) inline virtual inherited
Reimplemented in rawspeed::DngOpcodes::DeltaRowOrCol< S >, rawspeed::DngOpcodes::LookupOpcode, and rawspeed::DngOpcodes::FixBadPixelsConstant.
Definition at line 54 of file DngOpcodes.cpp.
Referenced by rawspeed::DngOpcodes::DeltaRowOrCol< S >::setup().
Member Data Documentation
badPixels
std::vector<uint32_t> rawspeed::DngOpcodes::FixBadPixelsList::badPixels private
Definition at line 152 of file DngOpcodes.cpp.
The documentation for this class was generated from the following file:
librawspeed/common/DngOpcodes.cpp