RawSpeed: rawspeed::rstest Namespace Reference
rawspeed::rstest Namespace Reference
Classes
struct options
class RstestHashMismatch
struct Timer
Typedefs
using file_ptr = std::unique_ptr< FILE, decltype(&fclose)>
Functions
std::string img_hash (const rawspeed::RawImage &r)
void writePPM (const rawspeed::RawImage &raw, const std::string &fn)
void writePFM (const rawspeed::RawImage &raw, const std::string &fn)
md5::md5_state imgDataHash (const rawspeed::RawImage &raw)
void writeImage (const rawspeed::RawImage &raw, const std::string &fn)
size_t process (const std::string &filename, const rawspeed::CameraMetaData *metadata, const options &o)
static void __attribute__ ((format(printf, 2, 3))) APPEND(ostringstream *oss
va_start (args, format)
vsnprintf (line.data(), sizeof(line), format, args)
va_end (args)
for (auto ba :r->blackAreas) APPEND(&oss
for (uint32_t p :r->mBadPixelPositions) APPEND(&oss
APPEND & oss (hash_of_line_hashes).c_str()
for (const string &e :errors) APPEND(&oss
WARNING e c_str ())
return oss str ()
static int results (const map< string, string > &failedTests, const options &o)
static int usage (const char *progname)
Variables
static void const char * format
static void const char va_list args
*oss<< line.data();}string img_hash(const RawImage &r) { ostringstream oss;APPEND(&oss, "make: %s\n", r->metadata.make.c_str());APPEND(&oss, "model: %s\n", r->metadata.model.c_str());APPEND(&oss, "mode: %s\n", r->metadata.mode.c_str());APPEND(&oss, "canonical_make: %s\n", r->metadata.canonical_make.c_str());APPEND(&oss, "canonical_model: %s\n", r->metadata.canonical_model.c_str());APPEND(&oss, "canonical_alias: %s\n", r->metadata.canonical_alias.c_str());APPEND(&oss, "canonical_id: %s\n", r->metadata.canonical_id.c_str());APPEND(&oss, "isoSpeed: %d\n", r->metadata.isoSpeed);APPEND(&oss, "blackLevel: %d\n", r->blackLevel);APPEND(&oss, "whitePoint: %d\n", r->whitePoint);APPEND(&oss, "blackLevelSeparate: %d %d %d %d\n", r->blackLevelSeparate[0], r->blackLevelSeparate[1], r->blackLevelSeparate[2], r->blackLevelSeparate[3]);APPEND(&oss, "wbCoeffs: %f %f %f %f\n", r->metadata.wbCoeffs[0], r->metadata.wbCoeffs[1], r->metadata.wbCoeffs[2], r->metadata.wbCoeffs[3]);APPEND(&oss, "isCFA: %d\n", r->isCFA);APPEND(&oss, "cfa: %s\n", r->cfa.asString().c_str());APPEND(&oss, "filters: 0x%x\n", r->cfa.getDcrawFilter());APPEND(&oss, "bpp: %d\n", r->getBpp());APPEND(&oss, "cpp: %d\n", r->getCpp());APPEND(&oss, "dataType: %d\n", r->getDataType());const iPoint2D dimUncropped=r-> getUncroppedDim ()
APPEND & oss
const iPoint2D cropTL = r->getCropOffset()
d __pad0__
d ba isVertical
d ba ba offset
d ba ba ba size
d
p
rawspeed::md5::md5_state hash_of_line_hashes = imgDataHash(r)
const auto errors = r->getErrors()
WARNING __pad1__
Typedef Documentation
file_ptr
using rawspeed::rstest::file_ptr = typedef std::unique_ptr<FILE, decltype(&fclose)>
Definition at line 232 of file rstest.cpp.
Function Documentation
__attribute__()
static void rawspeed::rstest::__attribute__ ((format(printf, 2, 3))) static
c_str()
WARNING e rawspeed::rstest::c_str ()
for() [1/3]
rawspeed::rstest::for (auto ba :r-> blackAreas) &
for() [2/3]
rawspeed::rstest::for (const string &e :errors) &
for() [3/3]
rawspeed::rstest::for (uint32_t p :r-> mBadPixelPositions) &
img_hash()
std::string rawspeed::rstest::img_hash (const rawspeed::RawImage & r)
imgDataHash()
md5::md5_state rawspeed::rstest::imgDataHash (const rawspeed::RawImage & raw)
Definition at line 121 of file rstest.cpp.
References rawspeed::RawImageData::__attribute__(), rawspeed::RawImageData::getDataUncropped(), rawspeed::RawImage::operator->(), and rawspeed::iPoint2D::y.
oss()
APPEND& rawspeed::rstest::oss (hash_of_line_hashes)
process()
size_t rawspeed::rstest::process (const std::string & filename, const rawspeed::CameraMetaData * metadata, const options & o)
Definition at line 322 of file rstest.cpp.
References rawspeed::rstest::options::create, rawspeed::rstest::options::dump, rawspeed::rstest::Timer::operator()(), and rawspeed::rstest::RstestHashMismatch::RstestHashMismatch().
results()
static int rawspeed::rstest::results (const map< string, string > & failedTests, const options & o) static
Definition at line 409 of file rstest.cpp.
str()
return oss rawspeed::rstest::str ()
usage()
static int rawspeed::rstest::usage (const char * progname) static
Definition at line 455 of file rstest.cpp.
Referenced by main().
va_end()
rawspeed::rstest::va_end (args)
va_start()
rawspeed::rstest::va_start (args , format)
vsnprintf()
rawspeed::rstest::vsnprintf (line. data(), sizeof(line) , format , args)
writeImage()
void rawspeed::rstest::writeImage (const rawspeed::RawImage & raw, const std::string & fn)
Definition at line 309 of file rstest.cpp.
References rawspeed::RawImageData::getDataType(), rawspeed::RawImage::operator->(), rawspeed::TYPE_FLOAT32, and rawspeed::TYPE_USHORT16.
writePFM()
void rawspeed::rstest::writePFM (const rawspeed::RawImage & raw, const std::string & fn)
Definition at line 258 of file rstest.cpp.
References rawspeed::RawImageData::__attribute__(), rawspeed::RawImageData::getCpp(), rawspeed::RawImageData::getDataUncropped(), rawspeed::RawImage::operator->(), rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
writePPM()
void rawspeed::rstest::writePPM (const rawspeed::RawImage & raw, const std::string & fn)
Definition at line 234 of file rstest.cpp.
References rawspeed::RawImageData::__attribute__(), rawspeed::RawImageData::getCpp(), rawspeed::RawImageData::getDataUncropped(), rawspeed::RawImage::operator->(), rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
Variable Documentation
__pad0__
d rawspeed::rstest::__pad0__
Definition at line 204 of file rstest.cpp.
__pad1__
WARNING rawspeed::rstest::__pad1__
Definition at line 225 of file rstest.cpp.
args
void const char va_list rawspeed::rstest::args
Initial value:
{
  std::array<char, 1024> line
Definition at line 148 of file rstest.cpp.
cropTL
const iPoint2D rawspeed::rstest::cropTL = r->getCropOffset()
Definition at line 193 of file rstest.cpp.
d
rawspeed::rstest::d
Definition at line 214 of file rstest.cpp.
errors
const auto rawspeed::rstest::errors = r->getErrors()
Definition at line 223 of file rstest.cpp.
format
void const char* rawspeed::rstest::format
Definition at line 148 of file rstest.cpp.
getUncroppedDim
* oss<< line.data();}string img_hash(const RawImage& r) { ostringstream oss; APPEND(&oss, "make: %s\n", r->metadata.make.c_str()); APPEND(&oss, "model: %s\n", r->metadata.model.c_str()); APPEND(&oss, "mode: %s\n", r->metadata.mode.c_str()); APPEND(&oss, "canonical_make: %s\n", r->metadata.canonical_make.c_str()); APPEND(&oss, "canonical_model: %s\n", r->metadata.canonical_model.c_str()); APPEND(&oss, "canonical_alias: %s\n", r->metadata.canonical_alias.c_str()); APPEND(&oss, "canonical_id: %s\n", r->metadata.canonical_id.c_str()); APPEND(&oss, "isoSpeed: %d\n", r->metadata.isoSpeed); APPEND(&oss, "blackLevel: %d\n", r->blackLevel); APPEND(&oss, "whitePoint: %d\n", r->whitePoint); APPEND(&oss, "blackLevelSeparate: %d %d %d %d\n", r->blackLevelSeparate[0], r->blackLevelSeparate[1], r->blackLevelSeparate[2], r->blackLevelSeparate[3]); APPEND(&oss, "wbCoeffs: %f %f %f %f\n", r->metadata.wbCoeffs[0], r->metadata.wbCoeffs[1], r->metadata.wbCoeffs[2], r->metadata.wbCoeffs[3]); APPEND(&oss, "isCFA: %d\n", r->isCFA); APPEND(&oss, "cfa: %s\n", r->cfa.asString().c_str()); APPEND(&oss, "filters: 0x%x\n", r->cfa.getDcrawFilter()); APPEND(&oss, "bpp: %d\n", r->getBpp()); APPEND(&oss, "cpp: %d\n", r->getCpp()); APPEND(&oss, "dataType: %d\n", r->getDataType()); const iPoint2D dimUncropped = r-> rawspeed::rstest::getUncroppedDim()
Definition at line 190 of file rstest.cpp.
hash_of_line_hashes
rawspeed::md5::md5_state rawspeed::rstest::hash_of_line_hashes = imgDataHash(r)
Definition at line 219 of file rstest.cpp.
isVertical
d ba rawspeed::rstest::isVertical
Definition at line 204 of file rstest.cpp.
offset
d ba ba rawspeed::rstest::offset
Definition at line 204 of file rstest.cpp.
oss
APPEND & rawspeed::rstest::oss
Definition at line 191 of file rstest.cpp.
p
rawspeed::rstest::p
Definition at line 214 of file rstest.cpp.
size
d ba ba ba rawspeed::rstest::size
Definition at line 204 of file rstest.cpp.