RawSpeed: rawspeed::SamsungV0Decompressor Class Reference
rawspeed::SamsungV0Decompressor Class Reference final
#include "decompressors/SamsungV0Decompressor.h"
Public Member Functions
SamsungV0Decompressor (const RawImage &image, const ByteStream &bso, const ByteStream &bsr)
void decompress () const
Protected Attributes
RawImage mRaw
Private Member Functions
void computeStripes (ByteStream bso, ByteStream bsr)
void decompressStrip (int row, const ByteStream &bs) const
Static Private Member Functions
static int32_t calcAdj (BitPumpMSB32 *bits, int b)
Private Attributes
std::vector< ByteStream > stripes
Detailed Description
Definition at line 34 of file SamsungV0Decompressor.h.
Constructor & Destructor Documentation
SamsungV0Decompressor()
rawspeed::SamsungV0Decompressor::SamsungV0Decompressor (const RawImage & image, const ByteStream & bso, const ByteStream & bsr)
Definition at line 40 of file SamsungV0Decompressor.cpp.
References computeStripes(), rawspeed::RawImageData::dim, rawspeed::RawImage::operator->(), rawspeed::ByteStream::peekStream(), rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
Referenced by LLVMFuzzerTestOneInput().
Member Function Documentation
calcAdj()
int32_t rawspeed::SamsungV0Decompressor::calcAdj (BitPumpMSB32 * bits, int b) static private
Definition at line 101 of file SamsungV0Decompressor.cpp.
computeStripes()
void rawspeed::SamsungV0Decompressor::computeStripes (ByteStream bso, ByteStream bsr) private
Definition at line 58 of file SamsungV0Decompressor.cpp.
References rawspeed::RawImageData::dim, rawspeed::RawImage::operator->(), and rawspeed::iPoint2D::y.
Referenced by SamsungV0Decompressor().
decompress()
void rawspeed::SamsungV0Decompressor::decompress () const
Definition at line 89 of file SamsungV0Decompressor.cpp.
Referenced by LLVMFuzzerTestOneInput().
decompressStrip()
void rawspeed::SamsungV0Decompressor::decompressStrip (int row, const ByteStream & bs) const private
Definition at line 107 of file SamsungV0Decompressor.cpp.
Member Data Documentation
mRaw
RawImage rawspeed::AbstractSamsungDecompressor::mRaw protected inherited
Definition at line 30 of file AbstractSamsungDecompressor.h.
stripes
std::vector<ByteStream> rawspeed::SamsungV0Decompressor::stripes private
Definition at line 35 of file SamsungV0Decompressor.h.
The documentation for this class was generated from the following files:
librawspeed/decompressors/SamsungV0Decompressor.h
librawspeed/decompressors/SamsungV0Decompressor.cpp