RawSpeed: rawspeed::CrwDecompressor Class Reference
rawspeed::CrwDecompressor Class Reference final
#include "decompressors/CrwDecompressor.h"
Public Member Functions
CrwDecompressor (const RawImage &img, uint32_t dec_table_, bool lowbits_, ByteStream rawData)
void decompress ()
Private Types
using crw_hts = std::array< HuffmanTable, 2 >
Static Private Member Functions
static HuffmanTable makeDecoder (const uint8_t *ncpl, const uint8_t *values)
static crw_hts initHuffTables (uint32_t table)
static void decodeBlock (std::array< int16_t, 64 > *diffBuf, const crw_hts &mHuff, BitPumpJPEG *bs)
Private Attributes
RawImage mRaw
crw_hts mHuff
const bool lowbits
ByteStream lowbitInput
ByteStream rawInput
Detailed Description
Definition at line 35 of file CrwDecompressor.h.
Member Typedef Documentation
crw_hts
using rawspeed::CrwDecompressor::crw_hts = std::array<HuffmanTable, 2> private
Definition at line 36 of file CrwDecompressor.h.
Constructor & Destructor Documentation
CrwDecompressor()
rawspeed::CrwDecompressor::CrwDecompressor (const RawImage & img, uint32_t dec_table_, bool lowbits_, ByteStream rawData)
Definition at line 41 of file CrwDecompressor.cpp.
References rawspeed::RawImageData::dim, rawspeed::ByteStream::getRemainSize(), rawspeed::ByteStream::getStream(), lowbitInput, lowbits, mRaw, rawspeed::RawImage::operator->(), rawspeed::RawImage::RawImage(), rawInput, rawspeed::ByteStream::skipBytes(), rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
Referenced by LLVMFuzzerTestOneInput().
Member Function Documentation
decodeBlock()
void rawspeed::CrwDecompressor::decodeBlock (std::array< int16_t, 64 > * diffBuf, const crw_hts & mHuff, BitPumpJPEG * bs) inline static private
Definition at line 164 of file CrwDecompressor.cpp.
References rawspeed::AbstractHuffmanTable::__attribute__().
decompress()
void rawspeed::CrwDecompressor::decompress ()
Definition at line 202 of file CrwDecompressor.cpp.
References lowbits.
Referenced by LLVMFuzzerTestOneInput().
initHuffTables()
CrwDecompressor::crw_hts rawspeed::CrwDecompressor::initHuffTables (uint32_t table) static private
Definition at line 84 of file CrwDecompressor.cpp.
makeDecoder()
HuffmanTable rawspeed::CrwDecompressor::makeDecoder (const uint8_t * ncpl, const uint8_t * values) static private
Definition at line 72 of file CrwDecompressor.cpp.
References rawspeed::HuffmanTableLUT::setup().
Member Data Documentation
lowbitInput
ByteStream rawspeed::CrwDecompressor::lowbitInput private
Definition at line 42 of file CrwDecompressor.h.
Referenced by CrwDecompressor().
lowbits
const bool rawspeed::CrwDecompressor::lowbits private
Definition at line 40 of file CrwDecompressor.h.
Referenced by CrwDecompressor(), and decompress().
mHuff
crw_hts rawspeed::CrwDecompressor::mHuff private
Definition at line 39 of file CrwDecompressor.h.
mRaw
RawImage rawspeed::CrwDecompressor::mRaw private
Definition at line 38 of file CrwDecompressor.h.
Referenced by CrwDecompressor().
rawInput
ByteStream rawspeed::CrwDecompressor::rawInput private
Definition at line 43 of file CrwDecompressor.h.
Referenced by CrwDecompressor().
The documentation for this class was generated from the following files:
librawspeed/decompressors/CrwDecompressor.h
librawspeed/decompressors/CrwDecompressor.cpp