RawSpeed: rawspeed::RawDecoderException Class Reference
rawspeed::RawDecoderException Class Reference
#include "decoders/RawDecoderException.h"
Public Member Functions
RAWSPEED_UNLIKELY_FUNCTION RAWSPEED_NOINLINE RawDecoderException (const char *msg)
Static Private Member Functions
static void RAWSPEED_UNLIKELY_FUNCTION RAWSPEED_NOINLINE log (const char *msg)
Detailed Description
Definition at line 29 of file RawDecoderException.h.
Constructor & Destructor Documentation
RawDecoderException()
RAWSPEED_UNLIKELY_FUNCTION RAWSPEED_NOINLINE rawspeed::RawDecoderException::RawDecoderException (const char * msg) inline explicit
Definition at line 32 of file RawDecoderException.h.
References rawspeed::RawspeedException::RawspeedException().
Referenced by rawspeed::FileIOException::FileIOException().
Member Function Documentation
log()
static void RAWSPEED_UNLIKELY_FUNCTION RAWSPEED_NOINLINE rawspeed::RawspeedException::log (const char * msg) inline static private inherited
Definition at line 60 of file RawspeedException.h.
References rawspeed::DEBUG_PRIO_EXTRA, and rawspeed::writeLog().
Referenced by rawspeed::RawspeedException::RawspeedException().
The documentation for this class was generated from the following file:
librawspeed/decoders/RawDecoderException.h