RawSpeed: utilities/identify/rawspeed-identify.cpp File Reference
rawspeed-identify.cpp File Reference
#include "RawSpeed-API.h"
#include <array>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <memory>
#include <string>
#include <sys/stat.h>
#include <vector>
Namespaces
rawspeed
rawspeed::identify
Functions
std::string rawspeed::identify::find_cameras_xml (const char *argv0)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 124 of file rawspeed-identify.cpp.
References rawspeed::RawImageData::__attribute__(), rawspeed::RawImageData::blackLevel, rawspeed::RawImageData::dim, rawspeed::RawImageData::getBpp(), rawspeed::RawImageData::getCpp(), rawspeed::RawImageData::getDataType(), rawspeed::RawImageData::getDataUncropped(), rawspeed::RawImageData::isCFA, rawspeed::RawImage::operator->(), rawspeed::TYPE_FLOAT32, rawspeed::TYPE_USHORT16, rawspeed::RawImageData::whitePoint, rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.