RawSpeed: rawspeed::VC5Decompressor Class Reference
rawspeed::VC5Decompressor Class Reference final
#include "decompressors/VC5Decompressor.h"
Classes
struct Channel
struct DecodeableBand
struct ReconstructionStep
class Wavelet
Public Member Functions
VC5Decompressor (ByteStream bs, const RawImage &img)
void decode (unsigned int offsetX, unsigned int offsetY, unsigned int width, unsigned int height)
Private Member Functions
void initVC5LogTable ()
void parseLargeCodeblock (const ByteStream &bs)
void prepareBandDecodingPlan ()
void prepareBandReconstruction ()
void prepareDecodingPlan ()
void decodeBands (bool *exceptionThrown) const noexcept
void reconstructLowpassBands () const noexcept
void combineFinalLowpassBands () const noexcept
void decodeThread (bool *exceptionThrown) const noexcept
void parseVC5 ()
Static Private Member Functions
static void getRLV (BitPumpMSB *bits, int *value, unsigned int *count)
Private Attributes
RawImage mRaw
ByteStream mBs
int outputBits
SimpleLUT< unsigned, VC5_LOG_TABLE_BITWIDTH > mVC5LogTable
struct {
uint16_t iChannel = 0
Optional< uint16_t > iSubband
Optional< uint16_t > lowpassPrecision
Optional< int16_t > quantization
const uint16_t imgFormat = 4
const uint16_t patternWidth = 2
const uint16_t patternHeight = 2
const uint16_t cps = 1
} mVC5
std::array< Channel, numChannels > channels
std::vector< DecodeableBand > allDecodeableBands
std::vector< ReconstructionStep > reconstructionSteps
Static Private Attributes
static constexpr auto VC5_LOG_TABLE_BITWIDTH = 12
static constexpr int numWaveletLevels = 3
static constexpr int numHighPassBands = 3
static constexpr int numLowPassBands = 1
static constexpr int numSubbands
static constexpr int numChannels = 4
static constexpr int numSubbandsTotal = numSubbands * numChannels
static constexpr int numLowPassBandsTotal = numWaveletLevels * numChannels
Detailed Description
Definition at line 89 of file VC5Decompressor.h.
Constructor & Destructor Documentation
VC5Decompressor()
rawspeed::VC5Decompressor::VC5Decompressor (ByteStream bs, const RawImage & img)
Definition at line 320 of file VC5Decompressor.cpp.
References mRaw, rawspeed::RawImage::operator->(), outputBits, parseVC5(), rawspeed::RawImage::RawImage(), VC5Decompressor(), and rawspeed::RawImageData::whitePoint.
Referenced by VC5Decompressor().
Member Function Documentation
combineFinalLowpassBands()
void rawspeed::VC5Decompressor::combineFinalLowpassBands () const private noexcept
Definition at line 770 of file VC5Decompressor.cpp.
Referenced by decodeThread().
decode()
void rawspeed::VC5Decompressor::decode (unsigned int offsetX, unsigned int offsetY, unsigned int width, unsigned int height)
Definition at line 711 of file VC5Decompressor.cpp.
References decodeThread(), initVC5LogTable(), and prepareDecodingPlan().
Referenced by LLVMFuzzerTestOneInput().
decodeBands()
void rawspeed::VC5Decompressor::decodeBands (bool * exceptionThrown) const private noexcept
Definition at line 737 of file VC5Decompressor.cpp.
Referenced by decodeThread().
decodeThread()
void rawspeed::VC5Decompressor::decodeThread (bool * exceptionThrown) const private noexcept
Definition at line 696 of file VC5Decompressor.cpp.
References combineFinalLowpassBands(), decodeBands(), and reconstructLowpassBands().
Referenced by decode().
getRLV()
void rawspeed::VC5Decompressor::getRLV (BitPumpMSB * bits, int * value, unsigned int * count) inline static private
Definition at line 811 of file VC5Decompressor.cpp.
References anonymous_namespace{VC5Decompressor.cpp}::RLV::size.
initVC5LogTable()
void rawspeed::VC5Decompressor::initVC5LogTable () private
Definition at line 360 of file VC5Decompressor.cpp.
Referenced by decode().
parseLargeCodeblock()
void rawspeed::VC5Decompressor::parseLargeCodeblock (const ByteStream & bs) private
Definition at line 568 of file VC5Decompressor.cpp.
References rawspeed::VC5Decompressor::Wavelet::allBandsValid(), and rawspeed::VC5Decompressor::Wavelet::bands.
Referenced by parseVC5().
parseVC5()
void rawspeed::VC5Decompressor::parseVC5 () private
Definition at line 384 of file VC5Decompressor.cpp.
References rawspeed::VC5Decompressor::Wavelet::allBandsValid(), rawspeed::VC5Decompressor::Wavelet::bands, rawspeed::RawImageData::dim, rawspeed::is(), rawspeed::LARGE_CHUNK, rawspeed::LargeCodeblock, rawspeed::matches(), rawspeed::MaxBitsPerComponent, mBs, mRaw, numChannels, numWaveletLevels, rawspeed::operator-(), rawspeed::RawImage::operator->(), rawspeed::Optional, parseLargeCodeblock(), rawspeed::PrescaleShift, rawspeed::SMALL_CHUNK, VC5_LOG_TABLE_BITWIDTH, rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
Referenced by VC5Decompressor().
prepareBandDecodingPlan()
void rawspeed::VC5Decompressor::prepareBandDecodingPlan () private
Definition at line 640 of file VC5Decompressor.cpp.
References numChannels, numHighPassBands, and numWaveletLevels.
Referenced by prepareDecodingPlan().
prepareBandReconstruction()
void rawspeed::VC5Decompressor::prepareBandReconstruction () private
Definition at line 669 of file VC5Decompressor.cpp.
Referenced by prepareDecodingPlan().
prepareDecodingPlan()
void rawspeed::VC5Decompressor::prepareDecodingPlan () private
Definition at line 691 of file VC5Decompressor.cpp.
References prepareBandDecodingPlan(), and prepareBandReconstruction().
Referenced by decode().
reconstructLowpassBands()
void rawspeed::VC5Decompressor::reconstructLowpassBands () const private noexcept
Definition at line 759 of file VC5Decompressor.cpp.
Referenced by decodeThread().
Member Data Documentation
allDecodeableBands
std::vector<DecodeableBand> rawspeed::VC5Decompressor::allDecodeableBands private
Definition at line 205 of file VC5Decompressor.h.
channels
std::array<Channel, numChannels> rawspeed::VC5Decompressor::channels private
Definition at line 196 of file VC5Decompressor.h.
cps
const uint16_t rawspeed::VC5Decompressor::cps = 1
Definition at line 114 of file VC5Decompressor.h.
iChannel
uint16_t rawspeed::VC5Decompressor::iChannel = 0
Definition at line 106 of file VC5Decompressor.h.
imgFormat
const uint16_t rawspeed::VC5Decompressor::imgFormat = 4
Definition at line 111 of file VC5Decompressor.h.
iSubband
Optional<uint16_t> rawspeed::VC5Decompressor::iSubband
Definition at line 107 of file VC5Decompressor.h.
lowpassPrecision
Optional<uint16_t> rawspeed::VC5Decompressor::lowpassPrecision
Definition at line 108 of file VC5Decompressor.h.
mBs
ByteStream rawspeed::VC5Decompressor::mBs private
Definition at line 91 of file VC5Decompressor.h.
Referenced by parseVC5().
mRaw
RawImage rawspeed::VC5Decompressor::mRaw private
Definition at line 90 of file VC5Decompressor.h.
Referenced by parseVC5(), and VC5Decompressor().
mVC5
struct { ... } rawspeed::VC5Decompressor::mVC5
mVC5LogTable
SimpleLUT<unsigned, VC5_LOG_TABLE_BITWIDTH> rawspeed::VC5Decompressor::mVC5LogTable private
Definition at line 95 of file VC5Decompressor.h.
numChannels
constexpr int rawspeed::VC5Decompressor::numChannels = 4 static constexpr private
Definition at line 193 of file VC5Decompressor.h.
Referenced by parseVC5(), and prepareBandDecodingPlan().
numHighPassBands
constexpr int rawspeed::VC5Decompressor::numHighPassBands = 3 static constexpr private
Definition at line 100 of file VC5Decompressor.h.
Referenced by prepareBandDecodingPlan().
numLowPassBands
constexpr int rawspeed::VC5Decompressor::numLowPassBands = 1 static constexpr private
Definition at line 101 of file VC5Decompressor.h.
numLowPassBandsTotal
constexpr int rawspeed::VC5Decompressor::numLowPassBandsTotal = numWaveletLevels * numChannels static constexpr private
Definition at line 195 of file VC5Decompressor.h.
numSubbands
constexpr int rawspeed::VC5Decompressor::numSubbands static constexpr private
Initial value:
=
      numLowPassBands + numHighPassBands * numWaveletLevels
Definition at line 102 of file VC5Decompressor.h.
numSubbandsTotal
constexpr int rawspeed::VC5Decompressor::numSubbandsTotal = numSubbands * numChannels static constexpr private
Definition at line 194 of file VC5Decompressor.h.
numWaveletLevels
constexpr int rawspeed::VC5Decompressor::numWaveletLevels = 3 static constexpr private
Definition at line 99 of file VC5Decompressor.h.
Referenced by parseVC5(), and prepareBandDecodingPlan().
outputBits
int rawspeed::VC5Decompressor::outputBits private
Definition at line 94 of file VC5Decompressor.h.
Referenced by VC5Decompressor().
patternHeight
const uint16_t rawspeed::VC5Decompressor::patternHeight = 2
Definition at line 113 of file VC5Decompressor.h.
patternWidth
const uint16_t rawspeed::VC5Decompressor::patternWidth = 2
Definition at line 112 of file VC5Decompressor.h.
quantization
Optional<int16_t> rawspeed::VC5Decompressor::quantization
Definition at line 109 of file VC5Decompressor.h.
reconstructionSteps
std::vector<ReconstructionStep> rawspeed::VC5Decompressor::reconstructionSteps private
Definition at line 213 of file VC5Decompressor.h.
VC5_LOG_TABLE_BITWIDTH
constexpr auto rawspeed::VC5Decompressor::VC5_LOG_TABLE_BITWIDTH = 12 static constexpr private
Definition at line 93 of file VC5Decompressor.h.
Referenced by parseVC5().
The documentation for this class was generated from the following files:
librawspeed/decompressors/VC5Decompressor.h
librawspeed/decompressors/VC5Decompressor.cpp