RawSpeed: rawspeed::PanasonicDecompressorV4::ProxyStream Class Reference
rawspeed::PanasonicDecompressorV4::ProxyStream Class Reference
Public Member Functions
ProxyStream (ByteStream block_, int section_split_offset_)
uint32_t getBits (int nbits) noexcept
Private Member Functions
void parseBlock ()
Private Attributes
ByteStream block
const uint32_t section_split_offset
std::vector< uint8_t > buf
int vbits = 0
Detailed Description
Definition at line 124 of file PanasonicDecompressorV4.cpp.
Constructor & Destructor Documentation
ProxyStream()
rawspeed::PanasonicDecompressorV4::ProxyStream::ProxyStream (ByteStream block_, int section_split_offset_) inline
Definition at line 156 of file PanasonicDecompressorV4.cpp.
References parseBlock(), ProxyStream(), and section_split_offset.
Referenced by rawspeed::PanasonicDecompressorV4::processBlock(), and ProxyStream().
Member Function Documentation
getBits()
uint32_t rawspeed::PanasonicDecompressorV4::ProxyStream::getBits (int nbits) inline noexcept
Definition at line 161 of file PanasonicDecompressorV4.cpp.
References vbits.
Referenced by rawspeed::PanasonicDecompressorV4::processPixelPacket().
parseBlock()
void rawspeed::PanasonicDecompressorV4::ProxyStream::parseBlock () inline private
Definition at line 131 of file PanasonicDecompressorV4.cpp.
References block, rawspeed::PanasonicDecompressorV4::BlockSize, rawspeed::ByteStream::getBuffer(), rawspeed::ByteStream::getRemainSize(), and section_split_offset.
Referenced by ProxyStream().
Member Data Documentation
block
ByteStream rawspeed::PanasonicDecompressorV4::ProxyStream::block private
Definition at line 125 of file PanasonicDecompressorV4.cpp.
Referenced by parseBlock().
buf
std::vector<uint8_t> rawspeed::PanasonicDecompressorV4::ProxyStream::buf private
Definition at line 127 of file PanasonicDecompressorV4.cpp.
section_split_offset
const uint32_t rawspeed::PanasonicDecompressorV4::ProxyStream::section_split_offset private
Definition at line 126 of file PanasonicDecompressorV4.cpp.
Referenced by parseBlock(), and ProxyStream().
vbits
int rawspeed::PanasonicDecompressorV4::ProxyStream::vbits = 0 private
Definition at line 129 of file PanasonicDecompressorV4.cpp.
Referenced by getBits().
The documentation for this class was generated from the following file:
librawspeed/decompressors/PanasonicDecompressorV4.cpp