RawSpeed: rawspeed::PanasonicDecompressorV4 Class Reference
rawspeed::PanasonicDecompressorV4 Class Reference final
#include "decompressors/PanasonicDecompressorV4.h"
Classes
struct Block
class ProxyStream
Public Member Functions
PanasonicDecompressorV4 (const RawImage &img, const ByteStream &input_, bool zero_is_not_bad, uint32_t section_split_offset_)
void decompress () const noexcept
Private Member Functions
void chopInputIntoBlocks ()
void processPixelPacket (ProxyStream *bits, int row, int col, std::vector< uint32_t > *zero_pos) const noexcept
void processBlock (const Block &block, std::vector< uint32_t > *zero_pos) const noexcept
void decompressThread () const noexcept
Private Attributes
RawImage mRaw
ByteStream input
bool zero_is_bad
uint32_t section_split_offset
std::vector< Block > blocks
Static Private Attributes
static constexpr uint32_t BlockSize = 0x4000
static constexpr int PixelsPerPacket = 14
static constexpr uint32_t BytesPerPacket = 16
static constexpr uint32_t PacketsPerBlock = BlockSize / BytesPerPacket
static constexpr uint32_t PixelsPerBlock = PixelsPerPacket * PacketsPerBlock
Detailed Description
Definition at line 33 of file PanasonicDecompressorV4.h.
Constructor & Destructor Documentation
PanasonicDecompressorV4()
rawspeed::PanasonicDecompressorV4::PanasonicDecompressorV4 (const RawImage & img, const ByteStream & input_, bool zero_is_not_bad, uint32_t section_split_offset_)
Definition at line 46 of file PanasonicDecompressorV4.cpp.
References rawspeed::iPoint2D::__attribute__(), BytesPerPacket, chopInputIntoBlocks(), rawspeed::RawImageData::dim, rawspeed::iPoint2D::hasPositiveArea(), mRaw, rawspeed::RawImage::operator->(), PixelsPerPacket, rawspeed::RawImage::RawImage(), section_split_offset, rawspeed::iPoint2D::x, and zero_is_bad.
Member Function Documentation
chopInputIntoBlocks()
void rawspeed::PanasonicDecompressorV4::chopInputIntoBlocks () private
Definition at line 85 of file PanasonicDecompressorV4.cpp.
References rawspeed::iPoint2D::__attribute__(), rawspeed::RawImageData::dim, rawspeed::ByteStream::getRemainSize(), input, rawspeed::iPoint2D::iPoint2D(), mRaw, rawspeed::RawImage::operator->(), and rawspeed::iPoint2D::x.
Referenced by PanasonicDecompressorV4().
decompress()
void rawspeed::PanasonicDecompressorV4::decompress () const noexcept
Definition at line 256 of file PanasonicDecompressorV4.cpp.
References decompressThread().
Referenced by LLVMFuzzerTestOneInput().
decompressThread()
void rawspeed::PanasonicDecompressorV4::decompressThread () const private noexcept
Definition at line 238 of file PanasonicDecompressorV4.cpp.
Referenced by decompress().
processBlock()
void rawspeed::PanasonicDecompressorV4::processBlock (const Block & block, std::vector< uint32_t > * zero_pos) const private noexcept
Definition at line 215 of file PanasonicDecompressorV4.cpp.
References rawspeed::PanasonicDecompressorV4::Block::beginCoord, rawspeed::PanasonicDecompressorV4::Block::bs, rawspeed::RawImageData::dim, rawspeed::PanasonicDecompressorV4::Block::endCoord, mRaw, rawspeed::RawImage::operator->(), PixelsPerPacket, rawspeed::PanasonicDecompressorV4::ProxyStream::ProxyStream(), section_split_offset, rawspeed::iPoint2D::x, and rawspeed::iPoint2D::y.
processPixelPacket()
void rawspeed::PanasonicDecompressorV4::processPixelPacket (ProxyStream * bits, int row, int col, std::vector< uint32_t > * zero_pos) const inline private noexcept
Definition at line 168 of file PanasonicDecompressorV4.cpp.
References rawspeed::PanasonicDecompressorV4::ProxyStream::getBits(), and PixelsPerPacket.
Member Data Documentation
blocks
std::vector<Block> rawspeed::PanasonicDecompressorV4::blocks private
Definition at line 72 of file PanasonicDecompressorV4.h.
BlockSize
constexpr uint32_t rawspeed::PanasonicDecompressorV4::BlockSize = 0x4000 static constexpr private
Definition at line 34 of file PanasonicDecompressorV4.h.
Referenced by rawspeed::PanasonicDecompressorV4::ProxyStream::parseBlock().
BytesPerPacket
constexpr uint32_t rawspeed::PanasonicDecompressorV4::BytesPerPacket = 16 static constexpr private
Definition at line 38 of file PanasonicDecompressorV4.h.
Referenced by PanasonicDecompressorV4().
input
ByteStream rawspeed::PanasonicDecompressorV4::input private
Definition at line 47 of file PanasonicDecompressorV4.h.
Referenced by chopInputIntoBlocks().
mRaw
RawImage rawspeed::PanasonicDecompressorV4::mRaw private
Definition at line 44 of file PanasonicDecompressorV4.h.
Referenced by chopInputIntoBlocks(), PanasonicDecompressorV4(), and processBlock().
PacketsPerBlock
constexpr uint32_t rawspeed::PanasonicDecompressorV4::PacketsPerBlock = BlockSize / BytesPerPacket static constexpr private
Definition at line 40 of file PanasonicDecompressorV4.h.
PixelsPerBlock
constexpr uint32_t rawspeed::PanasonicDecompressorV4::PixelsPerBlock = PixelsPerPacket * PacketsPerBlock static constexpr private
Definition at line 42 of file PanasonicDecompressorV4.h.
PixelsPerPacket
constexpr int rawspeed::PanasonicDecompressorV4::PixelsPerPacket = 14 static constexpr private
Definition at line 36 of file PanasonicDecompressorV4.h.
Referenced by PanasonicDecompressorV4(), processBlock(), and processPixelPacket().
section_split_offset
uint32_t rawspeed::PanasonicDecompressorV4::section_split_offset private
Definition at line 56 of file PanasonicDecompressorV4.h.
Referenced by PanasonicDecompressorV4(), and processBlock().
zero_is_bad
bool rawspeed::PanasonicDecompressorV4::zero_is_bad private
Definition at line 48 of file PanasonicDecompressorV4.h.
Referenced by PanasonicDecompressorV4().
The documentation for this class was generated from the following files:
librawspeed/decompressors/PanasonicDecompressorV4.h
librawspeed/decompressors/PanasonicDecompressorV4.cpp