RawSpeed: rawspeed::HuffmanTableLUT Class Reference
rawspeed::HuffmanTableLUT Class Reference final
#include "decompressors/HuffmanTableLUT.h"
Public Member Functions
void setup (bool fullDecode_, bool fixDNGBug16_)
template<typename BIT_STREAM >
__attribute__ ((always_inline)) int decodeCodeValue(BIT_STREAM &bs) const
template<typename BIT_STREAM >
__attribute__ ((always_inline)) int decodeDifference(BIT_STREAM &bs) const
template<typename BIT_STREAM , bool FULL_DECODE>
__attribute__ ((always_inline)) int decode(BIT_STREAM &bs) const
template<typename BIT_STREAM >
int decodeCodeValue (BIT_STREAM &bs) const
template<typename BIT_STREAM >
int decodeDifference (BIT_STREAM &bs) const
template<typename BIT_STREAM , bool FULL_DECODE>
int decode (BIT_STREAM &bs) const
void verifyCodeSymbolsAreValidDiffLenghts () const
bool operator== (const AbstractHuffmanTable &other) const
uint32_t setNCodesPerLength (const Buffer &data)
void setCodeValues (const Buffer &data)
template<typename BIT_STREAM , bool FULL_DECODE>
int processSymbol (BIT_STREAM &bs, CodeSymbol symbol, int codeValue) const
if ((diff &(1<<(len - 1)))==0) ret -
Static Public Member Functions
static int __attribute__ ((const)) extend(uint32_t diff
Public Attributes
static int uint32_t len
auto ret = static_cast<int32_t>(diff)
return ret
Protected Member Functions
template<typename BIT_STREAM >
std::pair< CodeSymbol, int > finishReadingPartialSymbol (BIT_STREAM &bs, CodeSymbol partial) const
template<typename BIT_STREAM >
std::pair< CodeSymbol, int > readSymbol (BIT_STREAM &bs) const
size_t __attribute__ ((pure)) maxCodePlusDiffLength() const
std::vector< CodeSymbol > generateCodeSymbols () const
Static Protected Member Functions
static void VerifyCodeSymbols (const std::vector< CodeSymbol > &symbols)
Protected Attributes
std::vector< uint32_t > maxCodeOL
std::vector< uint16_t > codeOffsetOL
bool fullDecode = true
bool fixDNGBug16 = false
std::vector< unsigned int > nCodesPerLength
std::vector< uint8_t > codeValues
Private Attributes
std::vector< int32_t > decodeLookup
Static Private Attributes
static constexpr unsigned PayloadShift = 16
static constexpr unsigned FlagMask = 0x100
static constexpr unsigned LenMask = 0xff
static constexpr unsigned LookupDepth = 11
Detailed Description
Definition at line 71 of file HuffmanTableLUT.h.
Member Function Documentation
__attribute__() [1/5]
template<typename BIT_STREAM , bool FULL_DECODE> rawspeed::HuffmanTableLUT::__attribute__ ((always_inline)) const & inline
Definition at line 172 of file HuffmanTableLUT.h.
References rawspeed::AbstractHuffmanTable::CodeSymbol::code, rawspeed::AbstractHuffmanTable::CodeSymbol::code_len, rawspeed::AbstractHuffmanTable::fullDecode, and LookupDepth.
__attribute__() [2/5]
template<typename BIT_STREAM > rawspeed::HuffmanTableLUT::__attribute__ ((always_inline)) const & inline
Definition at line 150 of file HuffmanTableLUT.h.
References rawspeed::AbstractHuffmanTable::fullDecode.
__attribute__() [3/5]
template<typename BIT_STREAM > rawspeed::HuffmanTableLUT::__attribute__ ((always_inline)) const & inline
Definition at line 159 of file HuffmanTableLUT.h.
References rawspeed::AbstractHuffmanTable::fullDecode.
__attribute__() [4/5]
static int rawspeed::AbstractHuffmanTable::__attribute__ ((const)) inline static inherited
Referenced by rawspeed::CrwDecompressor::decodeBlock(), rawspeed::HasselbladDecompressor::getBits(), rawspeed::SonyArw1Decompressor::getDiff(), rawspeed::AbstractHuffmanTable::processSymbol(), and rawspeed::SamsungV1Decompressor::samsungDiff().
__attribute__() [5/5]
size_t rawspeed::AbstractHuffmanTable::__attribute__ ((pure)) const inline protected inherited
Definition at line 79 of file AbstractHuffmanTable.h.
decode()
template<typename BIT_STREAM , bool FULL_DECODE> int rawspeed::HuffmanTableLookup::decode (BIT_STREAM & bs) const inline inherited
Definition at line 159 of file HuffmanTableLookup.h.
References rawspeed::AbstractHuffmanTable::fullDecode.
decodeCodeValue()
template<typename BIT_STREAM > int rawspeed::HuffmanTableLookup::decodeCodeValue (BIT_STREAM & bs) const inline inherited
Definition at line 103 of file HuffmanTableLookup.h.
References rawspeed::AbstractHuffmanTable::fullDecode.
decodeDifference()
template<typename BIT_STREAM > int rawspeed::HuffmanTableLookup::decodeDifference (BIT_STREAM & bs) const inline inherited
Definition at line 111 of file HuffmanTableLookup.h.
References rawspeed::AbstractHuffmanTable::fullDecode.
finishReadingPartialSymbol()
template<typename BIT_STREAM > std::pair<CodeSymbol, int > rawspeed::HuffmanTableLookup::finishReadingPartialSymbol (BIT_STREAM & bs, CodeSymbol partial) const inline protected inherited
Definition at line 121 of file HuffmanTableLookup.h.
References rawspeed::AbstractHuffmanTable::CodeSymbol::code, and rawspeed::AbstractHuffmanTable::CodeSymbol::code_len.
generateCodeSymbols()
std::vector<CodeSymbol> rawspeed::AbstractHuffmanTable::generateCodeSymbols () const inline protected inherited
Definition at line 138 of file AbstractHuffmanTable.h.
References rawspeed::AbstractHuffmanTable::__attribute__().
if()
rawspeed::AbstractHuffmanTable::if ((diff &(1<<(len - 1))) = =0) inherited
operator==()
bool rawspeed::AbstractHuffmanTable::operator== (const AbstractHuffmanTable & other) const inline inherited
Definition at line 171 of file AbstractHuffmanTable.h.
processSymbol()
template<typename BIT_STREAM , bool FULL_DECODE> int rawspeed::AbstractHuffmanTable::processSymbol (BIT_STREAM & bs, CodeSymbol symbol, int codeValue) const inline inherited
Definition at line 241 of file AbstractHuffmanTable.h.
References rawspeed::AbstractHuffmanTable::__attribute__(), rawspeed::AbstractHuffmanTable::CodeSymbol::code_len, and rawspeed::AbstractHuffmanTable::fixDNGBug16.
readSymbol()
template<typename BIT_STREAM > std::pair<CodeSymbol, int > rawspeed::HuffmanTableLookup::readSymbol (BIT_STREAM & bs) const inline protected inherited
Definition at line 144 of file HuffmanTableLookup.h.
References rawspeed::AbstractHuffmanTable::CodeSymbol::code, and rawspeed::AbstractHuffmanTable::CodeSymbol::code_len.
setCodeValues()
void rawspeed::AbstractHuffmanTable::setCodeValues (const Buffer & data) inline inherited
Definition at line 228 of file AbstractHuffmanTable.h.
References rawspeed::AbstractHuffmanTable::__attribute__().
setNCodesPerLength()
uint32_t rawspeed::AbstractHuffmanTable::setNCodesPerLength (const Buffer & data) inline inherited
Definition at line 176 of file AbstractHuffmanTable.h.
References rawspeed::AbstractHuffmanTable::__attribute__().
setup()
void rawspeed::HuffmanTableLUT::setup (bool fullDecode_, bool fixDNGBug16_) inline
Definition at line 98 of file HuffmanTableLUT.h.
Referenced by rawspeed::CrwDecompressor::makeDecoder(), and rawspeed::PentaxDecompressor::SetupHuffmanTable().
VerifyCodeSymbols()
static void rawspeed::AbstractHuffmanTable::VerifyCodeSymbols (const std::vector< CodeSymbol > & symbols) inline static protected inherited
Definition at line 113 of file AbstractHuffmanTable.h.
verifyCodeSymbolsAreValidDiffLenghts()
void rawspeed::AbstractHuffmanTable::verifyCodeSymbolsAreValidDiffLenghts () const inline inherited
Definition at line 65 of file AbstractHuffmanTable.h.
Referenced by rawspeed::AbstractHuffmanTable::setup().
Member Data Documentation
codeOffsetOL
std::vector<uint16_t> rawspeed::HuffmanTableLookup::codeOffsetOL protected inherited
Definition at line 75 of file HuffmanTableLookup.h.
codeValues
std::vector<uint8_t> rawspeed::AbstractHuffmanTable::codeValues protected inherited
Definition at line 98 of file AbstractHuffmanTable.h.
decodeLookup
std::vector<int32_t> rawspeed::HuffmanTableLUT::decodeLookup private
Definition at line 86 of file HuffmanTableLUT.h.
fixDNGBug16
bool rawspeed::AbstractHuffmanTable::fixDNGBug16 = false protected inherited
Definition at line 77 of file AbstractHuffmanTable.h.
Referenced by rawspeed::AbstractHuffmanTable::processSymbol(), and rawspeed::AbstractHuffmanTable::setup().
FlagMask
constexpr unsigned rawspeed::HuffmanTableLUT::FlagMask = 0x100 static constexpr private
Definition at line 83 of file HuffmanTableLUT.h.
fullDecode
bool rawspeed::AbstractHuffmanTable::fullDecode = true protected inherited
Definition at line 76 of file AbstractHuffmanTable.h.
Referenced by __attribute__(), rawspeed::HuffmanTableVector::decode(), rawspeed::HuffmanTableTree::decode(), rawspeed::HuffmanTableLookup::decode(), rawspeed::HuffmanTableLookup::decodeCodeValue(), rawspeed::HuffmanTableVector::decodeCodeValue(), rawspeed::HuffmanTableTree::decodeCodeValue(), rawspeed::HuffmanTableLookup::decodeDifference(), rawspeed::HuffmanTableVector::decodeDifference(), rawspeed::HuffmanTableTree::decodeDifference(), and rawspeed::AbstractHuffmanTable::setup().
len
int uint32_t rawspeed::AbstractHuffmanTable::len inherited
Initial value:
{
    assert(len > 0)
Definition at line 266 of file AbstractHuffmanTable.h.
LenMask
constexpr unsigned rawspeed::HuffmanTableLUT::LenMask = 0xff static constexpr private
Definition at line 84 of file HuffmanTableLUT.h.
LookupDepth
constexpr unsigned rawspeed::HuffmanTableLUT::LookupDepth = 11 static constexpr private
Definition at line 85 of file HuffmanTableLUT.h.
Referenced by __attribute__().
maxCodeOL
std::vector<uint32_t> rawspeed::HuffmanTableLookup::maxCodeOL protected inherited
Definition at line 74 of file HuffmanTableLookup.h.
nCodesPerLength
std::vector<unsigned int> rawspeed::AbstractHuffmanTable::nCodesPerLength protected inherited
Definition at line 88 of file AbstractHuffmanTable.h.
PayloadShift
constexpr unsigned rawspeed::HuffmanTableLUT::PayloadShift = 16 static constexpr private
Definition at line 82 of file HuffmanTableLUT.h.
ret [1/2]
auto rawspeed::AbstractHuffmanTable::ret = static_cast<int32_t>(diff) inherited
Definition at line 268 of file AbstractHuffmanTable.h.
ret [2/2]
return rawspeed::AbstractHuffmanTable::ret inherited
Definition at line 271 of file AbstractHuffmanTable.h.
The documentation for this class was generated from the following file:
librawspeed/decompressors/HuffmanTableLUT.h